### ISSUE TITLE
win11 api版 chatgpt报错

### ISSUE THREAD

**Issue by wdnmd-ship** [lss233/chatgpt-mirai-qq-bot#101]
Traceback (most recent call last):
  File "C:\Users\WYC\Downloads\quickstart-windows-amd64\chatgpt\bot.py", line 23, in <module>
    import chatbot
  File "C:\Users\WYC\Downloads\quickstart-windows-amd64\chatgpt\chatbot.py", line 1, in <module>
    from revChatGPT.Official import Chatbot, Prompt
  File "C:\Users\WYC\Downloads\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\revChatGPT\Official.py", line 11, in <module>
    import tiktoken
ModuleNotFoundError: No module named 'tiktoken'
请问这是什么问题

**Comment by lss233** [comment]
依赖缺失了 需要你自己补一下

**Comment by wdnmd-ship** [comment]
> 依赖缺失了 需要你自己补一下
请问要怎么补呢

**Comment by lss233** [comment]
提示 ModuleNotFoundError: No module named 'tiktoken'‘
那你就执行
`python3.9\python.exe -m pip install tiktoken`
以此类推。
在启动ChatGPT之后出现的那个黑框里面执行。

**Comment by wdnmd-ship** [comment]
> 

万分感谢

**Comment by wdnmd-ship** [comment]
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
That model does not exist
这是什么情况

**Comment by lss233** [comment]
#82
