### ISSUE TITLE
[BUG] 第三方代理 出现 Exception: Incorrect response from OpenAI API

### ISSUE THREAD

**Issue by ferretgeek** [lss233/chatgpt-mirai-qq-bot#103]
**表现**  
2023-02-12 17:10:15.029 | INFO     | chatbot:<module>:16 - 登录 OpenAI 中...
2023-02-12 17:10:15.029 | INFO     | chatbot:<module>:18 - 当前模式：第三方代理
2023-02-12 17:10:20.882 | INFO     | launart.manager:launch_blocking:479 - Starting launart main task...
2023-02-12 17:10:20.889 | INFO     | launart.manager:launch:331 - Launching 5 components as async task...
2023-02-12 17:10:20.913 | INFO     | graia.ariadne.service:base_telemetry:144 -
    _         _           _
   / \   _ __(_) __ _  __| |_ __   ___
  / _ \ | '__| |/ _` |/ _` | '_ \ / _ \
 / ___ \| |  | | (_| | (_| | | | |  __/
/_/   \_\_|  |_|\__,_|\__,_|_| |_|\___|

graia-amnesia: 0.7.1
graia-ariadne: 0.10.3
graia-broadcast: 0.19.1
launart: 0.6.3
statv: 0.3.2
2023-02-12 17:10:20.914 | SUCCESS  | launart.manager:launch:384 - Layer #1:[cache.client/memcache, http.client/aiohttp] preparation completed.
2023-02-12 17:10:20.915 | SUCCESS  | launart.manager:launch:384 - Layer #3:[elizabeth.service] preparation completed.
2023-02-12 17:10:20.915 | INFO     | launart.manager:launch:389 - All components prepared, start blocking phase.
2023-02-12 17:10:22.952 | SUCCESS  | graia.ariadne.connection.ws:_:62 - Successfully got session key
2023-02-12 17:10:34.278 | INFO     | graia.ariadne.model:log:83 - 3194935366: [RECV][问心(2580115083)] -> 个
2023-02-12 17:10:34.279 | DEBUG    | chatbot:initial_process:95 - 初始化处理中...
Incorrect response from OpenAI API
2023-02-12 17:10:34.989 | ERROR    | __main__:handle_message:103 - Incorrect response from OpenAI API
Traceback (most recent call last):

  File "F:\Windows-quickstart-refs.tags.v1.5.4\chatgpt\python3.9\lib\site-packages\revChatGPT\Proxied.py", line 132, in ask
    response = response.text.splitlines()[-4]
               │        │    └ <method 'splitlines' of 'str' objects>
               │        └ '{"error":"Blocking operation in progress"}\n'
               └ <Response [200]>

IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "F:\Windows-quickstart-refs.tags.v1.5.4\chatgpt\bot.py", line 116, in friend_message_listener
    response = await handle_message(friend, f"friend-{friend.id}", chain.display, source)
                     │              │                              │     │        └ Source(id=18711, time=datetime.datetime(2023, 2, 12, 9, 10, 36, tzinfo=datetime.timezone.utc), type='Source')
                     │              │                              │     └ <property object at 0x0000014B6A30BB80>
                     │              │                              └ MessageChain([Plain(text='个')])
                     │              └ Friend(id=2580115083, nickname='问心', remark='问心')
                     └ <function handle_message at 0x0000014B70454F70>

> File "F:\Windows-quickstart-refs.tags.v1.5.4\chatgpt\bot.py", line 96, in handle_message
    resp = await session.get_chat_response(message)
                 │       │                 └ '个'
                 │       └ <function ChatSession.get_chat_response at 0x0000014B6A50EAF0>
                 └ <chatbot.ChatSession object at 0x0000014B704B7940>

  File "F:\Windows-quickstart-refs.tags.v1.5.4\chatgpt\chatbot.py", line 77, in get_chat_response
    final_resp = await loop.run_in_executor(None, bot.ask, message)
                       │    │                     │   │    └ '个'
                       │    │                     │   └ <function Chatbot.ask at 0x0000014B6A50E310>
                       │    │                     └ <revChatGPT.Proxied.Chatbot object at 0x0000014B6A484E80>
                       │    └ <function BaseEventLoop.run_in_executor at 0x0000014B6913BD30>
                       └ <ProactorEventLoop running=True closed=False debug=False>

  File "concurrent\futures\thread.py", line 58, in run

  File "F:\Windows-quickstart-refs.tags.v1.5.4\chatgpt\python3.9\lib\site-packages\revChatGPT\Proxied.py", line 136, in ask
    raise Exception("Incorrect response from OpenAI API") from exc

Exception: Incorrect response from OpenAI API
2023-02-12 17:10:35.059 | INFO     | graia.ariadne.model:log:83 - 3194935366: [SEND][问心(2580115083)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没 看见。\nIncorrect response from OpenAI API

**运行环境:**  
- 操作系统：Windows 11
- 项目版本：1.5.4

**复现步骤**  
描述你是如何触发这个 BUG 的
1.发消息就会自动触发
2.重置会话显示成功，但还是无限触发
3.Windows11开启clash代理，然后在config.cfg填入本地的IP和clash端口

**Comment by lss233** [comment]
```
Update 2023/02/11 - I am getting DDOSed. I might not be able to keep hosting it. Use V1 or host a bypass server yourself
```
***第三方代理*** 模式暂时不能用了。

**Comment by ferretgeek** [comment]
> 

这个可不可以用本地的clash代理呢

**Comment by lss233** [comment]
试试浏览器模式 + 正向代理吧
