### ISSUE TITLE
[BUG] API反代地址填写错误，正确格式应为 'https://<网址>/v1

### ISSUE THREAD

**Issue by AKEXZ** [lss233/chatgpt-mirai-qq-bot#1046]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Ubuntu 22.04.1 LTS x86_64(Py3.7.8)
- Docker： 最新
- 项目版本：最新

**复现步骤**  
描述你是如何触发这个 BUG 的

通过 Docker 部署 （适合已经有 Mirai 的用户)时
docker run --name mirai-chatgpt-bot \
    -v /path/to/config.cfg:/app/config.cfg \
    --network host \
    lss233/chatgpt-mirai-qq-bot:browser-version

2023-07-12 12:28:49.045 | ERROR    | config:scan_presets:566 - 检查预设：正常 <==> presets/default.txt [失败：文件不存在]
2023-07-12 12:28:49.046 | SUCCESS  | config:scan_presets:564 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-07-12 12:28:49.046 | SUCCESS  | config:scan_presets:577 - 注册预设：catgirl <==> ./presets/catgirl.txt [成功]
2023-07-12 12:28:49.046 | SUCCESS  | config:scan_presets:577 - 注册预设：预设模板 <==> ./presets/预设模板.txt [成功]
2023-07-12 12:28:49.046 | SUCCESS  | config:scan_presets:577 - 注册预设：issue402 <==> ./presets/issue402.txt [成功]
2023-07-12 12:28:49.046 | SUCCESS  | config:scan_presets:577 - 注册预设：catgirl_en <==> ./presets/catgirl_en.txt [成功]
2023-07-12 12:28:49.112 | INFO     | manager.bot:login_bing:218 - 正在解析第 1 个 Bing 账号
2023-07-12 12:28:49.112 | SUCCESS  | manager.bot:login_bing:223 - 解析成功！
2023-07-12 12:28:49.113 | SUCCESS  | manager.bot:login_bing:229 - 成功解析 1/1 个 Bing 账号！
2023-07-12 12:28:49.113 | INFO     | manager.bot:handle_openai:107 - 当前的 browserless_endpoint 为：https://chatgpt-proxy.lss233.com/api/
2023-07-12 12:28:49.113 | ERROR    | manager.bot:handle_openai:129 - API反代地址填写错误，正确格式应为 'https://<网址>/v1'
2023-07-12 12:28:49.113 | ERROR    | utils.exithooks:foo:35 - 看样子程序似乎没有正常退出。
2023-07-12 12:28:49.113 | ERROR    | utils.exithooks:foo:36 - API反代地址填写错误，正确格式应为 'https://<网址>/v1'
NoneType: None
2023-07-12 12:28:49.114 | ERROR    | utils.exithooks:foo:37 - 你可以在这里阅读常见问题的解决方案：
2023-07-12 12:28:49.114 | ERROR    | utils.exithooks:foo:38 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
Exception ignored in atexit callback: <function foo at 0x7f5c74bb9800>
Traceback (most recent call last):
  File "/app/utils/exithooks.py", line 39, in foo
    raise hooks.exception
  File "/app/bot.py", line 15, in <module>
    loop.run_until_complete(botManager.login())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/manager/bot.py", line 161, in login
    await login_func()
  File "/app/manager/bot.py", line 130, in handle_openai
    raise ValueError("API反代地址填写错误，正确格式应为 'https://<网址>/v1'")
ValueError: API反代地址填写错误，正确格式应为 'https://<网址>/v1'

**Comment by Haibersut** [comment]
字面意思（

**Comment by fangyuan99** [comment]
我也触发了这个bug，没有更改过配置突然就登录不上了，使用美国vps之前正常，配置如下：
```
[openai]
browserless_endpoint = "https://chatgpt-proxy.lss233.com/api/"
api_endpoint = "https://api.openai.com/v1/"

[[openai.accounts]]
api_key = "sk-xxx"
```

**Comment by Haibersut** [comment]
> 我也触发了这个bug，没有更改过配置突然就登录不上了，使用美国vps之前正常，配置如下：
> 
> ```
> [openai]
> browserless_endpoint = "https://chatgpt-proxy.lss233.com/api/"
> api_endpoint = "https://api.openai.com/v1/"
> 
> [[openai.accounts]]
> api_key = "sk-xxx"
> ```

正确格式应为 'https://<网址>/v1'
你填的是api_endpoint = "https://api.openai.com/v1/"
你觉得哪里有问题

**Comment by fangyuan99** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/62874116/bb1caeb4-779c-4b6d-a96f-abd9cf56c0f5)
我看官方文档也是这么填的，算了，我把那两行都删了就可以正常使用

**Comment by Haibersut** [comment]
docker的话你拉一下最新的就行，就是/v1和/v1/的区别
