### ISSUE TITLE
[BUG] 启动失败：RuntimeError: no running event loop

### ISSUE THREAD

**Issue by c19373842811** [lss233/chatgpt-mirai-qq-bot#1120]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
小白，第一次启动出现这个问题

**运行环境:**  
- 操作系统：Linux
- Docker： v1.0.28
- 项目版本：2.5.2

**复现步骤**  
启动报错

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志：
root@350d7afd7c39:~/chatgpt-mirai-qq-bot# python bot.py
2023-08-05 02:22:12.777 | SUCCESS  | config:scan_presets:565 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2023-08-05 02:22:12.777 | SUCCESS  | config:scan_presets:565 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-08-05 02:22:12.778 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl <==> ./presets/catgirl.txt [成功]
2023-08-05 02:22:12.778 | SUCCESS  | config:scan_presets:578 - 注册预设：预设模板 <==> ./presets/预设模板.txt [成功]
2023-08-05 02:22:12.778 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl_en <==> ./presets/catgirl_en.txt [成功]
2023-08-05 02:22:12.778 | SUCCESS  | config:scan_presets:578 - 注册预设：issue402 <==> ./presets/issue402.txt [成功]
2023-08-05 02:22:12.807 | INFO     | manager.bot:handle_openai:107 - 当前的 browserless_endpoint 为：https://chatgpt-proxy.lss233.com/api/
2023-08-05 02:22:12.807 | INFO     | manager.bot:handle_openai:123 - 当前的 api_endpoint 为：https://api.openai.com/v1
2023-08-05 02:22:12.808 | INFO     | manager.bot:login_openai:340 - 正在登录第 1 个 OpenAI 账号
2023-08-05 02:22:12.808 | INFO     | manager.bot:__login_openai_apikey:527 - 尝试使用 api_key 登录中...
2023-08-05 02:22:12.808 | INFO     | manager.bot:__login_openai_apikey:531 - 当前检查的 API Key 为：Link_ui3******B9zZ
2023-08-05 02:22:12.808 | WARNING  | manager.bot:__login_openai_apikey:534 - 在查询 API 额度时遇到问题，请自行确认额度。
2023-08-05 02:22:12.808 | SUCCESS  | manager.bot:login_openai:354 - 登录成功！
2023-08-05 02:22:12.808 | SUCCESS  | manager.bot:login_openai:375 - 成功登录 1/1 个 OpenAI 账号！
2023-08-05 02:22:12.808 | INFO     | manager.bot:login:173 - AI 类型：chatgpt-web - 可用账号： 0 个
2023-08-05 02:22:12.809 | INFO     | manager.bot:login:173 - AI 类型：openai-api - 可用账号： 1 个
2023-08-05 02:22:12.809 | INFO     | manager.bot:login:173 - AI 类型：poe-web - 可用账号： 0 个
2023-08-05 02:22:12.809 | INFO     | manager.bot:login:173 - AI 类型：bing-cookie - 可用账号： 0 个
2023-08-05 02:22:12.809 | INFO     | manager.bot:login:173 - AI 类型：bard-cookie - 可用账号： 0 个
2023-08-05 02:22:12.809 | INFO     | manager.bot:login:173 - AI 类型：yiyan-cookie - 可用账号： 0 个
2023-08-05 02:22:12.809 | INFO     | manager.bot:login:173 - AI 类型：xinghuo-cookie - 可用账号： 0 个
2023-08-05 02:22:12.809 | INFO     | manager.bot:login:173 - AI 类型：chatglm-api - 可用账号： 0 个
2023-08-05 02:22:12.810 | INFO     | manager.bot:login:173 - AI 类型：slack-accesstoken - 可用账号： 0 个
2023-08-05 02:22:12.810 | INFO     | __main__:<module>:19 - 检测到 mirai 配置，将启动 mirai 模式……
2023-08-05 02:22:13.011 | ERROR    | utils.text_to_img:<module>:56 - 未检测到 wkhtmltoimage，无法进行 Markdown 渲染！
2023-08-05 02:22:13.018 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
Traceback (most recent call last):

> File "/root/chatgpt-mirai-qq-bot/bot.py", line 20, in <module>
    from platforms.ariadne_bot import start_task

  File "/root/chatgpt-mirai-qq-bot/platforms/ariadne_bot.py", line 36, in <module>
    app = Ariadne(
          └ <class 'graia.ariadne.app.Ariadne'>

  File "/usr/local/lib/python3.11/site-packages/graia/ariadne/app.py", line 201, in __init__
    self._ensure_config()
    │    └ <classmethod(<function Ariadne._ensure_config at 0x7fc7ba4240e0>)>
    └ <graia.ariadne.app.Ariadne object at 0x7fc78c7a0950>
  File "/usr/local/lib/python3.11/site-packages/graia/ariadne/app.py", line 133, in _ensure_config
    cls.service.loop.set_exception_handler(loguru_exc_callback_async)
    │   │       │                          └ <function loguru_exc_callback_async at 0x7fc7bb33c860>
    │   │       └ <property object at 0x7fc7ba420270>
    │   └ <graia.ariadne.service.ElizabethService object at 0x7fc786284550>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "/usr/local/lib/python3.11/site-packages/graia/ariadne/service.py", line 245, in loop
    return self.broadcast.loop
           │    │         └ <property object at 0x7fc7bb5bdcb0>
           │    └ <graia.broadcast.Broadcast object at 0x7fc78c35cd10>
           └ <graia.ariadne.service.ElizabethService object at 0x7fc786284550>
  File "/usr/local/lib/python3.11/site-packages/graia/broadcast/__init__.py", line 100, in loop
    return asyncio.get_running_loop()
           │       └ <built-in function get_running_loop>
           └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>

RuntimeError: no running event loop

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by huangzhitian** [comment]
这是什么key,转发的话用不了群主的接入点

**Comment by Haibersut** [comment]
了解了，我试了一下，直接使用批处理文件启动会出现这个问题

**Comment by Dgruler** [comment]
> 了解了，我试了一下，直接使用批处理文件启动会出现这个问题

请问你是怎么解决的呢

**Comment by Haibersut** [comment]
> > 了解了，我试了一下，直接使用批处理文件启动会出现这个问题
> 
> 请问你是怎么解决的呢

你可以装python然后直接运行，或者下最新的2.5.3

**Comment by Haibersut** [comment]
> 2.5.1没遇到这个问题，2.5.3就不行了

啊？今天刚更新的，怎么样不行，你发日记我看看

**Comment by Dgruler** [comment]
> > 2.5.1没遇到这个问题，2.5.3就不行了
> 
> 啊？今天刚更新的，怎么样不行，你发日记我看看

请问你的python版本是多少呢，我和题主的报错是一致的，更新了2.5.3没有解决，不知道是不是python版本的问题

**Comment by Haibersut** [comment]
> > > 2.5.1没遇到这个问题，2.5.3就不行了
> > 
> > 
> > 啊？今天刚更新的，怎么样不行，你发日记我看看
> 
> 请问你的python版本是多少呢，我和题主的报错是一致的，更新了2.5.3没有解决，不知道是不是python版本的问题

你用安装器启动看看

**Comment by Haibersut** [comment]
初步排查应该是graia的某个依赖项的问题

**Comment by Haibersut** [comment]
目前如果graia版本如下是可以正常启动mirai的
creart 0.2.2
creart-graia 0.1.5
graiax-silkcoder: 0.3.6
graia-amnesia: 0.7.1
graia-ariadne: 0.11.5
graia-broadcast: 0.19.2
launart: 0.6.3
statv: 0.3.2

**Comment by Haibersut** [comment]
已经修复，使用2.5.3部署包的可以打开安装程序自动拉取源码更新
https://github.com/lss233/chatgpt-mirai-qq-bot/commit/ab761d35c67cf846be8f795e11997605dfd48764

**Comment by c19373842811** [comment]
谢谢，可以正常启动了
