### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'conversations'

### ISSUE THREAD

**Issue by woltium** [lss233/chatgpt-mirai-qq-bot#115]
配置好代理后出现以下问题
```
chatgpt-qq-mirai-1    | 2023-02-14 02:38:17 V/Bot.2546518385: 巨山超力霸(793967421) -> ？
chatgpt-qq-chatgpt-1  | 2023-02-14 02:38:17.165 | INFO     | graia.ariadne.model:log:83 - 2546518385: [RECV][巨山超力霸(793967421)] -> ？
chatgpt-qq-chatgpt-1  | 2023-02-14 02:38:17.165 | ERROR    | __main__:handle_message:79 - 'NoneType' object has no attribute 'conversations'
chatgpt-qq-chatgpt-1  | Traceback (most recent call last):
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/bot.py", line 124, in <module>
chatgpt-qq-chatgpt-1  |     app.launch_blocking()
chatgpt-qq-chatgpt-1  |     │   └ <classmethod object at 0x7ff8bf9b74f0>
chatgpt-qq-chatgpt-1  |     └ <graia.ariadne.app.Ariadne object at 0x7ff87bea37c0>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/graia/ariadne/app.py", line 313, in launch_blocking
chatgpt-qq-chatgpt-1  |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
chatgpt-qq-chatgpt-1  |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
chatgpt-qq-chatgpt-1  |     │   │              │                    │   │       └ <property object at 0x7ff8bf9b1450>
chatgpt-qq-chatgpt-1  |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7ff8c16fa520>
chatgpt-qq-chatgpt-1  |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1  |     │   │              └ <function Launart.launch_blocking at 0x7ff8c0b399d0>
chatgpt-qq-chatgpt-1  |     │   └ <launart.manager.Launart object at 0x7ff87b66d280>
chatgpt-qq-chatgpt-1  |     └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/launart/manager.py", line 494, in launch_blocking
chatgpt-qq-chatgpt-1  |     loop.run_until_complete(launch_task)
chatgpt-qq-chatgpt-1  |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.9/site-packages/launart/manager....
chatgpt-qq-chatgpt-1  |     │    └ <function BaseEventLoop.run_until_complete at 0x7ff8c0e6fb80>
chatgpt-qq-chatgpt-1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
chatgpt-qq-chatgpt-1  |     self.run_forever()
chatgpt-qq-chatgpt-1  |     │    └ <function BaseEventLoop.run_forever at 0x7ff8c0e6faf0>
chatgpt-qq-chatgpt-1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
chatgpt-qq-chatgpt-1  |     self._run_once()
chatgpt-qq-chatgpt-1  |     │    └ <function BaseEventLoop._run_once at 0x7ff8c0e72670>
chatgpt-qq-chatgpt-1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
chatgpt-qq-chatgpt-1  |     handle._run()
chatgpt-qq-chatgpt-1  |     │      └ <function Handle._run at 0x7ff8c0f95430>
chatgpt-qq-chatgpt-1  |     └ <Handle <TaskStepMethWrapper object at 0x7ff87b4fc370>()>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
chatgpt-qq-chatgpt-1  |     self._context.run(self._callback, *self._args)
chatgpt-qq-chatgpt-1  |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt-qq-chatgpt-1  |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7ff87b4fc370>()>
chatgpt-qq-chatgpt-1  |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt-qq-chatgpt-1  |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7ff87b4fc370>()>
chatgpt-qq-chatgpt-1  |     │    └ <member '_context' of 'Handle' objects>
chatgpt-qq-chatgpt-1  |     └ <Handle <TaskStepMethWrapper object at 0x7ff87b4fc370>()>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 191, in Executor
chatgpt-qq-chatgpt-1  |     result = await run_always_await(target_callable, **parameter_compile_result)
chatgpt-qq-chatgpt-1  |                    │                │                  └ {'app': <graia.ariadne.app.Ariadne object at 0x7ff87bea37c0>, 'friend': Friend(id=793967421, nickname='巨山超力霸', remark='巨山超力霸'...
chatgpt-qq-chatgpt-1  |                    │                └ <function friend_message_listener at 0x7ff87b678430>
chatgpt-qq-chatgpt-1  |                    └ <function run_always_await at 0x7ff8c0aedaf0>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
chatgpt-qq-chatgpt-1  |     obj = await obj
chatgpt-qq-chatgpt-1  |                 └ <coroutine object friend_message_listener at 0x7ff87b4adb40>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/bot.py", line 88, in friend_message_listener
chatgpt-qq-chatgpt-1  |     response = await handle_message(friend, f"friend-{friend.id}", chain.display, source)
chatgpt-qq-chatgpt-1  |                      │              │                              │     │        └ Source(id=49691, time=datetime.datetime(2023, 2, 14, 2, 38, 16, tzinfo=datetime.timezone.utc), type='Source')
chatgpt-qq-chatgpt-1  |                      │              │                              │     └ <property object at 0x7ff8bfab44f0>
chatgpt-qq-chatgpt-1  |                      │              │                              └ MessageChain([Plain(text='？')])
chatgpt-qq-chatgpt-1  |                      │              └ Friend(id=793967421, nickname='巨山超力霸', remark='巨山超力霸')
chatgpt-qq-chatgpt-1  |                      └ <function handle_message at 0x7ff87b678310>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  | > File "/app/bot.py", line 51, in handle_message
chatgpt-qq-chatgpt-1  |     session = chatbot.get_chat_session(session_id)
chatgpt-qq-chatgpt-1  |               │       │                └ 'friend-793967421'
chatgpt-qq-chatgpt-1  |               │       └ <function get_chat_session at 0x7ff87beb5f70>
chatgpt-qq-chatgpt-1  |               └ <module 'chatbot' from '/app/chatbot.py'>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/chatbot.py", line 98, in get_chat_session
chatgpt-qq-chatgpt-1  |     __sessions[id] = ChatSession(id)
chatgpt-qq-chatgpt-1  |     │          │     │           └ 'friend-793967421'
chatgpt-qq-chatgpt-1  |     │          │     └ <class 'chatbot.ChatSession'>
chatgpt-qq-chatgpt-1  |     │          └ 'friend-793967421'
chatgpt-qq-chatgpt-1  |     └ {}
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/chatbot.py", line 45, in __init__
chatgpt-qq-chatgpt-1  |     self.load_conversation()
chatgpt-qq-chatgpt-1  |     │    └ <function ChatSession.load_conversation at 0x7ff87aade0d0>
chatgpt-qq-chatgpt-1  |     └ <chatbot.ChatSession object at 0x7ff87b4fc790>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/chatbot.py", line 54, in load_conversation
chatgpt-qq-chatgpt-1  |     self.reset_conversation()
chatgpt-qq-chatgpt-1  |     │    └ <function ChatSession.reset_conversation at 0x7ff87aade1f0>
chatgpt-qq-chatgpt-1  |     └ <chatbot.ChatSession object at 0x7ff87b4fc790>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/chatbot.py", line 66, in reset_conversation
chatgpt-qq-chatgpt-1  |     bot.conversations.conversations[self.conversation_id] = Conversation()
chatgpt-qq-chatgpt-1  |     │                               │    │                  └ <class 'revChatGPT.V2.Conversation'>
chatgpt-qq-chatgpt-1  |     │                               │    └ 'friend-793967421'
chatgpt-qq-chatgpt-1  |     │                               └ <chatbot.ChatSession object at 0x7ff87b4fc790>
chatgpt-qq-chatgpt-1  |     └ None
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  | AttributeError: 'NoneType' object has no attribute 'conversations'
chatgpt-qq-mirai-1    | 2023-02-14 02:38:17 V/Bot.2546518385: Friend(793967421) <- [mirai:quote:[mirai:source:ids=[49691], internalIds=[1667224158], from friend 793967421 to 2546518385 at 1676342296], content=？]出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n'NoneType' object has no attribute 'conversations'
chatgpt-qq-chatgpt-1  | 2023-02-14 02:38:17.554 | INFO     | graia.ariadne.model:log:83 - 2546518385: [SEND][巨山超力霸(793967421)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n'NoneType' object has no attribute 'conversations'

```

**Comment by lss233** [comment]
初始化阶段出错了。 你把程序启动阶段的日志发出来看看。

**Comment by woltium** [comment]
```
chatgpt-qq-chatgpt-1  | 2023-02-14 02:37:56.210 | INFO     | launart.manager:launch_blocking:479 - Starting launart main task...
chatgpt-qq-chatgpt-1  | 2023-02-14 02:37:56.210 | INFO     | launart.manager:launch:331 - Launching 5 components as async task...
chatgpt-qq-chatgpt-1  | 2023-02-14 02:37:56.237 | INFO     | graia.ariadne.service:base_telemetry:144 - 
chatgpt-qq-chatgpt-1  |     _         _           _
chatgpt-qq-chatgpt-1  |    / \   _ __(_) __ _  __| |_ __   ___
chatgpt-qq-chatgpt-1  |   / _ \ | '__| |/ _` |/ _` | '_ \ / _ \
chatgpt-qq-chatgpt-1  |  / ___ \| |  | | (_| | (_| | | | |  __/
chatgpt-qq-chatgpt-1  | /_/   \_\_|  |_|\__,_|\__,_|_| |_|\___|
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  | graia-amnesia: 0.7.1
chatgpt-qq-chatgpt-1  | graia-ariadne: 0.10.3
chatgpt-qq-chatgpt-1  | graia-broadcast: 0.19.1
chatgpt-qq-chatgpt-1  | launart: 0.6.3
chatgpt-qq-chatgpt-1  | statv: 0.3.2
chatgpt-qq-chatgpt-1  | 2023-02-14 02:37:56.237 | SUCCESS  | launart.manager:launch:384 - Layer #1:[http.client/aiohttp, cache.client/memcache] preparation completed.
chatgpt-qq-chatgpt-1  | 2023-02-14 02:37:56.237 | INFO     | __main__:start_background:116 - OpenAI 服务器登录中……
chatgpt-qq-chatgpt-1  | 2023-02-14 02:37:56.238 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
chatgpt-qq-chatgpt-1  | Traceback (most recent call last):
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/bot.py", line 124, in <module>
chatgpt-qq-chatgpt-1  |     app.launch_blocking()
chatgpt-qq-chatgpt-1  |     │   └ <classmethod object at 0x7ff8bf9b74f0>
chatgpt-qq-chatgpt-1  |     └ <graia.ariadne.app.Ariadne object at 0x7ff87bea37c0>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/graia/ariadne/app.py", line 313, in launch_blocking
chatgpt-qq-chatgpt-1  |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
chatgpt-qq-chatgpt-1  |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
chatgpt-qq-chatgpt-1  |     │   │              │                    │   │       └ <property object at 0x7ff8bf9b1450>
chatgpt-qq-chatgpt-1  |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7ff8c16fa520>
chatgpt-qq-chatgpt-1  |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1  |     │   │              └ <function Launart.launch_blocking at 0x7ff8c0b399d0>
chatgpt-qq-chatgpt-1  |     │   └ <launart.manager.Launart object at 0x7ff87b66d280>
chatgpt-qq-chatgpt-1  |     └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/launart/manager.py", line 494, in launch_blocking
chatgpt-qq-chatgpt-1  |     loop.run_until_complete(launch_task)
chatgpt-qq-chatgpt-1  |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.9/site-packages/launart/manager....
chatgpt-qq-chatgpt-1  |     │    └ <function BaseEventLoop.run_until_complete at 0x7ff8c0e6fb80>
chatgpt-qq-chatgpt-1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
chatgpt-qq-chatgpt-1  |     self.run_forever()
chatgpt-qq-chatgpt-1  |     │    └ <function BaseEventLoop.run_forever at 0x7ff8c0e6faf0>
chatgpt-qq-chatgpt-1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
chatgpt-qq-chatgpt-1  |     self._run_once()
chatgpt-qq-chatgpt-1  |     │    └ <function BaseEventLoop._run_once at 0x7ff8c0e72670>
chatgpt-qq-chatgpt-1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
chatgpt-qq-chatgpt-1  |     handle._run()
chatgpt-qq-chatgpt-1  |     │      └ <function Handle._run at 0x7ff8c0f95430>
chatgpt-qq-chatgpt-1  |     └ <Handle <TaskStepMethWrapper object at 0x7ff87b605b50>()>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
chatgpt-qq-chatgpt-1  |     self._context.run(self._callback, *self._args)
chatgpt-qq-chatgpt-1  |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt-qq-chatgpt-1  |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7ff87b605b50>()>
chatgpt-qq-chatgpt-1  |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt-qq-chatgpt-1  |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7ff87b605b50>()>
chatgpt-qq-chatgpt-1  |     │    └ <member '_context' of 'Handle' objects>
chatgpt-qq-chatgpt-1  |     └ <Handle <TaskStepMethWrapper object at 0x7ff87b605b50>()>
chatgpt-qq-chatgpt-1  | > File "/usr/local/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 191, in Executor
chatgpt-qq-chatgpt-1  |     result = await run_always_await(target_callable, **parameter_compile_result)
chatgpt-qq-chatgpt-1  |                    │                │                  └ {'loop': <_UnixSelectorEventLoop running=True closed=False debug=False>}
chatgpt-qq-chatgpt-1  |                    │                └ <function start_background at 0x7ff87b678670>
chatgpt-qq-chatgpt-1  |                    └ <function run_always_await at 0x7ff8c0aedaf0>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
chatgpt-qq-chatgpt-1  |     obj = await obj
chatgpt-qq-chatgpt-1  |                 └ <coroutine object start_background at 0x7ff87b606c40>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/bot.py", line 120, in start_background
chatgpt-qq-chatgpt-1  |     raise e
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/bot.py", line 117, in start_background
chatgpt-qq-chatgpt-1  |     chatbot.setup()
chatgpt-qq-chatgpt-1  |     │       └ <function setup at 0x7ff8bf9d30d0>
chatgpt-qq-chatgpt-1  |     └ <module 'chatbot' from '/app/chatbot.py'>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/app/chatbot.py", line 26, in setup
chatgpt-qq-chatgpt-1  |     bot = Chatbot(email=config.openai.email, password=config.openai.password, proxy=config.openai.proxy, insecure=config.openai.insecure_auth, session_token=config.openai.session_token, paid=config.openai.paid)
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      │               │      │      │                            │      │      │                   │      │      └ False
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      │               │      │      │                            │      │      │                   │      └ OpenAIAuth(email='793967421@qq.com', password='xxx, session_token=None, proxy='http://127.0.0.1:7890', insecure_auth...
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      │               │      │      │                            │      │      │                   └ Config(mirai=Mirai(qq=2546518385, api_key='1234567890', http_url='http://mirai:8080', ws_url='http://mirai:8080'), openai=Ope...
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      │               │      │      │                            │      │      └ None
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      │               │      │      │                            │      └ OpenAIAuth(email='793967421@qq.com', password='xxx', session_token=None, proxy='http://127.0.0.1:7890', insecure_auth...
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      │               │      │      │                            └ Config(mirai=Mirai(qq=2546518385, api_key='1234567890', http_url='http://mirai:8080', ws_url='http://mirai:8080'), openai=Ope...
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      │               │      │      └ False
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      │               │      └ OpenAIAuth(email='793967421@qq.com', password='xxx', session_token=None, proxy='http://127.0.0.1:7890', insecure_auth...
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      │               └ Config(mirai=Mirai(qq=2546518385, api_key='1234567890', http_url='http://mirai:8080', ws_url='http://mirai:8080'), openai=Ope...
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      │      └ 'http://127.0.0.1:7890'
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               │      └ OpenAIAuth(email='793967421@qq.com', password='xxx', session_token=None, proxy='http://127.0.0.1:7890', insecure_auth...
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      │               └ Config(mirai=Mirai(qq=2546518385, api_key='1234567890', http_url='http://mirai:8080', ws_url='http://mirai:8080'), openai=Ope...
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      │      └ 'xxx'
chatgpt-qq-chatgpt-1  |           │             │      │      │               │      └ OpenAIAuth(email='793967421@qq.com', password='xxx', session_token=None, proxy='http://127.0.0.1:7890', insecure_auth...
chatgpt-qq-chatgpt-1  |           │             │      │      │               └ Config(mirai=Mirai(qq=2546518385, api_key='1234567890', http_url='http://mirai:8080', ws_url='http://mirai:8080'), openai=Ope...
chatgpt-qq-chatgpt-1  |           │             │      │      └ '793967421@qq.com'
chatgpt-qq-chatgpt-1  |           │             │      └ OpenAIAuth(email='793967421@qq.com', password='xxx', session_token=None, proxy='http://127.0.0.1:7890', insecure_auth...
chatgpt-qq-chatgpt-1  |           │             └ Config(mirai=Mirai(qq=2546518385, api_key='1234567890', http_url='http://mirai:8080', ws_url='http://mirai:8080'), openai=Ope...
chatgpt-qq-chatgpt-1  |           └ <class 'revChatGPT.V2.Chatbot'>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/revChatGPT/V2.py", line 135, in __init__
chatgpt-qq-chatgpt-1  |     self.login(email, password, proxy, insecure, session_token)
chatgpt-qq-chatgpt-1  |     │    │     │      │         │      │         └ None
chatgpt-qq-chatgpt-1  |     │    │     │      │         │      └ False
chatgpt-qq-chatgpt-1  |     │    │     │      │         └ 'http://127.0.0.1:7890'
chatgpt-qq-chatgpt-1  |     │    │     │      └ 'xxx'
chatgpt-qq-chatgpt-1  |     │    │     └ '793967421@qq.com'
chatgpt-qq-chatgpt-1  |     │    └ <function Chatbot.login at 0x7ff8900a11f0>
chatgpt-qq-chatgpt-1  |     └ <revChatGPT.V2.Chatbot object at 0x7ff87b605eb0>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/revChatGPT/V2.py", line 215, in login
chatgpt-qq-chatgpt-1  |     auth.begin()
chatgpt-qq-chatgpt-1  |     │    └ <function OpenAIAuth.begin at 0x7ff8bd645310>
chatgpt-qq-chatgpt-1  |     └ <OpenAIAuth.OpenAIAuth.OpenAIAuth object at 0x7ff87b605f40>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 76, in begin
chatgpt-qq-chatgpt-1  |     response = self.session.get(
chatgpt-qq-chatgpt-1  |                │    │       └ <function Session.get at 0x7ff8bd640d30>
chatgpt-qq-chatgpt-1  |                │    └ <tls_client.sessions.Session object at 0x7ff87b620040>
chatgpt-qq-chatgpt-1  |                └ <OpenAIAuth.OpenAIAuth.OpenAIAuth object at 0x7ff87b605f40>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/tls_client/sessions.py", line 363, in get
chatgpt-qq-chatgpt-1  |     return self.execute_request(method="GET", url=url, **kwargs)
chatgpt-qq-chatgpt-1  |            │    │                                 │      └ {'headers': {'Host': 'ask.openai.com', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Age...
chatgpt-qq-chatgpt-1  |            │    │                                 └ 'https://explorer.api.openai.com/'
chatgpt-qq-chatgpt-1  |            │    └ <function Session.execute_request at 0x7ff8bd640ca0>
chatgpt-qq-chatgpt-1  |            └ <tls_client.sessions.Session object at 0x7ff87b620040>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/tls_client/sessions.py", line 346, in execute_request
chatgpt-qq-chatgpt-1  |     raise TLSClientExeption(response_object["body"])
chatgpt-qq-chatgpt-1  |           │                 └ {'id': '8021b3d3-17c5-461b-9dec-b3d62e00711b', 'sessionId': '61a08a7f-7abc-415b-9af1-7b33dee29c93', 'status': 0, 'target': ''...
chatgpt-qq-chatgpt-1  |           └ <class 'tls_client.exceptions.TLSClientExeption'>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  | tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://explorer.api.openai.com/": dial tcp 127.0.0.1:7890: connect: connection refused
chatgpt-qq-chatgpt-1  | 2023-02-14 02:37:56.244 | SUCCESS  | launart.manager:launch:384 - Layer #3:[elizabeth.service] preparation completed.
chatgpt-qq-chatgpt-1  | 2023-02-14 02:37:56.244 | INFO     | launart.manager:launch:389 - All components prepared, start blocking phase.
chatgpt-qq-chatgpt-1  | 2023-02-14 02:37:56.246 | WARNING  | graia.amnesia.builtins.aiohttp:connection_manage:229 - ClientConnectorError(ConnectionKey(host='mirai', port=8080, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('172.21.0.2', 8080)"))

```

**Comment by lss233** [comment]
`connection refused`
没连上代理呀。

**Comment by woltium** [comment]
好的 我代理换好后这个问题解决了 不过unknowerror了 :D  躺着等解决办法了
