### ISSUE TITLE
1.6.0报错"unknown error"

### ISSUE THREAD

**Issue by tamakyi** [lss233/chatgpt-mirai-qq-bot#116]
在国外vps运行的，手动部署，今天更新之后前几个小时运行没问题，后面开始报错。
报错内容如下:
```
error: Unknown error
/root/miniconda3/envs/chatgpt/lib/python3.10/site-packages/httpx/_client.py:1978: UserWarning: Unclosed <httpx.AsyncClient object at 0x7f48712863e0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
  warnings.warn(
2023-02-14 11:14:02.381 | ERROR    | __main__:handle_message:79 - Unknown error
Traceback (most recent call last):

  File "/root/chatgpt-mirai-qq-bot/bot.py", line 124, in <module>
    app.launch_blocking()
    │   └ <classmethod(<function Ariadne.launch_blocking at 0x7f48a0d39240>)>
    └ <graia.ariadne.app.Ariadne object at 0x7f4871674ca0>

  File "/root/miniconda3/envs/chatgpt/lib/python3.10/site-packages/graia/ariadne/app.py", line 313, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x7f48a0d3c720>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7f48708deec0>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x7f48a1f7e050>
    │   └ <launart.manager.Launart object at 0x7f48712b53c0>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "/root/miniconda3/envs/chatgpt/lib/python3.10/site-packages/launart/manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /root/miniconda3/envs/chatgpt/lib/python3.10/site-packa...
    │    └ <function BaseEventLoop.run_until_complete at 0x7f48a2244040>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/root/miniconda3/envs/chatgpt/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f48a223bf40>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/root/miniconda3/envs/chatgpt/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f48a2245ab0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/root/miniconda3/envs/chatgpt/lib/python3.10/asyncio/base_events.py", line 1906, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f48a2788e50>
    └ <Handle <TaskStepMethWrapper object at 0x7f485f675a80>()>
  File "/root/miniconda3/envs/chatgpt/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f485f675a80>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f485f675a80>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f485f675a80>()>
  File "/root/miniconda3/envs/chatgpt/lib/python3.10/site-packages/graia/broadcast/__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {'group': Group(id=777163254, name='test', account_perm=<管理员>), 'source': Source(id=11072, time=datetime.datetime(2023, 2, 14,...
                   │                └ <function group_message_listener at 0x7f48712ab400>
                   └ <function run_always_await at 0x7f48a1de0160>
  File "/root/miniconda3/envs/chatgpt/lib/python3.10/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object group_message_listener at 0x7f4870a1af10>

  File "/root/chatgpt-mirai-qq-bot/bot.py", line 95, in group_message_listener
    response = await handle_message(group, f"group-{group.id}", chain.display, source)
                     │              │                           │     │        └ Source(id=11072, time=datetime.datetime(2023, 2, 14, 3, 14, 1, tzinfo=datetime.timezone.utc), type='Source')
                     │              │                           │     └ <property object at 0x7f48a100f2e0>
                     │              │                           └ MessageChain([Plain(text='你还好吗')])
                     │              └ Group(id=777163254, name='test', account_perm=<管理员>)
                      <function handle_message at 0x7f48712ab250>

> File "/root/chatgpt-mirai-qq-bot/bot.py", line 72, in handle_message
    resp = await session.get_chat_response(message)
                 │       │                 └ '你还好吗'
                 │       └ <function ChatSession.get_chat_response at 0x7f48708f5ab0>
                 └ <chatbot.ChatSession object at 0x7f48712869b0>

  File "/root/chatgpt-mirai-qq-bot/chatbot.py", line 90, in get_chat_response
    async for data in bot.ask(prompt=message, conversation_id=self.conversation_id):
                      │   │          │                        │    └ 'group-777163254'
                      │   │          │                        └ <chatbot.ChatSession object at 0x7f48712869b0>
                      │   │          └ '你还好吗'
                      │   └ <function Chatbot.ask at 0x7f489c2468c0>
                      └ <revChatGPT.V2.Chatbot object at 0x7f4871287880>

  File "/root/miniconda3/envs/chatgpt/lib/python3.10/site-packages/revChatGPT/V2.py", line 169, in ask
    raise Exception("Unknown error")

Exception: Unknown error
```

**Comment by lss233** [comment]
和这个有关： 
https://github.com/acheong08/ChatGPT/issues/719
你可以先使用 1.5.4 版或者 1.6-RC3。

**Comment by LayerLwb** [comment]
> 和这个有关： [acheong08/ChatGPT#719](https://github.com/acheong08/ChatGPT/issues/719) 你可以先使用 1.5.4 版或者 1.6-RC3。

一样的问题，请问如何使用一键部署脚本部署1.5.4

**Comment by tamakyi** [comment]
回退1.6rc3提示ModuleNotFoundError: No module named 'revChatGPT.Official'

**Comment by lss233** [comment]
1.6.0 已恢复

**Comment by tamakyi** [comment]
> 1.6.0 已恢复

确认已经回复了！辛苦了！

**Comment by tamakyi** [comment]
现在能正常登录了，但是机器人回复的内容有点异常，只会复述用户所说的话。
后台显示:
```
/root/miniconda3/envs/chatgpt/lib/python3.10/site-packages/httpx/_client.py:1978: UserWarning: Unclosed <httpx.AsyncClient object at 0x7fa5ad05d090>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
  warnings.warn(
2023-02-14 13:21:33.815 | DEBUG    | __main__:handle_message:74 - group-777163254 - 今天是星期几
2023-02-14 13:21:34.146 | INFO     | graia.ariadne.model:log:83 - 1726209469: [SEND][半狼团(777163254)] <- 今天是星期几
```

**Comment by lss233** [comment]
> 现在能正常登录了，但是机器人回复的内容有点异常，只会复述用户所说的话。 后台显示:
> 
> ```
> /root/miniconda3/envs/chatgpt/lib/python3.10/site-packages/httpx/_client.py:1978: UserWarning: Unclosed <httpx.AsyncClient object at 0x7fa5ad05d090>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.
>   warnings.warn(
> 2023-02-14 13:21:33.815 | DEBUG    | __main__:handle_message:74 - group-777163254 - 今天是星期几
> 2023-02-14 13:21:34.146 | INFO     | graia.ariadne.model:log:83 - 1726209469: [SEND][半狼团(777163254)] <- 今天是星期几
> ```

已知问题

**Comment by lss233** [comment]
现在能用的还是 1.5.4 和 1.6-RC3
Linux 一键安装脚本：
```bash
bash -c "$(curl -fsSL https://gist.githubusercontent.com/lss233/54f0f794f2157665768b1bdcbed837fd/raw/2299c137b2ffa9569f8cfb5efe965d921027b18d/chatgpt-mirai-installer-154-16RC3.sh)"
```
Windows 版本请自行在 Releases 页面下载。
v1.6.0 版暂时 unknown error

**Comment by codeses** [comment]
请问 docker-compose 目前有办法解决吗

**Comment by lss233** [comment]
> 请问 docker-compose 目前有办法解决吗

 就用我上面发的那个脚本，装旧版。

**Comment by QAQKB** [comment]
问话一直显示这个
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
Unknown error

国内服务器，搭了梯子

**Comment by hyj8247878** [comment]
> 问话一直显示这个 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。 Unknown error
> 
> 国内服务器，搭了梯子

同

**Comment by LayerLwb** [comment]
> 现在能用的还是 1.5.4 (浏览器版) 和 1.6-RC3 (API 版) Linux 一键安装脚本：
> 
> ```shell
> bash -c "$(curl -fsSL https://gist.githubusercontent.com/lss233/54f0f794f2157665768b1bdcbed837fd/raw/chatgpt-mirai-installer-154-16RC3.sh)"
> ```
> 
> 更新日志及 Windows 版本下载地址（建议阅读）：
> 
> * 1.5.4：       https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.5.4
> * 1.6-RC3：  https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.6-RC3
> 
> 如果你使用 1.6-RC3，可能会遇到这个问题： #82
> 
> v1.6.0 版暂时 unknown error

1.5.4版本遭遇浏览器登录后无反应：#108 ，网页版已不可用，网页方案似乎陷入了死循环，目前仅API可用

**Comment by lss233** [comment]
1.6.0 版已不可用。

**Comment by lss233** [comment]
> > 现在能用的还是 1.5.4 (浏览器版) 和 1.6-RC3 (API 版) Linux 一键安装脚本：
> > ```shell
> > bash -c "$(curl -fsSL https://gist.githubusercontent.com/lss233/54f0f794f2157665768b1bdcbed837fd/raw/chatgpt-mirai-installer-154-16RC3.sh)"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 更新日志及 Windows 版本下载地址（建议阅读）：
> > 
> > * 1.5.4：       https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.5.4
> > * 1.6-RC3：  https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.6-RC3
> > 
> > 如果你使用 1.6-RC3，可能会遇到这个问题： #82
> > v1.6.0 版暂时 unknown error
> 
> 1.5.4版本遭遇浏览器登录后无反应，浏览器也没有正常退出，日志没有任何提示：#108 ，网页版已不可用，网页方案似乎陷入了死循环，目前仅API可用

1.5.x 系列最新版本已提供方法修复此问题。
