### ISSUE TITLE
bing回复报错

### ISSUE THREAD

**Issue by ZJY303** [lss233/chatgpt-mirai-qq-bot#1200]
2023-09-13 13:01:48.773 | DEBUG    | platforms.onebot_bot:_:148 - 私聊消息：切换AI bing-b
2023-09-13 13:01:48.774 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-09-13 13:01:48.775 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-09-13 13:01:48.779 | DEBUG    | middlewares.timeout:create_timeout_task:61 - [Timeout] 开始计时……
2023-09-13 13:01:49.861 | ERROR    | middlewares.timeout:handle_request:36 - 发生错误: 'conversationSignature'
2023-09-13 13:01:49.861 | ERROR    | universal:handle_message:297 - 'conversationSignature'
Traceback (most recent call last):

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\bot.py", line 58, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai...
    │    │                  │       └ <function gather at 0x0000012DE03B8310>
    │    │                  └ <module 'asyncio' from 'C:\\Users\\32279\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000012DE03C0F70>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\32279\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000012DE1BF1FC0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\32279\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\32279\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000012DE03C29E0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\32279\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000012DE035DBD0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\32279\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\platforms\onebot_bot.py", line 151, in _
    await handle_message(
          └ <function handle_message at 0x0000012DEB3BDFC0>

> File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 271, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x0000012DEB420940>
          │      │           │       │        └ None
          │      │           │       └ <method 'strip' of 'str' objects>
          │      │           └ '切换AI bing-b'
          │      └ 'friend-3227963745'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000012DEB420AF0>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000012DEB420A60>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x0000012DEB420940>
          │ │              │           └ '切换AI bing-b'
          │ │              └ 'friend-3227963745'
          │ └ <function MiddlewareConcurrentLock.handle_request at 0x0000012DEB3BE680>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x0000012DEB3C9BD0>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x0000012DEB420940>
          │      │           │       └ None
          │      │           └ '切换AI bing-b'
          │      └ 'friend-3227963745'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000012DEB420A60>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000012DEB4204C0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x0000012DEB420940>
          │ │              │           └ '切换AI bing-b'
          │ │              └ 'friend-3227963745'
          │ └ <function Middleware.handle_request at 0x0000012DEB3BD750>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x0000012DEB3C8D60>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x0000012DEB420940>
          │      │           │       └ None
          │      │           └ '切换AI bing-b'
          │      └ 'friend-3227963745'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000012DEB4204C0>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000012DEB420550>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x0000012DEB420940>
          │ │              │           └ '切换AI bing-b'
          │ │              └ 'friend-3227963745'
          │ └ <function MiddlewareRatelimit.handle_request at 0x0000012DEB3BD990>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x0000012DEB3C8D30>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\ratelimit.py", line 23, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x0000012DEB420940>
          │      │           │       └ None
          │      │           └ '切换AI bing-b'
          │      └ 'friend-3227963745'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000012DEB420550>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x0000012DEB4209D0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x0000012DEB420940>
          │ │              │           └ '切换AI bing-b'
          │ │              └ 'friend-3227963745'
          │ └ <function MiddlewareTimeout.handle_request at 0x0000012DEB3BE7A0>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x0000012DEB3C8D00>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\timeout.py", line 40, in handle_request
    raise e

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
          │       │        │          │      │        └ 600.0
          │       │        │          │      └ Response(mode='mixed', buffer_delay=15, default_ai='chatgpt-api', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一 段新的会话，或者发送 “回滚...
          │       │        │          └ <unprintable Config object>
          │       │        └ <Task finished name='Task-26' coro=<handle_message.<locals>.request() done, defined at F:\GPT\Windows-quickstart-go-cqhttp-re...
          │       └ <function wait_for at 0x0000012DE0397D90>
          └ <module 'asyncio' from 'C:\\Users\\32279\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>

  File "C:\Users\32279\Miniconda3\envs\chatgpt\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
           │   └ <method 'result' of '_asyncio.Task' objects>
           └ <Task finished name='Task-26' coro=<handle_message.<locals>.request() done, defined at F:\GPT\Windows-quickstart-go-cqhttp-re...

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 120, in request
    await conversation_handler.create(
          │                    └ <function ConversationHandler.create at 0x0000012DEB3BD5A0>
          └ <conversation.ConversationHandler object at 0x0000012DEB499720>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\conversation.py", line 294, in create
    conversation = ConversationContext(_type, self.session_id)
                   │                   │      │    └ 'friend-3227963745'
                   │                   │      └ <conversation.ConversationHandler object at 0x0000012DEB499720>
                   │                   └ 'bing-b'
                   └ <class 'conversation.ConversationContext'>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\conversation.py", line 100, in __init__
    self.adapter = BingAdapter(self.session_id, ConversationStyle.balanced)
    │              │           │    │           │                 └ <ConversationStyle.balanced: ['nlu_direct_response_filter', 'deepleo', 'disable_emoji_spoken_text', 'responsible_ai_policy_23...
    │              │           │    │           └ <enum 'ConversationStyle'>
    │              │           │    └ 'friend-3227963745'
    │              │           └ <conversation.ConversationContext object at 0x0000012DEB499E10>
    │              └ <class 'adapter.ms.bing.BingAdapter'>
    └ <conversation.ConversationContext object at 0x0000012DEB499E10>

  File "F:\GPT\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\adapter\ms\bing.py", line 47, in __init__
    self.bot = EdgeChatbot(cookies=self.cookieData, proxy=account.proxy)
    │          │                   │    │                 │       └ 'http://127.0.0.1:7890'
    │          │                   │    │                 └ BingCookiePath(cookie_content='[{"domain":".bing.com","expirationDate":1729133854.964622,"hostOnly":false,"httpOnly":false,"n...
    │          │                   │    └ [{'domain': '.bing.com', 'expirationDate': 1729133854.964622, 'hostOnly': False, 'httpOnly': False, 'name': 'SRCHUSR', 'path'...
    │          │                   └ <adapter.ms.bing.BingAdapter object at 0x0000012DEB499C60>
    │          └ <class 'EdgeGPT.EdgeGPT.Chatbot'>
    └ <adapter.ms.bing.BingAdapter object at 0x0000012DEB499C60>

  File "C:\Users\32279\Miniconda3\envs\chatgpt\lib\site-packages\EdgeGPT\EdgeGPT.py", line 28, in __init__
    self.chat_hub: ChatHub = ChatHub(
    │                        └ <class 'EdgeGPT.chathub.ChatHub'>
    └ <EdgeGPT.EdgeGPT.Chatbot object at 0x0000012DEB499B10>

  File "C:\Users\32279\Miniconda3\envs\chatgpt\lib\site-packages\EdgeGPT\chathub.py", line 42, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           │            └ {'conversationId': '51D|BingProd|C86F37A213D3326A99613DD3932E12E85364FD422E2851F1756908506F637721', 'clientId': '985154006918...
                           └ <EdgeGPT.conversation.Conversation object at 0x0000012DEB499E40>

KeyError: 'conversationSignature'
2023-09-13 13:01:49.890 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
原因：'conversationSignature'

**Comment by lss233** [comment]
v3 已修复

**Comment by pandoradevin** [comment]
conversationSignature

**Comment by pandoradevin** [comment]
V3不会安装，没有docker一键安装的链接
