### ISSUE TITLE
[BUG] 使用指令的时候：出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。 原因：'conversationSignature'

### ISSUE THREAD

**Issue by zsanjin-p** [lss233/chatgpt-mirai-qq-bot#1208]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
给机器人发送ping、切换ai等指令的时候，都出现：出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
原因：'conversationSignature'

前两天还正常能用，今天就一直报错了

人呢
chatgpt-qq-chatgpt-1     | 2023-09-27 14:18:34.679 | ERROR    | universal:handle_message:297 - 'conversationSignature'
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/bot.py", line 58, in <module>
chatgpt-qq-chatgpt-1     |     loop.run_until_complete(asyncio.gather(*bots))
chatgpt-qq-chatgpt-1     |     │    │                  │       │       └ [<Task pending name='Task-3' coro=<start_task() running at /app/platforms/onebot_bot.py:356> wait_for=<_GatheringFuture pendi...
chatgpt-qq-chatgpt-1     |     │    │                  │       └ <function gather at 0x7f06647023b0>
chatgpt-qq-chatgpt-1     |     │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7f0664722f80>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
chatgpt-qq-chatgpt-1     |     self.run_forever()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7f0664722ef0>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
chatgpt-qq-chatgpt-1     |     self._run_once()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7f0664724a60>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
chatgpt-qq-chatgpt-1     |     handle._run()
chatgpt-qq-chatgpt-1     |     │      └ <function Handle._run at 0x7f06646d4430>
chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7f061f8816c0>()>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
chatgpt-qq-chatgpt-1     |     self._context.run(self._callback, *self._args)
chatgpt-qq-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f061f8816c0>()>
chatgpt-qq-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7f061f8816c0>()>
chatgpt-qq-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7f061f8816c0>()>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/platforms/onebot_bot.py", line 183, in _
chatgpt-qq-chatgpt-1     |     await handle_message(
chatgpt-qq-chatgpt-1     |           └ <function handle_message at 0x7f061f852710>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | > File "/app/universal.py", line 263, in handle_message
chatgpt-qq-chatgpt-1     |     conversation_handler.current_conversation = await conversation_handler.create(
chatgpt-qq-chatgpt-1     |     │                    │                            │                    └ <function ConversationHandler.create at 0x7f061f851e10>
chatgpt-qq-chatgpt-1     |     │                    │                            └ <conversation.ConversationHandler object at 0x7f061ea93f10>
chatgpt-qq-chatgpt-1     |     │                    └ None
chatgpt-qq-chatgpt-1     |     └ <conversation.ConversationHandler object at 0x7f061ea93f10>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 296, in create
chatgpt-qq-chatgpt-1     |     conversation = ConversationContext(_type, self.session_id)
chatgpt-qq-chatgpt-1     |                    │                   │      │    └ 'group-244435406'
chatgpt-qq-chatgpt-1     |                    │                   │      └ <conversation.ConversationHandler object at 0x7f061ea93f10>
chatgpt-qq-chatgpt-1     |                    │                   └ 'bard'
chatgpt-qq-chatgpt-1     |                    └ <class 'conversation.ConversationContext'>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 124, in __init__
chatgpt-qq-chatgpt-1     |     self.drawing_adapter = BingAdapter(self.session_id, ConversationStyle.creative)
chatgpt-qq-chatgpt-1     |     │    │                 │           │    │           │                 └ <ConversationStyle.creative: ['nlu_direct_response_filter', 'deepleo', 'disable_emoji_spoken_text', 'responsible_ai_policy_23...
chatgpt-qq-chatgpt-1     |     │    │                 │           │    │           └ <enum 'ConversationStyle'>
chatgpt-qq-chatgpt-1     |     │    │                 │           │    └ 'group-244435406'
chatgpt-qq-chatgpt-1     |     │    │                 │           └ <conversation.ConversationContext object at 0x7f061ea2ae60>
chatgpt-qq-chatgpt-1     |     │    │                 └ <class 'adapter.ms.bing.BingAdapter'>
chatgpt-qq-chatgpt-1     |     │    └ None
chatgpt-qq-chatgpt-1     |     └ <conversation.ConversationContext object at 0x7f061ea2ae60>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/adapter/ms/bing.py", line 47, in __init__
chatgpt-qq-chatgpt-1     |     self.bot = EdgeChatbot(cookies=self.cookieData, proxy=account.proxy)
chatgpt-qq-chatgpt-1     |     │          │                   │    │                 │       └ None
chatgpt-qq-chatgpt-1     |     │          │                   │    │                 └ BingCookiePath(cookie_content='[{"domain":".bing.com","expirationDate":1726585277.391743,"hostOnly":false,"httpOnly":false,"n...
chatgpt-qq-chatgpt-1     |     │          │                   │    └ [{'domain': '.bing.com', 'expirationDate': 1726585277.391743, 'hostOnly': False, 'httpOnly': False, 'name': 'SnrOvr', 'path':...
chatgpt-qq-chatgpt-1     |     │          │                   └ <adapter.ms.bing.BingAdapter object at 0x7f061ea2afb0>
chatgpt-qq-chatgpt-1     |     │          └ <class 'EdgeGPT.EdgeGPT.Chatbot'>
chatgpt-qq-chatgpt-1     |     └ <adapter.ms.bing.BingAdapter object at 0x7f061ea2afb0>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/site-packages/EdgeGPT/EdgeGPT.py", line 28, in __init__
chatgpt-qq-chatgpt-1     |     self.chat_hub: ChatHub = ChatHub(
chatgpt-qq-chatgpt-1     |     │                        └ <class 'EdgeGPT.chathub.ChatHub'>
chatgpt-qq-chatgpt-1     |     └ <EdgeGPT.EdgeGPT.Chatbot object at 0x7f061ea28220>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.10/site-packages/EdgeGPT/chathub.py", line 42, in __init__
chatgpt-qq-chatgpt-1     |     conversation_signature=conversation.struct["conversationSignature"],
chatgpt-qq-chatgpt-1     |                            │            └ {'conversationId': '51D|BingProd|D06EAD568BBEBC82619FC65D6E627A64D988006B7F9D4FFB1A5596CB5B19A5D9', 'clientId': '985157447901...
chatgpt-qq-chatgpt-1     |                            └ <EdgeGPT.conversation.Conversation object at 0x7f061ea2b190>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | KeyError: 'conversationSignature'
chatgpt-qq-chatgpt-1     | 2023-09-27 14:18:34.697 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
chatgpt-qq-chatgpt-1     | 原因：'conversationSignature'
chatgpt-qq-chatgpt-1     | 2023-09-27 14:18:35.461 | DEBUG    | platforms.onebot_bot:_:178 - 丢弃群聊消息：[CQ:reply,id=-1430127557]出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
chatgpt-qq-chatgpt-1     | 原因：'conversationSignature'（原因：不符合触发前缀）

**运行环境:**  
- 操作系统：centos7
- Docker： 24.0.6
- 项目版本：2.5.3

**复现步骤**  
描述你是如何触发这个 BUG 的
直接发送ping等指令

**Comment by zsanjin-p** [comment]
问题在bing上面，不知道为什么会这样 ，明明没动bing的配置，昨天还好好的

**Comment by pandoradevin** [comment]
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
'conversationSignature'

我也是这个，而且这个会影响其他AI运行

**Comment by MyNameErala** [comment]
一样的问题，bing引出的问题导致指令ping都无法正常出结果，也会影响其他AI输出😢

**Comment by Benson80** [comment]
出现这个错误提示conversationSignature，是Bing的问题，怎么解决？
