### ISSUE TITLE
[BUG] BOT无法使用bing

### ISSUE THREAD

**Issue by KKKKKKD32** [lss233/chatgpt-mirai-qq-bot#1212]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

KKK  
hello
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
原因：Authentication failed
控制台:Status code: 403

https://edgeservices.bing.com/edgesvc/turing/conversation/create
2023-09-30 14:34:35.949 | ERROR    | universal:handle_message:297 - Authentication failed
Traceback (most recent call last):

  File "E:\bot\chatgpt-mirai-qq-bot\bot.py", line 58, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at E:\bot\chatgpt-mirai-qq-bot\platforms\onebot_bot.py:356> wait_for=...
    │    │                  │       └ <function gather at 0x000001ACD228DAB0>
    │    │                  └ <module 'asyncio' from 'C:\\Users\\K\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x000001ACD22AE710>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001ACD3ADF640>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001ACD22B01F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001ACD2247520>
    └ <Handle <TaskStepMethWrapper object at 0x000001ACFDB2D9F0>()>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000001ACFDB2D9F0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000001ACFDB2D9F0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001ACFDB2D9F0>()>

  File "E:\bot\chatgpt-mirai-qq-bot\platforms\onebot_bot.py", line 151, in _
    await handle_message(
          └ <function handle_message at 0x000001ACFDA38B80>

> File "E:\bot\chatgpt-mirai-qq-bot\universal.py", line 263, in handle_message
    conversation_handler.current_conversation = await conversation_handler.create(
    │                    │                            │                    └ <function ConversationHandler.create at 0x000001ACFDA38280>
    │                    │                            └ <conversation.ConversationHandler object at 0x000001ACFDB2DD50>
    │                    └ None
    └ <conversation.ConversationHandler object at 0x000001ACFDB2DD50>

  File "E:\bot\chatgpt-mirai-qq-bot\conversation.py", line 294, in create
    conversation = ConversationContext(_type, self.session_id)
                   │                   │      │    └ 'friend-3573908988'
                   │                   │      └ <conversation.ConversationHandler object at 0x000001ACFDB2DD50>
                   │                   └ 'bing'
                   └ <class 'conversation.ConversationContext'>

  File "E:\bot\chatgpt-mirai-qq-bot\conversation.py", line 96, in __init__
    self.adapter = BingAdapter(self.session_id)
    │              │           │    └ 'friend-3573908988'
    │              │           └ <conversation.ConversationContext object at 0x000001ACFDB2DDB0>
    │              └ <class 'adapter.ms.bing.BingAdapter'>
    └ <conversation.ConversationContext object at 0x000001ACFDB2DDB0>

  File "E:\bot\chatgpt-mirai-qq-bot\adapter\ms\bing.py", line 47, in __init__
    self.bot = EdgeChatbot(cookies=self.cookieData, proxy=account.proxy)
    │          │                   │    │                 │       └ None
    │          │                   │    │                 └ BingCookiePath(cookie_content='[{"domain":".bing.com","expirationDate":1730592295.273543,"hostOnly":false,"httpOnly":false,"n...
    │          │                   │    └ [{'domain': '.bing.com', 'expirationDate': 1730592295.273543, 'hostOnly': False, 'httpOnly': False, 'name': 'SRCHUSR', 'path'...
    │          │                   └ <adapter.ms.bing.BingAdapter object at 0x000001ACFDB2DDE0>
    │          └ <class 'EdgeGPT.EdgeGPT.Chatbot'>
    └ <adapter.ms.bing.BingAdapter object at 0x000001ACFDB2DDE0>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\site-packages\EdgeGPT\EdgeGPT.py", line 29, in __init__
    Conversation(self.proxy, cookies=cookies),
    │            │    │              └ [{'domain': '.bing.com', 'expirationDate': 1730592295.273543, 'hostOnly': False, 'httpOnly': False, 'name': 'SRCHUSR', 'path'...
    │            │    └ None
    │            └ <EdgeGPT.EdgeGPT.Chatbot object at 0x000001ACFDB2D420>
    └ <class 'EdgeGPT.conversation.Conversation'>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\site-packages\EdgeGPT\conversation.py", line 55, in __init__
    raise Exception("Authentication failed")

Exception: Authentication failed
2023-09-30 14:34:35.963 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见

**运行环境:**  
- 操作系统：Windows10
- 项目版本：2.5.3

**复现步骤**  
描述你是如何触发这个 BUG 的
1. Go to '..运行程序后和机器人聊天.'

**截图**  
(https://github.com/lss233/chatgpt-mirai-qq-bot/assets/146516706/663129b0-ca67-4b86-acef-2ce0c2e4116a)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by p1aintiff** [comment]
config.cfg 中在bing账号下添加wss，使用edge浏览器重新登录，重新获取cookie。

**Comment by KKKKKKD32** [comment]
wws是什么?







                       
原始邮件
                       
                     

发件人："p1aintiff"< ***@***.*** &gt;;

发件时间：2023/9/30 23:33

收件人："lss233/chatgpt-mirai-qq-bot"< ***@***.*** &gt;;

抄送人："KKKKKKD32"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [lss233/chatgpt-mirai-qq-bot] [BUG] BOT无法使用bing (Issue #1212)




 
config.cfg 中在bing账号下添加wss，使用edge浏览器重新登录，重新获取cookie。

**Comment by KKKKKKD32** [comment]
请问配置了接入点还要挂代理吗







                       
原始邮件
                       
                     

发件人："p1aintiff"< ***@***.*** &gt;;

发件时间：2023/9/30 23:33

收件人："lss233/chatgpt-mirai-qq-bot"< ***@***.*** &gt;;

抄送人："KKKKKKD32"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [lss233/chatgpt-mirai-qq-bot] [BUG] BOT无法使用bing (Issue #1212)




 
config.cfg 中在bing账号下添加wss，使用edge浏览器重新登录，重新获取cookie。

**Comment by KKKKKKD32** [comment]
现在显示: File "C:\Users\K\Miniconda3\envs\chatgpt\lib\site-packages\EdgeGPT\conversation.py", line 57, in __init__
    self.struct = response.json()
    │    │        │        └ <function Response.json at 0x0000024451B55240>
    │    │        └ <Response [200 OK]>
    │    └ {'conversationId': None, 'clientId': None, 'conversationSignature': None, 'result': {'value': 'Success', 'message': None}}
    └ <EdgeGPT.conversation.Conversation object at 0x000002447A39C670>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           │       │     │    │       └ {}
           │       │     │    └ <property object at 0x0000024451B47830>
           │       │     └ <Response [200 OK]>
           │       └ <function loads at 0x0000024450703B50>
           └ <module 'json' from 'C:\\Users\\K\\Miniconda3\\envs\\chatgpt\\lib\\json\\__init__.py'>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ ''
           │                └ <function JSONDecoder.decode at 0x0000024450703400>
           └ <json.decoder.JSONDecoder object at 0x00000244507066B0>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ ''
               │    │          │      └ <built-in method match of re.Pattern object at 0x0000024450721700>
               │    │          └ ''
               │    └ <function JSONDecoder.raw_decode at 0x0000024450703490>
               └ <json.decoder.JSONDecoder object at 0x00000244507066B0>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ ''
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "E:\bot\chatgpt-mirai-qq-bot\bot.py", line 58, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at E:\bot\chatgpt-mirai-qq-bot\platforms\onebot_bot.py:356> wait_for=...
    │    │                  │       └ <function gather at 0x000002444E96DAB0>
    │    │                  └ <module 'asyncio' from 'C:\\Users\\K\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x000002444E98E710>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000244501BF640>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002444E9901F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002444E927520>
    └ <Handle <TaskStepMethWrapper object at 0x000002447A2CCC40>()>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000002447A2CCC40>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x000002447A2CCC40>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000002447A2CCC40>()>

  File "E:\bot\chatgpt-mirai-qq-bot\platforms\onebot_bot.py", line 151, in _
    await handle_message(
          └ <function handle_message at 0x000002447A292560>

> File "E:\bot\chatgpt-mirai-qq-bot\universal.py", line 263, in handle_message
    conversation_handler.current_conversation = await conversation_handler.create(
    │                    │                            │                    └ <function ConversationHandler.create at 0x000002447A291C60>
    │                    │                            └ <conversation.ConversationHandler object at 0x000002447A391C00>
    │                    └ None
    └ <conversation.ConversationHandler object at 0x000002447A391C00>

  File "E:\bot\chatgpt-mirai-qq-bot\conversation.py", line 294, in create
    conversation = ConversationContext(_type, self.session_id)
                   │                   │      │    └ 'friend-3573908988'
                   │                   │      └ <conversation.ConversationHandler object at 0x000002447A391C00>
                   │                   └ 'bing'
                   └ <class 'conversation.ConversationContext'>

  File "E:\bot\chatgpt-mirai-qq-bot\conversation.py", line 96, in __init__
    self.adapter = BingAdapter(self.session_id)
    │              │           │    └ 'friend-3573908988'
    │              │           └ <conversation.ConversationContext object at 0x000002447A391810>
    │              └ <class 'adapter.ms.bing.BingAdapter'>
    └ <conversation.ConversationContext object at 0x000002447A391810>

  File "E:\bot\chatgpt-mirai-qq-bot\adapter\ms\bing.py", line 47, in __init__
    self.bot = EdgeChatbot(cookies=self.cookieData, proxy=account.proxy)
    │          │                   │    │                 │       └ 'http://127.0.0.1:7890'
    │          │                   │    │                 └ BingCookiePath(cookie_content='[{"domain":".bing.com","hostOnly":false,"httpOnly":false,"name":"ENSEARCH","path":"/","sameSit...
    │          │                   │    └ [{'domain': '.bing.com', 'hostOnly': False, 'httpOnly': False, 'name': 'ENSEARCH', 'path': '/', 'sameSite': 'no_restriction',...
    │          │                   └ <adapter.ms.bing.BingAdapter object at 0x000002447A39C580>
    │          └ <class 'EdgeGPT.EdgeGPT.Chatbot'>
    └ <adapter.ms.bing.BingAdapter object at 0x000002447A39C580>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\site-packages\EdgeGPT\EdgeGPT.py", line 29, in __init__
    Conversation(self.proxy, cookies=cookies),
    │            │    │              └ [{'domain': '.bing.com', 'hostOnly': False, 'httpOnly': False, 'name': 'ENSEARCH', 'path': '/', 'sameSite': 'no_restriction',...
    │            │    └ 'http://127.0.0.1:7890'
    │            └ <EdgeGPT.EdgeGPT.Chatbot object at 0x000002447A391DE0>
    └ <class 'EdgeGPT.conversation.Conversation'>

  File "C:\Users\K\Miniconda3\envs\chatgpt\lib\site-packages\EdgeGPT\conversation.py", line 59, in __init__
    raise Exception(

Exception: Authentication failed. You have not been accepted into the beta.
2023-10-01 11:06:45.440 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：出现故障！如果这个问题持 续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
原因：Authentication failed. You have not been accepted into the beta

**Comment by pandoradevin** [comment]
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
'conversationSignature'

一直是这个错误，谁有能用的教程和节点

**Comment by glaw1984** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/128808448/ef06f7fd-c959-4d77-baf9-140496d49497)
bing完全无法使用
