### ISSUE TITLE
1.5.4.1 版本报错：'generator' object is not subscriptable

### ISSUE THREAD

**Issue by Bejukoro** [lss233/chatgpt-mirai-qq-bot#123]
使用第三方代理模式时，Bot 收到来自使用者的私聊消息后，发生以下报错：
```
2023-02-14 20:09:00.703 | ERROR    | __main__:handle_message:103 - 'generator' object is not subscriptable
Traceback (most recent call last):

  File "/home/bejukoro/chatgpt-mirai-qq-bot/bot.py", line 141, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x7f58a9b08490>
    └ <graia.ariadne.app.Ariadne object at 0x7f58ab6739a0>

  File "/home/bejukoro/.local/lib/python3.9/site-packages/graia/ariadne/app.py", line 313, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x7f58a9b01a90>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7f58ab679130>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x7f58aab64e50>
    │   └ <launart.manager.Launart object at 0x7f587afb1df0>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "/home/bejukoro/.local/lib/python3.9/site-packages/launart/manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /home/bejukoro/.local/lib/python3.9/site-packages/launa...
    │    └ <function BaseEventLoop.run_until_complete at 0x7f58aaf14670>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f58aaf145e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f58aaf16160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f58aaf860d0>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f587a5eb220>(<Future finis...7f587a650660>>)>
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7f587a5eb220>(<Future finis...7f587a650660>>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7f587a5eb220>(<Future finis...7f587a650660>>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f587a5eb220>(<Future finis...7f587a650660>>)>
  File "/home/bejukoro/.local/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {'app': <graia.ariadne.app.Ariadne object at 0x7f58ab6739a0>, 'friend': Friend(id=[使用者的QQ号], nickname='使用者的QQ昵称', remark='...
                   │                └ <function friend_message_listener at 0x7f587af42a60>
                   └ <function run_always_await at 0x7f58aab22550>
  File "/home/bejukoro/.local/lib/python3.9/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object friend_message_listener at 0x7f587a6359c0>

  File "/home/bejukoro/chatgpt-mirai-qq-bot/bot.py", line 116, in friend_message_listener
    response = await handle_message(friend, f"friend-{friend.id}", chain.display, source)
                     │              │                              │     │        └ Source(id=25509, time=datetime.datetime(2023, 2, 14, 12, 9, tzinfo=datetime.timezone.utc), type='Source')
                     │              │                              │     └ <property object at 0x7f58a9c06950>
                     │              │                              └ MessageChain([Plain(text='你好')])
                     │              └ Friend(id=[使用者的QQ号], nickname='使用者的QQ昵称', remark='使用者的QQ昵称')
                     └ <function handle_message at 0x7f587af42940>

> File "/home/bejukoro/chatgpt-mirai-qq-bot/bot.py", line 96, in handle_message
    resp = await session.get_chat_response(message)
                 │       │                 └ '你好'
                 │       └ <function ChatSession.get_chat_response at 0x7f58a9868ca0>
                 └ <chatbot.ChatSession object at 0x7f587af71f10>

  File "/home/bejukoro/chatgpt-mirai-qq-bot/chatbot.py", line 78, in get_chat_response
    self.conversation_id = final_resp["conversation_id"]
    │    │                 └ <generator object Chatbot.ask at 0x7f587a650660>
    │    └ None
    └ <chatbot.ChatSession object at 0x7f587af71f10>

TypeError: 'generator' object is not subscriptable
2023-02-14 20:09:00.788 | INFO     | graia.ariadne.model:log:83 - [Bot的QQ号]: [SEND][使用者的昵称和QQ号] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作     没看见。\n'generator' object is not subscriptable
```

**Comment by linxp001** [comment]
我也是同样的错误，不管群聊私聊都报这个错。

**Comment by lss233** [comment]
这个是我傻逼了，没有认真测试。马上修复

**Comment by lss233** [comment]
v1.5.4.2 已发布。
