### ISSUE TITLE
[BUG] cannot import name 'url_decode' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by PaienNate** [lss233/chatgpt-mirai-qq-bot#1232]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
程序无法运行。

**运行环境:**  
- 操作系统：Debian13（运行在安卓手机上的）
- Docker： 否
- 项目版本：截止目前最新版本（git clone)
- 注：使用手动部署方式进行的部署，Python版本为3.11

**复现步骤**  
配置设置完成后直接运行即可。配置为Claude配置 + onebot协议。

**预期行为**  
应当正常运行

**日志**  
```c
2023-10-19 10:23:10.582 | SUCCESS  | config:scan_presets:597 - 注册预设：catgirl <==> ./pr
esets/catgirl.txt [成功]
2023-10-19 10:23:10.582 | SUCCESS  | config:scan_presets:597 - 注册预设：catgirl_en <==> .
/presets/catgirl_en.txt [成功]
2023-10-19 10:23:10.582 | SUCCESS  | config:scan_presets:597 - 注册预设：issue402 <==> ./p
resets/issue402.txt [成功]
2023-10-19 10:23:10.582 | SUCCESS  | config:scan_presets:597 - 注册预设：预设模板 <==> ./p
resets/预设模板.txt [成功]
2023-10-19 10:23:10.606 | INFO     | manager.bot:login_slack:264 - 正在解析第 1 个 Claude 
(Slack) 账号
2023-10-19 10:23:10.607 | SUCCESS  | manager.bot:login_slack:268 - 解析成功！
2023-10-19 10:23:10.607 | SUCCESS  | manager.bot:login_slack:274 - 成功解析 1/1 个 Claude 
(Slack) 账号！
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：chatgpt-web - 可用账
号： 0 个
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：openai-api - 可用账 
号： 0 个
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：poe-web - 可用账号：
 0 个
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：bing-cookie - 可用账
号： 0 个
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：bard-cookie - 可用账
号： 0 个
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：yiyan-cookie - 可用 
账号： 0 个
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：xinghuo-cookie - 可 
用账号： 0 个
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：chatglm-api - 可用账
号： 0 个
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：slack-accesstoken - 
可用账号： 1 个
2023-10-19 10:23:10.607 | INFO     | manager.bot:login:182 - AI 类型：gpt4free - 可用账号 
： 0 个
2023-10-19 10:23:10.608 | INFO     | __main__:<module>:25 - 检测到 Onebot 配置，将启动 One
bot 模式……
2023-10-19 10:23:10.685 | ERROR    | utils.exithooks:foo:35 - 看样子程序似乎没有正常退出。
2023-10-19 10:23:10.685 | ERROR    | utils.exithooks:foo:36 - cannot import name 'url_deco
de' from 'werkzeug.urls' (/root/chatgpt/myvenv/lib/python3.11/site-packages/werkzeug/urls.
py)
NoneType: None
2023-10-19 10:23:10.685 | ERROR    | utils.exithooks:foo:37 - 你可以在这里阅读常见问题的解
决方案：
2023-10-19 10:23:10.685 | ERROR    | utils.exithooks:foo:38 - https://github.com/lss233/ch
atgpt-mirai-qq-bot/issues/85
Exception ignored in atexit callback: <function foo at 0x730df68400>
Traceback (most recent call last):
  File "/root/chatgpt/chatgpt-mirai-qq-bot/utils/exithooks.py", line 39, in foo
    raise hooks.exception
  File "/root/chatgpt/chatgpt-mirai-qq-bot/bot.py", line 26, in <module>
    from platforms.onebot_bot import start_task
  File "/root/chatgpt/chatgpt-mirai-qq-bot/platforms/onebot_bot.py", line 7, in <module>
    from aiocqhttp import CQHttp, Event, MessageSegment
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/aiocqhttp/__init__.py", line 19,
 in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/__init__.py", line 7, in <
module>
    from .app import Quart
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/app.py", line 46, in <modu
le>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/asgi.py", line 29, in <mod
ule>
2023-10-19 10:23:10.685 | ERROR    | utils.exithooks:foo:37 - 你可以在这里阅读常见问题的解决方案：
2023-10-19 10:23:10.685 | ERROR    | utils.exithooks:foo:38 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
Exception ignored in atexit callback: <function foo at 0x730df68400>
Traceback (most recent call last):
  File "/root/chatgpt/chatgpt-mirai-qq-bot/utils/exithooks.py", line 39, in foo
    raise hooks.exception
  File "/root/chatgpt/chatgpt-mirai-qq-bot/bot.py", line 26, in <module>
    from platforms.onebot_bot import start_task
  File "/root/chatgpt/chatgpt-mirai-qq-bot/platforms/onebot_bot.py", line 7, in <module>
    from aiocqhttp import CQHttp, Event, MessageSegment
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/aiocqhttp/__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/__init__.py", line 7, in <module>
    from .app import Quart
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/app.py", line 46, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/asgi.py", line 29, in <module>
    from .debug import traceback_response
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/debug.py", line 8, in <module>
    from .wrappers import Response
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/wrappers/__init__.py", line 4, in <module>
    from .request import Body, Request
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/wrappers/request.py", line 23, in <module>
    from ..formparser import FormDataParser
  File "/root/chatgpt/myvenv/lib/python3.11/site-packages/quart/formparser.py", line 23, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/root/chatgpt/myvenv/lib/python3.11/site-packages/werkzeug/urls.py)
```

**其他内容**  
没得了。

**Comment by lvwenzhuo2003** [comment]
我把werkzeug从2.1.3换成2.1.2版本就好了

**Comment by nufeng1999** [comment]
pip install Werkzeug==2.3.0

**Comment by plapha** [comment]
我也遇到了，楼上两个方法都没用，Windows 11 系统

**Comment by GTian28** [comment]
打开anaconda的powershell，conda activate chatgpt，然后输入conda install werkzeug=2.3。等代码跑完重新再运行试试

**Comment by nufeng1999** [comment]
> 我也遇到了，楼上两个方法都没用，Windows 11 系统

先  pip uninstall  Werkzeug   ,再  pip install Werkzeug==2.3.0

**Comment by SaxonLee** [comment]
> > 我也遇到了，楼上两个方法都没用，Windows 11 系统
> 
> 先 pip uninstall Werkzeug ，再 pip install Werkzeug==2.3.0

试了还是报错....

**Comment by pelapi** [comment]
> > > 我也遇到了，楼上两个方法都没用，Windows 11 系统
> > 
> > 
> > 先 pip uninstall Werkzeug ，再 pip install Werkzeug==2.3.0
> 
> 试了还是报错....

我刚解决，后来你install的文件位置不是chatgpt的，你把2.3的文件替换掉里面的，默认是3.0我这边

**Comment by haojing8312** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/39109151/6d93cbed-c327-4c31-8bdf-4804903fe0ba)
我是用docker方式在linux部署，开启http配置后，也产生了这个问题，有没有大佬解决的呀

**Comment by wzzeus** [comment]
> ![image](https://user-images.githubusercontent.com/39109151/285385757-6d93cbed-c327-4c31-8bdf-4804903fe0ba.png) 我是用docker方式在linux部署，开启http配置后，也产生了这个问题，有没有大佬解决的呀

我没配http之前就一直报这个问题，我按照楼上说的试了2.1.2版本和2.3.0版本还是解决不了

**Comment by Skyzayre** [comment]
> ![image](https://user-images.githubusercontent.com/39109151/285385757-6d93cbed-c327-4c31-8bdf-4804903fe0ba.png)
> 我是用docker方式在linux部署，开启http配置后，也产生了这个问题，有没有大佬解决的呀

—————————
今天我在使用docker部署，pull最新版本的image（tag: browser-version，ls233 pushed in Nov,22,2023）时出现了同样问题。但回退到v2.5.3时恢复正常（所有配置文件均未更改），v3.0.0暂未尝试。

如果暂时无法解决的话，可以先回退image版本

**Comment by Skyzayre** [comment]
> > > ![image](https://user-images.githubusercontent.com/39109151/285385757-6d93cbed-c327-4c31-8bdf-4804903fe0ba.png)
> > > 我是用docker方式在linux部署，开启http配置后，也产生了这个问题，有没有大佬解决的呀
> > 
> > 
> > ————————— 今天我在使用docker部署，pull最新版本的image（tag: browser-version，ls233 pushed in Nov,22,2023）时出现了同样问题。但回退到v2.5.3时恢复正常（所有配置文件均未更改），v3.0.0暂未尝试。怀疑是docker封装时的Werkzeug版本问题
> > 如果暂时无法解决的话，可以先回退image版本（最简单的方法） @wzzeus @haojing8312
> 
> 大佬应该怎么操作你这些流程呀，麻烦啦qwq


********
有一个热心老哥给出了另一个解决方案（无需回退版本）：**手动重新挂载依赖**https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1261

********
如果要回退版本的话，在docker-compose.yaml对应处修改image版本为v2.5.3
```
chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:browser-version
```
修改为

```
chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:v2.5.3
```

**Comment by PawOfPuzzle** [comment]
> > > > ![image](https://user-images.githubusercontent.com/39109151/285385757-6d93cbed-c327-4c31-8bdf-4804903fe0ba.png)
> > > > 我是用docker方式在linux部署，开启http配置后，也产生了这个问题，有没有大佬解决的呀
> > > 
> > > 
> > > ————————— 今天我在使用docker部署，pull最新版本的image（tag: browser-version，ls233 pushed in Nov,22,2023）时出现了同样问题。但回退到v2.5.3时恢复正常（所有配置文件均未更改），v3.0.0暂未尝试。怀疑是docker封装时的Werkzeug版本问题
> > > 如果暂时无法解决的话，可以先回退image版本（最简单的方法） @wzzeus @haojing8312
> > 
> > 
> > 大佬应该怎么操作你这些流程呀，麻烦啦qwq
> 
> 有一个热心老哥给出了另一个解决方案（无需回退版本）：**手动重新挂载依赖**#1261
> 
> 如果要回退版本的话，在docker-compose.yaml对应处修改image版本为v2.5.3
> 
> ```
> chatgpt:
>     image: lss233/chatgpt-mirai-qq-bot:browser-version
> ```
> 
> 修改为
> 
> ```
> chatgpt:
>     image: lss233/chatgpt-mirai-qq-bot:v2.5.3
> ```
> 
> 然后docker-compose重新部署

谢谢大佬，你分享的这位老哥的方法我试了很多次，也不能成功，所以想试试你的方法

**Comment by PawOfPuzzle** [comment]
> > > > ![image](https://user-images.githubusercontent.com/39109151/285385757-6d93cbed-c327-4c31-8bdf-4804903fe0ba.png)
> > > > 我是用docker方式在linux部署，开启http配置后，也产生了这个问题，有没有大佬解决的呀
> > > 
> > > 
> > > ————————— 今天我在使用docker部署，pull最新版本的image（tag: browser-version，ls233 pushed in Nov,22,2023）时出现了同样问题。但回退到v2.5.3时恢复正常（所有配置文件均未更改），v3.0.0暂未尝试。怀疑是docker封装时的Werkzeug版本问题
> > > 如果暂时无法解决的话，可以先回退image版本（最简单的方法） @wzzeus @haojing8312
> > 
> > 
> > 大佬应该怎么操作你这些流程呀，麻烦啦qwq
> 
> 有一个热心老哥给出了另一个解决方案（无需回退版本）：**手动重新挂载依赖**#1261
> 
> 如果要回退版本的话，在docker-compose.yaml对应处修改image版本为v2.5.3
> 
> ```
> chatgpt:
>     image: lss233/chatgpt-mirai-qq-bot:browser-version
> ```
> 
> 修改为
> 
> ```
> chatgpt:
>     image: lss233/chatgpt-mirai-qq-bot:v2.5.3
> ```
> 
> 然后docker-compose重新部署

谢谢大佬

**Comment by imRhoAias** [comment]
> Reference in

windows怎么处理啊，我人都麻木了

**Comment by imRhoAias** [comment]
> > > > ![image](https://user-images.githubusercontent.com/39109151/285385757-6d93cbed-c327-4c31-8bdf-4804903fe0ba.png)
> > > > 我是用docker方式在linux部署，开启http配置后，也产生了这个问题，有没有大佬解决的呀
> > > 
> > > 
> > > ————————— 今天我在使用docker部署，pull最新版本的image（tag: browser-version，ls233 pushed in Nov,22,2023）时出现了同样问题。但回退到v2.5.3时恢复正常（所有配置文件均未更改），v3.0.0暂未尝试。怀疑是docker封装时的Werkzeug版本问题
> > > 如果暂时无法解决的话，可以先回退image版本（最简单的方法） @wzzeus @haojing8312
> > 
> > 
> > 大佬应该怎么操作你这些流程呀，麻烦啦qwq
> 
> 有一个热心老哥给出了另一个解决方案（无需回退版本）：**手动重新挂载依赖**#1261
> 
> 如果要回退版本的话，在docker-compose.yaml对应处修改image版本为v2.5.3
> 
> ```
> chatgpt:
>     image: lss233/chatgpt-mirai-qq-bot:browser-version
> ```
> 
> 修改为
> 
> ```
> chatgpt:
>     image: lss233/chatgpt-mirai-qq-bot:v2.5.3
> ```
> 
> 然后docker-compose重新部署

大佬windows怎么处理啊，人要麻木了

**Comment by Skyzayre** [comment]
> 大佬windows怎么处理啊，人要麻木了

以下三个方法都可以：
1. 部署老版本（v2.5.3）
2. docker部署的话参考issue#1261手动挂载依赖
3. 手动替换文件

**Comment by imRhoAias** [comment]
> > 大佬windows怎么处理啊，人要麻木了
> 
> 以下三个方法都可以：
> 
> 1. 部署老版本（v2.5.3）
> 2. docker部署的话参考 issue#1261 手动挂载依赖
> 3. 手动替换文件

好了，我强行把那个文件搬到目录下面解决了，谢谢

**Comment by Paldo26** [comment]
> > > 大佬windows怎么处理啊，人要麻木了
> > 
> > 
> > 以下三个方法都可以：
> > 
> > 1. 部署老版本（v2.5.3）
> > 2. docker部署的话参考 issue#1261 手动挂载依赖
> > 3. 手动替换文件
> 
> 好了，我强行把那个文件搬到目录下面解决了，谢谢

help救救我，为什么我替换没用，具体怎么操作的啊

**Comment by imRhoAias** [comment]
> > > > 大佬windows怎么处理啊，人要麻木了
> > > 
> > > 
> > > 以下三个方法都可以：
> > > 
> > > 1. 部署老版本（v2.5.3）
> > > 2. docker部署的话参考 issue#1261 手动挂载依赖
> > > 3. 手动替换文件
> > 
> > 
> > 好了，我强行把那个文件搬到目录下面解决了，谢谢
> 
> help救救我，为什么我替换没用，具体怎么操作的啊

不就是搬文件到目录下面就行了，替换啥
