### ISSUE TITLE
[BUG] 即便配置了代理也仍然报错404

### ISSUE THREAD

**Issue by monworlig** [lss233/chatgpt-mirai-qq-bot#1254]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
2023-11-19 02:48:26.768 | ERROR    | framework.universal:handle_message:290 - 无法请求 ()
Traceback (most recent call last):

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\llm\openai\api.py", line 106, in ask
    async for resp in self.bot.ask_stream_async(prompt=prompt,
                      │    │   │                       └ '你好'
                      │    │   └ <function Chatbot.ask_stream_async at 0x000001C2F7012340>
                      │    └ <revChatGPT.V3.Chatbot object at 0x000001C2FEB67B50>
                      └ <framework.llm.openai.api.ChatGPTAPIAdapter object at 0x000001C2F65FB310>

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\python3.11\Lib\site-packages\revChatGPT\V3.py", line 319, in ask_stream_async
    raise t.APIConnectionError(
          │ └ <class 'revChatGPT.typings.APIConnectionError'>
          └ <module 'revChatGPT.typings' from 'N:\\AI\\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\\python3.11\\Lib\\site-packag...
revChatGPT.typings.APIConnectionError: 404 Not Found {
  "error": {
    "message": "Invalid URL (POST /chat/completions)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

Please check if there is a problem with your network connection
Please check that the input is correct, or you can resolve this issue by filing an issue

Project URL: https://github.com/acheong08/ChatGPT

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\bot.py", line 99, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<coroutine object setup_web_service at 0x000001C2F70C20C0>]
    │    │                  │       └ <function gather at 0x000001C2ECABFD80>
    │    │                  └ <module 'asyncio' from 'N:\\AI\\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\\python3.11\\python311.zip\\asyncio\\__i...
    │    └ <function BaseEventLoop.run_until_complete at 0x000001C2ECEF4AE0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\platforms\onebot_bot.py", line 194, in _
    await handle_message(request, response)
          │              │        └ <framework.request.Response object at 0x000001C2FC4F5C90>
          │              └ <framework.request.Request object at 0x000001C2FDAAF550>
          └ <function handle_message at 0x000001C2FD92DD00>

> File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\universal.py", line 264, in handle_message
    await action(request, response)
          │      │        └ <framework.request.Response object at 0x000001C2FC4F5C90>
          │      └ <framework.request.Request object at 0x000001C2FDAAF550>
          └ functools.partial(<bound method MiddlewareConcurrentLock.handle_request of <framework.middlewares.concurrentlock.MiddlewareCo...

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\middlewares\concurrentlock.py", line 44, in handle_request
    await _next(request, response)
          │     │        └ <framework.request.Response object at 0x000001C2FC4F5C90>
          │     └ <framework.request.Request object at 0x000001C2FDAAF550>
          └ functools.partial(<bound method Middleware.handle_request of <framework.middlewares.baiducloud.MiddlewareBaiduCloud object at...

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\middlewares\middleware.py", line 8, in handle_request
    return await _next(request, response)
                 │     │        └ <framework.request.Response object at 0x000001C2FC4F5C90>
                 │     └ <framework.request.Request object at 0x000001C2FDAAF550>
                 └ functools.partial(<bound method MiddlewareRatelimit.handle_request of <framework.middlewares.ratelimit.MiddlewareRatelimit ob...

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\middlewares\ratelimit.py", line 24, in handle_request
    await _next(request, response)
          │     │        └ <framework.request.Response object at 0x000001C2FC4F5C90>
          │     └ <framework.request.Request object at 0x000001C2FDAAF550>
          └ functools.partial(<bound method MiddlewareTimeout.handle_request of <framework.middlewares.timeout.MiddlewareTimeout object a...

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\middlewares\timeout.py", line 28, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
          │       │        │          │      │        └ 600.0
          │       │        │          │      └ Response(mode='mixed', buffer_delay=1.0, default_ai='chatgpt-api', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回...
          │       │        │          └ Config(onebot=Onebot(manager_qq=2878392943), mirai=None, telegram=None, discord=None, http=HttpService(host='0.0.0.0', port=8...
          │       │        └ <Task finished name='Task-28' coro=<handle_message.<locals>._request_func() done, defined at N:\AI\Windows-quickstart-go-cqht...
          │       └ <function wait_for at 0x000001C2ECABF7E0>
          └ <module 'asyncio' from 'N:\\AI\\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\\python3.11\\python311.zip\\asyncio\\__i...

  File "asyncio\tasks.py", line 479, in wait_for
    for f in todo:

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\universal.py", line 255, in _request_func
    await context.input(prompt=request.message)
          │       │            │       └ MessageChain([Plain(text='你好')])
          │       │            └ <framework.request.Request object at 0x000001C2FDAAF550>
          │       └ <function AsyncPromptExecutionContext.input at 0x000001C2FD90F740>
          └ <framework.conversation.AsyncPromptExecutionContext object at 0x000001C2FD684C10>

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\conversation.py", line 71, in input    async for item in self.conversation.llm_adapter.ask(self.variables["input"]["message"]):
                      │    │            │           │   │    └ {'input': {'message': '你好'}, 'user': {'nickname': '界辉'}, 'output': {}, 'tts_engine': {}}
                      │    │            │           │   └ <framework.conversation.AsyncPromptExecutionContext object at 0x000001C2FD684C10>
                      │    │            │           └ <function ChatGPTAPIAdapter.ask at 0x000001C2F712B060>
                      │    │            └ <framework.llm.openai.api.ChatGPTAPIAdapter object at 0x000001C2F65FB310>
                      │    └ <framework.conversation.ConversationContext object at 0x000001C2FDAAFFD0>
                      └ <framework.conversation.AsyncPromptExecutionContext object at 0x000001C2FD684C10>

  File "N:\AI\Windows-quickstart-go-cqhttp-refs.tags.v3.0.0-alpha2\chatgpt\framework\llm\openai\api.py", line 116, in ask
    raise LlmRequestFailedException("chatgpt-api") from e
          └ <class 'framework.exceptions.LlmRequestFailedException'>

framework.exceptions.LlmRequestFailedException: 无法请求 ()

说啥都报错这个

**运行环境:**  
- 操作系统：win10 22h2 x64
- Docker：没得，直接跑的
- 项目版本：3.0.0 alpha2

**复现步骤**  
用的gpt的api，别的方式去用这个api的时候一切正常，换到这里每条消息都会触发

**预期行为**  
正常回复才对嘛

**截图**  

**其他内容**

**Comment by whitebalck547** [comment]
请问解决了吗？

**Comment by monworlig** [comment]
> 请问解决了吗？

解决了。3.0.0是个没开发完的半吊子版本，请使用2.5.3
