### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by zro227** [lss233/chatgpt-mirai-qq-bot#1268]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows11
- Docker： ？
- 项目版本：v2.5.2

**复现步骤**  
描述你是如何触发这个 BUG 的
发消息无法回复

**预期行为**  
如何设置才能正常回复我的话

**截图**  
![111](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/91720372/0e175362-8bd9-49b2-b6c7-004e4321cfdd)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by Vsxbamboo** [comment]
我使用的文心一言的接入方式，发现这个项目用来计算文心一言的api的网页服务应该挂了。

**Comment by Vsxbamboo** [comment]
完整报错如下（有重复报错）：
`2023-12-14 00:34:41.665 | DEBUG    | platforms.onebot_bot:_:148 - 私聊消息：ask 你好
2023-12-14 00:34:42.276 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-12-14 00:34:42.361 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-12-14 00:34:42.395 | DEBUG    | platforms.onebot_bot:_:148 - 私聊消息：ask 你好
2023-12-14 00:34:42.482 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 1 个人！
2023-12-14 00:34:42.573 | DEBUG    | platforms.onebot_bot:_:148 - 私聊消息：ask 你好
2023-12-14 00:34:42.603 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 2 个人！
2023-12-14 00:34:42.693 | DEBUG    | middlewares.timeout:create_timeout_task:61 - [Timeout] 开始计时……
2023-12-14 00:34:43.665 | ERROR    | middlewares.timeout:handle_request:36 - 发生错误: Expecting value: line 1 column 1 (char 0)
2023-12-14 00:34:44.085 | ERROR    | universal:handle_message:297 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\bot.py", line 58, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.t...
    │    │                  │       └ <function gather at 0x000002791C830700>
    │    │                  └ <module 'asyncio' from 'C:\\Users\\Administrator\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x000002791C83D3F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002791E4760E0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002791C83EE60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002791C7DDFC0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\platforms\onebot_bot.py", line 151, in _
    await handle_message(
          └ <function handle_message at 0x000002794803A8C0>

> File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 271, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x0000027948259510>
          │      │           │       │        └ None
          │      │           │       └ <method 'strip' of 'str' objects>
          │      │           └ '你好'
          │      └ 'friend-1924868164'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000279482597E0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000027948259750>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x0000027948259510>
          │ │              │           └ '你好'
          │ │              └ 'friend-1924868164'
          │ └ <function MiddlewareConcurrentLock.handle_request at 0x000002794803AEF0>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x000002794804C2B0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x0000027948259510>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'friend-1924868164'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000027948259750>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000279482596C0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x0000027948259510>
          │ │              │           └ '你好'
          │ │              └ 'friend-1924868164'
          │ └ <function Middleware.handle_request at 0x000002794803A170>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x0000027947FFB3D0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x0000027948259510>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'friend-1924868164'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000279482596C0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000027948259630>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x0000027948259510>
          │ │              │           └ '你好'
          │ │              └ 'friend-1924868164'
          │ └ <function MiddlewareRatelimit.handle_request at 0x000002794803A3B0>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x0000027947FFB3A0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\ratelimit.py", line 23, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x0000027948259510>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'friend-1924868164'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x0000027948259630>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x00000279482595A0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x0000027948259510>
          │ │              │           └ '你好'
          │ │              └ 'friend-1924868164'
          │ └ <function MiddlewareTimeout.handle_request at 0x000002794803B010>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x0000027947FFB370>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\timeout.py", line 40, in handle_request
    raise e

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\middlewares\timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
          │       │        │          │      │        └ 600.0
          │       │        │          │      └ Response(mode='mixed', buffer_delay=15, default_ai='yiyan', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回...
          │       │        │          └ Config(onebot=Onebot(manager_qq=1924868164, reverse_ws_host='0.0.0.0', reverse_ws_port=5900), mirai=None, telegram=None, disc...
          │       │        └ <Task finished name='Task-297' coro=<handle_message.<locals>.request() done, defined at C:\Users\Administrator\Desktop\Window...
          │       └ <function wait_for at 0x000002791C8301F0>
          └ <module 'asyncio' from 'C:\\Users\\Administrator\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
           │   └ <method 'result' of '_asyncio.Task' objects>
           └ <Task finished name='Task-297' coro=<handle_message.<locals>.request() done, defined at C:\Users\Administrator\Desktop\Window...

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\universal.py", line 224, in request
    async for rendered in task:
                          └ <async_generator object retry.<locals>.decorator.<locals>.wrapper at 0x0000027948223E40>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\utils\retry.py", line 21, in wrapper
    async for result in func(*args, **kwargs):
                        │     │       └ {'prompt': '你好', 'chain': MessageChain([Plain(text='ask 你好')]), 'name': 'player_vsx'}
                        │     └ (<conversation.ConversationContext object at 0x00000279480DE290>,)
                        └ <function ConversationContext.ask at 0x0000027948039AB0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\conversation.py", line 195, in ask
    async for item in self.adapter.ask(prompt):
                      │    │       │   └ '你好'
                      │    │       └ <function YiyanAdapter.ask at 0x0000027946EE1000>
                      │    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x00000279480DE2C0>
                      └ <conversation.ConversationContext object at 0x00000279480DE290>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\adapter\baidu\yiyan.py", line 94, in ask
    self.client.headers['Acs-Token'] = await self.get_sign()
    │    │      │                            │    └ <function YiyanAdapter.get_sign at 0x0000027946EE11B0>
    │    │      │                            └ <adapter.baidu.yiyan.YiyanAdapter object at 0x00000279480DE2C0>
    │    │      └ <property object at 0x000002791FDE1350>
    │    └ <httpx.AsyncClient object at 0x00000279480DE590>
    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x00000279480DE2C0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\adapter\baidu\yiyan.py", line 192, in get_sign
    return req.json()['acs']
           │   └ <function Response.json at 0x000002791FA0EB90>
           └ <Response [502 Bad Gateway]>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           │       │     │    │       └ {}
           │       │     │    └ <property object at 0x000002791FA10590>
           │       │     └ <Response [502 Bad Gateway]>
           │       └ <function loads at 0x000002791C197010>
           └ <module 'json' from 'C:\\Users\\Administrator\\Miniconda3\\envs\\chatgpt\\lib\\json\\__init__.py'>

  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ '<!DOCTYPE html>\n\n\n\n\n<!--[if IE 7]>    <html class="...
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Vsxbamboo** [comment]
在github上找到了文心一言的网页版api封装，或可作为替代，但原作者的代码已经不能使用，我简单写了一个基于node.js的demo（有些杂乱，见谅，仅作为演示），现在是可以使用的，可以稍作修改。
```javascript
import puppeteer, {KnownDevices} from 'puppeteer'
import sleep from 'then-sleep'

const cookie=''
const prompt='在所有对我的回答的末尾加上一个#，包括对这个问题的回答。'
const {texts}=await headless({
	cookie,
	prompt
})

console.log(texts)

async function headless({ cookie, timeout = 1000 * 60, headless = 'new', prompt = '' }) {
    let browser;
	cookie='__yjs_duid=1_18ce468937da9ab70c59e0fb9d2033ba1675068694783; BAIDUID=07027F9874C38F32D6F82BE4656CD9AF:FG=1; PSTM=1697554155; BIDUPSID=EEC4CB8A3346225ED2393A0357AA67FE; H_WISE_SIDS=39712_39780_39704_39681_39842_39905_39819_39909_39935_39932_39941_39939_39931; BDORZ=B490B5EBF6F3CD402E515D22BCDA1598; H_WISE_SIDS_BFESS=39712_39780_39704_39681_39842_39905_39819_39909_39935_39932_39941_39939_39931; BDUSS=kRjTXBSZFdPWkF6UjdDbmxBLTcweExRaTZTSE9Jc29aLUFwMDFWZ08xSHJyWjVsSUFBQUFBJCQAAAAAAQAAAAEAAAAiu2F8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOsgd2XrIHdlf; BDUSS_BFESS=kRjTXBSZFdPWkF6UjdDbmxBLTcweExRaTZTSE9Jc29aLUFwMDFWZ08xSHJyWjVsSUFBQUFBJCQAAAAAAQAAAAEAAAAiu2F8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOsgd2XrIHdlf; Hm_lvt_01e907653ac089993ee83ed00ef9c2f3=1702049435,1702460075; H_PS_PSSID=39712_39780_39842_39905_39819_39909_39935_39932_39941_39939_39931_39732_39781; BDSFRCVID=iWtOJeCT5G3oo_TqfobQhKNeXUCs_PJTTPjcTR5qJ04BtyCVNwZ1EG0PtDQqHgCbwBlLogKKBeOTH6KF_2uxOjjg8UtVJeC6EG0Ptf8g0M5; H_BDCLCKID_SF=tbC8VCDKJDD3HnRv5t8_-4_tbh_X5-RLfb5nop7F54nKDp0RQJb8jn_pXGOQaUnw5GbMahvKQDOxsMTsQtjMWJ0AyHOuKt3JQecz2P3N3KJmf-8lqtOp5tjBMGb-2-biW2JM2MbdQlRP_IoG2Mn8M4bb3qOpBtQmJeTxoUJ25DnJhhCGe6-aejcLjGDDq-jeHDrKBRbaHJOoDDvOhfvcy4LbKxnxJMQe2JvDaqu2annv8R5ybURv5l5y3-OkWUQ9babTQ-tbBp3k8MQDWxvbQfbQ0hOeJCrb36Ta_JFb5R7JOpvsbUnxyhLTQRPH-Rv92DQMVU52QqcqEIQHQT3m5-5bbN3ut6IDJbKj_KKKfbOSDP5gqROqh4t8hl8X5-RLf5vwop7F54nKDp0RQqL-jn_ED4JWaUnw5GbMahvKQDOxsMTsQqOODtAgDhCjXfkOQeFt-lcN3KJmfb7pQPOhBIue2a742-biW2JM2MbdQlRP_IoG2Mn8M4bb3qOpBtQmJeTxoUJ25DnJhhCGe6LbejOWjHDs5JtXKD600PK8Kb7VbnvcLUnkbJkXhPte0l_qJ56hoq3o2pvFefnTyUR-36t7Qbrr0xRfyNReQIO13hcdSlLG3f6pQT8r5MnK0-3tX-jyXInNab3vOpRTXpO13fAzBN5thURB2DkO-4bCWJ5TMl5jDh3Mb6ksD-FtqjtjJRCjoK_bf-3bfTrP-trf5DCShUFsalbJB2Q-5M-a3KOoDU72Ktjo-l_JyPT-XpQm-aOTafbmLncjSM_GKfC2jMD32tbpWJbztmTxoUJ23UjaOb3J-RJIhMAebPRi3tQ9Qg-qahQ7tt5W8ncFbT7l5hKpbt-q0x-jLTnhVn0MBCK0HPonHjKbDjOb3e; BAIDUID_BFESS=07027F9874C38F32D6F82BE4656CD9AF:FG=1; BDSFRCVID_BFESS=iWtOJeCT5G3oo_TqfobQhKNeXUCs_PJTTPjcTR5qJ04BtyCVNwZ1EG0PtDQqHgCbwBlLogKKBeOTH6KF_2uxOjjg8UtVJeC6EG0Ptf8g0M5; H_BDCLCKID_SF_BFESS=tbC8VCDKJDD3HnRv5t8_-4_tbh_X5-RLfb5nop7F54nKDp0RQJb8jn_pXGOQaUnw5GbMahvKQDOxsMTsQtjMWJ0AyHOuKt3JQecz2P3N3KJmf-8lqtOp5tjBMGb-2-biW2JM2MbdQlRP_IoG2Mn8M4bb3qOpBtQmJeTxoUJ25DnJhhCGe6-aejcLjGDDq-jeHDrKBRbaHJOoDDvOhfvcy4LbKxnxJMQe2JvDaqu2annv8R5ybURv5l5y3-OkWUQ9babTQ-tbBp3k8MQDWxvbQfbQ0hOeJCrb36Ta_JFb5R7JOpvsbUnxyhLTQRPH-Rv92DQMVU52QqcqEIQHQT3m5-5bbN3ut6IDJbKj_KKKfbOSDP5gqROqh4t8hl8X5-RLf5vwop7F54nKDp0RQqL-jn_ED4JWaUnw5GbMahvKQDOxsMTsQqOODtAgDhCjXfkOQeFt-lcN3KJmfb7pQPOhBIue2a742-biW2JM2MbdQlRP_IoG2Mn8M4bb3qOpBtQmJeTxoUJ25DnJhhCGe6LbejOWjHDs5JtXKD600PK8Kb7VbnvcLUnkbJkXhPte0l_qJ56hoq3o2pvFefnTyUR-36t7Qbrr0xRfyNReQIO13hcdSlLG3f6pQT8r5MnK0-3tX-jyXInNab3vOpRTXpO13fAzBN5thURB2DkO-4bCWJ5TMl5jDh3Mb6ksD-FtqjtjJRCjoK_bf-3bfTrP-trf5DCShUFsalbJB2Q-5M-a3KOoDU72Ktjo-l_JyPT-XpQm-aOTafbmLncjSM_GKfC2jMD32tbpWJbztmTxoUJ23UjaOb3J-RJIhMAebPRi3tQ9Qg-qahQ7tt5W8ncFbT7l5hKpbt-q0x-jLTnhVn0MBCK0HPonHjKbDjOb3e; delPer=0; BA_HECTOR=2g8l8g8h04058l21a4212lak1inkqsn1q; ZFY=HJv6X5Poptbjm1T2RzBA6XvLTYNZGbfKQsj:ADqhAI:Bs:C; PSINO=3; __bid_n=18b088c58b47184b6e1175; ab_sr=1.0.1_NTk2OGE2NGQyMGI2MTg2MTlkM2Q1Yjc4NDJkMTVlOTA2OTIwMDFiZDFlM2Y4YzdjNzkwZGI2NTQ0NzQyMDYyY2FiZWUxYTdhMDg1MzkyYjRiMzRiYTNhOTRkNTBiZjgzYjMyMzZhNzUwZjFkMmQ4NjgxNDM1NTk2NzE1MjcxNjIyN2IxYWFmODE3YjMxZGNmNjk4YTE5ZmEwNzE2NTFjZWMxNTExYjkxNzIxNGQ5Yzc3ODVjN2Q3NDgxZDQ4ZjYw; XFI=19bd0d50-9a2d-11ee-8a5a-df243b5f0b47; Hm_lpvt_01e907653ac089993ee83ed00ef9c2f3=1702522899; RT="z=1&dm=baidu.com&si=76d27f3a-8eb0-4ea5-a981-f1bcdb4efd9c&ss=lq4m4vfq&sl=5&tt=7u3&bcn=https%3A%2F%2Ffclog.baidu.com%2Flog%2Fweirwood%3Ftype%3Dperf"; XFCS=B40BD955861DD2110A0A7D82D7CAE7699B1BD21822480D088C630C33AECB378C; XFT=yoUw7AriNXW7vsNweU+WMidXV3J/yKvenTHl0iWbivY='
    try {
        browser = await puppeteer.launch({
            headless,
            ignoreDefaultArgs: ['--enable-automation'],
            args: ['--disable-blink-features=AutomationControlled', '--no-sandbox', '--disable-setuid-sandbox'],
        });

        const page = await browser.newPage();
        await page.emulate(KnownDevices['iPhone SE']);

        // Check if 'cookie' is provided before using it
        if (cookie) {
            await page.setCookie(...parse_cookie(cookie));
        }
		
		await page.goto('https://yiyan.baidu.com', {waitUntil: 'networkidle0'})
		
        // 在 Node.js 环境中无法使用 document.body.innerText，使用 page.evaluate 来获取页面内容
        
		
		
		const message_input = await page.waitForSelector('#dialogue-input', {
            timeout,
        })
		
		
		await message_input.type(prompt)
		await sleep(1000)
		
		await page.evaluate(async () => {
            function get_parent_next_sibling(element) {
                const parent = element.parentNode
                let next_sibling = parent.nextSibling
                while (next_sibling && next_sibling.nodeType !== 1) {
                    next_sibling = next_sibling.nextSibling
                }
                return next_sibling
            }

            const message_input = document.querySelector('#dialogue-input')
            const send_button = get_parent_next_sibling(message_input)
            send_button.click()
        })
		
		// 使用 page.waitForFunction 等待条件成立
		await page.waitForFunction(
			() => {
				const elements = document.querySelectorAll('.custom-html');
				const lastElement = elements[elements.length - 1];
				return lastElement && lastElement.textContent.trim().endsWith('#');
			},
			{ timeout: 6000 }  // 设置最大等待时间，例如 6000 毫秒（6 秒）
		);

		// 条件成立后的处理代码
		console.log('最后一个 .custom-html 元素的内容以 # 结尾');


		
		const texts = await page.evaluate(() => {
			// 获取包含文字的所有元素，通过类名查找
			const elements = document.querySelectorAll('.custom-html');

			// 遍历所有元素并提取文字内容
			let c=""
			for(let i=0;i<elements.length;i++){
				c=c+" "+elements[i].textContent
			}
			return c
        });
		
        return { texts }
    } finally {
        // 关闭浏览器
        await browser?.close();
    }
}

function parse_cookie(cookie) {
    return cookie
        .trim()
        .split('; ')
        .map(item => {
            const [name, ...value] = item.split('=');
            return {
                name: name?.trim(),
                value: value.join('='),
                domain: 'yiyan.baidu.com',
            };
        })
        .filter(item => item.name);
}




```

**Comment by Vsxbamboo** [comment]
可以转而使用Python的pyppeter转写一下。

**Comment by Vsxbamboo** [comment]
在github上找到了可能是本项目文心一言的参考项目[https://github.com/XiaoXinYo/Easy-Ernie](https://github.com/XiaoXinYo/Easy-Ernie)，因此，一种修改方法可能是借用那个项目的api。此时，那个项目的api仍然可用。作者说文心一言的acs-token计算参数经常改变。
