### ISSUE TITLE
[BUG] 请填写标题

### ISSUE THREAD

**Issue by SteveJiyu** [lss233/chatgpt-mirai-qq-bot#1292]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
无法登录bing的ai，反馈 Authentication failed. You have not been accepted into the beta. 我确认我的服务器在国外且能正常访问Bing

**运行环境:**  
- 操作系统：ubuntu 22.0.4 LTS
- 部署方式：手动部署 
- 项目版本：2.3.0

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 部署项目
2. 正常设置并启动项目
3. 向机器人发送 你好 消息
4. 机器人反馈 Authentication failed. You have not been accepted into the beta.

**预期行为**  
Bing正常返回信息

**日志**  
2024-01-13 15:47:17.650 | DEBUG    | platforms.onebot_bot:_:148 - 私聊消息：切换AI bing-c
2024-01-13 15:47:17.651 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2024-01-13 15:47:17.651 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2024-01-13 15:47:17.651 | DEBUG    | middlewares.timeout:create_timeout_task:61 - [Timeout] 开始计时……
2024-01-13 15:47:17.755 | ERROR    | middlewares.timeout:handle_request:36 - 发生错误: Authentication failed. You have not been accepted into the beta.
2024-01-13 15:47:17.755 | ERROR    | universal:handle_message:297 - Authentication failed. You have not been accepted into the beta.
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT/conversation.py", line 57, in __init__
    self.struct = response.json()
    │    │        │        └ <function Response.json at 0x7f346a14ef80>
    │    │        └ <Response [200 OK]>
    │    └ {'conversationId': None, 'clientId': None, 'conversationSignature': None, 'result': {'value': 'Success', 'message': None}}
    └ <EdgeGPT.conversation.Conversation object at 0x7f342b947d90>
  File "/usr/local/lib/python3.10/dist-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           │       │     │    │       └ {}
           │       │     │    └ <property object at 0x7f346a154c20>
           │       │     └ <Response [200 OK]>
           │       └ <function loads at 0x7f346b4bdf30>
           └ <module 'json' from '/usr/lib/python3.10/json/__init__.py'>
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ ''
           │                └ <function JSONDecoder.decode at 0x7f346b4bd7e0>
           └ <json.decoder.JSONDecoder object at 0x7f346b4a97b0>
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ ''
               │    │          │      └ <built-in method match of re.Pattern object at 0x7f346b46cd40>
               │    │          └ ''
               │    └ <function JSONDecoder.raw_decode at 0x7f346b4bd870>
               └ <json.decoder.JSONDecoder object at 0x7f346b4a97b0>
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ ''
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/chatgpt-qq/bot.py", line 58, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at /opt/chatgpt-qq/platforms/onebot_bot.py:356> wait_for=<Future pend...
    │    │                  │       └ <function gather at 0x7f346b590700>
    │    │                  └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x7f346b5992d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f346b599240>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f346b59ad40>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f346b536710>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "/opt/chatgpt-qq/platforms/onebot_bot.py", line 151, in _
    await handle_message(
          └ <function handle_message at 0x7f342b07df30>

> File "/opt/chatgpt-qq/universal.py", line 271, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x7f342b399bd0>
          │      │           │       │        └ None
          │      │           │       └ <method 'strip' of 'str' objects>
          │      │           └ '切换AI bing-c'
          │      └ 'friend-1***2'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f342b03f9a0>

  File "/opt/chatgpt-qq/universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f342b36dea0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7f342b399bd0>
          │ │              │           └ '切换AI bing-c'
          │ │              └ 'friend-1***2'
          │ └ <function MiddlewareConcurrentLock.handle_request at 0x7f342b07e440>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x7f342b0623b0>

  File "/opt/chatgpt-qq/middlewares/concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7f342b399bd0>
          │      │           │       └ None
          │      │           └ '切换AI bing-c'
          │      └ 'friend-1***2'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f342b36dea0>

  File "/opt/chatgpt-qq/universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f342b399ea0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7f342b399bd0>
          │ │              │           └ '切换AI bing-c'
          │ │              └ 'friend-1***2'
          │ └ <function Middleware.handle_request at 0x7f342b07d6c0>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x7f342b061480>

  File "/opt/chatgpt-qq/middlewares/middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           ���       │                     └ <function handle_message.<locals>.respond at 0x7f342b399bd0>
          │      │           │       └ None
          │      │           └ '切换AI bing-c'
          │      └ 'friend-1***2'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f342b399ea0>

  File "/opt/chatgpt-qq/universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f342b399cf0>
          │ │              │           │        ���        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7f342b399bd0>
          │ │              │           └ '切换AI bing-c'
          │ │              └ 'friend-1***2'
          │ └ <function MiddlewareRatelimit.handle_request at 0x7f342b07d900>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x7f342b061450>

  File "/opt/chatgpt-qq/middlewares/ratelimit.py", line 23, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7f342b399bd0>
          │      ��           │       └ None
          │      │           └ '切换AI bing-c'
          │      └ 'friend-1***2'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f342b399cf0>

  File "/opt/chatgpt-qq/universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x7f342b399c60>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7f342b399bd0>
          │ │              │           └ '切换AI bing-c'
          │ │              └ 'friend-1***2'
          │ └ <function MiddlewareTimeout.handle_request at 0x7f342b07e560>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x7f342b061420>

  File "/opt/chatgpt-qq/middlewares/timeout.py", line 40, in handle_request
    raise e

  File "/opt/chatgpt-qq/middlewares/timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
          │       │        │          │      │        └ 600.0
          │       │        │          │      └ Response(mode='mixed', buffer_delay=15, default_ai='chatgpt-api', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚...
          │       │        │          └ <unprintable Config object>
          │       │        └ <Task finished name='Task-37' coro=<handle_message.<locals>.request() done, defined at /opt/chatgpt-qq/universal.py:107> exce...
          │       └ <function wait_for at 0x7f346b5901f0>
          └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>

  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
           │   └ <method 'result' of '_asyncio.Task' objects>
           └ <Task finished name='Task-37' coro=<handle_message.<locals>.request() done, defined at /opt/chatgpt-qq/universal.py:107> exce...

  File "/opt/chatgpt-qq/universal.py", line 120, in request
    await conversation_handler.create(
          │                    └ <function ConversationHandler.create at 0x7f342b07d510>
          └ <conversation.ConversationHandler object at 0x7f3429b29c60>

  File "/opt/chatgpt-qq/conversation.py", line 296, in create
    conversation = ConversationContext(_type, self.session_id)
                   │                   │      │    └ 'friend-1***2'
                   │                   │      └ <conversation.ConversationHandler object at 0x7f3429b29c60>
                   │                   └ 'bing-c'
                   └ <class 'conversation.ConversationContext'>

  File "/opt/chatgpt-qq/conversation.py", line 98, in __init__
    self.adapter = BingAdapter(self.session_id, ConversationStyle.creative)
    │              │           │    │           │                 └ <ConversationStyle.creative: ['nlu_direct_response_filter', 'deepleo', 'disable_emoji_spoken_text', 'responsible_ai_policy_23...
    │              │           │    │           └ <enum 'ConversationStyle'>
    │              │           │    └ 'friend-1***2'
    │              │           └ <conversation.ConversationContext object at 0x7f342b97baf0>
    │              └ <class 'adapter.ms.bing.BingAdapter'>
    └ <conversation.ConversationContext object at 0x7f342b97baf0>

  File "/opt/chatgpt-qq/adapter/ms/bing.py", line 47, in __init__
    self.bot = EdgeChatbot(cookies=self.cookieData, proxy=account.proxy)
    │          │                   │    │                 │       └ None
    │          │                   │    │                 └ BingCookiePath(cookie_content='[{"domain":".bing.com","expirationDate":1736613166.802619,"hostOnly":false,"httpOnly":false,"n...
    │          │                   │    └ [{'domain': '.bing.com', 'expirationDate': 1736613166.802619, 'hostOnly': False, 'httpOnly': False, 'name': 'SnrOvr', 'path':...
    │          │                   └ <adapter.ms.bing.BingAdapter object at 0x7f342b944c70>
    │          └ <class 'EdgeGPT.EdgeGPT.Chatbot'>
    └ <adapter.ms.bing.BingAdapter object at 0x7f342b944c70>

  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT/EdgeGPT.py", line 29, in __init__
    Conversation(self.proxy, cookies=cookies),
    │            │    │              └ [{'domain': '.bing.com', 'expirationDate': 1736613166.802619, 'hostOnly': False, 'httpOnly': False, 'name': 'SnrOvr', 'path':...
    │            │    └ None
    │            └ <EdgeGPT.EdgeGPT.Chatbot object at 0x7f342b9474c0>
    └ <class 'EdgeGPT.conversation.Conversation'>
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT/conversation.py", line 59, in __init__
    raise Exception(

Exception: Authentication failed. You have not been accepted into the beta.
2024-01-13 15:47:17.769 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
原因：Authentication failed. You have not been accepted into the beta.

注："?"字符是终端输出不当，可忽略。

**Comment by huangzhitian** [comment]
接入点的问题，群主这个接入点早不能用了，issue找一下，别人分享的

**Comment by JJTools** [comment]
还不如直接用 chatgpt 。代理接口多而且还比较稳定。一个key 三个月。2块钱的事情。几乎就是0成本

**Comment by DYnamiC9750** [comment]
> 还不如直接用 chatgpt 。代理接口多而且还比较稳定。一个key 三个月。2块钱的事情。几乎就是0成本

大佬怎么买key呢

**Comment by JJTools** [comment]
> > 还不如直接用 chatgpt 。代理接口多而且还比较稳定。一个key 三个月。2块钱的事情。几乎就是0成本
> 
> 大佬怎么买key呢

Q 30247543 备注github。我不卖，送你几个

**Comment by JJTools** [comment]
> > 还不如直接用 chatgpt 。代理接口多而且还比较稳定。一个key 三个月。2块钱的事情。几乎就是0成本
> 
> 大佬怎么买key呢

网上搜一下吧。现在体验金没了。不过买key也不贵

**Comment by SkyCol** [comment]
Need to Update
