### ISSUE TITLE
语音功能无法正常使用

### ISSUE THREAD

**Issue by SteveJiyu** [lss233/chatgpt-mirai-qq-bot#1293]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在开启Edge TTS的功能后，gocqhttp发送语音时报错并强制退出。

**运行环境:**  
- 操作系统：ubuntu 22.0.4 LTS
- 部署方式：手动部署 
- 项目版本：2.5.3

**复现步骤**  
1. 部署项目
2. 正常设置并启动项目（已安装ffmpeg）
3. 向机器人发送 你好 消息
4. 机器人可正常返回文本消息，但无法正确处理语音消息，chatgpt-qq进程成功转换TTS，提交向gocqhttp时，gocqhttp被强制退出。（如果不开启TTS不会出现这种情况）

**预期行为**  
机器人发送文本/图片消息与语音消息

**截图**  
[2024-01-13 15:25:49] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://localhost:8554/ws 
[2024-01-13 15:25:49] [INFO]: 正在检查更新. 
[2024-01-13 15:25:49] [INFO]: 已连接到反向WebSocket Universal服务器 ws://localhost:8554/ws 
[2024-01-13 15:25:49] [INFO]: 检查更新完成. 当前已运行最新版本. 
[2024-01-13 15:25:49] [INFO]: 开始诊断网络情况 
[2024-01-13 15:25:52] [INFO]: 网络诊断完成. 未发现问题 
[2024-01-13 15:25:58] [INFO]: 收到好友 落*****(1***2) 的消息: 你好 (-840970102) 
[2024-01-13 15:26:00] [INFO]: 发送好友 1***2(1***2)  的消息: [{"type":  ... (1911601515) 
panic: runtime error: index out of range [0] with length 0

goroutine 160 [running]:
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).nextAddr(0xc0004027c0?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/highway.go:227 +0xfd
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).selectConn(0xfa21e0?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/highway.go:248 +0xe5
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).uploadSingle(0xc0000c4990, {0x1a, {0xbf6f80, 0xc000163bc0}, {0xc00037c830, 0x10, 0x10}, 0x1be7, {0x0, 0x0, ...}, ...})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/bdh.go:39 +0x68
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).Upload(0xc0000c4990, {0x1a, {0xbf6f80, 0xc000163bc0}, {0xc00037c830, 0x10, 0x10}, 0x1be7, {0x0, 0x0, ...}, ...})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/bdh.go:117 +0x425
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadVoice(0xc0002b2000, {0x48?, 0x0?, 0xc0001dcf10?}, {0xbf9668?, 0xc000163bc0})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/ptt.go:76 +0x358
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadMedia.func2()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:245 +0xff
github.com/Mrs4s/go-cqhttp/coolq.(*worker).do.func1()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:142 +0x5a
created by github.com/Mrs4s/go-cqhttp/coolq.(*worker).do
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:140 +0x85

**配置文件**  
[text_to_speech]
engine = "edge"
always = false
default = "zh-CN-XiaoxiaoNeural"

**Comment by SteveJiyu** [comment]
重启就解决，但是调用多了还是会报错。
