### ISSUE TITLE
[BUG] 启动chatgpt时报错：toml.decoder.TomlDecodeError: Key name found without value. 

### ISSUE THREAD

**Issue by Tywh202** [lss233/chatgpt-mirai-qq-bot#1294]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
刚启动控制台报错如下：
Active code page: 65001
2024-01-16 22:54:51.042 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：chatgpt-web
2024-01-16 22:54:51.043 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：openai-api
2024-01-16 22:54:51.043 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：baidu
2024-01-16 22:54:51.043 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：slack
2024-01-16 22:54:51.043 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：bard
2024-01-16 22:54:51.043 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：bing
2024-01-16 22:54:51.043 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：bing
2024-01-16 22:54:51.044 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：bing
2024-01-16 22:54:51.044 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：chatglm
2024-01-16 22:54:51.044 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：poe-token
2024-01-16 22:54:51.044 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：poe-token
2024-01-16 22:54:51.044 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：poe-token
2024-01-16 22:54:51.044 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：poe-token
2024-01-16 22:54:51.044 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：poe-token
2024-01-16 22:54:51.045 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：poe-token
2024-01-16 22:54:51.045 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：poe-token
2024-01-16 22:54:51.045 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：poe-token
2024-01-16 22:54:51.045 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：poe-token
2024-01-16 22:54:51.045 | DEBUG    | framework.accounts.manager:register_type:35 - [AccountManager] 注册账号类型：xinghuo-cookie
Traceback (most recent call last):
  File "F:\QQbot\Windowsv.3.0.0-Alpha2\chatgpt\bot.py", line 14, in <module>
    import constants
  File "F:\QQbot\Windowsv.3.0.0-Alpha2\chatgpt\constants.py", line 41, in <module>
    config = Config.load_config()
             ^^^^^^^^^^^^^^^^^^^^
  File "F:\QQbot\Windowsv.3.0.0-Alpha2\chatgpt\config.py", line 831, in load_config
    return Config.parse_obj(toml.loads(str(guessed_str)))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\QQbot\Windowsv.3.0.0-Alpha2\python3.11\Lib\site-packages\toml\decoder.py", line 213, in loads
    raise TomlDecodeError("Key name found without value."" Reached end of line.", original, i)
toml.decoder.TomlDecodeError: Key name found without value. Reached end of line. (line 7 column 3 char 118)
程序已停止运行。
Press any key to continue . . .

**运行环境:**  
操作系统：Windows 11 22H2
部署方式：Windows快速启动包
项目版本：[[早期预览版] v3.0.0-alpha2

**复现步骤**  
描述你是如何触发这个 BUG 的
1初始化并按照教程修改配置文件结束
2打开启动ChatGPT.cmd
3控制台报错

**截图**  
![Quicker_20240116_230340](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/132920830/4346e5c6-e3b7-49cb-8800-07de04454934)

**Comment by whitebalck547** [comment]
这个账号怎么设置？好像跟2.5.3和.2版本不一样啊

**Comment by mcxgjkh** [comment]
我也是3.00，他好像有bug，尝试一下低版本的包

**Comment by mcxgjkh** [comment]
![Snipaste_2024-02-22_14-31-12](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/94793068/f558e7c6-8543-4e47-832b-fa13cc7fd02d)
我的建议是用2.5.3
gocqhttp的教程没了只能用mirai版的了

**Comment by mcxgjkh** [comment]
亲测可以，2.5.3登录成功
![Uploading Snipaste_2024-02-22_14-38-51.png…]()
