### ISSUE TITLE
[Feature] 优化"session_id"处理逻辑

### ISSUE THREAD

**Issue by liu2-3zhi** [lss233/chatgpt-mirai-qq-bot#1301]
奇奇怪怪的报错

~~貌似是第三方软件的api没有适配好。~~

 "session_id"可否优化一下"session_id"的处理逻辑， 避免因为适配问题导致的"IndexError"
 
"session_id"处理参考代码

```python
    if '-' not in data['session_id'] or data['session_id'].startswith('-'):
        data['session_id'] = 'friend-' + data['session_id']
        parts = data['session_id'].split('-', 1)
        data['session_id'] = parts[0] + '-' + parts[1].replace('-', '_')
    else:
        parts = data['session_id'].split('-', 1)
        data['session_id'] = parts[0] + '-' + parts[1].replace('-', '_')
```
 
以下为错误日志：

```python
2024-02-03 04:18:06.058 | INFO     | platforms.http_service:construct_bot_request:174 - Get message from wxid_abcdefg1234567[wxid_abcdefg1234567]:
你好
2024-02-03 04:18:06.059 | DEBUG    | platforms.http_service:process_request:101 - Start to process bot request 1706933886059.
2024-02-03 04:18:06.060 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2024-02-03 04:18:06.060 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
INFO:quart.serving:192.168.1.254:34294 POST /v2/chat 1.1 200 13 105797
[2024-02-03 04:18:06,163] 192.168.1.254:34294 POST /v2/chat 1.1 200 13 105797
INFO:quart.serving:192.168.1.254:34294 POST /v2/chat 1.1 - - 107120
2024-02-03 04:18:06.165 | DEBUG    | middlewares.timeout:create_timeout_task:61 - [Timeout] 开始计时……
[2024-02-03 04:18:06,164] 192.168.1.254:34294 POST /v2/chat 1.1 - - 107120
[2024-02-03 04:18:06,163] 192.168.1.254:34294 POST /v2/chat 1.1 200 13 105797
[2024-02-03 04:18:06,164] 192.168.1.254:34294 POST /v2/chat 1.1 - - 107120
2024-02-03 04:18:07.025 | DEBUG    | adapter.chatgpt.api:ask:300 - [尝试使用ChatGPT-API:gpt-3.5-turbo] 请求：你好
2024-02-03 04:18:07.035 | DEBUG    | platforms.http_service:v2_chat_response:151 - Bot request 1706933886059 response -> 
{"result": "SUCCESS", "message": [], "voice": [], "image": []}
INFO:quart.serving:192.168.1.254:34294 GET /v2/chat/response 1.1 200 62 2694
[2024-02-03 04:18:07,036] 192.168.1.254:34294 GET /v2/chat/response 1.1 200 62 2694
[2024-02-03 04:18:07,036] 192.168.1.254:34294 GET /v2/chat/response 1.1 200 62 2694
INFO:quart.serving:192.168.1.254:34294 GET /v2/chat/response 1.1 - - 3450
[2024-02-03 04:18:07,037] 192.168.1.254:34294 GET /v2/chat/response 1.1 - - 3450
[2024-02-03 04:18:07,037] 192.168.1.254:34294 GET /v2/chat/response 1.1 - - 3450
2024-02-03 04:18:07.744 | DEBUG    | adapter.chatgpt.api:ask:312 - [ChatGPT-API:gpt-3.5-turbo] 响应：你好！有什么我可以帮助你的吗？
2024-02-03 04:18:07.744 | DEBUG    | adapter.chatgpt.api:ask:313 - [ChatGPT-API:gpt-3.5-turbo] 使用 token 数：33
2024-02-03 04:18:07.745 | DEBUG    | adapter.chatgpt.api:ask:318 - [ChatGPT-API:gpt-3.5-turbo] 接收到全部消息花费了0.72秒
2024-02-03 04:18:07.747 | DEBUG    | middlewares.timeout:handle_respond:52 - [Timeout] 取消计时……
2024-02-03 04:18:07.747 | INFO     | platforms.http_service:response:86 - Got response msg -> <class 'graia.ariadne.message.chain.MessageChain'> -> 你好！有什么我可以帮助你的吗？
2024-02-03 04:18:07.748 | DEBUG    | middlewares.timeout:create_timeout_task:61 - [Timeout] 开始计时……
2024-02-03 04:18:07.748 | ERROR    | middlewares.timeout:handle_request:36 - 发生错误: list index out of range
2024-02-03 04:18:07.749 | ERROR    | universal:handle_message:297 - list index out of range
Traceback (most recent call last):

  File "/app/bot.py", line 58, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at /app/platforms/onebot_bot.py:356> wait_for=<Future pending cb=[Tas...
    │    │                  │       └ <function gather at 0x7fce0788e560>
    │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x7fce078a7130>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fce078a70a0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fce078acc10>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fce078605e0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "/app/platforms/http_service.py", line 106, in process_request
    await handle_message(
          └ <function handle_message at 0x7fcdc2ea8f70>

> File "/app/universal.py", line 271, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x7fcdc2ed4670>
          │      │           │       │        └ <conversation.ConversationContext object at 0x7fcdc0885f30>
          │      │           │       └ <method 'strip' of 'str' objects>
          │      │           └ '你好'
          │      └ 'wxid_abcdefg1234567'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fcdc2ed4940>

  File "/app/universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fcdc2ed48b0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fcdc2ed4670>
          │ │              │           └ '你好'
          │ │              └ 'wxid_abcdefg1234567'
          │ └ <function MiddlewareConcurrentLock.handle_request at 0x7fcdc2ea96c0>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x7fcdc2eb0a30>

  File "/app/middlewares/concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fcdc2ed4670>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'wxid_abcdefg1234567'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fcdc2ed48b0>

  File "/app/universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fcdc2ed4820>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fcdc2ed4670>
          │ │              │           └ '你好'
          │ │              └ 'wxid_abcdefg1234567'
          │ └ <function Middleware.handle_request at 0x7fcdc2ea8820>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x7fcdc2e4fc70>

  File "/app/middlewares/middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fcdc2ed4670>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'wxid_abcdefg1234567'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fcdc2ed4820>

  File "/app/universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fcdc2ed4790>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fcdc2ed4670>
          │ │              │           └ '你好'
          │ │              └ 'wxid_abcdefg1234567'
          │ └ <function MiddlewareRatelimit.handle_request at 0x7fcdc2ea8a60>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x7fcdc2e4fc40>

  File "/app/middlewares/ratelimit.py", line 23, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fcdc2ed4670>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'wxid_abcdefg1234567'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fcdc2ed4790>

  File "/app/universal.py", line 53, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x7fcdc2ed4700>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fcdc2ed4670>
          │ │              │           └ '你好'
          │ │              └ 'wxid_abcdefg1234567'
          │ └ <function MiddlewareTimeout.handle_request at 0x7fcdc2ea97e0>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x7fcdc2e4fc10>

  File "/app/middlewares/timeout.py", line 40, in handle_request
    raise e

  File "/app/middlewares/timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
          │       │        │          │      │        └ 600.0
          │       │        │          │      └ Response(mode='mixed', buffer_delay=15.0, default_ai='chatgpt-api', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “...
          │       │        │          └ <unprintable Config object>
          │       │        └ <Task finished name='Task-22' coro=<handle_message.<locals>.request() done, defined at /app/universal.py:107> exception=Index...
          │       └ <function wait_for at 0x7fce0788e050>
          └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>

  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
           │   └ <method 'result' of '_asyncio.Task' objects>
           └ <Task finished name='Task-22' coro=<handle_message.<locals>.request() done, defined at /app/universal.py:107> exception=Index...

  File "/app/universal.py", line 236, in request
    await m.handle_respond_completed(session_id, prompt, respond)
          │ │                        │           │       └ <function handle_message.<locals>.respond at 0x7fcdc2ed4670>
          │ │                        │           └ '你好'
          │ │                        └ 'wxid_abcdefg1234567'
          │ └ <function MiddlewareRatelimit.handle_respond_completed at 0x7fcdc2ea8af0>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x7fcdc2e4fc40>

  File "/app/middlewares/ratelimit.py", line 27, in handle_respond_completed
    msg_id = session_id.split('-', 1)[1]
             │          └ <method 'split' of 'str' objects>
             └ 'wxid_abcdefg1234567'

IndexError: list index out of range
2024-02-03 04:18:07.916 | INFO     | platforms.http_service:response:86 - Got response msg -> <class 'str'> -> 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
list index out of range
2024-02-03 04:18:07.922 | DEBUG    | platforms.http_service:process_request:115 - Bot request 1706933886059 done.

```

**Comment by liu2-3zhi** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/pull/1310

**Comment by lss233** [comment]
OK，感谢建议
