### ISSUE TITLE
openAI账号登录失败

### ISSUE THREAD

**Issue by 12342435** [lss233/chatgpt-mirai-qq-bot#1333]
![屏幕截图 2024-03-21 203355](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/162893725/252249fb-3e4c-4ee4-9227-474a04ead4ad)
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
[2024-03-21 20:19:06.946] [info] 请选择项目源：1. 官方源 2. 镜像源
[2024-03-21 20:19:06.946] [info] 一般项目源选择官方源即可，如果下不下来可以选择镜像源
1
[2024-03-21 20:19:08.966] [info] 已选择官方源
[2024-03-21 20:19:08.966] [info] 请选择PIP下载源：1. 官方源 2. 镜像源
[2024-03-21 20:19:08.966] [info] 一般项目源选择镜像源，如果需要更新的话则选择官方源
2
[2024-03-21 20:19:10.011] [info] 已选择镜像源
[2024-03-21 20:19:11.082] [info] CHATGPT环境已存在
[2024-03-21 20:19:11.268] [info] 检查项目版本
Updating 757eac9..0aa5b69
error: Your local changes to the following files would be overwritten by merge:
        requirements.txt
Please commit your changes or stash them before you merge.
Aborting
[2024-03-21 20:19:18.194] [info] 开始安装依赖
[2024-03-21 20:19:18.195] [info] 当前PIP镜像源是：https://pypi.tuna.tsinghua.edu.cn/simple
找不到 C:\WINDOWS\TEMP\tmpuh1nt36g.bat
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: graia-ariadne==0.11.7 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 2)) (0.11.7)
Requirement already satisfied: graiax-silkcoder in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 3)) (0.3.6)
Requirement already satisfied: python-telegram-bot==20.4 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 4)) (20.4)
Requirement already satisfied: discord.py in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 5)) (2.3.2)
Requirement already satisfied: wechatpy~=2.0.0a26 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 6)) (2.0.0a26)
Requirement already satisfied: revChatGPT~=6.8.6 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 9)) (6.8.6)
Requirement already satisfied: openai~=0.27.8 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 10)) (0.27.10)
Requirement already satisfied: EdgeGPT==0.13.2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 11)) (0.13.2)
Requirement already satisfied: OpenAIAuth>=2.0.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 12)) (3.0.0)
Requirement already satisfied: BingImageCreator~=0.4.4 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 13)) (0.4.4)
Requirement already satisfied: poe-api==0.5.2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 14)) (0.5.2)
Requirement already satisfied: tiktoken~=0.4.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 15)) (0.4.0)
Requirement already satisfied: azure-cognitiveservices-speech in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 18)) (1.36.0)
Requirement already satisfied: edge-tts in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 19)) (6.1.10)
Requirement already satisfied: toml~=0.10.2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 22)) (0.10.2)
Requirement already satisfied: Pillow>=9.3.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 23)) (10.2.0)
Requirement already satisfied: tinydb~=4.8.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 24)) (4.8.0)
Requirement already satisfied: loguru~=0.7.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 25)) (0.7.2)
Requirement already satisfied: asyncio~=3.4.3 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 26)) (3.4.3)
Requirement already satisfied: pydantic in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 27)) (1.10.14)
Requirement already satisfied: markdown~=3.4.4 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 28)) (3.4.4)
Requirement already satisfied: python-markdown-math~=0.8 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 29)) (0.8)
Requirement already satisfied: pygments~=2.15.1 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 30)) (2.15.1)
Requirement already satisfied: imgkit~=1.2.3 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 31)) (1.2.3)
Requirement already satisfied: qrcode~=7.4.2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 32)) (7.4.2)
Requirement already satisfied: aiohttp~=3.8.5 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 33)) (3.8.6)
Requirement already satisfied: urllib3~=2.0.4 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 34)) (2.0.7)
Requirement already satisfied: requests~=2.31.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 35)) (2.31.0)
Requirement already satisfied: uuid~=1.30 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 36)) (1.30)
Requirement already satisfied: aiocqhttp~=1.4.4 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 37)) (1.4.4)
Requirement already satisfied: tls-client in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 38)) (1.0.1)
Requirement already satisfied: python-dateutil~=2.8.2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 39)) (2.8.2)
Requirement already satisfied: regex~=2023.6.3 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 40)) (2023.6.3)
Requirement already satisfied: httpx~=0.24.1 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 41)) (0.24.1)
Requirement already satisfied: Quart==0.17.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 42)) (0.17.0)
Requirement already satisfied: pydub~=0.25.1 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 43)) (0.25.1)
Requirement already satisfied: httpcore~=0.17.3 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 44)) (0.17.3)
Requirement already satisfied: graia-broadcast~=0.23.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requirements.txt (line 2)) (0.23.5)
Requirement already satisfied: typing-extensions<5.0,>=4.4 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requirements.txt (line 2)) (4.10.0)
Requirement already satisfied: graia-amnesia~=0.7.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requirements.txt (line 2)) (0.7.1)
Requirement already satisfied: launart<0.7,>=0.6.4 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requirements.txt (line 2)) (0.6.4)
Requirement already satisfied: packaging>=23.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requirements.txt (line 2)) (24.0)
Requirement already satisfied: creart~=0.3.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requirements.txt (line 2)) (0.3.0)
Requirement already satisfied: websockets in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from EdgeGPT==0.13.2->-r requirements.txt (line 11)) (12.0)
Requirement already satisfied: rich in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from EdgeGPT==0.13.2->-r requirements.txt (line 11)) (13.7.1)
Requirement already satisfied: certifi in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from EdgeGPT==0.13.2->-r requirements.txt (line 11)) (2024.2.2)
Requirement already satisfied: prompt-toolkit in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from EdgeGPT==0.13.2->-r requirements.txt (line 11)) (3.0.43)
Requirement already satisfied: python-socks in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from poe-api==0.5.2->-r requirements.txt (line 14)) (2.4.4)
Requirement already satisfied: quickjs in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from poe-api==0.5.2->-r requirements.txt (line 14)) (1.19.4)
Requirement already satisfied: websocket-client in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from poe-api==0.5.2->-r requirements.txt (line 14)) (1.7.0)
Requirement already satisfied: aiofiles in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (23.2.1)
Requirement already satisfied: blinker in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (1.7.0)
Requirement already satisfied: click in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (8.1.7)
Requirement already satisfied: hypercorn>=0.11.2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (0.16.0)
Requirement already satisfied: itsdangerous in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (2.1.2)
Requirement already satisfied: jinja2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (3.1.3)
Requirement already satisfied: markupsafe in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (2.1.5)
Requirement already satisfied: werkzeug>=2.0.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (3.0.1)
Requirement already satisfied: cryptography>=3.1 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.txt (line 6)) (42.0.5)
Requirement already satisfied: optionaldict>=0.1.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.txt (line 6)) (0.1.2)
Requirement already satisfied: requests-pkcs12<2.0,>=1.7 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.txt (line 6)) (1.24)
Requirement already satisfied: xmltodict>=0.11.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.txt (line 6)) (0.13.0)
Requirement already satisfied: tqdm in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from openai~=0.27.8->-r requirements.txt (line 10)) (4.66.2)
Requirement already satisfied: colorama>=0.3.4 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from loguru~=0.7.0->-r requirements.txt (line 25)) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from loguru~=0.7.0->-r requirements.txt (line 25)) (1.1.0)
Requirement already satisfied: six in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from imgkit~=1.2.3->-r requirements.txt (line 31)) (1.16.0)
Requirement already satisfied: pypng in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from qrcode~=7.4.2->-r requirements.txt (line 32)) (0.20220715.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 33)) (23.2.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 33)) (3.3.2)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 33)) (6.0.5)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 33)) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 33)) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 33)) (1.4.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 33)) (1.3.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from requests~=2.31.0->-r requirements.txt (line 35)) (3.6)
Requirement already satisfied: sniffio in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from httpx~=0.24.1->-r requirements.txt (line 41)) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from httpcore~=0.17.3->-r requirements.txt (line 44)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from httpcore~=0.17.3->-r requirements.txt (line 44)) (4.3.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from anyio<5.0,>=3.0->httpcore~=0.17.3->-r requirements.txt (line 44)) (1.2.0)
Requirement already satisfied: importlib-metadata>=3.6 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from creart~=0.3.0->graia-ariadne==0.11.7->-r requirements.txt (line 2)) (7.1.0)
Requirement already satisfied: cffi>=1.12 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from cryptography>=3.1->wechatpy~=2.0.0a26->-r requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: statv>=0.2.2 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from graia-amnesia~=0.7.0->graia-ariadne==0.11.7->-r requirements.txt (line 2)) (0.3.2)
Requirement already satisfied: socksio==1.* in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT==0.13.2->-r requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: h2>=3.1.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 42)) (4.1.0)
Requirement already satisfied: priority in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 42)) (2.0.0)
Requirement already satisfied: taskgroup in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 42)) (0.0.0a4)
Requirement already satisfied: tomli in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 42)) (2.0.1)
Requirement already satisfied: wsproto>=0.14.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 42)) (1.2.0)
Requirement already satisfied: wcwidth in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from prompt-toolkit->EdgeGPT==0.13.2->-r requirements.txt (line 11)) (0.2.13)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from requests[socks]->poe-api==0.5.2->-r requirements.txt (line 14)) (1.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from rich->EdgeGPT==0.13.2->-r requirements.txt (line 11)) (3.0.0)
Requirement already satisfied: pycparser in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from cffi>=1.12->cryptography>=3.1->wechatpy~=2.0.0a26->-r requirements.txt (line 6)) (2.21)
Requirement already satisfied: hyperframe<7,>=6.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from h2>=3.1.0->hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 42)) (6.0.1)
Requirement already satisfied: hpack<5,>=4.0 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from h2>=3.1.0->hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 42)) (4.0.0)
Requirement already satisfied: zipp>=0.5 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from importlib-metadata>=3.6->creart~=0.3.0->graia-ariadne==0.11.7->-r requirements.txt (line 2)) (3.18.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\xytt8\miniconda3\envs\chatgpt\lib\site-packages (from markdown-it-py>=2.2.0->rich->EdgeGPT==0.13.2->-r requirements.txt (line 11)) (0.1.2)
[2024-03-21 20:19:25.533] [info] 启动程序
找不到 C:\WINDOWS\TEMP\tmp32y9694x.bat
2024-03-21 20:19:26.897 | SUCCESS  | config:scan_presets:565 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2024-03-21 20:19:26.897 | SUCCESS  | config:scan_presets:565 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2024-03-21 20:19:26.897 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl <==> ./presets\catgirl.txt [成功]
2024-03-21 20:19:26.897 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl_en <==> ./presets\catgirl_en.txt [成功]
2024-03-21 20:19:26.897 | SUCCESS  | config:scan_presets:578 - 注册预设：issue402 <==> ./presets\issue402.txt [成功]
2024-03-21 20:19:26.897 | SUCCESS  | config:scan_presets:578 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2024-03-21 20:19:26.971 | INFO     | manager.bot:__check_proxy:406 - [代理测试] 正在检查代理配置：http://127.0.0.1:10810
2024-03-21 20:19:27.166 | SUCCESS  | manager.bot:__check_proxy:414 - [代理测试] 连接成功！
2024-03-21 20:19:27.166 | INFO     | manager.bot:handle_openai:107 - 当前的 browserless_endpoint 为：https://chatgpt-proxy.lss233.com/api/
2024-03-21 20:19:27.166 | INFO     | manager.bot:handle_openai:123 - 当前的 api_endpoint 为：https://api.openai.com/v1
2024-03-21 20:19:27.166 | INFO     | manager.bot:login_openai:340 - 正在登录第 1 个 OpenAI 账号
2024-03-21 20:19:27.166 | INFO     | manager.bot:__login_V1:432 - 模式：无浏览器登录
2024-03-21 20:19:27.166 | INFO     | manager.bot:__login_V1:482 - 尝试使用 access_token 登录中...
2024-03-21 20:19:28.120 | ERROR    | manager.bot:login_openai:371 - 未知错误：
2024-03-21 20:19:28.123 | ERROR    | manager.bot:login_openai:372 - 'ascii' codec can't encode character '\uff09' in position 1193: ordinal not in range(128)
Traceback (most recent call last):

  File "D:\neat\Compressed\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\bot.py", line 14, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x00000210FD8553F0>
    │    │                  └ <manager.bot.BotManager object at 0x00000210FD850C10>
    │    └ <function BaseEventLoop.run_until_complete at 0x00000210F3CB5E10>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000210F54EAE60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000210F3CB7880>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000210F3C4EA70>
    └ <Handle <TaskStepMethWrapper object at 0x00000210FDA2E410>()>

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x00000210FDA2E410>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x00000210FDA2E410>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000210FDA2E410>()>

  File "D:\neat\Compressed\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\manager\bot.py", line 162, in login
    await login_func()
          └ <bound method BotManager.handle_openai of <manager.bot.BotManager object at 0x00000210FD850C10>>

  File "D:\neat\Compressed\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\manager\bot.py", line 130, in handle_openai
    await self.login_openai()
          │    └ <function BotManager.login_openai at 0x00000210FD855990>
          └ <manager.bot.BotManager object at 0x00000210FD850C10>

> File "D:\neat\Compressed\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\manager\bot.py", line 346, in login_openai
    bot = await self.__login_V1(account)
                │               └ OpenAIAccessTokenAuth(mode='browserless', proxy=None, driver_exec_path=None, browser_exec_path=None, conversation=None, paid=...
                └ <manager.bot.BotManager object at 0x00000210FD850C10>

  File "D:\neat\Compressed\Windows-quickstart-go-cqhttp-refs.tags.v2.5.3\chatgpt-mirai-qq-bot\manager\bot.py", line 484, in __login_V1
    bot = V1Chatbot(config=config)
          │                └ {'proxy': 'http://127.0.0.1:10810', 'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZC...
          └ <class 'revChatGPT.V1.AsyncChatbot'>

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\site-packages\revChatGPT\V1.py", line 1099, in __init__
    self.session = AsyncClient(headers=self.session.headers)
    │    │         │                   │    │       └ {'Accept': 'text/event-stream', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRN...
    │    │         │                   │    └ <requests.sessions.Session object at 0x00000210FDA2E740>
    │    │         │                   └ <revChatGPT.V1.AsyncChatbot object at 0x00000210FDA2EAD0>
    │    │         └ <class 'httpx.AsyncClient'>
    │    └ <requests.sessions.Session object at 0x00000210FDA2E740>
    └ <revChatGPT.V1.AsyncChatbot object at 0x00000210FDA2EAD0>

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\site-packages\httpx\_client.py", line 1371, in __init__
    super().__init__(

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\site-packages\httpx\_client.py", line 182, in __init__
    self.headers = Headers(headers)
    │    │         │       └ {'Accept': 'text/event-stream', 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRN...
    │    │         └ <class 'httpx.Headers'>
    │    └ <property object at 0x00000210F728EF20>
    └ <httpx.AsyncClient object at 0x00000210FDA2E830>

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\site-packages\httpx\_models.py", line 71, in __init__
    self._list = [
    └ <unprintable Headers object>

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\site-packages\httpx\_models.py", line 75, in <listcomp>
    normalize_header_value(v, encoding),
    │                      │  └ None
    │                      └ 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZ...
    └ <function normalize_header_value at 0x00000210F335A0E0>

  File "C:\Users\xytt8\Miniconda3\envs\chatgpt\lib\site-packages\httpx\_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
           │     │      └ None
           │     └ <method 'encode' of 'str' objects>
           └ 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZ...

UnicodeEncodeError: 'ascii' codec can't encode character '\uff09' in position 1193: ordinal not in range(128)
2024-03-21 20:19:28.132 | SUCCESS  | manager.bot:login_openai:375 - 成功登录 0/1 个 OpenAI 账号！
2024-03-21 20:19:28.132 | ERROR    | manager.bot:login:169 - 没有登录成功的账号，程序无法启动！
[2024-03-21 20:19:28.253] [info] 按任意键退出...

**运行环境:**  
- 操作系统：windows
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/162893725/52c3b7bf-4c26-4fe4-9b72-c09bfa9394da)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by drearry** [comment]
我用新版没反应，换成旧版就能用了。
v2.5.2
