### ISSUE TITLE
Window 手动部署，Mirai 使用了签名服务依旧无法登录

### ISSUE THREAD

**Issue by not-Ilyina** [lss233/chatgpt-mirai-qq-bot#1357]
{
    "code": 0,
    "msg": "IAA 云天明 章北海",
    "data": {
        "version": "1.1.9",
        "protocol": {
            "qua": "V1_AND_SQ_8.9.58_4106_YYB_D",
            "version": "8.9.58",
            "code": "4106",
            "package_name": "com.tencent.mobileqq"
        }
    }
}
2024-07-13 13:47:31 I/UnidbgFetchQsign: Bot(3591693732) initialize by http://127.0.0.1:8081
2024-07-13 13:47:32 I/UnidbgFetchQsign: Bot(3591693732) register, Instance loaded successfully.
2024-07-13 13:47:32 I/UnidbgFetchQsign: Bot(3591693732) initialize complete
2024-07-13 13:47:35 I/Bot.3591693732: Calculating type 2 PoW, it can take some time....
2024-07-13 13:47:35 I/Bot.3591693732: Got PoW result, cost: 87 ms
2024-07-13 13:48:04 I/UnidbgFetchQsign: Bot(3591693732) destroy, Instance destroyed successfully.
2024-07-13 13:48:04 E/main: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3591693732), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)

**Comment by alsojiangshi** [comment]
风控问题，用ANDROID_PAD的协议，详见mirai仓库closed issue的#2864

**Comment by lss233** [comment]
关闭issue原因：非本项目问题。
