### ISSUE TITLE
[BUG] 对接mirai时出现报错

### ISSUE THREAD

**Issue by Bio233** [lss233/chatgpt-mirai-qq-bot#1378]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：win11
- Docker： ？
- 项目版本：Windows-quickstart-mirai-refs.tags.v2.5.3

**复现步骤**  
描述你是如何触发这个 BUG 的
采用反向连接，mirai等待对接时启动gpt，gpt和mirai出现如下报错

**预期行为**  
连接成功

**截图**  

2024-11-23 15:35:42.349 | INFO     | launart.manager:_launchable_task_done_callback:69 - [elizabeth.connection.3433779255.websocket_server_connection] completed.
2024-11-23 15:35:42.349 | INFO     | graia.amnesia.builtins.aiohttp:launch:513 - starting server on 0.0.0.0:8554
2024-11-23 15:35:42.362 | SUCCESS  | launart.manager:launch:385 - Layer #1:[http.server/aiohttp, cache.client/memcache, http.client/aiohttp] preparation completed.
2024-11-23 15:35:42.363 | INFO     | platforms.ariadne_bot:start_background:192 - 尝试从 Mirai 服务中读取机器人 QQ 的 session key……
2024-11-23 15:35:42.363 | INFO     | platforms.ariadne_bot:start_background:194 - [提示] 当前为反向 ws 模式，请确保你的 mirai api http 设置了正确的 reverse-ws adapter 配置
2024-11-23 15:35:42.363 | INFO     | platforms.ariadne_bot:start_background:195 - [提示] 配置不正确会导致 Mirai 端出现错误提示。
2024-11-23 15:35:42.363 | SUCCESS  | launart.manager:launch:385 - Layer #3:[elizabeth.service] preparation completed.
2024-11-23 15:35:42.363 | INFO     | launart.manager:launch:390 - All components prepared, start blocking phase.
2024-11-23 15:35:42.977 | INFO     | __main__:<module>:52 - [Edge TTS] 读取成功！
2024-11-23 15:35:47.254 | ERROR    | graia.amnesia.transport.rider:trigger_callbacks:37 - Host 'localhost:8554' cannot contain ':' (at position 9)
Traceback (most recent call last):

> File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\graia\ariadne\connection\ws.py", line 142, in _
    req: HttpRequest = await io.extra(HttpRequest)
                             │  │     └ <class 'graia.amnesia.transport.common.http.extra.HttpRequest'>
                             │  └ <function AiohttpServerWebsocketIO.extra at 0x000001E2417CB9A0>
                             └ <graia.amnesia.builtins.aiohttp.AiohttpServerWebsocketIO object at 0x000001E26A560EB0>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\graia\amnesia\builtins\aiohttp.py", line 386, in extra
    self.request.url,
    │    │       └ <aiohttp._helpers.reify object at 0x000001E241727490>
    │    └ <Request GET / >
    └ <graia.amnesia.builtins.aiohttp.AiohttpServerWebsocketIO object at 0x000001E26A560EB0>

  File "aiohttp\_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__
    val = self.wrapped(inst)

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\aiohttp\web_request.py", line 437, in url
    url = URL.build(scheme=self.scheme, host=self.host)
          │   │            │    │            │    └ <aiohttp._helpers.reify object at 0x000001E2417279D0>
          │   │            │    │            └ <Request GET / >
          │   │            │    └ <aiohttp._helpers.reify object at 0x000001E241725540>
          │   │            └ <Request GET / >
          │   └ <classmethod(<function URL.build at 0x000001E24135EDD0>)>
          └ <class 'yarl.URL'>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\yarl\_url.py", line 387, in build
    _host = _encode_host(host, validate_host=True)
            │            └ 'localhost:8554'
            └ <functools._lru_cache_wrapper object at 0x000001E2413A1A60>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\yarl\_url.py", line 1476, in _encode_host
    raise ValueError(

ValueError: Host 'localhost:8554' cannot contain ':' (at position 9)
2024-11-23 15:35:47.260 | INFO     | graia.ariadne.connection.ws:_:92 - Websocket connection closed
2024-11-23 15:35:47.261 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
Traceback (most recent call last):

  File "E:\TOOL\GPT_mirai\chatgpt-mirai-qq-bot\bot.py", line 58, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at E:\TOOL\GPT_mirai\chatgpt-mirai-qq-bot\platforms\ariadne_bot.py:33...
    │    │                  │       └ <function gather at 0x000001E24076B400>
    │    │                  └ <module 'asyncio' from 'C:\\Users\\Bio\\Miniconda3\\envs\\chatgpt\\lib\\asyncio\\__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x000001E24078C0D0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001E24080A9E0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001E24078DB40>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001E23EF58EE0>
    └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>

> File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
                 │               └ <Request GET / >
                 └ <bound method Application._handle of <Application 0x1e26a441570>>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
                 │       └ <Request GET / >
                 └ <bound method AiohttpRouter.handle_websocket_request of <graia.amnesia.builtins.aiohttp.AiohttpRouter object at 0x000001E26A4...

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\graia\amnesia\builtins\aiohttp.py", line 468, in handle_websocket_request
    await websocket_io.close()
          │            └ <function AiohttpServerWebsocketIO.close at 0x000001E2417CBC70>
          └ <graia.amnesia.builtins.aiohttp.AiohttpServerWebsocketIO object at 0x000001E26A560EB0>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\graia\amnesia\builtins\aiohttp.py", line 411, in close
    await self.websocket.close()
          │    │         └ <function WebSocketResponse.close at 0x000001E2417AF6D0>
          │    └ <WebSocketResponse Switching Protocols not prepared>
          └ <graia.amnesia.builtins.aiohttp.AiohttpServerWebsocketIO object at 0x000001E26A560EB0>

  File "C:\Users\Bio\Miniconda3\envs\chatgpt\lib\site-packages\aiohttp\web_ws.py", line 337, in close
    raise RuntimeError("Call .prepare() first")

RuntimeError: Call .prepare() first
ERROR:aiohttp.server:Error handling request

![image](https://github.com/user-attachments/assets/9318e88f-03e6-4826-95c7-65138a4aefa8)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by Bio233** [comment]
> **提交 issue 前，请先确认：**
> 
> * [√] 我已看过 **FAQ**，此问题不在列表中
> * [√] 我已看过其他 issue，他们不能解决我的问题
> * [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG
> 
> **表现** 描述 BUG 的表现情况
> 
> **运行环境:**
> 
> * 操作系统：win11
> * Docker： ？
> * 项目版本：Windows-quickstart-mirai-refs.tags.v2.5.3
> 
> **复现步骤** 描述你是如何触发这个 BUG 的 采用反向连接，mirai等待对接时启动gpt，gpt和mirai出现如下报错
> 
> **预期行为** 连接成功
> 
> **截图**
> 
![image](https://github.com/user-attachments/assets/afc2f909-1a5d-46c8-af95-a4cdf49ece52)
![image](https://github.com/user-attachments/assets/f433e4aa-ddf6-4f2d-a37f-9638ba00e96a)
![image](https://github.com/user-attachments/assets/f2aacd18-a2de-4b76-9d47-f71b1619ccb2)
![image](https://github.com/user-attachments/assets/c4d89238-2264-4bbd-87a1-c3b23bf704dc)

> 
> ![image](https://private-user-images.githubusercontent.com/179860162/389182442-9318e88f-03e6-4826-95c7-65138a4aefa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDg1MjYsIm5iZiI6MTczMjM0ODIyNiwicGF0aCI6Ii8xNzk4NjAxNjIvMzg5MTgyNDQyLTkzMThlODhmLTAzZTYtNDgyNi05NWM3LTY1MTM4YTRhZWZhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QwNzUwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGJlMTA1MmFjZGIzYjhiYmY1YTUxYWQxNmFhMDUxZWIyY2ZlZGI4NWNkZDE0NmQ1YjQyNTUxNjNjNWYwYTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rPz8TVnbxhBwJGsduTfE643LFLcIeQLQiHZS5e-YZaQ)
> 
> **其他内容** 此处填写其他内容，没有可跳过

**Comment by hapa3** [comment]
同样的问题

**Comment by sanxianxiaohuntun** [comment]
问题 1: ValueError: Host 'localhost:8554' cannot contain ':'
是因为在 localhost:8554 中的 : 被认为是无效字符。你可以尝试写成127.0.0.1:8554
问题 2: RuntimeError: Call .prepare() first
这个问题发生在尝试关闭 WebSocket 连接时，提示在调用 close 之前，应该先调用 .prepare() 方法。这通常是因为在处理 WebSocket 请求时，aiohttp 的 WebSocketResponse 对象没有被正确初始化。

**Comment by Ghostlikes** [comment]
> 问题 1: ValueError: Host 'localhost:8554' cannot contain ':' 是因为在 localhost:8554 中的 : 被认为是无效字符。你可以尝试写成127.0.0.1:8554 问题 2: RuntimeError: Call .prepare() first 这个问题发生在尝试关闭 WebSocket 连接时，提示在调用 close 之前，应该先调用 .prepare() 方法。这通常是因为在处理 WebSocket 请求时，aiohttp 的 WebSocketResponse 对象没有被正确初始化。

请问问题一应该在哪个文件修改呢

**Comment by Adydio** [comment]
我目前解决了可以运行。https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/dui-jie-liao-tian-ping-tai/dui-jie-mirai 我采用了正向连接，修改了\mirai\config\net.mamoe.mirai-api-http\config.yml的内容。上述报错跟反向连接有关，我先试了一个讯飞的可以顺利运行。

**Comment by lss233** [comment]
自 v3 开始项目已不再主动支持 mirai，第三方开发者可以自行编写插件对接。
