### ISSUE TITLE
chat-chatgpt-1运行失败

### ISSUE THREAD

**Issue by dmfhyjk** [lss233/chatgpt-mirai-qq-bot#15]
```
chat-chatgpt-1  | Traceback (most recent call last):
chat-chatgpt-1  |   File "/app/bot.py", line 11, in <module>
chat-chatgpt-1  |     import chatbot
chat-chatgpt-1  |   File "/app/chatbot.py", line 4, in <module>
chat-chatgpt-1  |     config_data = json.load(jsonfile)
chat-chatgpt-1  |   File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
chat-chatgpt-1  |     return loads(fp.read(),
chat-chatgpt-1  |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
chat-chatgpt-1  |     return _default_decoder.decode(s)
chat-chatgpt-1  |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
chat-chatgpt-1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
chat-chatgpt-1  |   File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
chat-chatgpt-1  |     obj, end = self.scan_once(s, idx)
chat-chatgpt-1  | json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 27 (char 43)
****
```

**Comment by dmfhyjk** [comment]
> `config.json`第三行有语言错误哈，检查一下

懂了，config.json要把注释删掉
