### ISSUE TITLE
通过 docker run 运行时报 json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by Pil0tXia** [lss233/chatgpt-mirai-qq-bot#17]
按照了`通过 Docker 部署 （适合已经有 Mirai 的用户)`
```bash
root@UbuntuVM:~/mirai-api-http/chatgpt-mirai-qq-bot$ sudo docker run --name mirai-chatgpt-bot -v /home/root/mirai-api-http/chatgpt-mirai-qq-bot/config.json:/app/config.json --network host lss233/chatgpt-mirai-qq-bot:latest
Traceback (most recent call last):
  File "/app/bot.py", line 11, in <module>
    import chatbot
  File "/app/chatbot.py", line 4, in <module>
    config_data = json.load(jsonfile)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 27 (char 43)
```

**Comment by lss233** [comment]
#15

**Comment by Pil0tXia** [comment]
好的，删掉注释就没有报错了，但是出现了新的错误：
```
Traceback (most recent call last):
  File "/app/bot.py", line 11, in <module>
    import chatbot
  File "/app/chatbot.py", line 7, in <module>
    bot = Chatbot(config_data["openai"], conversation_id=None)
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 32, in __init__
    self.refresh_session()
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 241, in refresh_session
    raise exc
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 238, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 265, in login
    raise exc
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 258, in login
    auth.begin()
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 83, in begin
    self.part_two()
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 112, in part_two
    self.part_three(token=csrf_token)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 144, in part_three
    self.part_four(url=url)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 178, in part_four
    self.part_five(state=state)
  File "/usr/local/lib/python3.9/site-packages/OpenAIAuth/OpenAIAuth.py", line 215, in part_five
    raise ValueError("Captcha detected")
ValueError: Captcha detected
```

**Comment by lss233** [comment]
#9

**Comment by Pil0tXia** [comment]
感谢！
