### ISSUE TITLE
[BUG] 启动初始化在PIP的是报错 一片红

### ISSUE THREAD

**Issue by ziwuchina** [lss233/chatgpt-mirai-qq-bot#200]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：win10专业工作站版
- Docker： ？
- 项目版本：1.5.7
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "http\client.py", line 463, in read
  File "http\client.py", line 507, in readinto
  File "socket.py", line 704, in readinto
  File "ssl.py", line 1242, in recv_into
  File "ssl.py", line 1100, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\commands\install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\urllib3\response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "contextlib.py", line 137, in __exit__
  File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp_u__6wni\pip.zip\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read

**Comment by lss233** [comment]
这个就是你的网络问题了。 可以试试 v1.5.8-alpha 版本，已经不需要下载这些东西了

**Comment by lss233** [comment]
新版本的快速部署包已经不会再出现此问题。
