### ISSUE TITLE
最后一步，404

### ISSUE THREAD

**Issue by 666Thanos** [lss233/chatgpt-mirai-qq-bot#202]
**提交 issue 前，请先确认：**
- [ ] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows11
- Docker： ？
- 项目版本：1.5.7

**复现步骤**  
描述你是如何触发这个 BUG 的
最后一步，404了

![image](https://user-images.githubusercontent.com/106792549/221361853-fd424273-4594-4f01-9c1a-ed834a1586e5.png)
![image](https://user-images.githubusercontent.com/106792549/221361864-fc2223e7-b584-4271-807d-f82adda32938.png)

**Comment by magisk317** [comment]
你这个跟我之前遇到的一个问题很想， 不过我是在docker里遇到的，你这看着像是直接跑的
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/187#issuecomment-1443453122

**Comment by lss233** [comment]
此问题原因是 mirai api http 未配置 ws adapter。 可以在 Wiki 找到相关章节补充配置。

**Comment by 666Thanos** [comment]
> 此问题原因是 mirai api http 未配置 ws adapter。 可以在 Wiki 找到相关章节补充配置。

补充配置后，问题依旧未解决。
![image](https://user-images.githubusercontent.com/106792549/221398897-4797b9ea-f487-401d-8560-a9e31c92204e.png)

**Comment by lss233** [comment]
需要提供 mirai 的运行日志截图。

**Comment by magisk317** [comment]
> 需要提供 mirai 的运行日志截图。

我来贴log吧，我跟他报错一样

错误日志：
```
2023-02-27 12:43:46 chatgpt-mirai-1       | 2023-02-27 04:43:46 I/main: 
2023-02-27 12:43:46 chatgpt-mirai-1       | 
2023-02-27 12:43:46 chatgpt-mirai-1       | ==================================[ Mirai consosle 2.14.0 ]===================================
2023-02-27 12:43:46 chatgpt-mirai-1       |  __       __ __                   __  ______                                      __
2023-02-27 12:43:46 chatgpt-mirai-1       | |  \     /  \  \                 |  \/      \                                    |  \
2023-02-27 12:43:46 chatgpt-mirai-1       | | ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
2023-02-27 12:43:46 chatgpt-mirai-1       | | ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
2023-02-27 12:43:46 chatgpt-mirai-1       | | ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
2023-02-27 12:43:46 chatgpt-mirai-1       | | ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
2023-02-27 12:43:46 chatgpt-mirai-1       | | ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
2023-02-27 12:43:46 chatgpt-mirai-1       | | ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
2023-02-27 12:43:46 chatgpt-mirai-1       |  \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓
2023-02-27 12:43:46 chatgpt-mirai-1       | 
2023-02-27 12:43:46 chatgpt-mirai-1       | 
2023-02-27 12:43:46 chatgpt-mirai-1       | 2023-02-27 04:43:46 I/main: Backend: version 2.14.0, built on 2023-02-06 06:25:21.
2023-02-27 12:43:46 chatgpt-mirai-1       | 2023-02-27 04:43:46 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-02-27 12:43:46 chatgpt-mirai-1       | 2023-02-27 04:43:46 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-27 12:43:47 chatgpt-chatgpt-1     | 2023-02-27 04:43:47,141 Warning: webcam forwarding is disabled
2023-02-27 12:43:47 chatgpt-chatgpt-1     | 2023-02-27 04:43:47,141  the virtual video directory '/sys/devices/virtual/video4linux' was not found
2023-02-27 12:43:47 chatgpt-chatgpt-1     | 2023-02-27 04:43:47,141  make sure that the 'v4l2loopback' kernel module is installed and loaded
2023-02-27 12:43:47 chatgpt-chatgpt-1     | 2023-02-27 04:43:47,141  or use the 'webcam=no' option
2023-02-27 12:43:47 chatgpt-chatgpt-1     | 2023-02-27 04:43:47,141 found 0 virtual video devices for webcam forwarding
2023-02-27 12:43:47 chatgpt-chatgpt-1     | 2023-02-27 04:43:47,229 started command `xterm -e python bot.py 2>&1 | tee /tmp/log.txt` with pid 45
2023-02-27 12:43:50 chatgpt-mirai-1       | 2023-02-27 04:43:50 I/plugin: Successfully loaded plugin mirai-api-http v2.8.0
2023-02-27 12:43:50 chatgpt-mirai-1       | 2023-02-27 04:43:50 I/plugin: Successfully loaded plugin mirai-device-generator v1.1.3
2023-02-27 12:43:50 chatgpt-mirai-1       | 2023-02-27 04:43:50 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-27 12:43:51 chatgpt-mirai-1       | 2023-02-27 04:43:51 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-27 12:43:52 chatgpt-chatgpt-1     | 2023-02-27 04:43:52,535 waiting for initialization thread to complete
2023-02-27 12:43:52 chatgpt-chatgpt-1     | 2023-02-27 04:43:52,535 xpra is ready.
2023-02-27 12:43:52 chatgpt-chatgpt-1     | 2023-02-27 04:43:52,536 xpra X11 seamless version 4.4.3-r0 64-bit
2023-02-27 12:43:52 chatgpt-chatgpt-1     | 2023-02-27 04:43:52,536  uid=0 (root), gid=0 (root)
2023-02-27 12:43:52 chatgpt-chatgpt-1     | 2023-02-27 04:43:52,537  running with pid 7 on Linux Debian 11 bullseye
2023-02-27 12:43:52 chatgpt-chatgpt-1     | 2023-02-27 04:43:52,722  connected to X11 display :0 with 24 bit colors
2023-02-27 12:43:53 chatgpt-chatgpt-1     | 2023-02-27 04:43:53,092 7.7GB of system memory
2023-02-27 12:43:53 chatgpt-chatgpt-1     | 2023-02-27 04:43:53,121 Warning: OpenGL support check failed:
2023-02-27 12:43:53 chatgpt-chatgpt-1     | 2023-02-27 04:43:53,121  unknown error
2023-02-27 12:43:53 chatgpt-mirai-1       | 2023-02-27 04:43:53 I/Mirai HTTP API: ********************************************************
2023-02-27 12:43:53 chatgpt-mirai-1       | 2023-02-27 04:43:53 I/MahKtorAdapter[http]: Autoreload is disabled because the development mode is off.
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 I/MahKtorAdapter[http]: Application started in 0.397 seconds.
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 I/MahKtorAdapter[http]: Responding at http://mirai:8080
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 I/http adapter: >>> [http adapter] is listening at http://mirai:8080
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 I/Mirai HTTP API: Http api server is running with verifyKey: 0123456789
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 I/Mirai HTTP API: adaptors: [http]
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 I/Mirai HTTP API: ********************************************************
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 I/main: 3 plugin(s) enabled.
2023-02-27 12:43:54 chatgpt-mirai-1       | 2023-02-27 04:43:54 I/main: Auto-login *********, protocol: ANDROID_WATCH, heartbeatStrategy: STAT_HB
2023-02-27 12:43:55 chatgpt-mirai-1       | 2023-02-27 04:43:55 I/Bot.*********: Login successful
2023-02-27 12:43:55 chatgpt-mirai-1       | 2023-02-27 04:43:55 I/Bot.*********: Saved account secrets to local cache for fast login.
2023-02-27 12:43:55 chatgpt-mirai-1       | 2023-02-27 04:43:55 I/Bot.*********: Login successful.
2023-02-27 12:43:56 chatgpt-mirai-1       | 2023-02-27 04:43:56 V/Bot.*********: Event: BotOnlineEvent(bot=Bot(*********))
2023-02-27 12:43:56 chatgpt-mirai-1       | 2023-02-27 04:43:56 I/Bot.*********: Bot login successful.
2023-02-27 12:43:56 chatgpt-mirai-1       | 2023-02-27 04:43:56 I/main: mirai-console started successfully.
2023-02-27 12:43:56 chatgpt-mirai-1       | > 2023-02-27 04:43:56 W/console: Closing input service...
2023-02-27 12:44:00 chatgpt-chatgpt-1     | 2023-02-27 04:44:00.022 | INFO     | launart.manager:launch_blocking:479 - Starting launart main task...
2023-02-27 12:44:00 chatgpt-chatgpt-1     | 2023-02-27 04:44:00.022 | INFO     | launart.manager:launch:331 - Launching 5 components as async task...
2023-02-27 12:44:00 chatgpt-chatgpt-1     | 2023-02-27 04:44:00.944 | INFO     | graia.ariadne.service:base_telemetry:108 - 
2023-02-27 12:44:00 chatgpt-chatgpt-1     |     _         _           _
2023-02-27 12:44:00 chatgpt-chatgpt-1     |    / \   _ __(_) __ _  __| |_ __   ___
2023-02-27 12:44:00 chatgpt-chatgpt-1     |   / _ \ | '__| |/ _` |/ _` | '_ \ / _ \
2023-02-27 12:44:00 chatgpt-chatgpt-1     |  / ___ \| |  | | (_| | (_| | | | |  __/
2023-02-27 12:44:00 chatgpt-chatgpt-1     | /_/   \_\_|  |_|\__,_|\__,_|_| |_|\___|
2023-02-27 12:44:00 chatgpt-chatgpt-1     | 
2023-02-27 12:44:00 chatgpt-chatgpt-1     | graia-amnesia: 0.7.1
2023-02-27 12:44:00 chatgpt-chatgpt-1     | graia-ariadne: 0.11.0
2023-02-27 12:44:00 chatgpt-chatgpt-1     | graia-broadcast: 0.19.1
2023-02-27 12:44:00 chatgpt-chatgpt-1     | launart: 0.6.3
2023-02-27 12:44:00 chatgpt-chatgpt-1     | statv: 0.3.2
2023-02-27 12:44:00 chatgpt-chatgpt-1     | 2023-02-27 04:44:00.945 | SUCCESS  | launart.manager:launch:384 - Layer #1:[http.client/aiohttp, cache.client/memcache] preparation completed.
2023-02-27 12:44:00 chatgpt-chatgpt-1     | 2023-02-27 04:44:00.945 | INFO     | __main__:start_background:162 - OpenAI 服务器登录中……
2023-02-27 12:44:00 chatgpt-chatgpt-1     | 2023-02-27 04:44:00.946 | INFO     | manager:login:116 - 正在登录第 1 个 OpenAI 账号
2023-02-27 12:44:00 chatgpt-chatgpt-1     | 2023-02-27 04:44:00.946 | INFO     | manager:__login_V1:175 - 模式：无浏览器登录
2023-02-27 12:44:00 chatgpt-chatgpt-1     | 2023-02-27 04:44:00.946 | INFO     | manager:__login_V1:198 - 尝试使用 access_token 登录中...
2023-02-27 12:44:02 chatgpt-chatgpt-1     | 2023-02-27 04:44:02.726 | SUCCESS  | manager:login:127 - 登录成功！
2023-02-27 12:44:02 chatgpt-chatgpt-1     | 2023-02-27 04:44:02.726 | DEBUG    | manager:login:128 - 等待 8 秒……
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.733 | SUCCESS  | manager:login:146 - 成功登录 1/1 个账号！
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.748 | SUCCESS  | config:scan_presets:179 - 检查预设：正常 <==> presets/default.txt [成功]
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.748 | SUCCESS  | config:scan_presets:179 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.748 | SUCCESS  | config:scan_presets:192 - 注册预设：catgirl <==> ./presets/catgirl.txt [成功]
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.749 | SUCCESS  | config:scan_presets:192 - 注册预设：预设模板 <==> ./presets/预设模板.txt [成功]
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.749 | SUCCESS  | config:scan_presets:192 - 注册预设：default <==> ./presets/default.txt [成功]
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.749 | INFO     | __main__:start_background:167 - OpenAI 服务器登录成功
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.749 | INFO     | __main__:start_background:168 - 尝试从 Mirai 服务中读取机器人 QQ 的 session key……
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.750 | SUCCESS  | launart.manager:launch:384 - Layer #3:[elizabeth.service] preparation completed.
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.750 | INFO     | launart.manager:launch:389 - All components prepared, start blocking phase.
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.917 | ERROR    | graia.amnesia.builtins.aiohttp:connection_manage:231 - 404, message='Invalid response status', url=URL('http://mirai:8080/all?qq=*********&verifyKey=0123456789')
2023-02-27 12:44:10 chatgpt-chatgpt-1     | Traceback (most recent call last):
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 
2023-02-27 12:44:10 chatgpt-chatgpt-1     |   File "/app/bot.py", line 171, in <module>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     app.launch_blocking()
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │   └ <classmethod object at 0x7fdff4495580>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     └ <graia.ariadne.app.Ariadne object at 0x7fdff61d65e0>
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 
2023-02-27 12:44:10 chatgpt-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │   │              │                    │   │       └ <property object at 0x7fdff4497d10>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7fdff030bdc0>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │   │              └ <function Launart.launch_blocking at 0x7fdff5620af0>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │   └ <launart.manager.Launart object at 0x7fdfc50b61f0>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     └ <class 'graia.ariadne.app.Ariadne'>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/launart/manager.py", line 494, in launch_blocking
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     loop.run_until_complete(launch_task)
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.9/site-packages/launart/manager....
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fdff584be50>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     self.run_forever()
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7fdff584bdc0>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     self._run_once()
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7fdff584d940>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     handle._run()
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │      └ <function Handle._run at 0x7fdff59123a0>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     └ <Handle <TaskWakeupMethWrapper object at 0x7fdfc5069910>(<Future finished result=None>)>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     self._context.run(self._callback, *self._args)
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7fdfc5069910>(<Future finished result=None>)>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7fdfc5069910>(<Future finished result=None>)>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     └ <Handle <TaskWakeupMethWrapper object at 0x7fdfc5069910>(<Future finished result=None>)>
2023-02-27 12:44:10 chatgpt-chatgpt-1     | > File "/usr/local/lib/python3.9/site-packages/graia/amnesia/builtins/aiohttp.py", line 217, in connection_manage
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     await self._start_conn()
2023-02-27 12:44:10 chatgpt-chatgpt-1     |           │    └ <function AiohttpClientConnectionRider._start_conn at 0x7fdff45d5820>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |           └ <graia.amnesia.builtins.aiohttp.AiohttpClientConnectionRider object at 0x7fdfc504aa90>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/graia/amnesia/builtins/aiohttp.py", line 180, in _start_conn
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     self.response = await self.conn_func(**self.call_param)
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    │                │    │           │    └ {'url': 'http://mirai:8080/all?qq=*********&verifyKey=0123456789', 'heartbeat': 30.0}
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    │                │    │           └ <graia.amnesia.builtins.aiohttp.AiohttpClientConnectionRider object at 0x7fdfc504aa90>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    │                │    └ <bound method ClientSession.ws_connect of <aiohttp.client.ClientSession object at 0x7fdfc504a580>>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    │                └ <graia.amnesia.builtins.aiohttp.AiohttpClientConnectionRider object at 0x7fdfc504aa90>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     │    └ None
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     └ <graia.amnesia.builtins.aiohttp.AiohttpClientConnectionRider object at 0x7fdfc504aa90>
2023-02-27 12:44:10 chatgpt-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 795, in _ws_connect
2023-02-27 12:44:10 chatgpt-chatgpt-1     |     raise WSServerHandshakeError(
2023-02-27 12:44:10 chatgpt-chatgpt-1     |           └ <class 'aiohttp.client_exceptions.WSServerHandshakeError'>
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 
2023-02-27 12:44:10 chatgpt-chatgpt-1     | aiohttp.client_exceptions.WSServerHandshakeError: 404, message='Invalid response status', url=URL('http://mirai:8080/all?qq=2246752013&verifyKey=0123456789')
2023-02-27 12:44:10 chatgpt-chatgpt-1     | 2023-02-27 04:44:10.982 | WARNING  | graia.ariadne.connection.ws:_:76 - Websocket reconnecting in 5s...
2023-02-27 12:44:15 chatgpt-chatgpt-1     | 2023-02-27 04:44:15.984 | WARNING  | graia.ariadne.connection.ws:_:78 - Websocket reconnecting...
```

配置：
```
adapters: 
  - http
debug: false
enableVerify: true
verifyKey: 0123456789
singleMode: false
cacheSize: 4096
persistenceFactory: 'built-in'
adapterSettings:
  ## HTTP 服务的主机, 端口和跨域设置
  http:
    host: mirai
    port: 8080
    cors: ["*"]

  ## Websocket 服务的主机, 端口和事件同步ID设置
  ws:
    host: mirai
    port: 8080
    reservedSyncId: -1
```

config部分：
```
[mirai]
qq = *********

# 以下设置如果不了解，可以不用理会
api_key = "0123456789"
http_url = "http://mirai:8080"
ws_url = "http://mirai:8080"
```

**Comment by lss233** [comment]
你的配置少了 websocket 的部分：
```
adapters: 
  - http
  - ws # 这里
debug: false
enableVerify: true
verifyKey: 0123456789
singleMode: false
cacheSize: 4096
persistenceFactory: 'built-in'
adapterSettings:
  ## HTTP 服务的主机, 端口和跨域设置
  http:
    host: mirai
    port: 8080
    cors: ["*"]

  ## Websocket 服务的主机, 端口和事件同步ID设置
  ws:
    host: mirai
    port: 8080
    reservedSyncId: -1
```

建议用快速部署包，不会有此问题。
