### ISSUE TITLE
[BUG] 系统找不到指定路径

### ISSUE THREAD

**Issue by hammer-wh** [lss233/chatgpt-mirai-qq-bot#223]
**提交 issue 前，请先确认：**
- [✔] 我已看过 **FAQ**，此问题不在列表中
- [✔]] 我已看过其他 issue，他们不能解决我的问题 
- [✔] ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
运行`启动chatGPT.cmd`文件时，会报这个错。注意，已经确认非代理问题，我从网页端直接登陆是可行的。

**运行环境:**  
- 操作系统：window10
- Docker： ？
- 项目版本：1.5.8-beta

**截图**  
![image](https://user-images.githubusercontent.com/81762236/222021954-5e548131-06e8-467a-832f-0e9fd9a3a364.png)

**其他内容**  
事实上，我之前并不会报这个错误，昨天添加启用了多账号登陆之后开始失败，后面关闭多账号登陆重试依旧不行。

**Comment by hammer-wh** [comment]
```
2023-03-01 09:32:42.387 | SUCCESS  | launart.manager:launch:384 - Layer #1:[http.client/aiohttp, cache.client/memcache] preparation completed.
2023-03-01 09:32:42.388 | INFO     | __main__:start_background:182 - OpenAI 服务器登录中……
2023-03-01 09:32:42.389 | INFO     | manager:login:126 - 正在登录第 1 个 OpenAI 账号
2023-03-01 09:32:42.390 | INFO     | manager:__login_V1:185 - 模式：无浏览器登录
2023-03-01 09:32:42.392 | INFO     | manager:__login_V1:189 - 正在检查代理配置：http://127.0.0.1:7890
2023-03-01 09:32:42.395 | INFO     | manager:__login_V1:227 - 尝试使用 email + password 登录中...
2023-03-01 09:32:47.149 | ERROR    | manager:login:151 - 未知错误：
2023-03-01 09:32:47.151 | ERROR    | manager:login:152 - [WinError 3] 系统找不到指定的路径。: ''
Traceback (most recent call last):

  File "D:\MOSS\chatgpt\bot.py", line 191, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x0000023E42F2E880>
    └ <graia.ariadne.app.Ariadne object at 0x0000023E3FDC8130>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x0000023E42F33F40>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x0000023E3FF36A00>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x0000023E42328A60>
    │   └ <launart.manager.Launart object at 0x0000023E695996D0>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at D:\MOSS\chatgpt\python3.9\lib\site-packages\launart\man...
    │    └ <function BaseEventLoop.run_until_complete at 0x0000023E41D16A60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 634, in run_until_complete
    ', '.join(str(exc) for exc in exceptions)))
                                  └ <module 'asyncio.exceptions' from 'D:\\MOSS\\chatgpt\\python3.9\\python39.zip\\asyncio\\exceptions.pyc'>

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 601, in run_forever
    exc.errno, 'error while '

  File "asyncio\base_events.py", line 1905, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000023E695BBD90>()>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\graia\broadcast\__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {}
                   │                └ <function start_background at 0x0000023E695A8670>
                   └ <function run_always_await at 0x0000023E423683A0>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\graia\broadcast\utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object start_background at 0x0000023E695CE0C0>

  File "D:\MOSS\chatgpt\bot.py", line 183, in start_background
    chatbot.setup()
    │       └ <function setup at 0x0000023E42F733A0>
    └ <module 'chatbot' from 'D:\\MOSS\\chatgpt\\chatbot.py'>

  File "D:\MOSS\chatgpt\chatbot.py", line 17, in setup
    botManager.login()
    │          └ <function BotManager.login at 0x0000023E693194C0>
    └ <manager.BotManager object at 0x0000023E43076D00>

> File "D:\MOSS\chatgpt\manager.py", line 129, in login
    bot = self.__login_V1(account)
          │               └ OpenAIEmailAuth(mode='browserless', proxy='http://127.0.0.1:7890', driver_exec_path=None, browser_exec_path=None, conversatio...
          └ <manager.BotManager object at 0x0000023E43076D00>

  File "D:\MOSS\chatgpt\manager.py", line 232, in __login_V1
    bot = V1Chatbot(config=config)
          │                └ {'proxy': 'http://127.0.0.1:7890', 'email': 'sviridova-7icww@rambler.ru', 'password': 'b89rZ6EbqOMl', 'session_token': 'eyJhb...
          └ <class 'revChatGPT.V1.Chatbot'>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
          │     │       └ {'config': {'proxy': 'http://127.0.0.1:7890', 'email': 'sviridova-7icww@rambler.ru', 'password': 'b89rZ6EbqOMl', 'session_tok...
          │     └ (<revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>,)
          └ <function Chatbot.__init__ at 0x0000023E43AA7820>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 147, in __init__
    self.__check_credentials()
    └ <revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
          │     │       └ {}
          │     └ (<revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>,)
          └ <function Chatbot.__check_credentials at 0x0000023E43AA7940>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 161, in __check_credentials
    self.__login()
    └ <revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
          │     │       └ {}
          │     └ (<revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>,)
          └ <function Chatbot.__login at 0x0000023E43AAB040>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 271, in __login
    self.__refresh_headers(auth.access_token)
    │                      │    └ 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJ...
    │                      └ <OpenAIAuth.Authenticator object at 0x0000023E695C7220>
    └ <revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
          │     │       └ {}
          │     └ (<revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>, 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNM...
          └ <function Chatbot.__refresh_headers at 0x0000023E43AA7A60>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 183, in __refresh_headers
    self.__cache_access_token(email, access_token)
    │                         │      └ 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJ...
    │                         └ 'sviridova-7icww@rambler.ru'
    └ <revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
          │     │       └ {}
          │     └ (<revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>, 'sviridova-7icww@rambler.ru', 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImt...
          └ <function Chatbot.__cache_access_token at 0x0000023E43AA7CA0>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 230, in __cache_access_token
    self.__write_cache(cache)
    │                  └ {'access_tokens': {'sviridova-7icww@rambler.ru': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWp...
    └ <revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 45, in wrapper
    out = func(*args, **kwargs)
          │     │       └ {}
          │     └ (<revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>, {'access_tokens': {'sviridova-7icww@rambler.ru': 'eyJhbGciOiJSUzI1NiIs...
          └ <function Chatbot.__write_cache at 0x0000023E43AA7DC0>

  File "D:\MOSS\chatgpt\python3.9\lib\site-packages\revChatGPT\V1.py", line 234, in __write_cache
    os.makedirs(osp.dirname(self.cache_path), exist_ok=True)
    │  │        │   │       │    └ '.chatgpt_cache.json'
    │  │        │   │       └ <revChatGPT.V1.Chatbot object at 0x0000023E695C79D0>
    │  │        │   └ <function dirname at 0x0000023E3FD98DC0>
    │  │        └ <module 'ntpath' from 'D:\\MOSS\\chatgpt\\python3.9\\python39.zip\\ntpath.pyc'>
    │  └ <function makedirs at 0x0000023E3FD53CA0>
    └ <module 'os' from 'D:\\MOSS\\chatgpt\\python3.9\\python39.zip\\os.pyc'>

  File "os.py", line 225, in makedirs

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: ''
2023-03-01 09:32:47.410 | ERROR    | manager:login:154 - 所有账号均登录失败，无法继续启动！
2023-03-01 09:32:47.411 | ERROR    | __main__:start_background:185 - OpenAI 服务器失败！
2023-03-01 09:32:47.415 | INFO     | chatbot:conversation_remover:100 - 删除会话中……
```

**Comment by xxsoul** [comment]
看了下这版的revChatGPT库的版本和当前开发版本的不太匹配，提交日志显示变更了revChatGPT的版本从2.3.13降到了2.3.11，怀疑是2.3.13版本的revChatGPT可能有bug。
去requirements.txt里，把revChatGPT的版本从2.3.13变更到2.3.11，重新```pip install -r requirements.txt```后再启动项目试下吧

**Comment by hammer-wh** [comment]
已确认修改为2.3.11
![image](https://user-images.githubusercontent.com/81762236/222037646-41926866-6c6e-4ce2-9946-2af945333226.png)

依旧不行，错误信息一样（除了内存地址变了

当我把登陆方式修改为浏览器登陆时，会长时间停留在此处，提示我用无浏览器登陆。陷入死循环了。。。
![image](https://user-images.githubusercontent.com/81762236/222036658-83ff676b-d3cb-4d97-b99e-adac548a6746.png)

**后续**
已找出问题所在，在`config.cfg`文件中，当我注释掉`auto_remove_old_conversations = true`时服务变得可用，同时登陆模式变回assess_token登陆。
