### ISSUE TITLE
求大佬帮忙解决一下启动报错,我用的session_token登陆的

### ISSUE THREAD

**Issue by Huaxidesu** [lss233/chatgpt-mirai-qq-bot#23]
`> python bot.py
Traceback (most recent call last):
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chat.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\robot\HuaxixiNew\chatgpt-mirai-qq-bot\bot.py", line 11, in <module>
    import chatbot
  File "F:\robot\HuaxixiNew\chatgpt-mirai-qq-bot\chatbot.py", line 7, in <module>
    bot = Chatbot(config_data["openai"], conversation_id=None)
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\revChatGPT.py", line 83, in __init__
    self.refresh_session()
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\revChatGPT\revChatGPT.py", line 268, in refresh_session
    response = s.get(
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Huaxidesu\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='chat.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))`

**Comment by lss233** [comment]
你网不好，请按照 https://github.com/lss233/chatgpt-mirai-qq-bot#%E4%BD%BF%E7%94%A8%E4%BB%A3%E7%90%86 配置代理。
