### ISSUE TITLE
[BUG] 最新API版本keyerror 'conversation_id'

### ISSUE THREAD

**Issue by jinzhuer** [lss233/chatgpt-mirai-qq-bot#239]
**提交 issue 前，请先确认：**
- [✓] 我已看过 **FAQ**，此问题不在列表中
- [ ✓] 我已看过其他 issue，他们不能解决我的问题 
- [✓ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
最新的API版本，报错

**运行环境:**  
- 操作系统：ubuntu
- Docker： docker compose部署
- 项目版本：最新1.58API版

**截图**  
相关日志、聊天记录的截图，没有可跳过
```
chatbot-mirai-1       | 2023-03-03 04:17:56 V/Bot.100001: 飞翔的企鹅(88888888) -> 重置会话
chatbot-mirai-1       | 2023-03-03 04:17:56 V/Bot.100001: Friend(88888888) <- [mirai:quote:[mirai:source:ids=[18776], internalIds=[119015364], from friend 88888888 to 100001 at 1677817075], content=重置会话]会话已重置。
chatbot-chatgpt-1     | 2023-03-03 04:17:56.926 | INFO     | graia.ariadne.model:log:82 - 100001: [SEND][飞翔的企鹅(88888888)] <- 会话已重置。
chatbot-chatgpt-1     | 2023-03-03 04:17:58.563 | INFO     | graia.ariadne.model:log:82 - 100001: [RECV][飞翔的企鹅(88888888)] -> 你好
chatbot-mirai-1       | 2023-03-03 04:17:58 V/Bot.100001: 飞翔的企鹅(88888888) -> 你好
chatbot-chatgpt-1     | 2023-03-03 04:17:59.514 | ERROR    | __main__:handle_message:151 - 'conversation_id'
chatbot-chatgpt-1     | Traceback (most recent call last):
chatbot-chatgpt-1     |
chatbot-chatgpt-1     |   File "/app/bot.py", line 274, in <module>
chatbot-chatgpt-1     |     app.launch_blocking()
chatbot-chatgpt-1     |     │   └ <classmethod object at 0x7f0511d140d0>
chatbot-chatgpt-1     |     └ <graia.ariadne.app.Ariadne object at 0x7f0513a2fc10>
chatbot-chatgpt-1     |
chatbot-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
chatbot-chatgpt-1     |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
chatbot-chatgpt-1     |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
chatbot-chatgpt-1     |     │   │              │                    │   │       └ <property object at 0x7f0511d17950>
chatbot-chatgpt-1     |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7f0513a3ed90>
chatbot-chatgpt-1     |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
chatbot-chatgpt-1     |     │   │              └ <function Launart.launch_blocking at 0x7f0512e9b940>
chatbot-chatgpt-1     |     │   └ <launart.manager.Launart object at 0x7f04e1011a60>
chatbot-chatgpt-1     |     └ <class 'graia.ariadne.app.Ariadne'>
chatbot-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/launart/manager.py", line 494, in launch_blocking
chatbot-chatgpt-1     |     loop.run_until_complete(launch_task)
chatbot-chatgpt-1     |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.9/site-packages/launart/manager...                      .
chatbot-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7f05130c5ca0>
chatbot-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatbot-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
chatbot-chatgpt-1     |     self.run_forever()
chatbot-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7f05130c5c10>
chatbot-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatbot-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
chatbot-chatgpt-1     |     self._run_once()
chatbot-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7f05130c8790>
chatbot-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatbot-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
chatbot-chatgpt-1     |     handle._run()
chatbot-chatgpt-1     |     │      └ <function Handle._run at 0x7f051310c1f0>
chatbot-chatgpt-1     |     └ <Handle <TaskWakeupMethWrapper object at 0x7f04e05ac490>(<Future finis...什么我可以帮助你的吗？'}>)>
chatbot-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
chatbot-chatgpt-1     |     self._context.run(self._callback, *self._args)
chatbot-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatbot-chatgpt-1     |     │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7f04e05ac490>(<Future finis...什么我可以帮助你的吗？'}>)>
chatbot-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatbot-chatgpt-1     |     │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7f04e05ac490>(<Future finis...什么我可以帮助你的吗？'}>)>
chatbot-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
chatbot-chatgpt-1     |     └ <Handle <TaskWakeupMethWrapper object at 0x7f04e05ac490>(<Future finis...什么我可以帮助你的吗？'}>)>
chatbot-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 191, in Executor
chatbot-chatgpt-1     |     result = await run_always_await(target_callable, **parameter_compile_result)
chatbot-chatgpt-1     |                    │                │                  └ {'app': <graia.ariadne.app.Ariadne object at 0x7f0513a2fc10>, 'friend': Friend(id=88888888, nickname='飞翔的企鹅', remark='飞翔的企鹅...
chatbot-chatgpt-1     |                    │                └ <function friend_message_listener at 0x7f04e1020160>
chatbot-chatgpt-1     |                    └ <function run_always_await at 0x7f0512e4ea60>
chatbot-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
chatbot-chatgpt-1     |     obj = await obj
chatbot-chatgpt-1     |                 └ <coroutine object friend_message_listener at 0x7f04e05af140>
chatbot-chatgpt-1     |
chatbot-chatgpt-1     |   File "/app/bot.py", line 173, in friend_message_listener
chatbot-chatgpt-1     |     response = await handle_message(friend, f"friend-{friend.id}", chain.display, source)
chatbot-chatgpt-1     |                      │              │                              │     │        └ Source(id=18777, time=datetime.datetime(2023, 3, 3, 4, 17, 58, tzinfo=datetime.timezone.utc), type='Source')
chatbot-chatgpt-1     |                      │              │                              │     └ <property object at 0x7f0511e1c0e0>
chatbot-chatgpt-1     |                      │              │                              └ MessageChain([Plain(text='你好')])
chatbot-chatgpt-1     |                      │              └ Friend(id=88888888, nickname='飞翔的企鹅', remark='飞翔的企鹅')
chatbot-chatgpt-1     |                      └ <function handle_message at 0x7f04e1020040>
chatbot-chatgpt-1     |
chatbot-chatgpt-1     | > File "/app/bot.py", line 121, in handle_message
chatbot-chatgpt-1     |     resp = await session.get_chat_response(message)
chatbot-chatgpt-1     |                  │       │                 └ '你好'
chatbot-chatgpt-1     |                  │       └ <function ChatSession.get_chat_response at 0x7f050c4729d0>
chatbot-chatgpt-1     |                  └ <chatbot.ChatSession object at 0x7f04e06d62e0>
chatbot-chatgpt-1     |
chatbot-chatgpt-1     |   File "/app/chatbot.py", line 85, in get_chat_response
chatbot-chatgpt-1     |     self.conversation_id = resp["conversation_id"]
chatbot-chatgpt-1     |     │    │                 └ {'message': '\n\n你好！有什么我可以帮助你的吗？'}
chatbot-chatgpt-1     |     │    └ None
chatbot-chatgpt-1     |     └ <chatbot.ChatSession object at 0x7f04e06d62e0>
chatbot-chatgpt-1     |
chatbot-chatgpt-1     | KeyError: 'conversation_id'
chatbot-mirai-1       | 2023-03-03 04:17:59 V/Bot.100001: Friend(88888888) <- [mirai:quote:[mirai:source:ids=[18777], internalIds=[997078316], from friend 88888888 to 100001 at 1677817078], content=你好]出现故障，可能是openai服务器拥堵！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话。\n'conversat                      ion_id'
```

**Comment by jinzhuer** [comment]
临时解决方法，删除chatbot.py的85行和86行
![image](https://user-images.githubusercontent.com/39551840/222636205-afbb1996-718c-44ae-93f1-d015b8aca13c.png)

**Comment by lss233** [comment]
已修复，感谢提醒
