### ISSUE TITLE
运行报错 看上去是json出了什么问题

### ISSUE THREAD

**Issue by hisakochan** [lss233/chatgpt-mirai-qq-bot#24]
F:\OpenAI\chatgpt-mirai-qq-bot-1.2>python bot.py
Traceback (most recent call last):
  File "F:\OpenAI\chatgpt-mirai-qq-bot-1.2\bot.py", line 11, in <module>
    import chatbot
  File "F:\OpenAI\chatgpt-mirai-qq-bot-1.2\chatbot.py", line 4, in <module>
    config_data = json.load(jsonfile)
  File "F:\Python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "F:\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "F:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

json本身格式应该没问题，只是改了用token登陆。

**Comment by hisakochan** [comment]
已解决 万恶的BOM编码（）
