### ISSUE TITLE
[BUG] RuntimeError: coroutine raised StopIteration

### ISSUE THREAD

**Issue by foxMaxwell** [lss233/chatgpt-mirai-qq-bot#247]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
报错：RuntimeError: coroutine raised StopIteration
机器人不回复任何信息，mirai已经登录，账号应该也没有被风控，在chatGPT的cmd窗口中存在报错
我尝试阅读过其他issue但没有找到合适的解决方案和相同的案例

**运行环境:**  
- 操作系统：Windows-2016-Datacenter
- Docker： ？
- 项目版本：1.5.8

**复现步骤**  
描述你是如何触发这个 BUG 的
1.运行chatgpt，出现错误：2023-03-04 02:00:20.311 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
2.在成功获取网站登录的key之前会出现错误，情况如下：aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host pastebin.mozilla.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]
2023-03-04 02:08:25.343 | SUCCESS  | graia.ariadne.connection.ws:_:62 - Successfully got session key
3.在尝试发送QQ信息以后，在运行一段代码后以如下报错结尾：RuntimeError: coroutine raised StopIteration

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
```
2023-03-04 02:00:19.683 | SUCCESS  | launart.manager:launch:384 - Layer #1:[http.client/aiohttp, cache.client/memcache] preparation completed.
2023-03-04 02:00:20.100 | SUCCESS  | launart.manager:launch:384 - Layer #3:[elizabeth.service] preparation completed.
2023-03-04 02:00:20.167 | INFO     | launart.manager:launch:389 - All components prepared, start blocking phase.
2023-03-04 02:00:20.311 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
Traceback (most recent call last):

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
                 │    │     │                  │       └ {'ssl': <ssl.SSLContext object at 0x000001E9EA1558C0>, 'family': <AddressFamily.AF_INET: 2>, 'proto': 0, 'flags': <AddressInf...
                 │    │     │                  └ (functools.partial(<class 'aiohttp.client_proto.ResponseHandler'>, loop=<ProactorEventLoop running=True closed=False debug=Fa...
                 │    │     └ <function BaseEventLoop.create_connection at 0x000001E9DD374E50>
                 │    └ <ProactorEventLoop running=True closed=False debug=False>
                 └ <aiohttp.connector.TCPConnector object at 0x000001E9EA150EE0>

  File "asyncio\base_events.py", line 1090, in create_connection
    new_scheduled = []

  File "asyncio\base_events.py", line 1120, in _create_connection_transport
    level = logging.INFO

  File "asyncio\sslproto.py", line 534, in data_received
    return

  File "asyncio\sslproto.py", line 188, in feed_ssldata
    appdata = []

  File "ssl.py", line 945, in do_handshake

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\bot.py", line 274, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x000001E9DE591190>
    └ <graia.ariadne.app.Ariadne object at 0x000001E9DB61B400>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x000001E9DE59F1D0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x000001E9DB61B1C0>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x000001E9DD989D30>
    │   └ <launart.manager.Launart object at 0x000001E9EA118220>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\p...
    │    └ <function BaseEventLoop.run_until_complete at 0x000001E9DD3740D0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 634, in run_until_complete
    ', '.join(str(exc) for exc in exceptions)))
                                  └ <module 'asyncio.exceptions' from 'C:\\GPT3.5\\Windows-quickstart-refs.tags.v1.5.8\\chatgpt\\python3.9\\python39.zip\\asyncio...

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 601, in run_forever
    exc.errno, 'error while '

  File "asyncio\base_events.py", line 1905, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001E9EA19FDF0>()>

> File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\graia\broadcast\__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {}
                   │                └ <function start_background at 0x000001E9EA12FA60>
                   └ <function run_always_await at 0x000001E9DD9BDC10>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\graia\broadcast\utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object start_background at 0x000001E9EA155540>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\bot.py", line 222, in start_background
    await to_image("$$mc^2$$ test")
          └ <function to_image at 0x000001E9EA0EF670>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\utils\text_to_img.py", line 366, in to_image
    img = await text_to_image(text=text)
                │                  └ '$$mc^2$$ test'
                └ <function text_to_image at 0x000001E9EA0EF5E0>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\utils\text_to_img.py", line 320, in text_to_image
    .replace("{qrcode}", await get_qr_data(text))
                               │           └ '$$mc^2$$ test'
                               └ <function get_qr_data at 0x000001E9EA0EF550>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\utils\text_to_img.py", line 300, in get_qr_data
    async with session.post('https://pastebin.mozilla.org/api/',
               │       └ <function ClientSession.post at 0x000001E9DE328F70>
               └ <aiohttp.client.ClientSession object at 0x000001E9EA150F40>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
    │    │             │    └ <member '_coro' of '_BaseRequestContextManager' objects>
    │    │             └ <aiohttp.client._RequestContextManager object at 0x000001E9EA170E50>
    │    └ <member '_resp' of '_BaseRequestContextManager' objects>
    └ <aiohttp.client._RequestContextManager object at 0x000001E9EA170E50>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
                 │    └ None
                 └ <aiohttp.client.ClientSession object at 0x000001E9EA150F40>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
                  │    │                  │    │       └ ClientTimeout(total=300, connect=None, sock_read=None, sock_connect=None)
                  │    │                  │    └ []
                  │    │                  └ <aiohttp.client_reqrep.ClientRequest object at 0x000001E9EA170670>
                  │    └ <function TCPConnector._create_connection at 0x000001E9DE2BA790>
                  └ <aiohttp.connector.TCPConnector object at 0x000001E9EA150EE0>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
                     │    │                         │    │       └ ClientTimeout(total=300, connect=None, sock_read=None, sock_connect=None)
                     │    │                         │    └ []
                     │    │                         └ <aiohttp.client_reqrep.ClientRequest object at 0x000001E9EA170670>
                     │    └ <function TCPConnector._create_direct_connection at 0x000001E9DE2BADC0>
                     └ <aiohttp.connector.TCPConnector object at 0x000001E9EA150EE0>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
          └ ClientConnectorCertificateError(ConnectionKey(host='pastebin.mozilla.org', port=443, is_ssl=True, ssl=None, proxy=None, proxy...

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                          │    └ <function TCPConnector._wrap_create_connection at 0x000001E9DE2BAA60>
                          └ <aiohttp.connector.TCPConnector object at 0x000001E9EA150EE0>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
          │                               │   └ <property object at 0x000001E9DE290220>
          │                               └ <aiohttp.client_reqrep.ClientRequest object at 0x000001E9EA170670>
          └ <class 'aiohttp.client_exceptions.ClientConnectorCertificateError'>

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host pastebin.mozilla.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]
2023-03-04 02:00:27.735 | SUCCESS  | graia.ariadne.connection.ws:_:62 - Successfully got session key
2023-03-04 02:00:44.568 | INFO     | graia.ariadne.model:log:82 - 2521732440: [RECV][Mr.Wick(2803899607)] -> 你好
2023-03-04 02:00:44.630 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
Traceback (most recent call last):

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\bot.py", line 79, in handle_message
    session, is_new_session = chatbot.get_chat_session(session_id)
                              │       │                └ 'friend-2803899607'
                              │       └ <function get_chat_session at 0x000001E9E0AAE4C0>
                              └ <module 'chatbot' from 'C:\\GPT3.5\\Windows-quickstart-refs.tags.v1.5.8\\chatgpt\\chatbot.py'>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\chatbot.py", line 97, in get_chat_session
    __sessions[session_id] = ChatSession(session_id)
    │          │             │           └ 'friend-2803899607'
    │          │             └ <class 'chatbot.ChatSession'>
    │          └ 'friend-2803899607'
    └ {}

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\chatbot.py", line 34, in __init__
    self.chatbot = botManager.pick()
    │    │         │          └ <function BotManager.pick at 0x000001E9E0AC2940>
    │    │         └ <manager.bot.BotManager object at 0x000001E9DE743A60>
    │    └ None
    └ <chatbot.ChatSession object at 0x000001E9EA34F070>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\manager\bot.py", line 259, in pick
    return next(self.roundrobin)
                │    └ <itertools.cycle object at 0x000001E9EA1A5A80>
                └ <manager.bot.BotManager object at 0x000001E9DE743A60>

StopIteration


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\bot.py", line 274, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x000001E9DE591190>
    └ <graia.ariadne.app.Ariadne object at 0x000001E9DB61B400>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x000001E9DE59F1D0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x000001E9DB61B1C0>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x000001E9DD989D30>
    │   └ <launart.manager.Launart object at 0x000001E9EA118220>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\p...
    │    └ <function BaseEventLoop.run_until_complete at 0x000001E9DD3740D0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 634, in run_until_complete
    ', '.join(str(exc) for exc in exceptions)))
                                  └ <module 'asyncio.exceptions' from 'C:\\GPT3.5\\Windows-quickstart-refs.tags.v1.5.8\\chatgpt\\python3.9\\python39.zip\\asyncio...

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 601, in run_forever
    exc.errno, 'error while '

  File "asyncio\base_events.py", line 1905, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001E9EA19FD00>()>

> File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\graia\broadcast\__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {'app': <graia.ariadne.app.Ariadne object at 0x000001E9DB61B400>, 'friend': Friend(id=2803899607, nickname='Mr.Wick', remark=...
                   │                └ <function friend_message_listener at 0x000001E9EA12F820>
                   └ <function run_always_await at 0x000001E9DD9BDC10>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\python3.9\lib\site-packages\graia\broadcast\utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object friend_message_listener at 0x000001E9EA34D440>

  File "C:\GPT3.5\Windows-quickstart-refs.tags.v1.5.8\chatgpt\bot.py", line 173, in friend_message_listener
    response = await handle_message(friend, f"friend-{friend.id}", chain.display, source)
                     │              │                              │     │        └ Source(id=31817, time=datetime.datetime(2023, 3, 3, 18, 0, 42, tzinfo=datetime.timezone.utc), type='Source')
                     │              │                              │     └ <property object at 0x000001E9DE49C9A0>
                     │              │                              └ MessageChain([Plain(text='你好')])
                     │              └ Friend(id=2803899607, nickname='Mr.Wick', remark='Mr.Wick')
                     └ <function handle_message at 0x000001E9EA12F700>

RuntimeError: coroutine raised StopIteration
```
**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
看样子是网络的问题,试试 v2.0 版本能不能解决吧
