### ISSUE TITLE
[BUG] Bing AI 模式无法使用

### ISSUE THREAD

**Issue by whb04** [lss233/chatgpt-mirai-qq-bot#273]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  

bot无法正常使用Bing AI模式

出错部分的docker日志：

```
chatgpt-qq-chatgpt-1     | 2023-03-05 05:55:12.085 | INFO     | graia.ariadne.model:log:82 - qq号: [RECV][undefined(qq号)] -> 切换AI bing
chatgpt-qq-chatgpt-1     | 2023-03-05 05:55:12.123 | DEBUG    | middlewares.timeout:create_timeout_task:14 - [Timeout] 开始计时……
chatgpt-qq-chatgpt-1     | 2023-03-05 05:55:31.589 | ERROR    | __main__:request:182 - 'conversationSignature'
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/bot.py", line 292, in <module>
chatgpt-qq-chatgpt-1     |     app.launch_blocking()
chatgpt-qq-chatgpt-1     |     │   └ <classmethod object at 0x7fdccd10a0d0>
chatgpt-qq-chatgpt-1     |     └ <graia.ariadne.app.Ariadne object at 0x7fdcf80c0fd0>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
chatgpt-qq-chatgpt-1     |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
chatgpt-qq-chatgpt-1     |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
chatgpt-qq-chatgpt-1     |     │   │              │                    │   │       └ <property object at 0x7fdccd106c70>
chatgpt-qq-chatgpt-1     |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7fdcfcb90a90>
chatgpt-qq-chatgpt-1     |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1     |     │   │              └ <function Launart.launch_blocking at 0x7fdccd7f3430>
chatgpt-qq-chatgpt-1     |     │   └ <launart.manager.Launart object at 0x7fdcbf648220>
chatgpt-qq-chatgpt-1     |     └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/launart/manager.py", line 494, in launch_blocking
chatgpt-qq-chatgpt-1     |     loop.run_until_complete(launch_task)
chatgpt-qq-chatgpt-1     |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.9/site-packages/launart/manager....
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fdcfb8c0940>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
chatgpt-qq-chatgpt-1     |     self.run_forever()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7fdcfb8c08b0>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
chatgpt-qq-chatgpt-1     |     self._run_once()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7fdcfb8c3430>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
chatgpt-qq-chatgpt-1     |     handle._run()
chatgpt-qq-chatgpt-1     |     │      └ <function Handle._run at 0x7fdcfb8e3e50>
chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7fdcbf04b040>()>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
chatgpt-qq-chatgpt-1     |     self._context.run(self._callback, *self._args)
chatgpt-qq-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fdcbf04b040>()>
chatgpt-qq-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7fdcbf04b040>()>
chatgpt-qq-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7fdcbf04b040>()>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | > File "/app/bot.py", line 115, in request
chatgpt-qq-chatgpt-1     |     conversation_handler.current_conversation = await conversation_handler.create(bot_type_search.group(1).strip())
chatgpt-qq-chatgpt-1     |     │                    │                            │                    │      │               └ <method 'group' of 're.Match' objects>
chatgpt-qq-chatgpt-1     |     │                    │                            │                    │      └ <re.Match object; span=(0, 9), match='切换AI bing'>
chatgpt-qq-chatgpt-1     |     │                    │                            │                    └ <function ConversationHandler.create at 0x7fdcbe87e550>
chatgpt-qq-chatgpt-1     |     │                    │                            └ <conversation.ConversationHandler object at 0x7fdcbf600370>
chatgpt-qq-chatgpt-1     |     │                    └ <conversation.ConversationContext object at 0x7fdcbf61e7c0>
chatgpt-qq-chatgpt-1     |     └ <conversation.ConversationHandler object at 0x7fdcbf600370>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 99, in create
chatgpt-qq-chatgpt-1     |     conversation = ConversationContext(_type, self.session_id)
chatgpt-qq-chatgpt-1     |                    │                   │      │    └ 'friend-qq号'
chatgpt-qq-chatgpt-1     |                    │                   │      └ <conversation.ConversationHandler object at 0x7fdcbf600370>
chatgpt-qq-chatgpt-1     |                    │                   └ 'bing'
chatgpt-qq-chatgpt-1     |                    └ <class 'conversation.ConversationContext'>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 33, in __init__
chatgpt-qq-chatgpt-1     |     self.adapter = BingAdapter(self.session_id)
chatgpt-qq-chatgpt-1     |     │              │           │    └ 'friend-qq号'
chatgpt-qq-chatgpt-1     |     │              │           └ <conversation.ConversationContext object at 0x7fdcbf40e100>
chatgpt-qq-chatgpt-1     |     │              └ <class 'adapter.ms.bing.BingAdapter'>
chatgpt-qq-chatgpt-1     |     └ <conversation.ConversationContext object at 0x7fdcbf40e100>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/adapter/ms/bing.py", line 33, in __init__
chatgpt-qq-chatgpt-1     |     self.bot = EdgeChatbot(self.cookieFile.name)
chatgpt-qq-chatgpt-1     |     │          │           │    │          └ '/tmp/tmp9qqfllsq.json'
chatgpt-qq-chatgpt-1     |     │          │           │    └ <tempfile._TemporaryFileWrapper object at 0x7fdcbf04b4c0>
chatgpt-qq-chatgpt-1     |     │          │           └ <adapter.ms.bing.BingAdapter object at 0x7fdcbf04b670>
chatgpt-qq-chatgpt-1     |     │          └ <class 'EdgeGPT.Chatbot'>
chatgpt-qq-chatgpt-1     |     └ <adapter.ms.bing.BingAdapter object at 0x7fdcbf04b670>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/EdgeGPT.py", line 235, in __init__
chatgpt-qq-chatgpt-1     |     self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath))
chatgpt-qq-chatgpt-1     |     │                        │       │            │    └ '/tmp/tmp9qqfllsq.json'
chatgpt-qq-chatgpt-1     |     │                        │       │            └ <EdgeGPT.Chatbot object at 0x7fdcbf04b7f0>
chatgpt-qq-chatgpt-1     |     │                        │       └ <class 'EdgeGPT.Conversation'>
chatgpt-qq-chatgpt-1     |     │                        └ <class 'EdgeGPT.ChatHub'>
chatgpt-qq-chatgpt-1     |     └ <EdgeGPT.Chatbot object at 0x7fdcbf04b7f0>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.9/site-packages/EdgeGPT.py", line 171, in __init__
chatgpt-qq-chatgpt-1     |     conversation_signature=conversation.struct["conversationSignature"],
chatgpt-qq-chatgpt-1     |                            │            └ {'result': {'value': 'InternalServerError', 'message': 'Error processing request.'}}
chatgpt-qq-chatgpt-1     |                            └ <EdgeGPT.Conversation object at 0x7fdcbf04b8b0>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | KeyError: 'conversationSignature'
chatgpt-qq-chatgpt-1     | 2023-03-05 05:55:32.290 | INFO     | graia.ariadne.model:log:82 - qq号: [SEND][undefined(qq号)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n'conversationSignature'
chatgpt-qq-chatgpt-1     | 2023-03-05 05:55:32.293 | DEBUG    | middlewares.timeout:on_respond:38 - [Timeout] 取消计时……

```

**运行环境:**  
- 操作系统：Ubuntu 22.04
- Docker： 23.0.1
- 项目版本：2.1.0

**复现步骤**  
1. 配置了chatgpt-api和bing两种模式，所有账号均登录成功，使用chatgpt-api模式和bot正常对话
2. 管理员私聊bot发送"切换AI bing"后bot回复 `出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
'conversationSignature'`
3. bot仍然处于chatgpt模式

**预期行为**  
bot切换至bing AI模式

**Comment by whb04** [comment]
过了几个小时后自动恢复正常了
