### ISSUE TITLE
[BUG] V2.2.0队列失效，不能打断

### ISSUE THREAD

**Issue by magisk317** [lss233/chatgpt-mirai-qq-bot#280]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
多个问题直接报错

**运行环境:**  
- 操作系统：win11
- Docker： ？
- 项目版本：2.2.0

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 问第一个问题
2. 问第二个问题

**预期行为**  
加入队列依次回答，实际直接报错，提示等待回复时不能调用：cannot call recv while another coroutine is already waiting for the next message

**截图**  
```
2023-03-05 23:05:29.096 | DEBUG    | middlewares.timeout:create_timeout_task:14 - [Timeout] 开始计时……
2023-03-05 23:05:29.099 | ERROR    | __main__:request:210 - cannot call recv while another coroutine is already waiting for the next message
Traceback (most recent call last):

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\bot.py", line 324, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x000000002B8EF4F0>
    └ <graia.ariadne.app.Ariadne object at 0x000000000156C2B0>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\python3.9\lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x000000002B8F12C0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x0000000001540F70>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x000000002B5D5550>
    │   └ <launart.manager.Launart object at 0x000000002CCE0D90>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\python3.9\lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\pyth...
    │    └ <function BaseEventLoop.run_until_complete at 0x000000000320FA60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 634, in run_until_complete
    ', '.join(str(exc) for exc in exceptions)))
                                  └ <module 'asyncio.exceptions' from 'D:\\ROM\\Windows-quickstart-refs.tags.v2.2.0\\chatgpt\\python3.9\\python39.zip\\asyncio\\e...

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 601, in run_forever
    exc.errno, 'error while '

  File "asyncio\base_events.py", line 1905, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000000002C65BD00>()>

> File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\bot.py", line 177, in request
    async for rendered in task:
                          └ <async_generator object ConversationContext.ask at 0x000000002C65A0D0>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\conversation.py", line 84, in ask
    async for item in self.adapter.ask(prompt):
                      │    │       │   └ 'bing 不太押韵，再来一个'
                      │    │       └ <function BingAdapter.ask at 0x0000000003E8CC10>
                      │    └ <adapter.ms.bing.BingAdapter object at 0x000000002C2FA520>
                      └ <conversation.ConversationContext object at 0x000000002C2FA190>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\adapter\ms\bing.py", line 45, in ask
    async for final, response in self.bot.ask_stream(prompt=prompt, conversation_style=self.conversation_style):
                                 │    │   │                 │                          │    └ <ConversationStyle.creative: 'h3imaginative'>
                                 │    │   │                 │                          └ <adapter.ms.bing.BingAdapter object at 0x000000002C2FA520>
                                 │    │   │                 └ 'bing 不太押韵，再来一个'
                                 │    │   └ <function Chatbot.ask_stream at 0x000000002BC6AA60>
                                 │    └ <EdgeGPT.Chatbot object at 0x000000002C2FA5B0>
                                 └ <adapter.ms.bing.BingAdapter object at 0x000000002C2FA520>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\python3.9\lib\site-packages\EdgeGPT.py", line 295, in ask_stream
    async for response in self.chat_hub.ask_stream(
                          │    │        └ <function ChatHub.ask_stream at 0x000000002BC6A790>
                          │    └ <EdgeGPT.ChatHub object at 0x000000002C2FAFA0>
                          └ <EdgeGPT.Chatbot object at 0x000000002C2FA5B0>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\python3.9\lib\site-packages\EdgeGPT.py", line 236, in ask_stream
    objects = str(await self.wss.recv()).split(DELIMITER)
                        │    │   │             └ '\x1e'
                        │    │   └ <function WebSocketCommonProtocol.recv at 0x000000002BC64940>
                        │    └ <websockets.legacy.client.WebSocketClientProtocol object at 0x000000002CC9AC10>
                        └ <EdgeGPT.ChatHub object at 0x000000002C2FAFA0>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\python3.9\lib\site-packages\websockets\legacy\protocol.py", line 532, in recv
    raise RuntimeError(

RuntimeError: cannot call recv while another coroutine is already waiting for the next message
2023-03-05 23:05:29.245 | ERROR    | adapter.ms.bing:ask:62 - 'messages'
Traceback (most recent call last):

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\bot.py", line 324, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x000000002B8EF4F0>
    └ <graia.ariadne.app.Ariadne object at 0x000000000156C2B0>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\python3.9\lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x000000002B8F12C0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x0000000001540F70>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x000000002B5D5550>
    │   └ <launart.manager.Launart object at 0x000000002CCE0D90>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\python3.9\lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\pyth...
    │    └ <function BaseEventLoop.run_until_complete at 0x000000000320FA60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 634, in run_until_complete
    ', '.join(str(exc) for exc in exceptions)))
                                  └ <module 'asyncio.exceptions' from 'D:\\ROM\\Windows-quickstart-refs.tags.v2.2.0\\chatgpt\\python3.9\\python39.zip\\asyncio\\e...

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 601, in run_forever
    exc.errno, 'error while '

  File "asyncio\base_events.py", line 1905, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x000000002C693640>(<Future finished result=None>)>

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\bot.py", line 177, in request
    async for rendered in task:
              │           └ <async_generator object ConversationContext.ask at 0x000000002C6944C0>
              └ None

  File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\conversation.py", line 84, in ask
    async for item in self.adapter.ask(prompt):
              │       │    │       │   └ 'bing 土地权属确认的方法有哪些？'
              │       │    │       └ <function BingAdapter.ask at 0x0000000003E8CC10>
              │       │    └ <adapter.ms.bing.BingAdapter object at 0x000000002C2FA520>
              │       └ <conversation.ConversationContext object at 0x000000002C2FA190>
              └ '剩余回复数：4 / 8:\n[1]: https://bing.com/search?q=%E5%9C%9F%E5%9C%B0%E6%9D%83%E5%B1%9E%E7%A1%AE%E8%AE%A4%E7%9A%84%E6%96%B9%E6%B3%...

> File "D:\ROM\Windows-quickstart-refs.tags.v2.2.0\chatgpt\adapter\ms\bing.py", line 51, in ask
    suggestions = response["item"]["messages"][-1].get("suggestedResponses", [])
                  └ {'type': 2, 'invocationId': '4', 'item': {'firstNewMessageIndex': None, 'conversationId': '51D|BingProd|A9A5E788A4D6CF5906D42...

KeyError: 'messages'
2023-03-05 23:05:29.632 | INFO     | graia.ariadne.model:log:82 - **********: [SEND][ChatGPT test(**********)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话”
来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。\ncannot call recv while another coroutine is already waiting for the next message
```
**其他内容**  
此处填写其他内容，没有可跳过

**Comment by magisk317** [comment]
## 贴上配置
其实就是默认的

```
[response]
# 默认使用的 AI 类型，不填写时自动推测
default_ai = "chatgpt-web"
# 匹配指令成功但没有对话内容时发送的消息
placeholder = "您好！我是 Assistant，一个由 OpenAI 训练的大型语言模型。我不是真正的人，而是一个计算机程序，可以通过文本聊天来帮助您解决问题。如果您有任何问题，请随时告诉我，我将尽力回答。\n如果您需要重置我们的会话，请回复`重置会话`。"

# 发生错误时要发送的消息
error_format = "出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n{exc}"

# 发生网络错误时发送的消息，请注意可以插入 {exc} 作为异常占位符
error_network_failure = "网络故障！连接 OpenAI 服务器失败，我需要更好的网络才能服务！\n{exc}"

# OpenAI 账号登录失效时的提示
error_session_authenciate_failed = "身份验证失败！无法登录至 ChatGPT 服务器，请检查账号信息是否正确！\n{exc}"

# OpenAI 提示 Too many requests（太多请求） 时的提示
error_request_too_many = "糟糕！当前收到的请求太多了，我需要一段时间冷静冷静。你可以选择“重置会话”，或者过一会儿再来找我！\n{exc}"

# 服务器提示 Server overloaded(过载) 时的提示
error_server_overloaded = "抱歉，当前服务器压力有点大，请稍后再找我吧！"

# 是否要回复触发指令的消息
quote = true

# 发送下面那个提醒之前的等待时间
timeout = 30.0

# 超过响应时间时要发送的提醒
timeout_format = "我还在思考中，请再等一下~"

# 重置会话时发送的消息
reset = "会话已重置。"

# 回滚成功时发送的消息
rollback_success = "已回滚至上一条对话，你刚刚发的我就忘记啦！"

# 回滚失败时发送的消息
rollback_fail = "回滚失败，没有更早的记录了！"

# 等待处理的消息的最大数量，如果要关闭此功能，设置为 0
max_queue_size = 10

# 队列满时的提示
queue_full = "抱歉！我现在要回复的人有点多，暂时没有办法接收新的消息了，请过会儿再给我发吧！"

# 新消息加入队列会发送通知的长度最小值
queued_notice_size = 3

# 新消息进入队列时，发送的通知。 queue_size 是当前排队的消息数
queued_notice = "消息已收到！当前我还有{queue_size}条消息要回复，请您稍等。"
```

另外，超时机制也失效了，从开始计时，一直到3分钟后都没报超时：
![image](https://user-images.githubusercontent.com/93979778/222969195-42a5c4f8-b37e-4c4c-9490-436c7ae80764.png)

**Comment by lss233** [comment]
下一版本修复
