### ISSUE TITLE
[BUG] 2.2.2无法登陆，Internal Server Error

### ISSUE THREAD

**Issue by magisk317** [lss233/chatgpt-mirai-qq-bot#299]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
```
2023-03-07 19:52:14.079 | ERROR    | manager.bot:login_openai:129 - 未知错误：
2023-03-07 19:52:14.080 | ERROR    | manager.bot:login_openai:130 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):

  File "/Volumes/data/Download/diy/Windows-quickstart-refs.tags.v2.2.2/chatgpt/bot.py", line 325, in <module>
    app.launch_blocking()
    │   └ <classmethod(<function Ariadne.launch_blocking at 0x14d6a3740>)>
    └ <graia.ariadne.app.Ariadne object at 0x10b5fbb90>

  File "/usr/local/lib/python3.11/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x14d6accc0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x10b5cb750>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x14b3acc20>
    │   └ <launart.manager.Launart object at 0x14a865890>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "/usr/local/lib/python3.11/site-packages/launart/manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.11/site-packages/launart/manager...
    │    └ <function BaseEventLoop.run_until_complete at 0x10c1071a0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x10c107100>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10c10cf40>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x10bf6dd00>
    └ <Handle <TaskStepMethWrapper object at 0x14e087040>()>

  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x14e087040>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x14e087040>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x14e087040>()>

  File "/usr/local/lib/python3.11/site-packages/graia/broadcast/__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {}
                   │                └ <function start_background at 0x14e0bdbc0>
                   └ <function run_always_await at 0x14b3af240>
  File "/usr/local/lib/python3.11/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object start_background at 0x14e0c8ee0>

  File "/Volumes/data/Download/diy/Windows-quickstart-refs.tags.v2.2.2/chatgpt/bot.py", line 262, in start_background
    botManager.login()
    │          └ <function BotManager.login at 0x14af73240>
    └ <manager.bot.BotManager object at 0x10fb2eb50>

  File "/Volumes/data/Download/diy/Windows-quickstart-refs.tags.v2.2.2/chatgpt/manager/bot.py", line 67, in login
    self.login_openai()
    │    └ <function BotManager.login_openai at 0x14d5c98a0>
    └ <manager.bot.BotManager object at 0x10fb2eb50>

> File "/Volumes/data/Download/diy/Windows-quickstart-refs.tags.v2.2.2/chatgpt/manager/bot.py", line 107, in login_openai
    bot = self.__login_V1(account)
          │               └ OpenAIAccessTokenAuth(mode='browserless', proxy=None, driver_exec_path=None, browser_exec_path=None, conversation=None, paid=...
          └ <manager.bot.BotManager object at 0x10fb2eb50>

  File "/Volumes/data/Download/diy/Windows-quickstart-refs.tags.v2.2.2/chatgpt/manager/bot.py", line 192, in __login_V1
    if __V1_check_auth():

  File "/Volumes/data/Download/diy/Windows-quickstart-refs.tags.v2.2.2/chatgpt/manager/bot.py", line 180, in __V1_check_auth
    bot.get_conversations(0, 1)
    │   └ <function logger.<locals>.decorator.<locals>.wrapper at 0x110f8cea0>
    └ <revChatGPT.V1.Chatbot object at 0x14e091010>

  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 53, in wrapper
    out = func(*args, **kwargs)
          │     │       └ {}
          │     └ (<revChatGPT.V1.Chatbot object at 0x14e091010>, 0, 1)
          └ <function Chatbot.get_conversations at 0x110f8ce00>
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 600, in get_conversations
    data = json.loads(response.text)
           │    │     │        └ <property object at 0x10cdf2480>
           │    │     └ <Response [200]>
           │    └ <function loads at 0x10c17e160>
           └ <module 'json' from '/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__i...

  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ 'Internal Server Error'
           │                └ <function JSONDecoder.decode at 0x10c17d940>
           └ <json.decoder.JSONDecoder object at 0x10c14bc50>

  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ 'Internal Server Error'
               │    │          │      └ <built-in method match of re.Pattern object at 0x10c135490>
               │    │          └ 'Internal Server Error'
               │    └ <function JSONDecoder.raw_decode at 0x10c17d9e0>
               └ <json.decoder.JSONDecoder object at 0x10c14bc50>

  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ 'Internal Server Error'
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-03-07 19:52:14.092 | INFO     | manager.bot:login_openai:101 - 正在登录第 2 个 OpenAI 账号
2023-03-07 19:52:14.092 | SUCCESS  | manager.bot:login_openai:116 - 登录成功！
```

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by magisk317** [comment]
用了群里的endpoint，且2.2.2.1也是一样

**Comment by magisk317** [comment]
好吧，可能真的是服务器的原因，现在好了。。。
![image](https://user-images.githubusercontent.com/93979778/223436096-1c8918a1-d0f2-424d-95f1-9ea780a5cb24.png)
