### ISSUE TITLE
能够获取token 但仍然抛出登入失败错误

### ISSUE THREAD

**Issue by foxMaxwell** [lss233/chatgpt-mirai-qq-bot#302]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
我能够确定我的服务器IP可以解锁chatGPT
QQ可以正常登录
无法启动chatGPT,抛出“所有账号登录失败，程序无法启动！”以及“OpenAI 服务器登录失败！”的错误
排除网络和账号问题，浏览器可以正常登入并使用chatGPT
无论是否使用浏览器模式登入，最终都会抛出同样的错误

**运行环境:**  
- 操作系统：Windows-2022-Datacenter
- Docker： ？
- 项目版本：2.2.1

**复现步骤**  
描述你是如何触发这个 BUG 的：启动chatGPT
启动chatGPT（无论是否浏览器模式登录）都能复现这个错误：是
**预期行为**  
之前成功运行过，本应该正常使用，约2023年3月7日下午开始失联

**截图**  
2023-03-08 02:19:58.610 | ERROR    | config:scan_presets:235 - 检查预设：正常 <==> presets/default.txt [失败：文件不存在]
2023-03-08 02:19:58.610 | SUCCESS  | config:scan_presets:233 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-03-08 02:19:58.610 | SUCCESS  | config:scan_presets:246 - 注册预设：bing <==> ./presets/assistant\bing.txt [成功]
2023-03-08 02:19:58.610 | SUCCESS  | config:scan_presets:246 - 注册预设：debater <==> ./presets/assistant\debater.txt [成功]
2023-03-08 02:19:58.610 | SUCCESS  | config:scan_presets:246 - 注册预设：default <==> ./presets/assistant\default.txt [成功]
2023-03-08 02:19:58.626 | SUCCESS  | config:scan_presets:246 - 注册预设：lawyer <==> ./presets/assistant\lawyer.txt [成功]
2023-03-08 02:19:58.626 | SUCCESS  | config:scan_presets:246 - 注册预设：Lss233 <==> ./presets/assistant\Lss233.txt [成功]
2023-03-08 02:19:58.626 | SUCCESS  | config:scan_presets:246 - 注册预设：novelist <==> ./presets/assistant\novelist.txt [成功]
2023-03-08 02:19:58.626 | SUCCESS  | config:scan_presets:246 - 注册预设：poet <==> ./presets/assistant\poet.txt [成功]
2023-03-08 02:19:58.626 | SUCCESS  | config:scan_presets:246 - 注册预设：shineisheji <==> ./presets/assistant\shineisheji.txt [成功]
2023-03-08 02:19:58.626 | SUCCESS  | config:scan_presets:246 - 注册预设：catgirl <==> ./presets/role-play\catgirl.txt [成功]
2023-03-08 02:19:58.642 | SUCCESS  | config:scan_presets:246 - 注册预设：crazy <==> ./presets/role-play\crazy.txt [成功]2023-03-08 02:19:58.642 | SUCCESS  | config:scan_presets:246 - 注册预设：debatestick <==> ./presets/role-play\debatestick.txt [成功]
2023-03-08 02:19:58.642 | SUCCESS  | config:scan_presets:246 - 注册预设：dingzhen <==> ./presets/role-play\dingzhen.txt [成功]
2023-03-08 02:19:58.642 | SUCCESS  | config:scan_presets:246 - 注册预设：DJ <==> ./presets/role-play\DJ.txt [成功]
2023-03-08 02:19:58.642 | SUCCESS  | config:scan_presets:246 - 注册预设：gaoqiqiang <==> ./presets/role-play\gaoqiqiang.txt [成功]
2023-03-08 02:19:58.642 | SUCCESS  | config:scan_presets:246 - 注册预设：hanli <==> ./presets/role-play\hanli.txt [成功]2023-03-08 02:19:58.642 | SUCCESS  | config:scan_presets:246 - 注册预设：huxijin <==> ./presets/role-play\huxijin.txt [成功]
2023-03-08 02:19:58.659 | SUCCESS  | config:scan_presets:246 - 注册预设：ikun <==> ./presets/role-play\ikun.txt [成功]
2023-03-08 02:19:58.659 | SUCCESS  | config:scan_presets:246 - 注册预设：MOSS <==> ./presets/role-play\MOSS.txt [成功]
2023-03-08 02:19:58.659 | SUCCESS  | config:scan_presets:246 - 注册预设：welldone <==> ./presets/role-play\welldone.txt [成功]
2023-03-08 02:19:58.659 | SUCCESS  | config:scan_presets:246 - 注册预设：zhangweiwei <==> ./presets/role-play\zhangweiwei.txt [成功]
2023-03-08 02:19:58.671 | ERROR    | config:scan_presets:243 - 注册预设：catgirl <==> ./presets/catgirl.txt [失败：关键词已存在]
2023-03-08 02:19:58.675 | SUCCESS  | config:scan_presets:246 - 注册预设：预设模板 <==> ./presets/预设模板.txt [成功]
2023-03-08 02:19:59.863 | INFO     | launart.manager:launch_blocking:479 - Starting launart main task...
2023-03-08 02:19:59.863 | INFO     | launart.manager:launch:331 - Launching 5 components as async task...
2023-03-08 02:20:00.008 | INFO     | graia.ariadne.service:base_telemetry:108 -
    _         _           _
   / \   _ __(_) __ _  __| |_ __   ___
  / _ \ | '__| |/ _` |/ _` | '_ \ / _ \
 / ___ \| |  | | (_| | (_| | | | |  __/
/_/   \_\_|  |_|\__,_|\__,_|_| |_|\___|

graia-amnesia: 0.7.1
graia-ariadne: 0.11.1
graia-broadcast: 0.19.1
launart: 0.6.3
statv: 0.3.2
2023-03-08 02:20:00.027 | SUCCESS  | launart.manager:launch:384 - Layer #1:[cache.client/memcache, http.client/aiohttp] preparation completed.
2023-03-08 02:20:00.027 | INFO     | __main__:start_background:261 - OpenAI 服务器登录中……
2023-03-08 02:20:00.027 | INFO     | manager.bot:login_openai:101 - 正在登录第 1 个 OpenAI 账号
2023-03-08 02:20:00.044 | INFO     | manager.bot:__login_browser:136 - 模式：浏览器登录
2023-03-08 02:20:00.047 | INFO     | manager.bot:__login_browser:137 - 这需要你拥有最新版的 Chrome 浏览器。
2023-03-08 02:20:00.047 | INFO     | manager.bot:__login_browser:138 - 即将打开浏览器窗口……
2023-03-08 02:20:00.047 | INFO     | manager.bot:__login_browser:139 - 提示：如果你看见了 Cloudflare 验证码，请手动完成验证。
2023-03-08 02:20:00.047 | INFO     | manager.bot:__login_browser:140 - 如果你持续停留在 Found session token 环节，请使用无浏览器登录模式。
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
2023-03-08 02:20:43,468 - urllib3.connectionpool - WARNING - _put_conn - Connection pool is full, discarding connection: localhost. Connection pool size: 1
2023-03-08 02:21:20,937 - urllib3.connectionpool - WARNING - _put_conn - Connection pool is full, discarding connection: localhost. Connection pool size: 1
2023-03-08 02:21:22,875 - urllib3.connectionpool - WARNING - _put_conn - Connection pool is full, discarding connection: localhost. Connection pool size: 1
Found Session Token!
2023-03-08 02:22:25.597 | ERROR    | manager.bot:login_openai:129 - 未知错误：
2023-03-08 02:22:25.607 | ERROR    | manager.bot:login_openai:130 - Message:
Stacktrace:
Backtrace:
        (No symbol) [0x006137D3]
        (No symbol) [0x005A8B81]
        (No symbol) [0x004AB36D]
        (No symbol) [0x004DD382]
        (No symbol) [0x004DD4BB]
        (No symbol) [0x00513302]
        (No symbol) [0x004FB464]
        (No symbol) [0x00511215]
        (No symbol) [0x004FB216]
        (No symbol) [0x004D0D97]
        (No symbol) [0x004D253D]
        GetHandleVerifier [0x0088ABF2+2510930]
        GetHandleVerifier [0x008B8EC1+2700065]
        GetHandleVerifier [0x008BC86C+2714828]
        GetHandleVerifier [0x006C3480+645344]
        (No symbol) [0x005B0FD2]
        (No symbol) [0x005B6C68]
        (No symbol) [0x005B6D4B]
        (No symbol) [0x005C0D6B]
        BaseThreadInitThunk [0x75C56709+25]
        RtlGetFullPathName_UEx [0x7798791D+173]
        RtlGetFullPathName_UEx [0x779878EB+123]

Traceback (most recent call last):

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\bot.py", line 325, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x00000249A66930D0>
    └ <graia.ariadne.app.Ariadne object at 0x00000249FCECD220>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x00000249A668E9A0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x00000249FCEA0E80>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x00000249A6376C10>
    │   └ <launart.manager.Launart object at 0x00000249A7BFDBE0>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\...
    │    └ <function BaseEventLoop.run_until_complete at 0x00000249FEB91820>    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 634, in run_until_complete
    ', '.join(str(exc) for exc in exceptions)))
                                  └ <module 'asyncio.exceptions' from 'C:\\chatGPT\\Windows-quickstart-refs.tags.v2.2.1\\chatgpt\\python3.9\\python39.zip\\asynci...

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 601, in run_forever
    exc.errno, 'error while '

  File "asyncio\base_events.py", line 1905, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000249A91746D0>()>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\graia\broadcast\__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {}
                   │                └ <function start_background at 0x00000249A7BB85E0>
                   └ <function run_always_await at 0x00000249A63A2160>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\graia\broadcast\utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object start_background at 0x00000249A7B96D40>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\bot.py", line 262, in start_background
    botManager.login()
    │          └ <function BotManager.login at 0x00000249A62CBAF0>
    └ <manager.bot.BotManager object at 0x00000249A62F43A0>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\manager\bot.py", line 67, in login
    self.login_openai()
    │    └ <function BotManager.login_openai at 0x00000249A62E38B0>
    └ <manager.bot.BotManager object at 0x00000249A62F43A0>

> File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\manager\bot.py", line 110, in login_openai
    bot = self.__login_browser(account)
          │                    └ OpenAIEmailAuth(mode='browser', proxy=None, driver_exec_path=None, browser_exec_path=None, conversation=None, paid=False, ver...
          └ <manager.bot.BotManager object at 0x00000249A62F43A0>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\manager\bot.py", line 145, in __login_browser
    bot = BrowserChatbot(config=account.dict(exclude_none=True, by_alias=False))
          │                     │       └ <cyfunction BaseModel.dict at 0x00000249FFB736C0>
          │                     └ OpenAIEmailAuth(mode='browser', proxy=None, driver_exec_path=None, browser_exec_path=None, conversation=None, paid=False, ver...
          └ <class 'revChatGPT.Unofficial.Chatbot'>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\revChatGPT\Unofficial.py", line 72, in __init__
    self.__email_login()
    └ <revChatGPT.Unofficial.Chatbot object at 0x00000249A9174AF0>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\revChatGPT\Unofficial.py", line 503, in __email_login
    WebDriverWait(driver, 120).until(
    └ <class 'selenium.webdriver.support.wait.WebDriverWait'>

  File "C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
          │                │        │       └ ['Backtrace:', '\t(No symbol) [0x006137D3]', '\t(No symbol) [0x005A8B81]', '\t(No symbol) [0x004AB36D]', '\t(No symbol) [0x00...
          │                │        └ None
          │                └ ''
          └ <class 'selenium.common.exceptions.TimeoutException'>

selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x006137D3]
        (No symbol) [0x005A8B81]
        (No symbol) [0x004AB36D]
        (No symbol) [0x004DD382]
        (No symbol) [0x004DD4BB]
        (No symbol) [0x00513302]
        (No symbol) [0x004FB464]
        (No symbol) [0x00511215]
        (No symbol) [0x004FB216]
        (No symbol) [0x004D0D97]
        (No symbol) [0x004D253D]
        GetHandleVerifier [0x0088ABF2+2510930]
        GetHandleVerifier [0x008B8EC1+2700065]
        GetHandleVerifier [0x008BC86C+2714828]
        GetHandleVerifier [0x006C3480+645344]
        (No symbol) [0x005B0FD2]
        (No symbol) [0x005B6C68]
        (No symbol) [0x005B6D4B]
        (No symbol) [0x005C0D6B]
        BaseThreadInitThunk [0x75C56709+25]
        RtlGetFullPathName_UEx [0x7798791D+173]
        RtlGetFullPathName_UEx [0x779878EB+123]

2023-03-08 02:22:25.775 | SUCCESS  | manager.bot:login_openai:133 - 成功登录 0/1 个 OpenAI 账号！
2023-03-08 02:22:25.775 | ERROR    | manager.bot:login:70 - 所有账号登录失败，程序无法启动！
2023-03-08 02:22:25.786 | ERROR    | __main__:start_background:264 - OpenAI 服务器登录失败！

C:\chatGPT\Windows-quickstart-refs.tags.v2.2.1\chatgpt>

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
重复： https://github.com/lss233/chatgpt-mirai-qq-bot/issues/211

**Comment by lss233** [comment]
stale
