### ISSUE TITLE
py运行报错 KeyError: 'openai'

### ISSUE THREAD

**Issue by pachi-33** [lss233/chatgpt-mirai-qq-bot#31]
报错如下：

```bash
Traceback (most recent call last):
  File "/app/bot.py", line 11, in <module>
    import chatbot
  File "/app/chatbot.py", line 7, in <module>
    bot = Chatbot(config_data["openai"], conversation_id=None)
KeyError: 'openai'
```

config.json配置：

```json
{
    "mirai": {
        "qq": ______,
        "api_key": "______",
        "http_url": "http://localhost:8080",
        "ws_url": "http://localhost:8080"
    },
    "openai": {
        "email": "________",
        "password": "_______"

  	},
	"text_to_image": {
    	"font_size": 30,
    	"width": 700,
    	"font_path": "fonts/sarasa-mono-sc-regular.ttf",
    	"offset_x": 50,
    	"offset_y": 50
	}
}
```

**Comment by lss233** [comment]
JSON 是没什么问题，确定它读取的 JSON 是你展示的这份 config.json 吗？

**Comment by pachi-33** [comment]
用的是docker-compose，然后改是这个位置的config.json。
root@OpenWrt:/opt/overlay2/d0f9bb2a0ae0e51b5461144496e2c0c57b5385aa8f0a88688e0f2846a553aa57/diff/app/config.json
请佬指点。
