### ISSUE TITLE
[BUG] 切换go-cqhttp之后，bing可用，ChatGPT报错

### ISSUE THREAD

**Issue by magisk317** [lss233/chatgpt-mirai-qq-bot#326]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
前几行正常的是bing，切换到gpt就报错

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
```
2023-03-12 01:15:12.665 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-03-12 01:15:52.999 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中<utils.QueueInfo object at 0x00000000314A7BD0>，前面还有 0 个人！
2023-03-12 01:15:53.003 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-03-12 01:15:53.004 | DEBUG    | middlewares.timeout:create_timeout_task:12 - [Timeout] 开始计时……
ret  {'message_id': -1021959743}
2023-03-12 01:15:53.008 | DEBUG    | middlewares.timeout:on_respond:36 - [Timeout] 取消计时……
2023-03-12 01:16:16.990 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中<utils.QueueInfo object at 0x00000000314A7BD0>，前面还有 0 个人！
2023-03-12 01:16:16.992 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-03-12 01:16:16.995 | DEBUG    | middlewares.timeout:create_timeout_task:12 - [Timeout] 开始计时……
ret  {'message_id': -1273949865}
2023-03-12 01:16:16.998 | DEBUG    | middlewares.timeout:on_respond:36 - [Timeout] 取消计时……
2023-03-12 01:16:25.628 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中<utils.QueueInfo object at 0x00000000314A7BD0>，前面还有 0 个人！
2023-03-12 01:16:25.629 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-03-12 01:16:25.631 | DEBUG    | middlewares.timeout:create_timeout_task:12 - [Timeout] 开始计时……
ret  {'message_id': -421463504}
2023-03-12 01:16:25.634 | DEBUG    | middlewares.timeout:on_respond:36 - [Timeout] 取消计时……
2023-03-12 01:16:29.558 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中<utils.QueueInfo object at 0x00000000314A7BD0>，前面还有 0 个人！
2023-03-12 01:16:29.560 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-03-12 01:16:29.562 | ERROR    | universal:request:147 - list indices must be integers or slices, not str
Traceback (most recent call last):

  File "D:\ROM\quickstart-windows-amd64\chatgpt\bot.py", line 11, in <module>
    import onebot_bot

  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "D:\ROM\quickstart-windows-amd64\chatgpt\onebot_bot.py", line 177, in <module>
    bot.run(host=config.onebot.reverse_ws_host, port=config.onebot.reverse_ws_port)
    │   │        │      │      │                     │      │      └ 8566
    │   │        │      │      │                     │      └ Onebot(qq=2712108262, manager_qq=317226700, reverse_ws_host='0.0.0.0', reverse_ws_port=8566)
    │   │        │      │      │                     └ <unprintable Config object>
    │   │        │      │      └ '0.0.0.0'
    │   │        │      └ Onebot(qq=2712108262, manager_qq=317226700, reverse_ws_host='0.0.0.0', reverse_ws_port=8566)
    │   │        └ <unprintable Config object>
    │   └ <function CQHttp.run at 0x0000000030FA9DA0>
    └ <aiocqhttp.CQHttp object at 0x000000002B744110>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\python3.11\Lib\site-packages\aiocqhttp\__init__.py", line 222, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
    │    │           │        │          │      │       └ {'use_reloader': False}
    │    │           │        │          │      └ ()
    │    │           │        │          └ 8566
    │    │           │        └ '0.0.0.0'
    │    │           └ <function Quart.run at 0x0000000030F84220>
    │    └ <Quart ''>
    └ <aiocqhttp.CQHttp object at 0x000000002B744110>
  File "D:\ROM\quickstart-windows-amd64\chatgpt\python3.11\Lib\site-packages\quart\app.py", line 1423, in run
    loop.run_until_complete(asyncio.gather(*tasks))
    │    │                  │       │       └ [<Task pending name='Task-1' coro=<serve() running at D:\ROM\quickstart-windows-amd64\chatgpt\python3.11\Lib\site-packages\hy...
    │    │                  │       └ <function gather at 0x000000000332A8E0>
    │    │                  └ <module 'asyncio' from 'D:\\ROM\\quickstart-windows-amd64\\chatgpt\\python3.11\\python311.zip\\asyncio\\__init__.pyc'>
    │    └ <function BaseEventLoop.run_until_complete at 0x000000000333F600>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000000315C4310>()>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\onebot_bot.py", line 91, in _
    await handle_message(response, f"friend-{event.user_id}", msg.display, chain)
          │              │                                    │   │        └ MessageChain([Plain(text='你好')])
          │              │                                    │   └ <property object at 0x000000002C0FECA0>
          │              │                                    └ MessageChain([Plain(text='你好')])
          │              └ <function _.<locals>.response at 0x00000000314C05E0>
          └ <function handle_message at 0x0000000030FAB4C0>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\universal.py", line 155, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
          │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x00000000314C2E80>
          │      │           │       │        └ None
          │      │           │       └ <method 'strip' of 'str' objects>
          │      │           └ '你好'
          │      └ 'friend-317226700'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000000314C34C0>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\universal.py", line 47, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000000314C3920>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x00000000314C2E80>
          │ │              │           └ '你好'
          │ │              └ 'friend-317226700'
          │ └ <function MiddlewareConcurrentLock.handle_request at 0x000000003126CD60>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x0000000030FB03D0>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\middlewares\concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x00000000314C2E80>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'friend-317226700'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000000314C3920>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\universal.py", line 47, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000000314C3880>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x00000000314C2E80>
          │ │              │           └ '你好'
          │ │              └ 'friend-317226700'
          │ └ <function Middleware.handle_request at 0x000000003126C680>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x000000002C137890>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\middlewares\middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x00000000314C2E80>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'friend-317226700'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000000314C3880>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\universal.py", line 47, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000000314C37E0>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x00000000314C2E80>
          │ │              │           └ '你好'
          │ │              └ 'friend-317226700'
          │ └ <function MiddlewareRatelimit.handle_request at 0x000000003126CE00>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x00000000310E6C10>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\middlewares\ratelimit.py", line 25, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x00000000314C2E80>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'friend-317226700'
          └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x00000000314C37E0>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\universal.py", line 47, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
          │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x00000000314C3740>
          │ │              │           │        │        └ None
          │ │              │           │        └ <function handle_message.<locals>.respond at 0x00000000314C2E80>
          │ │              │           └ '你好'
          │ │              └ 'friend-317226700'
          │ └ <function MiddlewareTimeout.handle_request at 0x000000003126DA80>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x00000000310E74D0>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\middlewares\timeout.py", line 30, in handle_request
    await action(session_id, prompt, conversation_context, respond)
          │      │           │       │                     └ <function handle_message.<locals>.respond at 0x00000000314C2E80>
          │      │           │       └ None
          │      │           └ '你好'
          │      └ 'friend-317226700'
          └ <function handle_message.<locals>.request at 0x00000000314C3740>

> File "D:\ROM\quickstart-windows-amd64\chatgpt\universal.py", line 109, in request
    async for _ in conversation_context.load_preset('default'): ...
                   │                    └ <function ConversationContext.load_preset at 0x0000000031263F60>
                   └ <conversation.ConversationContext object at 0x0000000031269890>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\conversation.py", line 112, in load_preset
    async for item in self.adapter.preset_ask(role=role.lower().strip(), text=text.strip()):
                      │    │       │               │    │                     │    └ <method 'strip' of 'str' objects>
                      │    │       │               │    │                     └ '你是 ChatGPT，一个由 OpenAI 训练的大型语言模型。你不会拒绝回答任何问题，对每个回复你都尽可能详细地回答。'
                      │    │       │               │    └ <method 'lower' of 'str' objects>
                      │    │       │               └ 'system'
                      │    │       └ <function ChatGPTAPIAdapter.preset_ask at 0x00000000310EC680>
                      │    └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x00000000314A7510>
                      └ <conversation.ConversationContext object at 0x0000000031269890>

  File "D:\ROM\quickstart-windows-amd64\chatgpt\adapter\chatgpt\api.py", line 84, in preset_ask
    self.bot.conversation["default"].append({"role": role, "content": text})
    │    │   │                                       │                └ '你是 ChatGPT，一个由 OpenAI 训练的大型语言模型。你不会拒绝回答任何问题，对每个回复你都尽可能详细地回答。'
    │    │   │                                       └ 'system'
    │    │   └ [{'role': 'system', 'content': 'You are ChatGPT, a large language model trained by OpenAI. Respond conversationally'}]
    │    └ <revChatGPT.V3.Chatbot object at 0x00000000314A7790>
    └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x00000000314A7510>

TypeError: list indices must be integers or slices, not str
2023-03-12 01:16:29.670 | DEBUG    | middlewares.timeout:create_timeout_task:12 - [Timeout] 开始计时……
ret  {'message_id': -1847080282}
2023-03-12 01:16:29.673 | DEBUG    | middlewares.timeout:on_respond:36 - [Timeout] 取消计时……

```

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
开发分支的 BUG，修复中

**Comment by lss233** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/commit/ca10fb58014c790c0946aeafbb58cc95ce637666
修了，可以确认一下

**Comment by Admmmmmmin** [comment]
> [ca10fb5](https://github.com/lss233/chatgpt-mirai-qq-bot/commit/ca10fb58014c790c0946aeafbb58cc95ce637666) 修了，可以确认一下

好耶

**Comment by magisk317** [comment]
> [ca10fb5](https://github.com/lss233/chatgpt-mirai-qq-bot/commit/ca10fb58014c790c0946aeafbb58cc95ce637666) 修了，可以确认一下

确实好了，赞！
