### ISSUE TITLE
[BUG] 在图片模式无法转换为文本模式

### ISSUE THREAD

**Issue by beiyaohhhc** [lss233/chatgpt-mirai-qq-bot#327]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在图片模式下切换为图片模式是正常的 但切换文本模式显示无管理权限

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的
1.向机器人发送文本模式 显示无管理员权限
2. 向机器人使用指令重载配置文件 可以正常重载
3. 在图片模式中切换为图片模式 可以正常切换
4. 尝试切换为文本模式无法切换

**预期行为**  
可以正常切换为文本模式

**截图**  
![image](https://user-images.githubusercontent.com/98569420/224502602-91a244ce-501c-4f80-9a5e-ec56c0d37206.png)
![image](https://user-images.githubusercontent.com/98569420/224502613-635495bf-ab9b-45f7-aa31-f50a95970e4f.png)
![image](https://user-images.githubusercontent.com/98569420/224502620-22663640-a3a7-4b2d-80ff-f8ff9ca45dc3.jpeg)
![image](https://user-images.githubusercontent.com/98569420/224502677-709d4a98-147c-4278-ae3c-c7cb6de0b32b.jpeg)
**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
重启即可。

**Comment by beiyaohhhc** [comment]
重启了 手机代理报错 而不是切换报错 但依然无法切换

**Comment by beiyaohhhc** [comment]
这是运行日志

` 2023-03-12 01:41:13.264 | ERROR    | config:scan_presets:235 - 检查预设：正常 <==> presets/default.txt [失败：文件不存在]
2023-03-12 01:41:13.264 | SUCCESS  | config:scan_presets:233 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-03-12 01:41:13.264 | SUCCESS  | config:scan_presets:246 - 注册预设：bing <==> ./presets\assistant\bing.txt [成功]
2023-03-12 01:41:13.264 | SUCCESS  | config:scan_presets:246 - 注册预设：debater <==> ./presets\assistant\debater.txt [ 成功]
2023-03-12 01:41:13.280 | SUCCESS  | config:scan_presets:246 - 注册预设：default <==> ./presets\assistant\default.txt [ 成功]
2023-03-12 01:41:13.280 | SUCCESS  | config:scan_presets:246 - 注册预设：lawyer <==> ./presets\assistant\lawyer.txt [成 功]
2023-03-12 01:41:13.280 | SUCCESS  | config:scan_presets:246 - 注册预设：Lss233 <==> ./presets\assistant\Lss233.txt [成 功]
2023-03-12 01:41:13.280 | SUCCESS  | config:scan_presets:246 - 注册预设：novelist <==> ./presets\assistant\novelist.txt [成功]
2023-03-12 01:41:13.280 | SUCCESS  | config:scan_presets:246 - 注册预设：poet <==> ./presets\assistant\poet.txt [成功]
2023-03-12 01:41:13.280 | SUCCESS  | config:scan_presets:246 - 注册预设：shineisheji <==> ./presets\assistant\shineisheji.txt [成功]
2023-03-12 01:41:13.296 | SUCCESS  | config:scan_presets:246 - 注册预设：catgirl <==> ./presets\role-play\catgirl.txt [ 成功]
2023-03-12 01:41:13.296 | SUCCESS  | config:scan_presets:246 - 注册预设：crazy <==> ./presets\role-play\crazy.txt [成功]
2023-03-12 01:41:13.296 | SUCCESS  | config:scan_presets:246 - 注册预设：debatestick <==> ./presets\role-play\debatestick.txt [成功]
2023-03-12 01:41:13.296 | SUCCESS  | config:scan_presets:246 - 注册预设：dingzhen <==> ./presets\role-play\dingzhen.txt [成功]
2023-03-12 01:41:13.296 | SUCCESS  | config:scan_presets:246 - 注册预设：DJ <==> ./presets\role-play\DJ.txt [成功]
2023-03-12 01:41:13.296 | SUCCESS  | config:scan_presets:246 - 注册预设：gaoqiqiang <==> ./presets\role-play\gaoqiqiang.txt [成功]
2023-03-12 01:41:13.296 | SUCCESS  | config:scan_presets:246 - 注册预设：hanli <==> ./presets\role-play\hanli.txt [成功]
2023-03-12 01:41:13.311 | SUCCESS  | config:scan_presets:246 - 注册预设：huxijin <==> ./presets\role-play\huxijin.txt [ 成功]
2023-03-12 01:41:13.311 | SUCCESS  | config:scan_presets:246 - 注册预设：ikun <==> ./presets\role-play\ikun.txt [成功]
2023-03-12 01:41:13.311 | SUCCESS  | config:scan_presets:246 - 注册预设：MOSS <==> ./presets\role-play\MOSS.txt [成功]
2023-03-12 01:41:13.311 | SUCCESS  | config:scan_presets:246 - 注册预设：welldone <==> ./presets\role-play\welldone.txt [成功]
2023-03-12 01:41:13.311 | SUCCESS  | config:scan_presets:246 - 注册预设：zhangweiwei <==> ./presets\role-play\zhangweiwei.txt [成功]
2023-03-12 01:41:13.326 | ERROR    | config:scan_presets:243 - 注册预设：catgirl <==> ./presets\catgirl.txt [失败：关键 词已存在]
2023-03-12 01:41:13.326 | SUCCESS  | config:scan_presets:246 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2023-03-12 01:41:14.316 | INFO     | launart.manager:launch_blocking:479 - Starting launart main task...
2023-03-12 01:41:14.316 | INFO     | launart.manager:launch:331 - Launching 5 components as async task...
2023-03-12 01:41:14.456 | INFO     | graia.ariadne.service:base_telemetry:108 -
    _         _           _
   / \   _ __(_) __ _  __| |_ __   ___
  / _ \ | '__| |/ _` |/ _` | '_ \ / _ \
 / ___ \| |  | | (_| | (_| | | | |  __/
/_/   \_\_|  |_|\__,_|\__,_|_| |_|\___|

graia-amnesia: 0.7.1
graia-ariadne: 0.11.1
graia-broadcast: 0.19.1
launart: 0.6.3
statv: 0.3.2
2023-03-12 01:41:14.456 | SUCCESS  | launart.manager:launch:384 - Layer #1:[cache.client/memcache, http.client/aiohttp] preparation completed.
2023-03-12 01:41:14.472 | INFO     | __main__:start_background:261 - OpenAI 服务器登录中……
2023-03-12 01:41:14.472 | INFO     | manager.bot:login_bing:86 - 正在解析第 1 个 Bing 账号
2023-03-12 01:41:14.472 | SUCCESS  | manager.bot:login_bing:90 - 解析成功！
2023-03-12 01:41:14.472 | SUCCESS  | manager.bot:login_bing:96 - 成功解析 1/1 个 Bing 账号！
2023-03-12 01:41:14.472 | INFO     | manager.bot:login_openai:101 - 正在登录第 1 个 OpenAI 账号
2023-03-12 01:41:14.488 | INFO     | manager.bot:__check_proxy:150 - 正在检查代理配置：http://127.0.0.1:7890
2023-03-12 01:41:14.488 | SUCCESS  | manager.bot:login_openai:116 - 登录成功！
2023-03-12 01:41:14.545 | INFO     | manager.bot:login_openai:101 - 正在登录第 2 个 OpenAI 账号
2023-03-12 01:41:14.545 | INFO     | manager.bot:__login_V1:171 - 模式：无浏览器登录
2023-03-12 01:41:14.561 | INFO     | manager.bot:__check_proxy:150 - 正在检查代理配置：http://127.0.0.1:1080
2023-03-12 01:41:15.584 | ERROR    | manager.bot:login_openai:129 - 未知错误：
2023-03-12 01:41:15.584 | ERROR    | manager.bot:login_openai:130 - 登录失败! 无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\bot.py", line 325, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x0000024AFCE88070>
    └ <graia.ariadne.app.Ariadne object at 0x0000024AF35B0220>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x0000024AFCE85090>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x0000024AF3583E80>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x0000024AFCB6BAF0>
    │   └ <launart.manager.Launart object at 0x0000024AFD6FC880>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at C:\Users\Administrator\Desktop\Windows-quickstart-refs....
    │    └ <function BaseEventLoop.run_until_complete at 0x0000024AF53744C0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 634, in run_until_complete
    ', '.join(str(exc) for exc in exceptions)))
                                  └ <module 'asyncio.exceptions' from 'C:\\Users\\Administrator\\Desktop\\Windows-quickstart-refs.tags.v2.2.1\\chatgpt\\python3.9...

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 601, in run_forever
    exc.errno, 'error while '

  File "asyncio\base_events.py", line 1905, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000024AFF8285E0>()>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\graia\broadcast\__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {}
                   │                └ <function start_background at 0x0000024AFE24E430>
                   └ <function run_always_await at 0x0000024AFCB77E50>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\python3.9\lib\site-packages\graia\broadcast\utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object start_background at 0x0000024AFF83A340>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\bot.py", line 262, in start_background
    botManager.login()
    │          └ <function BotManager.login at 0x0000024AFCAB9D30>
    └ <manager.bot.BotManager object at 0x0000024AFCAE16D0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\manager\bot.py", line 67, in login
    self.login_openai()
    │    └ <function BotManager.login_openai at 0x0000024AFCACEAF0>
    └ <manager.bot.BotManager object at 0x0000024AFCAE16D0>

> File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\manager\bot.py", line 107, in login_openai
    bot = self.__login_V1(account)
          │               └ OpenAIEmailAuth(mode='browserless', proxy='http://127.0.0.1:1080', driver_exec_path=None, browser_exec_path=None, conversatio...
          └ <manager.bot.BotManager object at 0x0000024AFCAE16D0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\manager\bot.py", line 174, in __login_V1
    if self.__check_proxy(account):
       │                  └ OpenAIEmailAuth(mode='browserless', proxy='http://127.0.0.1:1080', driver_exec_path=None, browser_exec_path=None, conversatio...
       └ <manager.bot.BotManager object at 0x0000024AFCAE16D0>

  File "C:\Users\Administrator\Desktop\Windows-quickstart-refs.tags.v2.2.1\chatgpt\manager\bot.py", line 154, in __check_proxy
    raise Exception("登录失败! 无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！")

Exception: 登录失败! 无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！
2023-03-12 01:41:15.740 | SUCCESS  | manager.bot:login_openai:133 - 成功登录 1/2 个 OpenAI 账号！
2023-03-12 01:41:15.756 | INFO     | __main__:start_background:266 - OpenAI 服务器登录成功
2023-03-12 01:41:15.756 | INFO     | __main__:start_background:267 - 尝试从 Mirai 服务中读取机器人 QQ 的 session key……
2023-03-12 01:41:15.771 | SUCCESS  | launart.manager:launch:384 - Layer #3:[elizabeth.service] preparation completed.
2023-03-12 01:41:15.771 | INFO     | launart.manager:launch:389 - All components prepared, start blocking phase.
2023-03-12 01:41:16.806 | SUCCESS  | graia.ariadne.connection.ws:_:62 - Successfully got session key
2023-03-12 01:42:05.650 | INFO     | graia.ariadne.model:log:82 - 3467350972: [RECV][北遥吃不胖(2383615282)] -> 文本模式
2023-03-12 01:42:05.666 | DEBUG    | middlewares.concurrentlock:handle_request:46 - [Concurrent] 排队中<utils.QueueInfo object at 0x0000024AA0527460>，前面还有 0 个人！
2023-03-12 01:42:05.666 | DEBUG    | middlewares.concurrentlock:handle_request:48 - [Concurrent] 排到了！
2023-03-12 01:42:05.728 | DEBUG    | middlewares.timeout:create_timeout_task:14 - [Timeout] 开始计时……
Loading page (1/2)
Rendering (2/2)
Done
2023-03-12 01:42:08.180 | INFO     | graia.ariadne.model:log:82 - 3467350972: [SEND][北遥吃不胖(2383615282)] <- [图片]
2023-03-12 01:42:08.180 | DEBUG    | middlewares.timeout:on_respond:42 - [Timeout] 取消计时……`
