### ISSUE TITLE
qq登录不了怎么回事???

### ISSUE THREAD

**Issue by hackhy2020** [lss233/chatgpt-mirai-qq-bot#33]
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(389554489), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:309)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2022-12-12 05:18:15 I/Bot.389554489: Bot cancelled: Bot closed
2022-12-12 05:18:15 I/main: mirai-console started successfully.
这个怎么解决????

**Comment by surf08** [comment]
更新mirai到最新版，登陆设备改为ANDROID_PAD，删除device.json

**Comment by lss233** [comment]
这个是 mirai 的问题，养号、换协议、手机短信验证登录，使用[mirai-device-generator](https://github.com/cssxsh/mirai-device-generator) 等方法 都可以试试。

**Comment by hisakochan** [comment]
有没有验证码阶段？如果有，用sakura过一次。
如果没有，那么是否是新注册的或者长期没有登陆过QQ号？如果是，在QQ的桌面或者手机端登陆一次然后等待大概一周再试。
如果否，切换其他协议尝试。

**Comment by hackhy2020** [comment]
谢谢回复 ，登录问题已经解决了。目前chatgpt已经加了cf，以我的技术水平暂时还没办法继续下一步。

**Comment by lss233** [comment]
我们正在跟进此问题。

**Comment by lss233** [comment]
#32

**Comment by henuyuanxiao** [comment]
windows的话，重装一遍mirai就行
