### ISSUE TITLE
更新至1.3后启动报错

### ISSUE THREAD

**Issue by Pil0tXia** [lss233/chatgpt-mirai-qq-bot#36]
config.json更换了最新的session_key，镜像重新pull了，容器rm掉之后重新run，报错如下：
```
azure_root@UbuntuVM:~/mirai-api-http/chatgpt-mirai-qq-bot$ sudo docker run --name mirai-chatgpt-bot -v /home/azure_root/mirai-api-http/chatgpt-mirai-qq-bot/config.json:/app/config.json --network host lss233/chatgpt-mirai-qq-bot:latest
Traceback (most recent call last):
  File "/app/bot.py", line 14, in <module>
    import chatbot
  File "/app/chatbot.py", line 7, in <module>
    bot = Chatbot(config_data["openai"], conversation_id=None, base_url=config_data["base_url"] if "base_url" in config_data else "https://chat.openai.com/")
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 96, in __init__
    self.refresh_session()
  File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 308, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code
```

**Comment by lss233** [comment]
#32， 容器还未更新，还需要等一下

**Comment by Pil0tXia** [comment]
好的

**Comment by lss233** [comment]
已经发布。
