### ISSUE TITLE
[Feature] 希望能够在只填写Bing的情况下使用

### ISSUE THREAD

**Issue by EvolvedGhost** [lss233/chatgpt-mirai-qq-bot#363]
目前版本会强制检测是否填有OpenAI相关信息，没有就会报配置项不正确

PS：建议尽量别用浏览器End Point，号号封完了

**Comment by lss233** [comment]
v2.2.4 已支持

**Comment by Leo01234** [comment]
> v2.2.4 已支持

v2.2.4删除openai相关配置后报错

```
Traceback (most recent call last):
   File "/app/bot.py", line 8, in <module>
     from constants import config
   File "/app/constants.py", line 7, in <module>
     botManager = BotManager(config)
                  ^^^^^^^^^^^^^^^^^^
   File "/app/manager/bot.py", line 48, in __init__
     if config.openai.browserless_endpoint:
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'browserless_endpoint'
 /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
   return _Gtk_main(*args, **kwargs)
```
