### ISSUE TITLE
点击启动后报错

### ISSUE THREAD

**Issue by SoDebug** [lss233/chatgpt-mirai-qq-bot#37]
Traceback (most recent call last):
  File "D:\OpenAiQQBot\chatgpt\bot.py", line 15, in <module>
    import chatbot
  File "D:\OpenAiQQBot\chatgpt\chatbot.py", line 7, in <module>
    bot = Chatbot(config_data["openai"], conversation_id=None, base_url=config_data["base_url"] if "base_url" in config_data else "https://chat.openai.com/")
  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 100, in __init__
    self.refresh_session()
  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 310, in refresh_session
    self.get_cf_cookies()
  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 390, in get_cf_cookies
    driver.get("https://chat.openai.com/chat")
  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\undetected_chromedriver\__init__.py", line 656, in get
    return super().get(url)
  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in get
    self.execute(Command.GET, {"url": url})
  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=108.0.5359.99)
Stacktrace:
Backtrace:
        (No symbol) [0x0097F243]
        (No symbol) [0x00907FD1]
        (No symbol) [0x007FD04D]
        (No symbol) [0x007F9152]
        (No symbol) [0x007F044D]
        (No symbol) [0x007F12EF]
        (No symbol) [0x007F071D]
        (No symbol) [0x007EFB0B]
        (No symbol) [0x007EFA5C]
        (No symbol) [0x007EE7E8]
        (No symbol) [0x007EEDC2]
        (No symbol) [0x007FEA5B]
        (No symbol) [0x0085D187]
        (No symbol) [0x0084858C]
        (No symbol) [0x0085C9EB]
        (No symbol) [0x00848386]
        (No symbol) [0x0082163C]
        (No symbol) [0x0082269D]
        GetHandleVerifier [0x00C19A22+2655074]
        GetHandleVerifier [0x00C0CA24+2601828]
        GetHandleVerifier [0x00A28C0A+619850]
        GetHandleVerifier [0x00A27830+614768]
        (No symbol) [0x009105FC]
        (No symbol) [0x00915968]
        (No symbol) [0x00915A55]
        (No symbol) [0x0092051B]
        BaseThreadInitThunk [0x76517BA9+25]
        RtlInitializeExceptionChain [0x770EBB9B+107]
        RtlClearBits [0x770EBB1F+191]

**Comment by lss233** [comment]
多试几次？

**Comment by SoDebug** [comment]
> 多试几次？

而且它会自动打开我的chrome，但是它打开那个chrome是坏的，无法访问任何地址

**Comment by lss233** [comment]
你需要让你的 Chrome 正常使用，因为它需要你的 Chrome 来通过 Cloudflare 的认证。

**Comment by SoDebug** [comment]
> 你需要让你的 Chrome 正常使用，因为它需要你的 Chrome 来通过 Cloudflare 的认证。

我的chrome是能正常使用的，只是它打开的那个窗口是坏掉的（无论我是否开启代理

**Comment by lss233** [comment]
你可以先更新到最新的 revChatGPT 试试。
如果实在不行，acheong08/ChatGPT#261 这里反馈一下吧
