### ISSUE TITLE
[BUG] 使用gocqhttp时机器人貌似不回复群聊消息

### ISSUE THREAD

**Issue by Apricityx** [lss233/chatgpt-mirai-qq-bot#371]
**提交 issue 前，请先确认：**
- [ ] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
私聊能回，bing和ChatGPT都正常，但群聊就不理我，群聊里试过prefix触发和at触发都无效，但使用命令.重新加载配置文件就能正常回复
**运行环境:**  
- 操作系统：Ubuntu
- Docker： ？
- 项目版本：v2.2.4

**复现步骤**  
群聊@机器人不回复

**预期行为**  
正常回复消息

**截图**  
![1](https://user-images.githubusercontent.com/78242039/225358912-240a25df-a231-4ebf-a134-f699bfc4d366.png)
*群聊中*

![2](https://user-images.githubusercontent.com/78242039/225358886-d55191ed-dbf6-4b11-87e1-54acfd197949.png)
*私聊中*

**Comment by lss233** [comment]
日志？配置文件？

**Comment by Apricityx** [comment]
> 日志？配置文件？
配置文件
[config.txt](https://github.com/lss233/chatgpt-mirai-qq-bot/files/10986694/config.txt)

**Comment by Apricityx** [comment]
> 日志？配置文件？

启动完后有这么一段报错，但我估摸着和这个问题没关系，配置文件前边发了，不知道有没有写错。
2023-03-17 16:53:32 W/stderr: Exception in thread "DefaultDispatcher-worker-1" java.net.ProtocolException: Expected HTTP 101 response but was '405 '
chatgpt-qq-mirai-1       | 2023-03-17 16:53:32 W/stderr:        at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
chatgpt-qq-mirai-1       | 2023-03-17 16:53:32 W/stderr:        at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
chatgpt-qq-mirai-1       | 2023-03-17 16:53:32 W/stderr:        at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
chatgpt-qq-mirai-1       | 2023-03-17 16:53:32 W/stderr:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
chatgpt-qq-mirai-1       | 2023-03-17 16:53:32 W/stderr:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
chatgpt-qq-mirai-1       | 2023-03-17 16:53:32 W/stderr:        at java.base/java.lang.Thread.run(Thread.java:833)
chatgpt-qq-mirai-1       | 2023-03-17 16:53:32 W/stderr:        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@25edcd83, Dispatchers.Default]

**Comment by Apricityx** [comment]
![Screenshot_20230318-010733.png](https://user-images.githubusercontent.com/78242039/225972151-c32f2e79-74d2-40a8-afee-2950913ba52d.png)

刚问了下，好像不止我一个人遇到了这样的问题。gocqhttp还蛮好用的，劳烦修复下这个问题。

**Comment by lss233** [comment]
你提供的那份日志，里面写着 mirai……  
我觉得应该不对吧？

**Comment by Apricityx** [comment]
> 你提供的那份日志，里面写着 mirai……  
> 我觉得应该不对吧？

正常启动后台会弹mirai吗?我这后台启动的时候会有mirai的消息，但连接的确实是gocqhttp。

我看后台一直跳W/reverse-ws adapter: [reverse-ws] Connection to chatgpt:8554/ interrupted. Trying reconnect in 5000 ms.
我就把onebot的反向连接端口改成8554了，ChatGPT的config也写的8554，是否和这个有关系?

**Comment by Apricityx** [comment]
docker里mirai没关，我把mirai的配置删了后后台不再弹关于mirai的消息，但是仍旧不回复群聊消息。顺便问下watchertower是用来干什么的，可不可以关掉?

**Comment by Apricityx** [comment]
concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！\n","stream":"stdout","time":"2023-03-18T02:52:07.352358132Z"}
{"log":"2023-03-18 02:52:07.352 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！\n","stream":"stdout","time":"2023-03-18T02:52:07.352449263Z"}
{"log":"2023-03-18 02:52:07.352 | DEBUG    | middlewares.timeout:create_timeout_task:12 - [Timeout] 开始计时……\n","stream":"stdout","time":"2023-03-18T02:52:07.352792417Z"}
{"log":"2023-03-18 02:52:07.352 | ERROR    | adapter.ms.bing:ask:64 - Cannot write to closing transport\n","stream":"stdout","time":"2023-03-18T02:52:07.366993794Z"}
{"log":"Traceback (most recent call last):\n","stream":"stdout","time":"2023-03-18T02:52:07.367019342Z"}
{"log":"\n","stream":"stdout","time":"2023-03-18T02:52:07.367023019Z"}
{"log":"  File \"/app/bot.py\", line 12, in \u003cmodule\u003e\n","stream":"stdout","time":"2023-03-18T02:52:07.367025774Z"}
{"log":"    import onebot_bot\n","stream":"stdout","time":"2023-03-18T02:52:07.367029331Z"}
{"log":"\n","stream":"stdout","time":"2023-03-18T02:52:07.367032226Z"}
{"log":"  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1178, in _find_and_load\n","stream":"stdout","time":"2023-03-18T02:52:07.367035012Z"}
{"log":"  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1149, in _find_and_load_unlocked\n","stream":"stdout","time":"2023-03-18T02:52:07.367038228Z"}
{"log":"  File \"\u003cfrozen importlib._bootstrap\u003e\", line 690, in _load_unlocked\n","stream":"stdout","time":"2023-03-18T02:52:07.367041303Z"}
{"log":"  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 940, in exec_module\n","stream":"stdout","time":"2023-03-18T02:52:07.367044339Z"}
{"log":"  File \"\u003cfrozen importlib._bootstrap\u003e\", line 241, in _call_with_frames_removed\n","stream":"stdout","time":"2023-03-18T02:52:07.367047475Z"}
{"log":"\n","stream":"stdout","time":"2023-03-18T02:52:07.367050591Z"}
{"log":"  File \"/app/onebot_bot.py\", line 184, in \u003cmodule\u003e\n","stream":"stdout","time":"2023-03-18T02:52:07.367053516Z"}
{"log":"    bot.run(host=config.onebot.reverse_ws_host, port=config.onebot.reverse_ws_port)\n","stream":"stdout","time":"2023-03-18T02:52:07.367056612Z"}
{"log":"    │   │        │      │      │                     │      │      └ 8554\n","stream":"stdout","time":"2023-03-18T02:52:07.367059588Z"}
{"log":"    │   │        │      │      │                     │      └ Onebot(qq=2182528859, manager_qq=3026194904, reverse_ws_host='0.0.0.0', reverse_ws_port=8554)\n","stream":"stdout","time":"2023-03-18T02:52:07.367063154Z"}
{"log":"    │   │        │      │      │                     └ \u003cunprintable Config object\u003e\n","stream":"stdout","time":"2023-03-18T02:52:07.36706647Z"}
{"log":"    │   │        │      │      └ '0.0.0.0'\n","stream":"stdout","time":"2023-03-18T02:52:07.367069747Z"}
{"log":"    │   │        │      └ Onebot(qq=2182528859, manager_qq=3026194904, reverse_ws_host='0.0.0.0', reverse_ws_port=8554)\n","stream":"stdout","time":"2023-03-18T02:52:07.367072742Z"}
{"log":"    │   │        └ \u003cunprintable Config object\u003e\n","stream":"stdout","time":"2023-03-18T02:52:07.367075868Z"}
{"log":"    │   └ \u003cfunction CQHttp.run at 0x7f7aa704bec0\u003e\n","stream":"stdout","time":"2023-03-18T02:52:07.367078964Z"}
{"log":"    └ \u003caiocqhttp.CQHttp object at 0x7f7ab41979d0\u003e\n","stream":"stdout","time":"2023-03-18T02:52:07.36708211Z"}
{"log":"\n","stream":"stdout","time":"2023-03-18T02:52:07.367085186Z"}
{"log":"  File \"/usr/local/lib/python3.11/site-packages/aiocqhttp/__init__.py\", line 222, in run\n","stream":"stdout","time":"2023-03-18T02:52:07.367088051Z"}
{"log":"    self._server_app.run(host=host, port=port, *args, **kwargs)\n","stream":"stdout","time":"2023-03-18T02:52:07.367091307Z"}
{"log":"    │    │           │        │          │      │       └ {'use_reloader': False}\n","stream":"stdout","time":"2023-03-18T02:52:07.367094373Z"}
{"log":"    │    │           │        │          │      └ ()\n","stream":"stdout","time":"2023-03-18T02:52:07.367097669Z"}
{"log":"    │    │           │        │          └ 8554\n","stream":"stdout","time":"2023-03-18T02:52:07.367100815Z"}
{"log":"    │    │           │        └ '0.0.0.0'\n","stream":"stdout","time":"2023-03-18T02:52:07.36710375Z"}
{"log":"    │    │           └ \u003cfunction Quart.run at 0x7f7aa7042480\u003e\n","stream":"stdout","time":"2023-03-18T02:52:07.367106786Z"}
{"log":"    │    └ \u003cQuart ''\u003e\n","stream":"stdout","time":"2023-03-18T02:52:07.367119871Z"}
{"log":"    └ \u003caiocqhttp.CQHttp object at 0x7f7ab41979d0\u003e\n","stream":"stdout","time":"2023-03-18T02:52:07.367123367Z"}
{"log":"  File \"/usr/local/lib/python3.11/site-packages/quart/app.py\", line 1423, in run\n","stream":"stdout","time":"2023-03-18T02:52:07.367126393Z"}
{"log":"    loop.run_until_complete(asyncio.gather(*tasks))\n","stream":"stdout","time":"2023-03-18T02:52:07.367130701Z"}
{"log":"    │    │

**Comment by KPotter0413** [comment]
我有遇到过类似的，我当时是启动顺序导致的问题，先启动这个qq bot然后再打开gocqhttp登录qq解决的
