### ISSUE TITLE
[BUG] ChatGPT 4.0 适配问题

### ISSUE THREAD

**Issue by jackjieYYY** [lss233/chatgpt-mirai-qq-bot#385]
**表现**  
在QQ聊天中经常遇到

![JO
18Z 8~}ULBPF3TXT(%4](https://user-images.githubusercontent.com/53422254/225878927-411c3c10-6b56-473b-8bf4-024a77d6ea70.png)

实际上通过网页的检查能发现该问题能被ChatGPT回答 请查看下面的截图

![8N6`1}{ DD1%RF@%X9TM Z3](https://user-images.githubusercontent.com/53422254/225879143-9bd56665-6d15-4fcf-998a-ef204b20fcc5.png)

**运行环境:**  
- 操作系统: Linux debian发行版
- Docker：no
- 项目版本: 7c33c0c

**其他内容**  
![PFO(VB60Q_OJM6DC%IZ194I](https://user-images.githubusercontent.com/53422254/225879946-87a732fb-71c4-4a31-818f-2f5b5d253da1.png)

**Comment by lss233** [comment]
需要提供日志。

**Comment by jackjieYYY** [comment]
> 需要提供日志。
```

[32m2023-03-17 12:15:02.672[0m | [31m[1mERROR   [0m | [36mconfig[0m:[36mscan_presets[0m:[36m291[0m - [31m[1m检查预设：正常 <==> presets/default.txt [失败：文件不存在][0m
[32m2023-03-17 12:15:02.672[0m | [32m[1mSUCCESS [0m | [36mconfig[0m:[36mscan_presets[0m:[36m289[0m - [32m[1m检查预设：猫娘 <==> presets/catgirl.txt [成功][0m
[32m2023-03-17 12:15:02.672[0m | [32m[1mSUCCESS [0m | [36mconfig[0m:[36mscan_presets[0m:[36m302[0m - [32m[1m注册预设：catgirl <==> ./presets/catgirl.txt [成功][0m
[32m2023-03-17 12:15:02.673[0m | [32m[1mSUCCESS [0m | [36mconfig[0m:[36mscan_presets[0m:[36m302[0m - [32m[1m注册预设：预设模板 <==> ./presets/预设模板.txt [成功][0m
[32m2023-03-17 12:15:02.673[0m | [1mINFO    [0m | [36m__main__[0m:[36m<module>[0m:[36m16[0m - [1m检测到 mirai 配置，将以 mirai 模式启动……[0m
[32m2023-03-17 12:15:02.840[0m | [31m[1mERROR   [0m | [36mutils.text_to_img[0m:[36m<module>[0m:[36m49[0m - [31m[1m未检测到 wkhtmltoimage，无法进行 Markdown 渲染！[0m
[32m2023-03-17 12:15:02.862[0m | [1mINFO    [0m | [36mlaunart.manager[0m:[36mlaunch_blocking[0m:[36m479[0m - [1mStarting launart main task...[0m
[32m2023-03-17 12:15:02.862[0m | [1mINFO    [0m | [36mlaunart.manager[0m:[36mlaunch[0m:[36m331[0m - [1mLaunching 5 components as async task...[0m
[32m2023-03-17 12:15:02.911[0m | [1mINFO    [0m | [36mgraia.ariadne.service[0m:[36mbase_telemetry[0m:[36m108[0m - [1m[36m
    _         _           _
   / \   _ __(_) __ _  __| |_ __   ___
  / _ \ | '__| |/ _` |/ _` | '_ \ / _ \
 / ___ \| |  | | (_| | (_| | | | |  __/
/_/   \_\_|  |_|\__,_|\__,_|_| |_|\___|[0m[1m

[35mgraia-amnesia[0m[1m: [32m0.7.1[0m[1m
[35mgraia-ariadne[0m[1m: [32m0.11.1[0m[1m
[35mgraia-broadcast[0m[1m: [32m0.19.2[0m[1m
[35mlaunart[0m[1m: [32m0.6.3[0m[1m
[35mstatv[0m[1m: [32m0.3.2[0m[1m[0m
[32m2023-03-17 12:15:02.911[0m | [32m[1mSUCCESS [0m | [36mlaunart.manager[0m:[36mlaunch[0m:[36m384[0m - [32m[1mLayer #1:[cache.client/memcache, http.client/aiohttp] preparation completed.[0m
[32m2023-03-17 12:15:02.912[0m | [1mINFO    [0m | [36mariadne_bot[0m:[36mstart_background[0m:[36m129[0m - [1mOpenAI 服务器登录中……[0m
[32m2023-03-17 12:15:02.912[0m | [1mINFO    [0m | [36mmanager.bot[0m:[36mlogin_bing[0m:[36m95[0m - [1m正在解析第 1 个 Bing 账号[0m
[32m2023-03-17 12:15:02.912[0m | [32m[1mSUCCESS [0m | [36mmanager.bot[0m:[36mlogin_bing[0m:[36m99[0m - [32m[1m解析成功！[0m
[32m2023-03-17 12:15:02.912[0m | [32m[1mSUCCESS [0m | [36mmanager.bot[0m:[36mlogin_bing[0m:[36m105[0m - [32m[1m成功解析 1/1 个 Bing 账号！[0m
[32m2023-03-17 12:15:02.912[0m | [1mINFO    [0m | [36mmanager.bot[0m:[36mlogin_openai[0m:[36m110[0m - [1m正在登录第 1 个 OpenAI 账号[0m
[32m2023-03-17 12:15:02.912[0m | [1mINFO    [0m | [36mmanager.bot[0m:[36m__login_V1[0m:[36m202[0m - [1m模式：无浏览器登录[0m
[32m2023-03-17 12:15:02.913[0m | [1mINFO    [0m | [36mmanager.bot[0m:[36m__login_V1[0m:[36m224[0m - [1m尝试使用 access_token 登录中...[0m
[32m2023-03-17 12:15:03.592[0m | [32m[1mSUCCESS [0m | [36mmanager.bot[0m:[36mlogin_openai[0m:[36m125[0m - [32m[1m登录成功！[0m
[32m2023-03-17 12:15:03.592[0m | [32m[1mSUCCESS [0m | [36mmanager.bot[0m:[36mlogin_openai[0m:[36m144[0m - [32m[1m成功登录 1/1 个 OpenAI 账号！[0m
[32m2023-03-17 12:15:03.593[0m | [1mINFO    [0m | [36mmanager.bot[0m:[36mlogin[0m:[36m81[0m - [1mAI 类型：chatgpt-web - 可用账号： 1 个[0m
[32m2023-03-17 12:15:03.593[0m | [1mINFO    [0m | [36mmanager.bot[0m:[36mlogin[0m:[36m81[0m - [1mAI 类型：openai-api - 可用账号： 0 个[0m
[32m2023-03-17 12:15:03.593[0m | [1mINFO    [0m | [36mmanager.bot[0m:[36mlogin[0m:[36m81[0m - [1mAI 类型：bing-cookie - 可用账号： 1 个[0m
[32m2023-03-17 12:15:03.593[0m | [1mINFO    [0m | [36mariadne_bot[0m:[36mstart_background[0m:[36m134[0m - [1mOpenAI 服务器登录成功[0m
[32m2023-03-17 12:15:03.593[0m | [1mINFO    [0m | [36mariadne_bot[0m:[36mstart_background[0m:[36m135[0m - [1m尝试从 Mirai 服务中读取机器人 QQ 的 session key……[0m
[32m2023-03-17 12:15:03.593[0m | [1mINFO    [0m | [36mariadne_bot[0m:[36mstart_background[0m:[36m141[0m - [1m[提示] 当前为正向 ws + http 模式，请确保你的 mirai api http 设置了正确的 ws 和 http 配置[0m
[32m2023-03-17 12:15:03.593[0m | [1mINFO    [0m | [36mariadne_bot[0m:[36mstart_background[0m:[36m142[0m - [1m[提示] 配置不正确或 Miria 未登录 QQ 都会导致 【Websocket reconnecting...】 提示的出现。[0m
[32m2023-03-17 12:15:03.593[0m | [32m[1mSUCCESS [0m | [36mlaunart.manager[0m:[36mlaunch[0m:[36m384[0m - [32m[1mLayer #3:[elizabeth.service] preparation completed.[0m
[32m2023-03-17 12:15:03.593[0m | [1mINFO    [0m | [36mlaunart.manager[0m:[36mlaunch[0m:[36m389[0m - [1mAll components prepared, start blocking phase.[0m
[32m2023-03-17 12:15:03.597[0m | [32m[1mSUCCESS [0m | [36mgraia.ariadne.connection.ws[0m:[36m_[0m:[36m62[0m - [32m[1mSuccessfully got session key[0m
[32m2023-03-17 12:15:53.291[0m | [1mINFO    [0m | [36mgraia.ariadne.model[0m:[36mlog[0m:[36m82[0m - [1m: [RECV][🐲🔥复仇者高铁动车群()] GK() -> @ 电影中的一镜到底是什么回事[0m
[32m2023-03-17 12:15:53.292[0m | [34m[1mDEBUG   [0m | [36mmiddlewares.concurrentlock[0m:[36mhandle_request[0m:[36m25[0m - [34m[1m[Concurrent] 使用 Adapter 内部的 Queue[0m
[32m2023-03-17 12:15:53.292[0m | [34m[1mDEBUG   [0m | [36mmiddlewares.concurrentlock[0m:[36mhandle_request[0m:[36m27[0m - [34m[1m[Concurrent] 排队中，前面还有 0 个人！[0m
[32m2023-03-17 12:15:53.292[0m | [34m[1mDEBUG   [0m | [36mmiddlewares.concurrentlock[0m:[36mhandle_request[0m:[36m40[0m - [34m[1m[Concurrent] 排队中，前面还有 0 个人！[0m
[32m2023-03-17 12:15:53.292[0m | [34m[1mDEBUG   [0m | [36mmiddlewares.concurrentlock[0m:[36mhandle_request[0m:[36m42[0m - [34m[1m[Concurrent] 排到了！[0m
[32m2023-03-17 12:15:53.293[0m | [34m[1mDEBUG   [0m | [36mmiddlewares.timeout[0m:[36mcreate_timeout_task[0m:[36m12[0m - [34m[1m[Timeout] 开始计时……[0m
[32m2023-03-17 12:16:23.994[0m | [1mINFO    [0m | [36mgraia.ariadne.model[0m:[36mlog[0m:[36m82[0m - [1m: [SEND][🐲🔥复仇者高铁动车群()] <- 我还在思考中，请再等一下~[0m
[32m2023-03-17 12:16:23.995[0m | [34m[1mDEBUG   [0m | [36mmiddlewares.timeout[0m:[36mon_respond[0m:[36m38[0m - [34m[1m[Timeout] 取消计时……[0m
[32m2023-03-17 12:16:23.995[0m | [34m[1mDEBUG   [0m | [36mmiddlewares.timeout[0m:[36mcreate_timeout_task[0m:[36m15[0m - [34m[1m[Timeout] 等待过久，发送提示[0m
--- Logging error ---
[32m2023-03-17 12:17:54.499[0m | [31m[1mERROR   [0m | [36mgraia.ariadne.util[0m:[36mloguru_exc_callback[0m:[36m76[0m - [31m[1mException:[0m
[33m[1mTraceback (most recent call last):[0m

  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0xffffba9659d0>
    └ <Thread(asyncio_0, started 281472856535520)>
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0xffffba965700>
    └ <Thread(asyncio_0, started 281472856535520)>
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(asyncio_0, started 281472856535520)>
    │    │        │    └ (<weakref at 0xffff81a289a0; to 'ThreadPoolExecutor' at 0xffff81a321c0>, <_queue.SimpleQueue object at 0xffff81a283b0>, None,...
    │    │        └ <Thread(asyncio_0, started 281472856535520)>
    │    └ <function _worker at 0xffff8268e940>
    └ <Thread(asyncio_0, started 281472856535520)>
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0xffff8268ea60>
    └ <concurrent.futures.thread._WorkItem object at 0xffff81a323a0>
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0xffff81a323a0>
             │    │   │    └ (<janus._SyncQueueProxy object at 0xffff81a32100>, '电影中的一镜到底是什么回事')
             │    │   └ <concurrent.futures.thread._WorkItem object at 0xffff81a323a0>
             │    └ <bound method ChatGPTWebAdapter.ask_sync of <adapter.chatgpt.web.ChatGPTWebAdapter object at 0xffff81b2c790>>
             └ <concurrent.futures.thread._WorkItem object at 0xffff81a323a0>

  File "[32m/root/qqbot/chatgpt-mirai-qq-bot/adapter/chatgpt/[0m[32m[1mweb.py[0m", line [33m54[0m, in [35mask_sync[0m
    [35m[1mfor[0m [1mresp[0m [35m[1min[0m [1mself[0m[35m[1m.[0m[1mbot[0m[35m[1m.[0m[1mask[0m[1m([0m[1mprompt[0m[1m,[0m [1mself[0m[35m[1m.[0m[1mconversation_id[0m[1m,[0m [1mself[0m[35m[1m.[0m[1mparent_id[0m[1m)[0m[1m:[0m
    [36m    │       │    │   │   │       │    │                │    └ [0m[36m[1m'352bb715-caf4-427b-a541-a062fb7d80e2'[0m
    [36m    │       │    │   │   │       │    │                └ [0m[36m[1m<adapter.chatgpt.web.ChatGPTWebAdapter object at 0xffff81b2c790>[0m
    [36m    │       │    │   │   │       │    └ [0m[36m[1m'f9a3a0df-519e-4d40-85c3-dd3bcd41ffe6'[0m
    [36m    │       │    │   │   │       └ [0m[36m[1m<adapter.chatgpt.web.ChatGPTWebAdapter object at 0xffff81b2c790>[0m
    [36m    │       │    │   │   └ [0m[36m[1m'电影中的一镜到底是什么回事'[0m
    [36m    │       │    │   └ [0m[36m[1m<function ChatGPTBrowserChatbot.ask at 0xffffb4082670>[0m
    [36m    │       │    └ [0m[36m[1m<chatbot.chatgpt.ChatGPTBrowserChatbot object at 0xffff81bba790 [unlocked]>[0m
    [36m    │       └ [0m[36m[1m<adapter.chatgpt.web.ChatGPTWebAdapter object at 0xffff81b2c790>[0m
    [36m    └ [0m[36m[1m{'message': '一镜到底（One-shot，也被称为长镜头、长跟踪镜头或长时间不剪辑镜头）是电影和电视制作中的一种拍摄技巧。在这种技巧中，导演和摄影指导在一个连续的、不间断的镜头中捕捉整个场景或者一部分场景。这意味着镜头在整个拍摄过程中没有...[0m

  File "[32m/root/qqbot/chatgpt-mirai-qq-bot/chatbot/[0m[32m[1mchatgpt.py[0m", line [33m66[0m, in [35mask[0m
    [35m[1mfor[0m [1mr[0m [35m[1min[0m [1mresp[0m[1m:[0m
    [36m    │    └ [0m[36m[1m<generator object Chatbot.ask at 0xffff81a1e4a0>[0m
    [36m    └ [0m[36m[1m{'message': '一镜到底（One-shot，也被称为长镜头、长跟踪镜头或长时间不剪辑镜头）是电影和电视制作中的一种拍摄技巧。在这种技巧中，导演和摄影指导在一个连续的、不间断的镜头中捕捉整个场景或者一部分场景。这意味着镜头在整个拍摄过程中没有...[0m

  File "[32m/usr/local/lib/python3.9/dist-packages/revChatGPT/[0m[32m[1mV1.py[0m", line [33m554[0m, in [35mask[0m
    [1mlog[0m[35m[1m.[0m[1merror[0m[1m([0m[36m"Field missing"[0m[1m,[0m [1mexc_info[0m[35m[1m=[0m[36m[1mTrue[0m[1m)[0m
    [36m│   └ [0m[36m[1m<function Logger.error at 0xffffba9751f0>[0m
    [36m└ [0m[36m[1m<Logger revChatGPT.V1 (ERROR)>[0m

  File "/usr/lib/python3.9/logging/__init__.py", line 1471, in error
    self._log(ERROR, msg, args, **kwargs)
    │    │    │      │    │       └ {'exc_info': True}
    │    │    │      │    └ ()
    │    │    │      └ 'Field missing'
    │    │    └ 40
    │    └ <function Logger._log at 0xffffba975550>
    └ <Logger revChatGPT.V1 (ERROR)>
  File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
    │    │      └ <LogRecord: revChatGPT.V1, 40, /usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py, 554, "Field missing">
    │    └ <function Logger.handle at 0xffffba9755e0>
    └ <Logger revChatGPT.V1 (ERROR)>
  File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
    │    │            └ <LogRecord: revChatGPT.V1, 40, /usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py, 554, "Field missing">
    │    └ <function Logger.callHandlers at 0xffffba975820>
    └ <Logger revChatGPT.V1 (ERROR)>
  File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
    │    │      └ <LogRecord: revChatGPT.V1, 40, /usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py, 554, "Field missing">
    │    └ <function Handler.handle at 0xffffba971ca0>
    └ <StreamHandler <stderr> (NOTSET)>
  File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
    │    │    └ <LogRecord: revChatGPT.V1, 40, /usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py, 554, "Field missing">
    │    └ <function StreamHandler.emit at 0xffffba972160>
    └ <StreamHandler <stderr> (NOTSET)>
> File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
          │    │      └ <LogRecord: revChatGPT.V1, 40, /usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py, 554, "Field missing">
          │    └ <function Handler.format at 0xffffba971b80>
          └ <StreamHandler <stderr> (NOTSET)>
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
           │   │      └ <LogRecord: revChatGPT.V1, 40, /usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py, 554, "Field missing">
           │   └ <function Formatter.format at 0xffffba9d7ee0>
           └ <logging.Formatter object at 0xffffb8e4cc70>
  File "/usr/lib/python3.9/logging/__init__.py", line 667, in format
    record.exc_text = self.formatException(record.exc_info)
    │      │          │    │               │      └ (None, None, None)
    │      │          │    │               └ <LogRecord: revChatGPT.V1, 40, /usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py, 554, "Field missing">
    │      │          │    └ <function Formatter.formatException at 0xffffba9d7ca0>
    │      │          └ <logging.Formatter object at 0xffffb8e4cc70>
    │      └ None
    └ <LogRecord: revChatGPT.V1, 40, /usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py, 554, "Field missing">
  File "/usr/lib/python3.9/logging/__init__.py", line 617, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
    │         │               │      │      │         └ <_io.StringIO object at 0xffff81a49ca0>
    │         │               │      │      └ None
    │         │               │      └ (None, None, None)
    │         │               └ (None, None, None)
    │         └ <function loguru_exc_callback at 0xffff82f38b80>
    └ <module 'traceback' from '/usr/lib/python3.9/traceback.py'>

  File "[32m/usr/local/lib/python3.9/dist-packages/graia/ariadne/util/[0m[32m[1m__init__.py[0m", line [33m75[0m, in [35mloguru_exc_callback[0m
    [35m[1mif[0m [35m[1mnot[0m [1missubclass[0m[1m([0m[1mcls[0m[1m,[0m [1m([0m[1mExecutionStop[0m[1m,[0m [1mPropagationCancelled[0m[1m)[0m[1m)[0m[1m:[0m
    [36m                  │     │              └ [0m[36m[1m<class 'graia.broadcast.exceptions.PropagationCancelled'>[0m
    [36m                  │     └ [0m[36m[1m<class 'graia.broadcast.exceptions.ExecutionStop'>[0m
    [36m                  └ [0m[36m[1mNone[0m

[31m[1mTypeError[0m:[1m issubclass() arg 1 must be a class[0m
Call stack:
  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/qqbot/chatgpt-mirai-qq-bot/adapter/chatgpt/web.py", line 54, in ask_sync
    for resp in self.bot.ask(prompt, self.conversation_id, self.parent_id):
  File "/root/qqbot/chatgpt-mirai-qq-bot/chatbot/chatgpt.py", line 66, in ask
    for r in resp:
  File "/usr/local/lib/python3.9/dist-packages/revChatGPT/V1.py", line 554, in ask
    log.error("Field missing", exc_info=True)
Message: 'Field missing'
Arguments: ()
ERROR:revChatGPT.V1:
[32m2023-03-17 12:17:54.506[0m | [31m[1mERROR   [0m | [36muniversal[0m:[36mrequest[0m:[36m154[0m - [31m[1mask: {'message': None, 'conversation_id': 'f9a3a0df-519e-4d40-85c3-dd3bcd41ffe6', 'error': 'Error in message stream'} (code: 1)[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m/root/qqbot/chatgpt-mirai-qq-bot/[0m[32m[1mbot.py[0m", line [33m17[0m, in [35m<module>[0m
    [35m[1mimport[0m [1mariadne_bot[0m

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "[32m/root/qqbot/chatgpt-mirai-qq-bot/[0m[32m[1mariadne_bot.py[0m", line [33m199[0m, in [35m<module>[0m
    [1mapp[0m[35m[1m.[0m[1mlaunch_blocking[0m[1m([0m[1m)[0m
    [36m│   └ [0m[36m[1m<classmethod object at 0xffff82c27c10>[0m
    [36m└ [0m[36m[1m<graia.ariadne.app.Ariadne object at 0xffff82fcb8b0>[0m

  File "[32m/usr/local/lib/python3.9/dist-packages/graia/ariadne/[0m[32m[1mapp.py[0m", line [33m312[0m, in [35mlaunch_blocking[0m
    [1mcls[0m[35m[1m.[0m[1mlaunch_manager[0m[35m[1m.[0m[1mlaunch_blocking[0m[1m([0m[1mloop[0m[35m[1m=[0m[1mcls[0m[35m[1m.[0m[1mservice[0m[35m[1m.[0m[1mloop[0m[1m,[0m [1mstop_signal[0m[35m[1m=[0m[1mstop_signals[0m[1m)[0m
    [36m│   │              │                    │   │       │                 └ [0m[36m[1m(<Signals.SIGINT: 2>,)[0m
    [36m│   │              │                    │   │       └ [0m[36m[1m<property object at 0xffff82c34090>[0m
    [36m│   │              │                    │   └ [0m[36m[1m<graia.ariadne.service.ElizabethService object at 0xffff82fcb8e0>[0m
    [36m│   │              │                    └ [0m[36m[1m<class 'graia.ariadne.app.Ariadne'>[0m
    [36m│   │              └ [0m[36m[1m<function Launart.launch_blocking at 0xffff82f66310>[0m
    [36m│   └ [0m[36m[1m<launart.manager.Launart object at 0xffff81bf2940>[0m
    [36m└ [0m[36m[1m<class 'graia.ariadne.app.Ariadne'>[0m

  File "[32m/usr/local/lib/python3.9/dist-packages/launart/[0m[32m[1mmanager.py[0m", line [33m494[0m, in [35mlaunch_blocking[0m
    [1mloop[0m[35m[1m.[0m[1mrun_until_complete[0m[1m([0m[1mlaunch_task[0m[1m)[0m
    [36m│    │                  └ [0m[36m[1m<Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.9/dist-packages/launart/manager....[0m
    [36m│    └ [0m[36m[1m<function BaseEventLoop.run_until_complete at 0xffffba35b820>[0m
    [36m└ [0m[36m[1m<_UnixSelectorEventLoop running=True closed=False debug=False>[0m

  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0xffffba35b790>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0xffffba35e310>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0xffffba3ec280>
    └ <Handle <TaskWakeupMethWrapper object at 0xffff81a44fd0>(<Future finished result=False>)>
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0xffff81a44fd0>(<Future finished result=False>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0xffff81a44fd0>(<Future finished result=False>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0xffff81a44fd0>(<Future finished result=False>)>

> File "[32m/root/qqbot/chatgpt-mirai-qq-bot/[0m[32m[1muniversal.py[0m", line [33m121[0m, in [35mrequest[0m
    [35m[1masync[0m [35m[1mfor[0m [1mrendered[0m [35m[1min[0m [1mtask[0m[1m:[0m
    [36m          │           └ [0m[36m[1m<async_generator object ConversationContext.ask at 0xffff81a31040>[0m
    [36m          └ [0m[36m[1mNone[0m

  File "[32m/root/qqbot/chatgpt-mirai-qq-bot/[0m[32m[1mconversation.py[0m", line [33m85[0m, in [35mask[0m
    [35m[1masync[0m [35m[1mfor[0m [1mitem[0m [35m[1min[0m [1mself[0m[35m[1m.[0m[1madapter[0m[35m[1m.[0m[1mask[0m[1m([0m[1mprompt[0m[1m)[0m[1m:[0m
    [36m          │       │    │       │   └ [0m[36m[1m'电影中的一镜到底是什么回事'[0m
    [36m          │       │    │       └ [0m[36m[1m<function ChatGPTWebAdapter.ask at 0xffff8254c9d0>[0m
    [36m          │       │    └ [0m[36m[1m<adapter.chatgpt.web.ChatGPTWebAdapter object at 0xffff81b2c790>[0m
    [36m          │       └ [0m[36m[1m<conversation.ConversationContext object at 0xffff81b2c7f0>[0m
    [36m          └ [0m[36m[1m'一镜到底（One-shot，也被称为长镜头、长跟踪镜头或长时间不剪辑镜头）是电影和电视制作中的一种拍摄技巧。在这种技巧中，导演和摄影指导在一个连续的、不间断的镜头中捕捉整个场景或者一部分场景。这意味着镜头在整个拍摄过程中没有剪辑，让观众感受到一种连...[0m

  File "[32m/root/qqbot/chatgpt-mirai-qq-bot/adapter/chatgpt/[0m[32m[1mweb.py[0m", line [33m115[0m, in [35mask[0m
    [35m[1mraise[0m [1me[0m

  File "[32m/root/qqbot/chatgpt-mirai-qq-bot/adapter/chatgpt/[0m[32m[1mweb.py[0m", line [33m72[0m, in [35mask[0m
    [35m[1mraise[0m [1mresp[0m
    [36m      └ [0m[36m[1mask: {'message': None, 'conversation_id': 'f9a3a0df-519e-4d40-85c3-dd3bcd41ffe6', 'error': 'Error in message stream'} (code: 1)[0m

  File "[32m/root/qqbot/chatgpt-mirai-qq-bot/adapter/chatgpt/[0m[32m[1mweb.py[0m", line [33m54[0m, in [35mask_sync[0m
    [35m[1mfor[0m [1mresp[0m [35m[1min[0m [1mself[0m[35m[1m.[0m[1mbot[0m[35m[1m.[0m[1mask[0m[1m([0m[1mprompt[0m[1m,[0m [1mself[0m[35m[1m.[0m[1mconversation_id[0m[1m,[0m [1mself[0m[35m[1m.[0m[1mparent_id[0m[1m)[0m[1m:[0m
    [36m    │       │    │   │   │       │    │                │    └ [0m[36m[1m'352bb715-caf4-427b-a541-a062fb7d80e2'[0m
    [36m    │       │    │   │   │       │    │                └ [0m[36m[1m<adapter.chatgpt.web.ChatGPTWebAdapter object at 0xffff81b2c790>[0m
    [36m    │       │    │   │   │       │    └ [0m[36m[1m'f9a3a0df-519e-4d40-85c3-dd3bcd41ffe6'[0m
    [36m    │       │    │   │   │       └ [0m[36m[1m<adapter.chatgpt.web.ChatGPTWebAdapter object at 0xffff81b2c790>[0m
    [36m    │       │    │   │   └ [0m[36m[1m'电影中的一镜到底是什么回事'[0m
    [36m    │       │    │   └ [0m[36m[1m<function ChatGPTBrowserChatbot.ask at 0xffffb4082670>[0m
    [36m    │       │    └ [0m[36m[1m<chatbot.chatgpt.ChatGPTBrowserChatbot object at 0xffff81bba790 [unlocked]>[0m
    [36m    │       └ [0m[36m[1m<adapter.chatgpt.web.ChatGPTWebAdapter object at 0xffff81b2c790>[0m
    [36m    └ [0m[36m[1m{'message': '一镜到底（One-shot，也被称为长镜头、长跟踪镜头或长时间不剪辑镜头）是电影和电视制作中的一种拍摄技巧。在这种技巧中，导演和摄影指导在一个连续的、不间断的镜头中捕捉整个场景或者一部分场景。这意味着镜头在整个拍摄过程中没有...[0m

  File "[32m/root/qqbot/chatgpt-mirai-qq-bot/chatbot/[0m[32m[1mchatgpt.py[0m", line [33m66[0m, in [35mask[0m
    [35m[1mfor[0m [1mr[0m [35m[1min[0m [1mresp[0m[1m:[0m
    [36m    │    └ [0m[36m[1m<generator object Chatbot.ask at 0xffff81a1e4a0>[0m
    [36m    └ [0m[36m[1m{'message': '一镜到底（One-shot，也被称为长镜头、长跟踪镜头或长时间不剪辑镜头）是电影和电视制作中的一种拍摄技巧。在这种技巧中，导演和摄影指导在一个连续的、不间断的镜头中捕捉整个场景或者一部分场景。这意味着镜头在整个拍摄过程中没有...[0m

  File "[32m/usr/local/lib/python3.9/dist-packages/revChatGPT/[0m[32m[1mV1.py[0m", line [33m574[0m, in [35mask[0m
    [35m[1mraise[0m [1mError[0m[1m([0m
    [36m      └ [0m[36m[1m<class 'revChatGPT.V1.Error'>[0m

[31m[1mrevChatGPT.V1.Error[0m:[1m ask: {'message': None, 'conversation_id': 'f9a3a0df-519e-4d40-85c3-dd3bcd41ffe6', 'error': 'Error in message stream'} (code: 1)[0m
[32m2023-03-17 12:17:55.282[0m | [1mINFO    [0m | [36mgraia.ariadne.model[0m:[36mlog[0m:[36m82[0m - [1m: [SEND][🐲🔥复仇者高铁动车群()] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。[0m

```

**Comment by lss233** [comment]
暂时没法复现这个问题，关注下

**Comment by Aite2** [comment]
gpt4.0一样的问题

**Comment by xiaobaozi233** [comment]
同碰到这个问题了，而看来gpt回答到一半断了
