### ISSUE TITLE
Incorrect response from OpenAI API

### ISSUE THREAD

**Issue by songrise** [lss233/chatgpt-mirai-qq-bot#39]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/54588043/207045576-ffa17f5f-48e0-46b2-bb54-9b2e40127a9d.png">

**Comment by songrise** [comment]
> 

一直出现

**Comment by lss233** [comment]
可以更新一下最新的代码试试看 有没有输出错误的详细信息

**Comment by songrise** [comment]
`2022-12-12 20:45:10.104 | ERROR    | __main__:handle_message:65 - Not a JSON response
Traceback (most recent call last):

  File "/Applications/anaconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 201, in __get_chat_text
    response = response.text.splitlines()[-4]
               │        └ <property object at 0x7fe73041ed10>
               └ <Response [429 Too Many Requests]>

IndexError: list index out of range


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Applications/anaconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 208, in __get_chat_text
    if resp['detail']['code'] == "invalid_api_key" or resp['detail']['code'] == "token_expired":
       │                                              └ {'detail': 'Too many requests, please slow down'}
       └ {'detail': 'Too many requests, please slow down'}

TypeError: string indices must be integers


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/songrise/Downloads/mirai-chatgpt-setup/chatgpt-mirai-qq-bot/bot.py", line 94, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x7fe7303d3df0>
    └ <graia.ariadne.app.Ariadne object at 0x7fe7305b6d00>

  File "/Applications/anaconda3/lib/python3.9/site-packages/graia/ariadne/app.py", line 298, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x7fe7303d9bd0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7fe728058a00>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x7fe72815c3a0>
    │   └ <launart.manager.Launart object at 0x7fe7282adeb0>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "/Applications/anaconda3/lib/python3.9/site-packages/launart/manager.py", line 461, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /Applications/anaconda3/lib/python3.9/site-packages/lau...
    │    └ <function BaseEventLoop.run_until_complete at 0x7fe74838c790>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Applications/anaconda3/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fe74838c700>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Applications/anaconda3/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fe74838e280>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Applications/anaconda3/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fe748329af0>
    └ <Handle <TaskStepMethWrapper object at 0x7fe748f58640>()>
  File "/Applications/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fe748f58640>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7fe748f58640>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7fe748f58640>()>
  File "/Applications/anaconda3/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {'group': Group(id=949427226, name='和谐⑨人组', account_perm=<普通成员>), 'source': Source(id=85758, time=datetime.datetime(2022, 12,...
                   │                └ <function group_message_listener at 0x7fe748f06160>
                   └ <function run_always_await at 0x7fe7482b2700>
  File "/Applications/anaconda3/lib/python3.9/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object group_message_listener at 0x7fe748f4a840>

  File "/Users/songrise/Downloads/mirai-chatgpt-setup/chatgpt-mirai-qq-bot/bot.py", line 86, in group_message_listener
    response = await handle_message(f"group-{group.id}", chain.display, task)
                     │                                   │     │        └ <Task pending name='Task-48' coro=<send_task() running at /Users/songrise/Downloads/mirai-chatgpt-setup/chatgpt-mirai-qq-bot/...
                     │                                   │     └ <property object at 0x7fe72817fc20>
                     │                                   └ MessageChain([Plain(text='你复活啦')])
                     └ <function handle_message at 0x7fe748efbee0>

> File "/Users/songrise/Downloads/mirai-chatgpt-setup/chatgpt-mirai-qq-bot/bot.py", line 58, in handle_message
    resp = await session.get_chat_response(message)
                 │       │                 └ '你复活啦'
                 │       └ <function ChatSession.get_chat_response at 0x7fe748edd9d0>
                 └ <chatbot.ChatSession object at 0x7fe7283aa280>

  File "/Applications/anaconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 258, in get_chat_response
    return await self.__get_chat_text(data)
                 │                    └ {'action': 'next', 'messages': [{'id': 'ed1ff1cf-e998-444e-8b5c-e7839e35f7bc', 'role': 'user', 'content': {'content_type': 't...
                 └ <revChatGPT.revChatGPT.AsyncChatbot object at 0x7fe748b92fd0>
  File "/Applications/anaconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 212, in __get_chat_text
    raise Exception("Not a JSON response") from exc2

Exception: Not a JSON response
2022-12-12 20:45:10.513 | INFO     | graia.ariadne.model:log:83 - 2787760211: [SEND][和谐⑨人组(949427226)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nNot a JSON response
`

**Comment by songrise** [comment]
···
2022-12-12 20:45:10.104 | ERROR    | __main__:handle_message:65 - Not a JSON response
Traceback (most recent call last):

  File "/Applications/anaconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 201, in __get_chat_text
    response = response.text.splitlines()[-4]
               │        └ <property object at 0x7fe73041ed10>
               └ <Response [429 Too Many Requests]>

IndexError: list index out of range


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Applications/anaconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 208, in __get_chat_text
    if resp['detail']['code'] == "invalid_api_key" or resp['detail']['code'] == "token_expired":
       │                                              └ {'detail': 'Too many requests, please slow down'}
       └ {'detail': 'Too many requests, please slow down'}

TypeError: string indices must be integers


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/songrise/Downloads/mirai-chatgpt-setup/chatgpt-mirai-qq-bot/bot.py", line 94, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x7fe7303d3df0>
    └ <graia.ariadne.app.Ariadne object at 0x7fe7305b6d00>

  File "/Applications/anaconda3/lib/python3.9/site-packages/graia/ariadne/app.py", line 298, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x7fe7303d9bd0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7fe728058a00>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x7fe72815c3a0>
    │   └ <launart.manager.Launart object at 0x7fe7282adeb0>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "/Applications/anaconda3/lib/python3.9/site-packages/launart/manager.py", line 461, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /Applications/anaconda3/lib/python3.9/site-packages/lau...
    │    └ <function BaseEventLoop.run_until_complete at 0x7fe74838c790>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Applications/anaconda3/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fe74838c700>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Applications/anaconda3/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fe74838e280>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Applications/anaconda3/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fe748329af0>
    └ <Handle <TaskStepMethWrapper object at 0x7fe748f58640>()>
  File "/Applications/anaconda3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fe748f58640>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7fe748f58640>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7fe748f58640>()>
  File "/Applications/anaconda3/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {'group': Group(id=949427226, name='和谐⑨人组', account_perm=<普通成员>), 'source': Source(id=85758, time=datetime.datetime(2022, 12,...
                   │                └ <function group_message_listener at 0x7fe748f06160>
                   └ <function run_always_await at 0x7fe7482b2700>
  File "/Applications/anaconda3/lib/python3.9/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object group_message_listener at 0x7fe748f4a840>

  File "/Users/songrise/Downloads/mirai-chatgpt-setup/chatgpt-mirai-qq-bot/bot.py", line 86, in group_message_listener
    response = await handle_message(f"group-{group.id}", chain.display, task)
                     │                                   │     │        └ <Task pending name='Task-48' coro=<send_task() running at /Users/songrise/Downloads/mirai-chatgpt-setup/chatgpt-mirai-qq-bot/...
                     │                                   │     └ <property object at 0x7fe72817fc20>
                     │                                   └ MessageChain([Plain(text='你复活啦')])
                     └ <function handle_message at 0x7fe748efbee0>

> File "/Users/songrise/Downloads/mirai-chatgpt-setup/chatgpt-mirai-qq-bot/bot.py", line 58, in handle_message
    resp = await session.get_chat_response(message)
                 │       │                 └ '你复活啦'
                 │       └ <function ChatSession.get_chat_response at 0x7fe748edd9d0>
                 └ <chatbot.ChatSession object at 0x7fe7283aa280>

  File "/Applications/anaconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 258, in get_chat_response
    return await self.__get_chat_text(data)
                 │                    └ {'action': 'next', 'messages': [{'id': 'ed1ff1cf-e998-444e-8b5c-e7839e35f7bc', 'role': 'user', 'content': {'content_type': 't...
                 └ <revChatGPT.revChatGPT.AsyncChatbot object at 0x7fe748b92fd0>
  File "/Applications/anaconda3/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 212, in __get_chat_text
    raise Exception("Not a JSON response") from exc2

Exception: Not a JSON response
2022-12-12 20:45:10.513 | INFO     | graia.ariadne.model:log:83 - 2787760211: [SEND][xxxxx)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nNot a JSON response

···

**Comment by songrise** [comment]
> 

更新最新的code [8a40feb](https://github.com/lss233/chatgpt-mirai-qq-bot/commit/8a40feb83131d2dd26c727f823de2a9fab9e1e2d) 后问题不是一直出现了（可能和我刚刚网络状况有关系吧）

**Comment by lss233** [comment]
`Response [429 Too Many Requests]`

是 OpenAI 服务器的问题。
