### ISSUE TITLE
[BUG] token登录GPT时报错'无效的 verifyKey 或其配置.', {'code': 1, 'msg': 'Auth Key错误'}

### ISSUE THREAD

**Issue by Aixsnow** [lss233/chatgpt-mirai-qq-bot#399]
graia-amnesia: 0.7.1
graia-ariadne: 0.11.1
graia-broadcast: 0.19.2
launart: 0.6.3
statv: 0.3.2
2023-03-21 11:45:36.498 | INFO     | launart.manager:_launchable_task_done_callback:68 - [elizabeth.connection.596392012.websocket_server_connection] completed.
2023-03-21 11:45:36.498 | INFO     | graia.amnesia.builtins.aiohttp:launch:513 - starting server on 0.0.0.0:8554
2023-03-21 11:45:36.499 | SUCCESS  | launart.manager:launch:384 - Layer #1:[http.server/aiohttp, cache.client/memcache, http.client/aiohttp] preparation completed.
2023-03-21 11:45:36.500 | INFO     | ariadne_bot:start_background:129 - OpenAI 服务器登录中……
2023-03-21 11:45:36.501 | INFO     | manager.bot:__check_proxy:175 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-03-21 11:45:41.517 | INFO     | manager.bot:__check_proxy:175 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-03-21 11:45:42.739 | SUCCESS  | manager.bot:__check_proxy:183 - [代理测试] 连接成功！
2023-03-21 11:45:42.740 | INFO     | manager.bot:login_openai:111 - 正在登录第 1 个 OpenAI 账号
2023-03-21 11:45:42.740 | INFO     | manager.bot:__login_V1:203 - 模式：无浏览器登录
2023-03-21 11:45:42.741 | INFO     | manager.bot:__check_proxy:175 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-03-21 11:45:43.485 | SUCCESS  | manager.bot:__check_proxy:183 - [代理测试] 连接成功！
2023-03-21 11:45:43.489 | INFO     | manager.bot:__login_V1:244 - 尝试使用 email + password 登录中...
2023-03-21 11:45:49.628 | ERROR    | manager.bot:login_openai:131 - 登录失败! 连接 OpenAI 服务器失败,请更换代理节点重试 ！HTTPSConnectionPool(host='auth0.openai.com', port=443): Max retries exceeded with url: /authorize?client_id=TdJIcbe16WoTHtN95nyywh5E4yOo6ItG&scope=openid%20email%20profile%20offline_access%20model.request%20model.read%20organization.read&response_type=code&redirect_uri=https%3A%2F%2Fexplorer.api.openai.com%2Fapi%2Fauth%2Fcallback%2Fauth0&audience=https%3A%2F%2Fapi.openai.com%2Fv1&prompt=login&state=iVchv9wynJsktp1p-tDQgNYAT3vUGx5Q-4HSAyhW1K4&code_challenge=T9A4fAZ7wau1OITseYOU852sEGPcz_qBrDUaiUt9y5k&code_challenge_method=S256 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2023-03-21 11:45:49.633 | INFO     | manager.bot:login_openai:111 - 正在登录第 2 个 OpenAI 账号
2023-03-21 11:45:49.634 | INFO     | manager.bot:__login_V1:203 - 模式：无浏览器登录
2023-03-21 11:45:49.635 | INFO     | manager.bot:__check_proxy:175 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-03-21 11:45:50.703 | SUCCESS  | manager.bot:__check_proxy:183 - [代理测试] 连接成功！
2023-03-21 11:45:50.704 | INFO     | manager.bot:__login_V1:225 - 尝试使用 access_token 登录中...
2023-03-21 11:45:51.793 | SUCCESS  | manager.bot:login_openai:126 - 登录成功！
2023-03-21 11:45:51.796 | SUCCESS  | manager.bot:login_openai:145 - 成功登录 1/2 个 OpenAI 账号！
2023-03-21 11:45:51.797 | INFO     | manager.bot:login:81 - AI 类型：chatgpt-web - 可用账号： 1 个
2023-03-21 11:45:51.798 | INFO     | manager.bot:login:81 - AI 类型：openai-api - 可用账号： 0 个
2023-03-21 11:45:51.798 | INFO     | manager.bot:login:81 - AI 类型：bing-cookie - 可用账号： 0 个
2023-03-21 11:45:51.799 | INFO     | ariadne_bot:start_background:134 - OpenAI 服务器登录成功
2023-03-21 11:45:51.799 | INFO     | ariadne_bot:start_background:135 - 尝试从 Mirai 服务中读取机器人 QQ 的 session key ……
2023-03-21 11:45:51.800 | INFO     | ariadne_bot:start_background:137 - [提示] 当前为反向 ws 模式，请确保你的 mirai api http 设置了正确的 reverse-ws adapter 配置
2023-03-21 11:45:51.802 | INFO     | ariadne_bot:start_background:138 - [提示] 配置不正确会导致 Mirai 端出现错误提示。
2023-03-21 11:45:51.804 | SUCCESS  | launart.manager:launch:384 - Layer #3:[elizabeth.service] preparation completed.
2023-03-21 11:45:51.805 | INFO     | launart.manager:launch:389 - All components prepared, start blocking phase.
2023-03-21 11:47:17.979 | ERROR    | graia.amnesia.transport.rider:trigger_callbacks:37 - ('无效的 verifyKey 或其配置.', {'code': 1, 'msg': 'Auth Key错误'})
Traceback (most recent call last):

> File "C:\ASP\Mirai-GPT\chatgpt\python3.11\Lib\site-packages\graia\amnesia\transport\common\websocket\shortcut.py", line 20, in wrapper
    return await func(self, io, data)
                 │    │     │   └ '{"code":1,"msg":"Auth Key错误"}'
                 │    │     └ <graia.amnesia.builtins.aiohttp.AiohttpServerWebsocketIO object at 0x000002B374FDFF10>
                 │    └ <WebsocketServerConnection <ConnectionStatus connected=False alive=False verified=False stage=None> with 2 callbacks>
                 └ <function WebsocketConnectionMixin._ at 0x000002B37527F740>
  File "C:\ASP\Mirai-GPT\chatgpt\python3.11\Lib\site-packages\graia\ariadne\connection\ws.py", line 52, in _
    validate_response(raw)  # raise it
    │                 └ {'code': 1, 'msg': 'Auth Key错误'}
    └ <function validate_response at 0x000002B374F8F380>
  File "C:\ASP\Mirai-GPT\chatgpt\python3.11\Lib\site-packages\graia\ariadne\connection\util.py", line 61, in validate_response
    raise exc
          └ InvalidVerifyKey('无效的 verifyKey 或其配置.', {'code': 1, 'msg': 'Auth Key错误'})

graia.ariadne.exception.InvalidVerifyKey: ('无效的 verifyKey 或其配置.', {'code': 1, 'msg': 'Auth Key错误'})

**Comment by Aixsnow** [comment]
似乎是网络问题，重做config后多试几次连上了
