### ISSUE TITLE
[BUG] new Bing 提示Authentication failed

### ISSUE THREAD

**Issue by d4renk** [lss233/chatgpt-mirai-qq-bot#412]
**提交 issue 前，请先确认：**
-  我已看过 **FAQ**，此问题不在列表中
-  我已看过其他 issue，他们不能解决我的问题 
-  我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
给机器人发送消息报错

**运行环境:**  
- 操作系统：debian11
- Docker： 源码运行
- 项目版本：0a32cff7eafb473cc439036ebeb3d2ec18b57b08

**复现步骤**  
描述你是如何触发这个 BUG 的
```
2023-03-23 17:57:43.488 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
Traceback (most recent call last):

  File "/home/app/app/chatgpt-mirai-qq-bot/bot.py", line 18, in <module>
    import ariadne_bot

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "/home/app/app/chatgpt-mirai-qq-bot/ariadne_bot.py", line 245, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x7f20e2ea3ac0>
    └ <graia.ariadne.app.Ariadne object at 0x7f20e329e820>

  File "/home/app/.local/lib/python3.9/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x7f20e2eaa180>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7f20e329e850>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x7f20e322c4c0>
    │   └ <launart.manager.Launart object at 0x7f20e1e6eaf0>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "/home/app/.local/lib/python3.9/site-packages/launart/manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /home/app/.local/lib/python3.9/site-packages/launart/ma...
    │    └ <function BaseEventLoop.run_until_complete at 0x7f20ea8cfa60>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f20ea8cf9d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f20ea8d2550>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f20ea9171f0>
    └ <Handle <TaskStepMethWrapper object at 0x7f20e0ce2cd0>()>
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f20e0ce2cd0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f20e0ce2cd0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f20e0ce2cd0>()>
> File "/home/app/.local/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {'app': <graia.ariadne.app.Ariadne object at 0x7f20e329e820>, 'target': Friend(id=***, nickname='～', remark='～'), 'sou...
                   │                └ <function friend_message_listener at 0x7f20e1e9e430>
                   └ <function run_always_await at 0x7f20e324a280>
  File "/home/app/.local/lib/python3.9/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object friend_message_listener at 0x7f20e0c9b840>

  File "/home/app/app/chatgpt-mirai-qq-bot/ariadne_bot.py", line 87, in friend_message_listener
    await handle_message(
          └ <function handle_message at 0x7f20e32d0040>

  File "/home/app/app/chatgpt-mirai-qq-bot/universal.py", line 51, in handle_message
    conversation_handler.current_conversation = await conversation_handler.create(
    │                    │                            │                    └ <function ConversationHandler.create at 0x7f20e1f40ca0>
    │                    │                            └ <conversation.ConversationHandler object at 0x7f20e1e0e490>
    │                    └ None
    └ <conversation.ConversationHandler object at 0x7f20e1e0e490>

  File "/home/app/app/chatgpt-mirai-qq-bot/conversation.py", line 172, in create
    conversation = ConversationContext(_type, self.session_id)
                   │                   │      │    └ 'friend-***'
                   │                   │      └ <conversation.ConversationHandler object at 0x7f20e1e0e490>
                   │                   └ 'bing-c'
                   └ <class 'conversation.ConversationContext'>

  File "/home/app/app/chatgpt-mirai-qq-bot/conversation.py", line 60, in __init__
    self.adapter = BingAdapter(self.session_id, ConversationStyle.creative)
    │              │           │    │           │                 └ <ConversationStyle.creative: 'h3imaginative'>
    │              │           │    │           └ <enum 'ConversationStyle'>
    │              │           │    └ 'friend-***'
    │              │           └ <conversation.ConversationContext object at 0x7f20e0cf9370>
    │              └ <class 'adapter.ms.bing.BingAdapter'>
    └ <conversation.ConversationContext object at 0x7f20e0cf9370>

  File "/home/app/app/chatgpt-mirai-qq-bot/adapter/ms/bing.py", line 32, in __init__
    self.bot = EdgeChatbot(cookies=self.cookieData, proxy=account.proxy)
    │          │                   │    │                 │       └ 'http://127.0.0.1:7890'
    │          │                   │    │                 └ BingCookiePath(cookie_content='SRCHD=AF=NOFORM; SRCHUID=V=2&GUID=***&dmnchg=1; _UR=QS=0&TQS=0; M...
    │          │                   │    └ [{'name': 'SRCHD', 'value': 'AF=NOFORM'}, {'name': 'SRCHUID', 'value': 'V=2&GUID=***&dmnchg=1'},...
    │          │                   └ <adapter.ms.bing.BingAdapter object at 0x7f20e0cf9790>
    │          └ <class 'EdgeGPT.Chatbot'>
    └ <adapter.ms.bing.BingAdapter object at 0x7f20e0cf9790>

  File "/home/app/.local/lib/python3.9/site-packages/EdgeGPT.py", line 317, in __init__
    Conversation(self.cookiePath, self.cookies, proxy)
    │            │    │           │    │        └ 'http://127.0.0.1:7890'
    │            │    │           │    └ [{'name': 'SRCHD', 'value': 'AF=NOFORM'}, {'name': 'SRCHUID', 'value': 'V=2&GUID=***&dmnchg=1'},...
    │            │    │           └ <EdgeGPT.Chatbot object at 0x7f20e1e0e8e0>
    │            │    └ ''
    │            └ <EdgeGPT.Chatbot object at 0x7f20e1e0e8e0>
    └ <class 'EdgeGPT.Conversation'>
  File "/home/app/.local/lib/python3.9/site-packages/EdgeGPT.py", line 219, in __init__
    raise Exception("Authentication failed")

Exception: Authentication failed
```
**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过
new bing 账号正常

**Comment by AriesOxO** [comment]
这个问题今天刚出现的，昨天还是好的，早上起来发现异常了，和你一样是这个“Authentication failed"问题

**Comment by Ifycyu** [comment]
早上我也遇到了,在bing里面加上代理就好了

**Comment by IZege** [comment]
docker部署出现同样的错误。使用代理无效

**Comment by K2Lin-Daniel** [comment]
Microsoft has denied all IPs from China to visit New Bing.  It will need to export the proxy address as an environment variable to solve the problem

**Comment by K2Lin-Daniel** [comment]
> > Microsoft has denied all IPs from China to visit New Bing.  It will need to export the proxy address as an environment variable to solve the problem
> 
> 我往环境变量写了代理 在浏览器中可以正常使用new bing 但在chatgpt-mirai-qq-bot中提示Authentication failed

Maybe try update EdgeGPT package?
Its locked to ==0.0.58.2 in requirements.txt

**Comment by RamSong** [comment]
我反代了https://edgeservices.bing.com/edgesvc/turing/conversation/create 
但具体要在哪里更改它呢？

**Comment by ZS629** [comment]
![image](https://user-images.githubusercontent.com/127756463/229310999-0e70212c-ceb2-4f62-a165-4417cdd92fa3.png)
这个什么问题
