### ISSUE TITLE
兼容 OpenAI API

### ISSUE THREAD

**Issue by lss233** [lss233/chatgpt-mirai-qq-bot#42]
ChatGPT 看起来已经被玩坏了。  

兼容 OpenAI API， 可用性会更高一些。

**Comment by wdnmd-ship** [comment]
Traceback (most recent call last):
  File "C:\Users\WYC\Downloads\quickstart-windows-amd64\chatgpt\bot.py", line 23, in <module>
    import chatbot
  File "C:\Users\WYC\Downloads\quickstart-windows-amd64\chatgpt\chatbot.py", line 1, in <module>
    from revChatGPT.Official import Chatbot, Prompt
  File "C:\Users\WYC\Downloads\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\revChatGPT\Official.py", line 11, in <module>
    import tiktoken
ModuleNotFoundError: No module named 'tiktoken'

C:\Users\WYC\Downloads\quickstart-windows-amd64\chatgpt>
这是怎么回事

**Comment by sudoskys** [comment]
我认为随着API的公布，此 issue 可以关闭了。
