### ISSUE TITLE
[ERROR]:404 message='Invalid response status', url=URL

### ISSUE THREAD

**Issue by SoDebug** [lss233/chatgpt-mirai-qq-bot#43]
Waiting for cookies...
2022-12-13 08:21:59.883 | INFO     | launart.manager:launch_blocking:446 - Starting launart main task...
2022-12-13 08:21:59.885 | INFO     | launart.manager:launch:313 - Launching 5 components as async task...
2022-12-13 08:21:59.941 | INFO     | graia.ariadne.service:base_telemetry:142 -
    _         _           _
   / \   _ __(_) __ _  __| |_ __   ___
  / _ \ | '__| |/ _` |/ _` | '_ \ / _ \
 / ___ \| |  | | (_| | (_| | | | |  __/
/_/   \_\_|  |_|\__,_|\__,_|_| |_|\___|

graia-amnesia: 0.7.0
graia-ariadne: 0.10.0
graia-broadcast: 0.19.0
launart: 0.6.1
statv: 0.3.2
2022-12-13 08:21:59.946 | INFO     | launart.manager:_launchable_task_done_callback:59 - [elizabeth.connection.1510834862.http_client_connection] completed.
2022-12-13 08:21:59.947 | SUCCESS  | launart.manager:launch:351 - Layer #1:[http.client/aiohttp, cache.client/memcache] preparation completed.
2022-12-13 08:21:59.948 | SUCCESS  | launart.manager:launch:351 - Layer #3:[elizabeth.service] preparation completed.
2022-12-13 08:21:59.950 | INFO     | launart.manager:launch:356 - All components prepared, start blocking phase.
2022-12-13 08:22:02.106 | ERROR    | graia.amnesia.builtins.aiohttp:connection_manage:231 - 404, message='Invalid response status', url=URL('http://localhost:8080/all?qq=1510834862&verifyKey=1234567890')
Traceback (most recent call last):

  File "D:\OpenAiQQBot\chatgpt\bot.py", line 94, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x000001EDD26A7D00>
    └ <graia.ariadne.app.Ariadne object at 0x000001EDFA0AA4C0>

  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\graia\ariadne\app.py", line 298, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x000001EDD26AECC0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x000001EDFA0AAE80>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x000001EDD172E8B0>
    │   └ <launart.manager.Launart object at 0x000001EDFA162EB0>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\launart\manager.py", line 461, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\laun...
    │    └ <function BaseEventLoop.run_until_complete at 0x000001EDD139DA60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 634, in run_until_complete

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 601, in run_forever

  File "asyncio\base_events.py", line 1905, in _run_once

  File "asyncio\events.py", line 80, in _run

> File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\graia\amnesia\builtins\aiohttp.py", line 217, in connection_manage
    await self._start_conn()
          │    └ <function AiohttpClientConnectionRider._start_conn at 0x000001EDD256D1F0>
          └ <graia.amnesia.builtins.aiohttp.AiohttpClientConnectionRider object at 0x000001EDFA189AC0>

  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\graia\amnesia\builtins\aiohttp.py", line 180, in _start_conn
    self.response = await self.conn_func(**self.call_param)
    │    │                │    │           │    └ {'url': 'http://localhost:8080/all?qq=1510834862&verifyKey=1234567890', 'heartbeat': 30.0}
    │    │                │    │           └ <graia.amnesia.builtins.aiohttp.AiohttpClientConnectionRider object at 0x000001EDFA189AC0>
    │    │                │    └ <bound method ClientSession.ws_connect of <aiohttp.client.ClientSession object at 0x000001EDFA181FA0>>
    │    │                └ <graia.amnesia.builtins.aiohttp.AiohttpClientConnectionRider object at 0x000001EDFA189AC0>
    │    └ None
    └ <graia.amnesia.builtins.aiohttp.AiohttpClientConnectionRider object at 0x000001EDFA189AC0>

  File "D:\OpenAiQQBot\chatgpt\python3.9\lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
          └ <class 'aiohttp.client_exceptions.WSServerHandshakeError'>

aiohttp.client_exceptions.WSServerHandshakeError: 404, message='Invalid response status', url=URL('http://localhost:8080/all?qq=1510834862&verifyKey=1234567890')
2022-12-13 08:22:02.145 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...
2022-12-13 08:22:07.163 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...

**Comment by lss233** [comment]
mirai-http-api 那边的配置看看？

**Comment by SoDebug** [comment]
> mirai-http-api 那边的配置看看？

![image](https://user-images.githubusercontent.com/30922923/207213681-e3eaeb25-7455-42e2-96db-04d98fce69ae.png)
z这个吗

**Comment by lss233** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/wiki/%E4%BD%BF%E7%94%A8-Docker-Compose-%E9%83%A8%E7%BD%B2%EF%BC%88%E5%90%8C%E6%97%B6%E4%BD%BF%E7%94%A8-Mirai-%E5%92%8C-%E6%9C%AC%E9%A1%B9%E7%9B%AE%EF%BC%89#5-%E9%85%8D%E7%BD%AE-mirai-http-api

**Comment by SoDebug** [comment]
> https://github.com/lss233/chatgpt-mirai-qq-bot/wiki/%E4%BD%BF%E7%94%A8-Docker-Compose-%E9%83%A8%E7%BD%B2%EF%BC%88%E5%90%8C%E6%97%B6%E4%BD%BF%E7%94%A8-Mirai-%E5%92%8C-%E6%9C%AC%E9%A1%B9%E7%9B%AE%EF%BC%89#5-%E9%85%8D%E7%BD%AE-mirai-http-api

已解决，主要是readme里面没看见Windows快速部署要配置mirai>_<
