### ISSUE TITLE
[BUG] 在使用onebot协议时向bot发送任何信息都会报错

### ISSUE THREAD

**Issue by lvwenzhuo2003** [lss233/chatgpt-mirai-qq-bot#461]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
bot出现报错后会断开反向ws连接并且无响应，不会发送任何qq回复

**运行环境:**  
- 操作系统：Ubuntu Linux 5.15.0-69-generic
- Docker： 未使用
- 项目版本：2.2.5

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 启动bot和go-cqhttp
2. 向bot发送任意消息
3. bot出现报错

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过
```
2023-03-30 06:11:31.107 | ERROR    | config:scan_presets:416 - 检查预设：正常 <==> presets/default.txt [失败：文件不存在]
2023-03-30 06:11:31.108 | SUCCESS  | config:scan_presets:414 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-03-30 06:11:31.108 | SUCCESS  | config:scan_presets:427 - 注册预设：预设模板 <==> ./presets/预设模板.txt [成功]
2023-03-30 06:11:31.108 | SUCCESS  | config:scan_presets:427 - 注册预设：catgirl <==> ./presets/catgirl.txt [成功]
2023-03-30 06:11:31.108 | SUCCESS  | config:scan_presets:427 - 注册预设：catgirl_en <==> ./presets/catgirl_en.txt [成功]
2023-03-30 06:11:31.108 | SUCCESS  | config:scan_presets:427 - 注册预设：issue402 <==> ./presets/issue402.txt [成功]
2023-03-30 06:11:31.109 | INFO     | __main__:<module>:19 - 检测到 Onebot 配置，将以 Onebot 模式启动……
2023-03-30 06:11:31.521 | ERROR    | utils.text_to_img:<module>:53 - 未检测到 wkhtmltoimage，无法进行 Markdown 渲染！
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://127.0.0.1:6555 (CTRL + C to quit)
2023-03-30 06:11:31.554 | INFO     | manager.bot:login_openai:226 - 正在登录第 1 个 OpenAI 账号
2023-03-30 06:11:31.554 | INFO     | manager.bot:__login_V1:318 - 模式：无浏览器登录
2023-03-30 06:11:31.555 | INFO     | manager.bot:__login_V1:342 - 尝试使用 access_token 登录中...
2023-03-30 06:11:32.710 | SUCCESS  | manager.bot:login_openai:241 - 登录成功！
2023-03-30 06:11:32.710 | SUCCESS  | manager.bot:login_openai:260 - 成功登录 1/1 个 OpenAI 账号！
2023-03-30 06:11:32.710 | INFO     | manager.bot:login:119 - AI 类型：chatgpt-web - 可用账号： 1 个
2023-03-30 06:11:32.710 | INFO     | manager.bot:login:119 - AI 类型：openai-api - 可用账号： 0 个
2023-03-30 06:11:32.711 | INFO     | manager.bot:login:119 - AI 类型：poe-web - 可用账号： 0 个
2023-03-30 06:11:32.711 | INFO     | manager.bot:login:119 - AI 类型：bing-cookie - 可用账号： 0 个
2023-03-30 06:11:32.711 | INFO     | manager.bot:login:119 - AI 类型：bard-cookie - 可用账号： 0 个
2023-03-30 06:11:32.711 | INFO     | manager.bot:login:119 - AI 类型：yiyan-cookie - 可用账号： 0 个
2023-03-30 06:11:32.711 | INFO     | manager.bot:login:119 - AI 类型：chatglm-api - 可用账号： 0 个
2023-03-30 06:11:32.711 | SUCCESS  | platforms.onebot_bot:startup:251 - 启动完毕，接收消息中……
[2023-03-30 06:11:32 +0800] [713742] [INFO] Running on http://127.0.0.1:6555 (CTRL + C to quit)
INFO:hypercorn.error:Running on http://127.0.0.1:6555 (CTRL + C to quit)
[2023-03-30 06:11:35 +0800] [713742] [INFO] 127.0.0.1:46892 GET /ws 1.1 101 - 880
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-16' coro=<CQHttp._handle_event_with_response() done, defined at /home/lvwenzhuo/.local/lib/python3.10/site-packages/aiocqhttp/__init__.py:606> exception=AttributeError("'list' object has no attribute 'startswith'")>
Traceback (most recent call last):
  File "/home/lvwenzhuo/.local/lib/python3.10/site-packages/aiocqhttp/__init__.py", line 608, in _handle_event_with_response
    response = await self._handle_event(payload)
  File "/home/lvwenzhuo/.local/lib/python3.10/site-packages/aiocqhttp/__init__.py", line 601, in _handle_event
    filter(lambda r: r is not None, await
  File "/home/lvwenzhuo/.local/lib/python3.10/site-packages/aiocqhttp/bus.py", line 60, in emit
    results += await run_async_funcs(self._subscribers[event], *args,
  File "/home/lvwenzhuo/.local/lib/python3.10/site-packages/aiocqhttp/utils.py", line 40, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "/home/lvwenzhuo/chatgpt-mirai-qq-bot/platforms/onebot_bot.py", line 112, in _
    if event.message.startswith('.'):
AttributeError: 'list' object has no attribute 'startswith'
```

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
有点奇怪。你的 gocqhttp 是什么版本？

**Comment by lvwenzhuo2003** [comment]
1.0.0-rc5

**Comment by lss233** [comment]
有可能是他们改了协议版本导致的。
目前我们是按照 onebot v11 来解析的数据，你使用的版本可能使用的是onebot v12发送的数据。可以试试降级 gocqhttp再试试看。

**Comment by lvwenzhuo2003** [comment]
换成了rc4，还是一样的问题

**Comment by lss233** [comment]
此 BUG 无法复现，请提供一下 go-cqhttp 的日志

**Comment by lvwenzhuo2003** [comment]
更新到2.2.6.1之后不会无响应也不会断开连接了，但是还是在报错
这个是go-cqhttp的日志
```
[2023-03-31 04:40:10] [INFO]: 当前版本:v1.0.0-rc4
[2023-03-31 04:40:10] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-03-31 04:40:10] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-03-31 04:40:15] [INFO]: 开始尝试登录并同步消息...
[2023-03-31 04:40:15] [INFO]: 使用协议: MacOS
[2023-03-31 04:40:18] [INFO]: Protocol -> connect to server: 43.135.106.161:8080
[2023-03-31 04:40:18] [WARNING]: Protocol -> device lock is disable. http api may fail.
[2023-03-31 04:40:22] [INFO]: 登录成功 欢迎使用: QQ昵称
[2023-03-31 04:40:22] [INFO]: 开始加载好友列表...
[2023-03-31 04:40:23] [INFO]: 共加载 6 个好友.
[2023-03-31 04:40:23] [INFO]: 开始加载群列表...
[2023-03-31 04:40:23] [INFO]: 共加载 4 个群.
[2023-03-31 04:40:24] [INFO]: 资源初始化完成, 开始处理信息.
[2023-03-31 04:40:24] [INFO]: アトリは、高性能ですから!
[2023-03-31 04:40:24] [INFO]: 正在检查更新.
[2023-03-31 04:40:24] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:6555/ws
[2023-03-31 04:40:24] [INFO]: 已连接到反向WebSocket Universal服务器 ws://127.0.0.1:6555/ws
[2023-03-31 04:40:24] [INFO]: 当前有更新的 go-cqhttp 可供更新, 请前往 https://github.com/Mrs4s/go-cqhttp/releases 下载.
[2023-03-31 04:40:24] [INFO]: 当前版本: v1.0.0-rc4 最新版本: v1.0.0-rc5
[2023-03-31 04:40:24] [INFO]: 开始诊断网络情况
[2023-03-31 04:40:30] [INFO]: 网络诊断完成. 未发现问题
[2023-03-31 04:40:38] [INFO]: 收到好友 QQ好友昵称(QQ好友号码) 的消息: 测试 (-1157036130)
[2023-03-31 04:42:53] [INFO]: 收到好友 QQ好友昵称(QQ好友号码) 的消息: 没有反应 (570447396)
```

**Comment by lvwenzhuo2003** [comment]
我把配置文件也贴出来吧
本bot的配置
```
#[mirai]
[onebot]
qq = example_qq_uin

# discard the following settings if you do not know what you are doing
#api_key = "1234567890"
#http_url = "http://localhost:8080"
#ws_url = "http://localhost:8080"
manager_qq = example_qq_uin
reverse_ws_host = "127.0.0.1"
reverse_ws_port = 6555

[openai]
# OpenAI settings
browserless_endpoint = "https://bypass.duti.tech/api/"
# First acct info
[[openai.accounts]]
# select mode. browser = browser login, browserless = no browser login
# If you use browser mode and stuck at "Found session token", try use browserless
mode = 'browserless'

#api_key = ""
# OpenAI acct email
email = "email@example.com"
# OpenAI acct passwd
password = "examplepassword"
access_token = "exampleaccesstoken"
# OpenAI session_token, for Microsoft/Google login
# session_token = "starts with ey***"

# OpenAI access_token, can be found in *https://chat.openai.com/api/auth/session* after login
# This is used with browserless mode. Please try this while you failed to login with browser mode
# access_token = ""

# Set to true if you are ChatGPT Plus
paid = false

# Proxy settings (for Mainland China)
#proxy="socks5://127.0.0.1:40000"


# Second acct info
#[[openai.accounts]]
#api_key = ""
#mode = 'browser'
#access_token = ""
#proxy="socks5://127.0.0.1:40000"
#paid = false

# Third acct info
# [[openai.accounts]]
# mode = 'browser'
# email = "xxxxx"
# password = "xxxxx"
# # proxy="http://127.0.0.1:1080"
# paid = false
[response]
default_ai = "chatgpt-web"
quote = true
timeout = 10.0
timeout_format = "请稍等~"
max_queue_size = 5


#[ratelimit]
#warning_rate = 0.8
#warning_msg = "警告：额度即将耗尽！当前小时已使用{usage}/{limit}条消息，请调整您的节奏！"
#exceed = "已达到额度限制，请等待下一小时继续对话。"

[trigger]
prefix = [ "#" ]



[system]
# Auto accept invitation to group
accept_group_invite = true
# Auto accept friend request
accept_friend_request = true

[presets]
# switch presets
command = "加载预设 (\\w+)"
loaded_successful = "preset loaded! "

[presets.keywords]
# preset keyword = preset file
"正常" = "presets/default.txt"
"猫娘" = "presets/catgirl.txt"
# USE WITH CAUTION! While default preset were enabled, all sessions would use this.
# "default" = "presets/default.txt"






[baiducloud]
check = true
baidu_api_key = "example_api_key"
baidu_secret_key = "example_secret_key"
```
gocq的配置
```
# go-cqhttp 默认配置文件

account: # 账号相关
  uin: example_qq_uin # QQ账号
  password: examplepassword # 密码为空时使用扫码登录
  encrypt: false  # 是否开启密码加密
  status: 0      # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  relogin: # 重连设置
    delay: 3   # 首次重连延迟, 单位秒
    interval: 3   # 重连间隔
    max-times: 0  # 最大重连次数, 0为无限制

  # 是否使用服务器下发的新地址进行重连
  # 注意, 此设置可能导致在海外服务器上连接情况更差
  use-sso-address: false
  # 是否允许发送临时会话消息
  allow-temp-session: false

heartbeat:
  # 心跳频率, 单位秒
  # -1 为关闭心跳
  interval: 5

message:
  # 上报数据类型
  # 可选: string,array
  post-format: array
  # 是否忽略无效的CQ码, 如果为假将原样发送
  ignore-invalid-cqcode: false
  # 是否强制分片发送消息
  # 分片发送将会带来更快的速度
  # 但是兼容性会有些问题
  force-fragment: false
  # 是否将url分片发送
  fix-url: false
  # 下载图片等请求网络代理
  proxy-rewrite: ''
  # 是否上报自身消息
  report-self-message: false
  # 移除服务端的Reply附带的At
  remove-reply-at: false
  # 为Reply附加更多信息
  extra-reply-data: false
  # 跳过 Mime 扫描, 忽略错误数据
  skip-mime-scan: false

output:
  # 日志等级 trace,debug,info,warn,error
  log-level: warn
  # 日志时效 单位天. 超过这个时间之前的日志将会被自动删除. 设置为 0 表示永久保留.
  log-aging: 15
  # 是否在每次启动时强制创建全新的文件储存日志. 为 false 的情况下将会在上次启动时创建的日志文件续写
  log-force-new: true
  # 是否启用日志颜色
  log-colorful: true
  # 是否启用 DEBUG
  debug: false # 开启调试模式

# 默认中间件锚点
default-middlewares: &default
  # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: ''
  # 事件过滤器文件目录
  filter: ''
  # API限速设置
  # 该设置为全局生效
  # 原 cqhttp 虽然启用了 rate_limit 后缀, 但是基本没插件适配
  # 目前该限速设置为令牌桶算法, 请参考:
  # https://baike.baidu.com/item/%E4%BB%A4%E7%89%8C%E6%A1%B6%E7%AE%97%E6%B3%95/6597000?fr=aladdin
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1  # 令牌回复频率, 单位秒
    bucket: 1     # 令牌桶大小

database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true

  # 媒体文件缓存， 删除此项则使用缓存文件(旧版行为)
  cache:
    image: data/image.db
    video: data/video.db

# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  # 反向WS设置
  - ws-reverse:
      # 反向WS Universal 地址
      universal: ws://127.0.0.1:6555/ws
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```

**Comment by lss233** [comment]
我看你设置了preform，你的消息应该以前缀开头才行。

另外，gocqhttp里面的上报消息类型应该填string而不是array。

**Comment by lvwenzhuo2003** [comment]
确实是gocqhttp的问题，改成string后就好了
