### ISSUE TITLE
Mirai 登录 code 45 错误

### ISSUE THREAD

**Issue by HappyTsing** [lss233/chatgpt-mirai-qq-bot#477]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
docker-compose run --rm mirai 登录失败，错误信息：
> Login failed: Error(bot=Bot(2429590425), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
2023-03-31 02:56:08 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2429590425), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2429590425), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**运行环境:**  
- 操作系统：ubuntu 18.04
- Docker：Docker version 23.0.2, build 569dd73
- 项目版本：最新

**复现步骤**  
描述你是如何触发这个 BUG 的
1. docker-compose run --rm mirai 
2. 浏览器滑块，获取ticket
3. 报错如上

**预期行为**  
正常登录

**Comment by G37H9** [comment]
看看你QQ开了允许陌生设备登录没
或者改一下自动登录配置 用  MACOS 试试看

**Comment by qingshanlanshan** [comment]
这个在mirai论坛里有置顶帖的，可以去看看

**Comment by lss233** [comment]
duplicated of #303
