### ISSUE TITLE
[BUG] openai账号无法登陆，我实在找不出原因

### ISSUE THREAD

**Issue by q23339860** [lss233/chatgpt-mirai-qq-bot#496]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
2023-04-01 19:25:07,103 Warning: cannot enable SSH socket upgrades
2023-04-01 19:25:07,103  No module named 'paramiko'
2023-04-01 19:25:07,104 created tcp socket '0.0.0.0:14500'
2023-04-01 19:25:07,106 no uinput module (not usually needed)
2023-04-01 19:25:08,586 pointer device emulation using XTest
2023-04-01 19:25:08,636 serving html content from '/usr/share/xpra/www'
2023-04-01 19:25:08,637 wrote pid 8 to '/tmp/0/server.pid'
2023-04-01 19:25:08,660 Warning: socket directory '/tmp/0'
2023-04-01 19:25:08,660  expected permissions 700 but found 750
2023-04-01 19:25:08,660 created unix domain socket '/run/user/1000/xpra/VM-0-10-opencloudos-0'
2023-04-01 19:25:08,660 created unix domain socket '/tmp/0/socket'
2023-04-01 19:25:08,660 xvfb pid=12
2023-04-01 19:25:08,714 Warning: cannot watch for application menu changes without pyinotify:
2023-04-01 19:25:08,714  No module named 'pyinotify'
2023-04-01 19:25:08,721 Warning: cannot load menu data
2023-04-01 19:25:08,721  No module named 'xdg'
2023-04-01 19:25:08,729 Warning: webcam forwarding is disabled
2023-04-01 19:25:08,729  the virtual video directory '/sys/devices/virtual/video4linux' was not found
2023-04-01 19:25:08,729  make sure that the 'v4l2loopback' kernel module is installed and loaded
2023-04-01 19:25:08,729  or use the 'webcam=no' option
2023-04-01 19:25:08,730 found 0 virtual video devices for webcam forwarding
2023-04-01 19:25:08,734 started command `xterm -e python bot.py 2>&1 | tee /tmp/log.txt` with pid 44
2023-04-01 19:25:08,875 1.7GB of system memory
2023-04-01 19:25:09,064 waiting for initialization thread to complete
2023-04-01 19:25:09,067 xpra is ready.
2023-04-01 19:25:09,067 xpra X11 seamless version 4.4.4-r0 64-bit
2023-04-01 19:25:09,068  uid=0 (root), gid=0 (root)
2023-04-01 19:25:09,068  running with pid 8 on Linux Debian 11 bullseye
2023-04-01 19:25:09,069  connected to X11 display :0 with 24 bit colors
2023-04-01 19:25:09,733 OpenGL is supported on display ':0'
2023-04-01 19:25:09,734  using 'llvmpipe (LLVM 11.0.1, 256 bits)' renderer
2023-04-01 19:25:10.112 | SUCCESS  | config:scan_presets:444 - 注册预设：catgirl_en <==> ./presets/catgirl_en.txt [成功]
2023-04-01 19:25:10.113 | SUCCESS  | config:scan_presets:444 - 注册预设：catgirl <==> ./presets/catgirl.txt [成功]
2023-04-01 19:25:10.113 | SUCCESS  | config:scan_presets:444 - 注册预设：预设模板 <==> ./presets/预设模板.txt [成功]
2023-04-01 19:25:10.113 | SUCCESS  | config:scan_presets:444 - 注册预设：issue402 <==> ./presets/issue402.txt [成功]
2023-04-01 19:25:10.113 | INFO     | __main__:<module>:19 - 检测到 Onebot 配置，将以 Onebot 模式启动……
2023-04-01 19:25:10.789 | INFO     | manager.bot:login:102 - 当前的 browserless_endpoint 为：https://bypass.churchless.tech/api/
2023-04-01 19:25:10.789 | INFO     | manager.bot:login:114 - 当前的 api_endpoint 为：https://api.oepnai.com/v1
2023-04-01 19:25:10.789 | INFO     | manager.bot:login_openai:235 - 正在登录第 1 个 OpenAI 账号
2023-04-01 19:25:10.789 | INFO     | manager.bot:__login_openai_apikey:421 - 尝试使用 api_key 登录中...
2023-04-01 19:25:10.789 | INFO     | manager.bot:__login_openai_apikey:425 - 当前检查的 API Key 为：sk-QA1ss******eRg5
2023-04-01 19:25:11.652 | ERROR    | manager.bot:login_openai:265 - 未知错误：
2023-04-01 19:25:11.652 | ERROR    | manager.bot:login_openai:266 - 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.oepnai.com/v1/dashboard/billing/credit_grants')
Traceback (most recent call last):

  File "/app/bot.py", line 32, in <module>
    main()
    └ <function main at 0x7f73a128ed40>

  File "/app/platforms/onebot_bot.py", line 266, in main
    bot.run(host=config.onebot.reverse_ws_host, port=config.onebot.reverse_ws_port)
    │   │        │      │      │                     │      │      └ 8566
    │   │        │      │      │                     │      └ Onebot(qq=3141541725, manager_qq=153565283, reverse_ws_host='0.0.0.0', reverse_ws_port=8566)
    │   │        │      │      │                     └ Config(onebot=Onebot(qq=3141541725, manager_qq=153565283, reverse_ws_host='0.0.0.0', reverse_ws_port=8566), mirai=None, teleg...
    │   │        │      │      └ '0.0.0.0'
    │   │        │      └ Onebot(qq=3141541725, manager_qq=153565283, reverse_ws_host='0.0.0.0', reverse_ws_port=8566)
    │   │        └ Config(onebot=Onebot(qq=3141541725, manager_qq=153565283, reverse_ws_host='0.0.0.0', reverse_ws_port=8566), mirai=None, teleg...
    │   └ <function CQHttp.run at 0x7f73a3aa4fe0>
    └ <aiocqhttp.CQHttp object at 0x7f73a42c5690>

  File "/usr/local/lib/python3.11/site-packages/aiocqhttp/__init__.py", line 222, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
    │    │           │        │          │      │       └ {'use_reloader': False}
    │    │           │        │          │      └ ()
    │    │           │        │          └ 8566
    │    │           │        └ '0.0.0.0'
    │    │           └ <function Quart.run at 0x7f73a3c77560>
    │    └ <Quart ''>
    └ <aiocqhttp.CQHttp object at 0x7f73a42c5690>
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1423, in run
    loop.run_until_complete(asyncio.gather(*tasks))
    │    │                  │       │       └ [<Task pending name='Task-1' coro=<serve() running at /usr/local/lib/python3.11/site-packages/hypercorn/asyncio/__init__.py:4...
    │    │                  │       └ <function gather at 0x7f73a6fff920>
    │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x7f73a7010680>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f73a70105e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f73a70123e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f73a6f64900>
    └ <Handle <TaskStepMethWrapper object at 0x7f73a1295630>()>
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f73a1295630>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f73a1295630>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f73a1295630>()>
  File "/usr/local/lib/python3.11/site-packages/hypercorn/asyncio/lifespan.py", line 43, in handle_lifespan
    await self.app(
          │    └ <hypercorn.app_wrappers.ASGIWrapper object at 0x7f73a2f8a790>
          └ <hypercorn.asyncio.lifespan.Lifespan object at 0x7f73a1298910>
  File "/usr/local/lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method Lifespan.asgi_send of <hypercorn.asyncio.lifespan.Lifespan object at 0x7f73a1298910>>
          │    │   │      └ <bound method Lifespan.asgi_receive of <hypercorn.asyncio.lifespan.Lifespan object at 0x7f73a1298910>>
          │    │   └ {'type': 'lifespan', 'asgi': {'spec_version': '2.0', 'version': '3.0'}}
          │    └ <Quart ''>
          └ <hypercorn.app_wrappers.ASGIWrapper object at 0x7f73a2f8a790>
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1902, in __call__
    await self.asgi_app(scope, receive, send)
          │    │        │      │        └ <bound method Lifespan.asgi_send of <hypercorn.asyncio.lifespan.Lifespan object at 0x7f73a1298910>>
          │    │        │      └ <bound method Lifespan.asgi_receive of <hypercorn.asyncio.lifespan.Lifespan object at 0x7f73a1298910>>
          │    │        └ {'type': 'lifespan', 'asgi': {'spec_version': '2.0', 'version': '3.0'}}
          │    └ <function Quart.asgi_app at 0x7f73a3c78400>
          └ <Quart ''>
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1928, in asgi_app
    await asgi_handler(receive, send)
          │            │        └ <bound method Lifespan.asgi_send of <hypercorn.asyncio.lifespan.Lifespan object at 0x7f73a1298910>>
          │            └ <bound method Lifespan.asgi_receive of <hypercorn.asyncio.lifespan.Lifespan object at 0x7f73a1298910>>
          └ <quart.asgi.ASGILifespan object at 0x7f73a1298bd0>
  File "/usr/local/lib/python3.11/site-packages/quart/asgi.py", line 311, in __call__
    await self.app.startup()
          │    │   └ <function Quart.startup at 0x7f73a3c784a0>
          │    └ <Quart ''>
          └ <quart.asgi.ASGILifespan object at 0x7f73a1298bd0>
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1936, in startup
    await self.ensure_async(func)()
          │    │            └ <function startup at 0x7f73a128e8e0>
          │    └ <function Quart.ensure_async at 0x7f73a3c77060>
          └ <Quart ''>

  File "/app/platforms/onebot_bot.py", line 261, in startup
    await botManager.login()
          │          └ <function BotManager.login at 0x7f73a471d1c0>
          └ <manager.bot.BotManager object at 0x7f73a76afd10>

  File "/app/manager/bot.py", line 116, in login
    await self.login_openai()
          │    └ <function BotManager.login_openai at 0x7f73a471db20>
          └ <manager.bot.BotManager object at 0x7f73a76afd10>

> File "/app/manager/bot.py", line 238, in login_openai
    bot = await self.__login_openai_apikey(account)
                │                          └ OpenAIAPIKey(mode='browserless', proxy=None, driver_exec_path=None, browser_exec_path=None, conversation=None, paid=False, gp...
                └ <manager.bot.BotManager object at 0x7f73a76afd10>

  File "/app/manager/bot.py", line 427, in __login_openai_apikey
    grant_used, grant_available, has_payment_method, total_usage, hard_limit_usd = await self.check_api_info(
                                                                                         │    └ <function BotManager.check_api_info at 0x7f73a471df80>
                                                                                         └ <manager.bot.BotManager object at 0x7f73a76afd10>

  File "/app/manager/bot.py", line 393, in check_api_info
    resp = await resp.json()
                 │    └ <function ClientResponse.json at 0x7f73a5b8b9c0>
                 └ <ClientResponse(https://api.oepnai.com/v1/dashboard/billing/credit_grants) [200 OK]>
                   <CIMultiDictProxy('Server': 'openresty',...

  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
          └ <class 'aiohttp.client_exceptions.ContentTypeError'>

aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.oepnai.com/v1/dashboard/billing/credit_grants')
2023-04-01 19:25:11.666 | SUCCESS  | manager.bot:login_openai:269 - 成功登录 0/1 个 OpenAI 账号！
2023-04-01 19:25:11.667 | ERROR    | manager.bot:login:123 - 没有登录成功的账号，程序无法启动！
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://0.0.0.0:8566 (CTRL + C to quit)
ERROR:asyncio:_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1423, in run
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/hypercorn/asyncio/lifespan.py", line 43, in handle_lifespan
    await self.app(
  File "/usr/local/lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1902, in __call__
    await self.asgi_app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1928, in asgi_app
    await asgi_handler(receive, send)
  File "/usr/local/lib/python3.11/site-packages/quart/asgi.py", line 311, in __call__
    await self.app.startup()
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1936, in startup
    await self.ensure_async(func)()
  File "/app/platforms/onebot_bot.py", line 261, in startup
    await botManager.login()
  File "/app/manager/bot.py", line 124, in login
    exit(-2)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: -2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hypercorn/asyncio/__init__.py", line 49, in serve
    await worker_serve(
  File "/usr/local/lib/python3.11/site-packages/hypercorn/asyncio/run.py", line 77, in worker_serve
    await lifespan.wait_for_startup()
  File "/usr/local/lib/python3.11/site-packages/hypercorn/asyncio/lifespan.py", line 76, in wait_for_startup
    await asyncio.wait_for(self.startup.wait(), timeout=self.config.startup_timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Lifespan.handle_lifespan() done, defined at /usr/local/lib/python3.11/site-packages/hypercorn/asyncio/lifespan.py:31> exception=SystemExit(-2)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1423, in run
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/hypercorn/asyncio/lifespan.py", line 43, in handle_lifespan
    await self.app(
  File "/usr/local/lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1902, in __call__
    await self.asgi_app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1928, in asgi_app
    await asgi_handler(receive, send)
  File "/usr/local/lib/python3.11/site-packages/quart/asgi.py", line 311, in __call__
    await self.app.startup()
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1936, in startup
    await self.ensure_async(func)()
  File "/app/platforms/onebot_bot.py", line 261, in startup
    await botManager.login()
  File "/app/manager/bot.py", line 124, in login
    exit(-2)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: -2
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
2023-04-01 19:25:11,888 child 'xterm -e 'python bot.py 2>&1 | tee /tmp/log.txt'' with pid 44 has terminated
2023-04-01 19:25:11,889 all children have exited and --exit-with-children was specified, exiting
2023-04-01 19:25:11,889 xpra X11 seamless server is terminating
2023-04-01 19:25:11,911 closing tcp socket '0.0.0.0:14500'
2023-04-01 19:25:11,912 removing unix domain socket '/run/user/1000/xpra/VM-0-10-opencloudos-0'
2023-04-01 19:25:11,912 removing unix domain socket '/tmp/0/socket'
2023-04-01 19:25:11,912 killing xvfb with pid 12

**运行环境:**  
- 操作系统：OpenCloudOS 8.6
- Docker：Docker version 23.0.2, build 569dd73
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by ZS629** [comment]
一大段文字看的好难受。建议截图QWQ

**Comment by q23339860** [comment]
![image](https://user-images.githubusercontent.com/58033184/229312799-95096e82-9c87-44b7-8aec-e8f1d36c17df.png)

**Comment by q23339860** [comment]
![image](https://user-images.githubusercontent.com/58033184/229312818-846d5264-5a70-4724-82b6-d1c1d6d2c453.png)

**Comment by q23339860** [comment]
> 一大段文字看的好难受。建议截图QWQ

兄弟能看出到底什么问题吗？

**Comment by ZS629** [comment]
其中
"No module named 'paramiko'" 表示缺少 paramiko 模块；
"No module named 'pyinotify'" 表示缺少 pyinotify 模块；
"No module named 'xdg'" 表示缺少 xdg 模块。
需要安装这些缺少的模块，可以使用 pip 等包管理器来安装这些模块
 "Warning: cannot enable SSH socket upgrades" 提示您无法启用 SSH socket 升级。这可能会导致连接到 xpra 服务器的客户端无法使用 SSH 连接。如果您需要使用 SSH 连接，需要使用 xpra 服务器的另一种方式，例如使用 TCP 或 SSL/TLS 连接。或者，如果您在使用 ssh 连接，请检查您的系统和网络配置，确保 ssh 可以正常工作。

"no uinput module (not usually needed)" 表示 uinput 模块通常不需要。如果您确实需要它，需要确保您的系统上已安装了该模块，并且权限设置正确。
"Warning: socket directory '/tmp/0' expected permissions 700 but found 750" 表示 socket 目录的权限设置不正确。您需要使用 chmod 命令将权限设置为 700： chmod 700 /tmp/0。
..............

具体的我也不太清楚，可以看看这个文档
https://chatgpt-qq.lss233.com/

**Comment by q23339860** [comment]
咦，我不是下了这些包吗···

**Comment by ZS629** [comment]
根据你给出的报错提示，应该就是缺少这些包，然后运行环境异常
Traceback抛出错误：
可以大致判断问题是出在 asyncio 模块的使用上，可能是一个异步调用的返回值没有正确处理，导致程序执行出错。应该是运行环境的原因导致的错误异常

**Comment by ZS629** [comment]
还有兄弟你这个运行环境

操作系统：OpenCloudOS 8.6
Docker：Docker version 23.0.2, build 569dd73
项目版本：？
这是Linux还是Windows

**Comment by q23339860** [comment]
linux






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vincent ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 凌晨4:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] openai账号无法登陆，我实在找不出原因 (Issue #496)





 
还有兄弟你这个运行环境
 
操作系统：OpenCloudOS 8.6
 Docker：Docker version 23.0.2, build 569dd73
 项目版本：？
 这是Linux还是Windows

**Comment by ZS629** [comment]
可以用这个一键部署
https://chatgpt-qq.lss233.com/bu-shu-jiao-cheng/kuai-su-bu-shu-jiao-cheng/linux-yi-jian-bu-shu-jiao-cheng

**Comment by q23339860** [comment]
![image](https://user-images.githubusercontent.com/58033184/229313644-024c3878-4319-4856-b62d-852a08134700.png)

**Comment by ZS629** [comment]
现在是北京时间2023年4月2日04:57:43
很晚了，我要睡觉了，实在不能解决问题明天问问作者大大吧QAQ

**Comment by q23339860** [comment]
不上线睡不着

**Comment by q23339860** [comment]
谢谢回复了·····我再想想办法

**Comment by ZS629** [comment]
直接执行

```bash
pip install -r requirements.txt
```

试试

如果不行就把pip换成pip3

**Comment by q23339860** [comment]
解决了，还是改dockerfile

这个输出显示，您成功地运行了容器，但它仍然缺少一些模块，如 'paramiko'、'pyinotify' 和 'xdg'。为了解决这个问题，您需要更新 Dockerfile，以便在构建镜像时安装这些模块。

首先，找到项目的 Dockerfile。然后，在 Dockerfile 中，找到安装 Python 包的部分，通常是一个 RUN pip install 命令。

将以下内容添加到 Dockerfile 中的 Python 包安装部分：

Copy code
paramiko \
pyinotify \
python3-xdg \
确保每个包都位于新的一行上，并且以反斜杠（\）结尾，除了最后一个包。然后，保存更改后的 Dockerfile。

重新构建镜像：

bash
Copy code
docker build -t lss233/chatgpt-mirai-qq-bot:browser-version .
然后，使用新构建的镜像重新运行容器：

bash
Copy code
docker run --name mirai-chatgpt-bot-2 -e XPRA_PASSWORD=iwanttofly93 -v /root/config.cfg:/app/config.cfg --network host lss233/chatgpt-mirai-qq-bot:browser-version
现在，容器应该有所需的模块，并且不再显示这些警告。

**Comment by q23339860** [comment]
![image](https://user-images.githubusercontent.com/58033184/229315974-8c56b247-8241-41c1-9015-7670cb24c7d9.png)
又出这个问题

**Comment by lss233** [comment]
OpenAI封了查询余额的接口，重新拉一下最新镜像应该可以解决。

**Comment by q23339860** [comment]
> OpenAI封了查询余额的接口，重新拉一下最新镜像应该可以解决。

2.2.6.3吗？

**Comment by lss233** [comment]
2.2.6.4

**Comment by q23339860** [comment]
收到

**Comment by ZS629** [comment]
删除当前秘钥，重新生成试试，或者找一个需要使用秘钥的项目，调试运行一下试试
我仓库里有一个Python项目，你不妨clone下来试试

```bash
git clone https://github.com/ZS629/chatgpt-py.git
```

![image](https://user-images.githubusercontent.com/127756463/229328809-9701dc9c-f252-4760-99ed-066d2f119cda.png)
