### ISSUE TITLE
[BUG] chatgpt调取失败

### ISSUE THREAD

**Issue by q23339860** [lss233/chatgpt-mirai-qq-bot#501]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

```
**表现**  
2023-04-02 02:56:40.186 | DEBUG    | platforms.onebot_bot:_:125 - 私聊消息：你好
2023-04-02 02:56:40.187 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-04-02 02:56:40.187 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-04-02 02:56:40.187 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
2023-04-02 02:56:41.057 | ERROR    | universal:request:230 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):

  File "/app/bot.py", line 32, in <module>
    main()
    └ <function main at 0x7f5bcfa8af20>

  File "/app/platforms/onebot_bot.py", line 300, in main
    bot.run(host=config.onebot.reverse_ws_host, port=config.onebot.reverse_ws_port)
    │   │        │      │      │                     │      │      └ 8848
    │   │        │      │      │                     │      └ Onebot(qq=3141541725, manager_qq=153565283, reverse_ws_host='0.0.0.0', reverse_ws_port=8848)
    │   │        │      │      │                     └ <unprintable Config object>
    │   │        │      │      └ '0.0.0.0'
    │   │        │      └ Onebot(qq=3141541725, manager_qq=153565283, reverse_ws_host='0.0.0.0', reverse_ws_port=8848)
    │   │        └ <unprintable Config object>
    │   └ <function CQHttp.run at 0x7f5bd0b25120>
    └ <aiocqhttp.CQHttp object at 0x7f5bd1979790>

  File "/usr/local/lib/python3.11/site-packages/aiocqhttp/__init__.py", line 222, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
    │    │           │        │          │      │       └ {'use_reloader': False}
    │    │           │        │          │      └ ()
    │    │           │        │          └ 8848
    │    │           │        └ '0.0.0.0'
    │    │           └ <function Quart.run at 0x7f5bd0af76a0>
    │    └ <Quart ''>
    └ <aiocqhttp.CQHttp object at 0x7f5bd1979790>
  File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1423, in run
    loop.run_until_complete(asyncio.gather(*tasks))
    │    │                  │       │       └ [<Task pending name='Task-1' coro=<serve() running at /usr/local/lib/python3.11/site-packages/hypercorn/asyncio/__init__.py:4...
    │    │                  │       └ <function gather at 0x7f5bd3ed3920>
    │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x7f5bd3ee8680>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f5bd3ee85e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f5bd3eea3e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f5bd3e38900>
    └ <Handle Task.task_wakeup(<Future finished result=False>)>
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=False>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=False>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=False>)>

> File "/app/universal.py", line 179, in request
    async for rendered in task:
                          └ <async_generator object ConversationContext.ask at 0x7f5bcfa5d6d0>

  File "/app/conversation.py", line 151, in ask
    async for item in self.adapter.ask(prompt):
                      │    │       │   └ '你好'
                      │    │       └ <function ChatGPTAPIAdapter.ask at 0x7f5bd035ac00>
                      │    └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x7f5bcfaae050>
                      └ <conversation.ConversationContext object at 0x7f5bcfaae090>

  File "/app/adapter/chatgpt/api.py", line 100, in ask
    raise resp
          └ JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

  File "/app/adapter/chatgpt/api.py", line 73, in ask_sync
    for resp in self.bot.ask_stream(prompt, role=self.hashed_user_id, convo_id=self.session_id):
                │    │   │          │            │    │                        │    └ 'friend-153565283'
                │    │   │          │            │    │                        └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x7f5bcfaae050>
                │    │   │          │            │    └ 'user-0a4784dd36b0a5fc'
                │    │   │          │            └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x7f5bcfaae050>
                │    │   │          └ '你好'
                │    │   └ <function Chatbot.ask_stream at 0x7f5bd035a340>
                │    └ <revChatGPT.V3.Chatbot object at 0x7f5bcfaaf050>
                └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x7f5bcfaae050>

  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V3.py", line 195, in ask_stream
    resp: dict = json.loads(line)
                 │    │     └ 'ype html><html data-adblockkey="MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANDrp2lz7AOmADaN8tA50LsWcjLFyQFcb/P2Txc58oYOeILb3vBw7J6f4pam...
                 │    └ <function loads at 0x7f5bd3c42020>
                 └ <module 'json' from '/usr/local/lib/python3.11/json/__init__.py'>
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ 'ype html><html data-adblockkey="MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANDrp2lz7AOmADaN8tA50LsWcjLFyQFcb/P2Txc58oYOeILb3vBw7J6f4pam...
           │                └ <function JSONDecoder.decode at 0x7f5bd3c41940>
           └ <json.decoder.JSONDecoder object at 0x7f5bd3c4c690>
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ 'ype html><html data-adblockkey="MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANDrp2lz7AOmADaN8tA50LsWcjLFyQFcb/P2Txc58oYOeILb3vBw7J6f4pam...
               │    │          │      └ <built-in method match of re.Pattern object at 0x7f5bd3c386c0>
               │    │          └ 'ype html><html data-adblockkey="MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANDrp2lz7AOmADaN8tA50LsWcjLFyQFcb/P2Txc58oYOeILb3vBw7J6f4pam...
               │    └ <function JSONDecoder.raw_decode at 0x7f5bd3c419e0>
               └ <json.decoder.JSONDecoder object at 0x7f5bd3c4c690>
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ 'ype html><html data-adblockkey="MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANDrp2lz7AOmADaN8tA50LsWcjLFyQFcb/P2Txc58oYOeILb3vBw7J6f4pam...
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-04-02 02:56:41.069 | DEBUG    | platforms.onebot_bot:respond:89 - [OneBot] 尝试发送消息：出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
原因：Expecting value: line 1 column 1 (char 0)
2023-04-02 02:56:41.567 | DEBUG    | middlewares.timeout:on_respond:40 - [Timeout] 取消计时……
```

**运行环境:**  
- 操作系统：OpenCloudOS 8.6
- Docker： Docker version 23.0.2, build 569dd73
- 项目版本：2.2.6.4

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 正常聊天回复出问题

**预期行为**  
调api回复内容

**截图**  
![image](https://user-images.githubusercontent.com/58033184/229330217-c33c4eaa-151f-4475-ab8d-461de07b5a06.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
看样子是 OpenAI 的后端返回了非 JSON 的内容。 你有设置过 api_endpoint 吗？ 没有的话那就是 OpenAI 的问题。

**Comment by lss233** [comment]
看样子是 OpenAI 的后端返回了非 JSON 的内容。 你有设置过 api_endpoint 吗？ 没有的话那就是 OpenAI 的问题。

**Comment by q23339860** [comment]
![image](https://user-images.githubusercontent.com/58033184/229330843-60d4b103-3833-4a1f-89f4-08c597a84255.png)
这样对不？

**Comment by lss233** [comment]
这个就是默认的配置。

**Comment by q23339860** [comment]
> 这个就是默认的配置，等价于没写。

那是需要从官网找接入点吗

**Comment by lss233** [comment]
> > 这个就是默认的配置，等价于没写。
> 
> 那是需要从官网找接入点吗

这个就是官网的接入点。

**Comment by q23339860** [comment]
接管网的接入点之后配置文件需要怎么改呢？

> > > 这个就是默认的配置，等价于没写。
> > 
> > 
> > 那是需要从官网找接入点吗
> 
> 这个就是官网的接入点，也就是说你的问题是 OpenAI 官方的问题。

**Comment by lss233** [comment]
不需要进行任何修改，你的问题是 OpenAI 官方的问题。

**Comment by lingboshuiyue** [comment]
> 不需要进行任何修改，你的问题是 OpenAI 官方的问题。

这个是不是拼写错了？我从2.2.5 升级上来后照着文档操作加了 api_endpoint 后发现也出现同样的问题，看了下 2.2.5 版本用的是 https://api.openai.com/v1 这个，删掉 api_endpoint 或将其改为  https://api.openai.com/v1 就没问题了。。。
![image](https://user-images.githubusercontent.com/24492313/229353482-227b5731-cd02-4440-bf59-d6978a19da91.png)
![image](https://user-images.githubusercontent.com/24492313/229353602-ef0595e5-8c80-4d32-a9f6-18027508f495.png)

**Comment by q23339860** [comment]
这……



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月2日(周日) 晚上8:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] chatgpt调取失败 (Issue #501)




  
不需要进行任何修改，你的问题是 OpenAI 官方的问题。
  
这个是不是拼写错了？我从2.2.5 升级上来后照着文档操作加了 api_endpoint 后发现也出现同样的问题，看了下 2.2.5 版本用的是 https://api.openai.com/v1 这个，删掉 api_endpoint 或将其改为  https://api.openai.com/v1 就没问题了。。。

**Comment by lingboshuiyue** [comment]
> 这……
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年4月2日(周日) 晚上8:46 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] chatgpt调取失败 (Issue #501) 不需要进行任何修改，你的问题是 OpenAI 官方的问题。 这个是不是拼写错了？我从2.2.5 升级上来后照着文档操作加了 api_endpoint 后发现也出现同样的问题，看了下 2.2.5 版本用的是 https://api.openai.com/v1 这个，删掉 api_endpoint 或将其改为 https://api.openai.com/v1 就没问题了。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

照理说如果接的是官网的，这二级域名也太怪了。。。

**Comment by lss233** [comment]
确实是打错了  感谢提醒!
