### ISSUE TITLE
[BUG] 文字转语音功能在使用bing时异常

### ISSUE THREAD

**Issue by iamyx123** [lss233/chatgpt-mirai-qq-bot#505]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
文字转语音功能在使用bing时异常

**运行环境:**  
- 操作系统：Win11
- Docker： ？
- 项目版本：v2.3.0-pre-1

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 给机器人发送消息
2. 回复正常消息
3. 继续回复错误消息，并输出错误信息的语音

**预期行为**  
回复正常消息和语音

**截图**  
![IMG_7625(20230402-203331)](https://user-images.githubusercontent.com/88130457/229353050-6abbc248-ed6a-4795-ad1a-310b7b364011.PNG)
报错：
```
 1651000187: [RECV][33(1470667317)] -> 你好
2023-04-02 20:23:57.264 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-04-02 20:23:57.265 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-04-02 20:23:57.266 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
2023-04-02 20:24:06.723 | DEBUG    | adapter.ms.bing:ask:78 - [Bing AI 响应] 你好，这里是必应。我可以用中文和你交流。😊

剩余回复数：1 / 20
Loading page (1/2)
Rendering (2/2)
Done
2023-04-02 20:24:08.958 | DEBUG    | middlewares.timeout:handle_respond:46 - [Timeout] 取消计时……
2023-04-02 20:24:09.966 | INFO     | graia.ariadne.model:log:82 - 1651000187: [SEND][x(1470667317)] <- [图片]
2023-04-02 20:24:09.967 | ERROR    | universal:request:230 - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\bot.py", line 32, in <module>
    main()
    └ <function main at 0x0000026831AE2C00>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\platforms\ariadne_bot.py", line 303, in main
    app.launch_blocking()
    │   └ <classmethod(<function Ariadne.launch_blocking at 0x00000268300C2D40>)>
    └ <graia.ariadne.app.Ariadne object at 0x000002682FBB1F10>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\python3.11\Lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x00000268300B5C60>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x000002683185E150>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x000002682FCA13A0>
    │   └ <launart.manager.Launart object at 0x0000026831AD6990>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\python3.11\Lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chat...
    │    └ <function BaseEventLoop.run_until_complete at 0x000002682D32C9A0>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>
  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)
  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()
  File "asyncio\base_events.py", line 1922, in _run_once
  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...': 'success'}>)>
> File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\universal.py", line 189, in request
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000026831BF7100>
          │      │           │       └ MessageChain([Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylB...
          │      │           └ '你好'
          │      └ 'friend-1470667317'
          └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000026831C4C9A0>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\universal.py", line 71, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000026831C4C5E0>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000026831BF7100>
          │ │              │           │        └ MessageChain([Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylB...
          │ │              │           └ '你好'
          │ │              └ 'friend-1470667317'
          │ └ <function Middleware.handle_respond at 0x0000026831853F60>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x000002683185F510>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000026831BF7100>
          │      │           │       └ MessageChain([Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylB...
          │      │           └ '你好'
          │      └ 'friend-1470667317'
          └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000026831C4C5E0>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\universal.py", line 71, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000026831C4CAE0>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000026831BF7100>
          │ │              │           │        └ MessageChain([Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylB...
          │ │              │           └ '你好'
          │ │              └ 'friend-1470667317'
          │ └ <function MiddlewareBaiduCloud.handle_respond at 0x000002683186CFE0>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x0000026831867B10>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\middlewares\baiducloud.py", line 86, in handle_respond
    return await action(session_id, prompt, rendered, respond)
                 │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000026831BF7100>
                 │      │           │       └ MessageChain([Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylB...
                 │      │           └ '你好'
                 │      └ 'friend-1470667317'
                 └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000026831C4CAE0>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\universal.py", line 71, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000026831C4C860>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000026831BF7100>
          │ │              │           │        └ MessageChain([Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylB...
          │ │              │           └ '你好'
          │ │              └ 'friend-1470667317'
          │ └ <function Middleware.handle_respond at 0x0000026831853F60>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x000002683187A610>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000026831BF7100>
          │      │           │       └ MessageChain([Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylB...
          │      │           └ '你好'
          │      └ 'friend-1470667317'
          └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000026831C4C860>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\universal.py", line 71, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.request.<locals>.<lambda> at 0x0000026831BF6D40>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000026831BF7100>
          │ │              │           │        └ MessageChain([Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylB...
          │ │              │           └ '你好'
          │ │              └ 'friend-1470667317'
          │ └ <function MiddlewareTimeout.handle_respond at 0x000002683186D4E0>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x000002682FFEB150>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\middlewares\timeout.py", line 48, in handle_respond
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000026831BF7100>
          │      │           │       └ MessageChain([Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylB...
          │      │           └ '你好'
          │      └ 'friend-1470667317'
          └ <function handle_message.<locals>.request.<locals>.<lambda> at 0x0000026831BF6D40>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\universal.py", line 93, in respond
    await _respond(await get_tts_voice(elem, conversation_context))
          │              │             │     └ <conversation.ConversationContext object at 0x0000026831B0C450>
          │              │             └ Image(base64='iVBORw0KGgoAAAANSUhEUgAAA+gAAAJkCAIAAAANxJykAAB+bElEQVR4nO3de3wU933v/8+shLiZq6SVtIqcxHYiQAqwUGylBD8IwXkEhRBFJY0...
          │              └ <function get_tts_voice at 0x000002683186D6C0>
          └ <function response.<locals>.respond at 0x0000026831BF6C00>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\platforms\ariadne_bot.py", line 67, in respond
    event = await app.send_message(
                  │   └ <function Ariadne.send_message at 0x00000268300CEC00>
                  └ <graia.ariadne.app.Ariadne object at 0x000002682FBB1F10>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\python3.11\Lib\site-packages\graia\ariadne\app.py", line 1948, in send_message
    data: Dict[Any, Any] = {"message": MessageChain(message)}
          │    │    │                  │            └ None
          │    │    │                  └ <class 'graia.ariadne.message.chain.MessageChain'>
          │    │    └ typing.Any
          │    └ typing.Any
          └ typing.Dict
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\python3.11\Lib\site-packages\graia\ariadne\message\chain.py", line 139, in __init__
    __root__=self.build_chain((__root__, *elements)),
             │    │            │          └ ()
             │    │            └ None
             │    └ <staticmethod(<function MessageChain.build_chain at 0x000002682FF79F80>)>
             └ <unprintable MessageChain object>
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\python3.11\Lib\site-packages\graia\ariadne\message\chain.py", line 91, in build_chain
    element_list.extend(MessageChain.build_chain(o))
    │            │      │            │           └ None
    │            │      │            └ <staticmethod(<function MessageChain.build_chain at 0x000002682FF79F80>)>
    │            │      └ <class 'graia.ariadne.message.chain.MessageChain'>
    │            └ <method 'extend' of 'list' objects>
    └ []
  File "C:\12333\Windows-quickstart-refs.tags.v2.3.0-pre-1\chatgpt\python3.11\Lib\site-packages\graia\ariadne\message\chain.py", line 86, in build_chain
    for o in obj:
             └ None
TypeError: 'NoneType' object is not iterable
Loading page (1/2)
Rendering (2/2)
Done
2023-04-02 20:24:11.519 | INFO     | graia.ariadne.model:log:82 - 1651000187: [SEND][x(1470667317)] <- [图片]
2023-04-02 20:24:11.521 | DEBUG    | utils.text_to_speech:get_tts_voice:20 - [TextToSpeech] 开始转换语音 - C:\Users\55821\AppData\Local\Temp\tmpigifi6i4.wav - friend-1470667317
2023-04-02 20:24:30.400 | SUCCESS  | utils.vits_tts:save_voice_file:64 - [VITS TTS] 文件已保存到：C:\Users\55821\AppData\Local\Temp\tmpigifi6i4.wav.silk
2023-04-02 20:24:30.401 | DEBUG    | utils.text_to_speech:get_tts_voice:26 - [TextToSpeech] 语音转换完成 - C:\Users\55821\AppData\Local\Temp\tmpigifi6i4.wav.silk - friend-1470667317
```
**其他内容**  
未开启分段发送，使用图片模式

**Comment by lss233** [comment]
是不是在发送图片之后出现问题？

**Comment by iamyx123** [comment]
> 是不是在发送图片之后出现问题？

对，发送完正常的回复之后出现问题

**Comment by tamakyi** [comment]
![Screenshot_2023-04-02-21-15-11-085_com tencent mobileqq-edit](https://user-images.githubusercontent.com/25850853/229355129-cd6a4d17-cffd-47eb-b8e2-940dadfde9d6.jpg)
一样，在第二句回复的时候都会报错

**Comment by lss233** [comment]
问题已确认，我正在修复中，请稍等

**Comment by lss233** [comment]
可以拉一下最新的开发分支测试下 BUG 是否已经解决.

**Comment by iamyx123** [comment]
> 可以拉一下最新的开发分支测试下 BUG 是否已经解决.

最新开发分支好像在回复图片回答后会卡在开始计时，不会继续文字转语音

> 2023-04-02 21:30:31.738 | INFO     | graia.ariadne.model:log:82 - 1651000187: [RECV][33(1470667317)] -> 你好
2023-04-02 21:30:33.989 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-04-02 21:30:33.990 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-04-02 21:30:33.991 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
2023-04-02 21:30:50.243 | DEBUG    | adapter.ms.bing:ask:78 - [Bing AI 响应] 你好，这里是必应。我可以用中文和你交流。😊
剩余回复数：1 / 20
Loading page (1/2)
Rendering (2/2)
Done
2023-04-02 21:30:52.301 | DEBUG    | middlewares.timeout:handle_respond:46 - [Timeout] 取消计时……
2023-04-02 21:30:53.035 | INFO     | graia.ariadne.model:log:82 - 1651000187: [SEND][孙逸轩(1470667317)] <- [图片]
2023-04-02 21:30:53.038 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……

**Comment by lss233** [comment]
我这里测试没有问题了，你可以再确认一下，麻烦啦！

**Comment by iamyx123** [comment]
使用最新代码好像还是有问题，无法使用vits

> graiax-silkcoder: 0.3.6
graia-amnesia: 0.7.1
graia-ariadne: 0.11.3
graia-broadcast: 0.19.2
launart: 0.6.3
statv: 0.3.2
2023-04-02 23:12:48.363 | INFO     | launart.manager:_launchable_task_done_callback:68 - [elizabeth.connection.1651000187.websocket_server_connection] completed.
2023-04-02 23:12:48.364 | INFO     | graia.amnesia.builtins.aiohttp:launch:513 - starting server on 0.0.0.0:8554
2023-04-02 23:12:48.365 | SUCCESS  | launart.manager:launch:384 - Layer #1:[http.server/aiohttp, http.client/aiohttp, cache.client/memcache] preparation completed.
2023-04-02 23:12:48.366 | INFO     | platforms.ariadne_bot:start_background:194 - ChatGPT for QQ 登录账号中……
2023-04-02 23:12:48.367 | INFO     | manager.bot:login_bing:151 - 正在解析第 1 个 Bing 账号
2023-04-02 23:12:48.368 | SUCCESS  | manager.bot:login_bing:156 - 解析成功！
2023-04-02 23:12:48.369 | SUCCESS  | manager.bot:login_bing:162 - 成功解析 1/1 个 Bing 账号！
2023-04-02 23:12:48.369 | INFO     | manager.bot:login_yiyan:206 - 正在解析第 1 个 文心一言 账号
2023-04-02 23:12:48.371 | SUCCESS  | manager.bot:login_yiyan:211 - 解析成功！
2023-04-02 23:12:48.372 | SUCCESS  | manager.bot:login_yiyan:217 - 成功解析 1/1 个 文心一言 账号！
2023-04-02 23:12:48.373 | INFO     | manager.bot:login:128 - AI 类型：chatgpt-web - 可用账号： 0 个
2023-04-02 23:12:48.374 | INFO     | manager.bot:login:128 - AI 类型：openai-api - 可用账号： 0 个
2023-04-02 23:12:48.375 | INFO     | manager.bot:login:128 - AI 类型：poe-web - 可用账号： 0 个
2023-04-02 23:12:48.376 | INFO     | manager.bot:login:128 - AI 类型：bing-cookie - 可用账号： 1 个
2023-04-02 23:12:48.377 | INFO     | manager.bot:login:128 - AI 类型：bard-cookie - 可用账号： 0 个
2023-04-02 23:12:48.378 | INFO     | manager.bot:login:128 - AI 类型：yiyan-cookie - 可用账号： 1 个
2023-04-02 23:12:48.379 | INFO     | manager.bot:login:128 - AI 类型：chatglm-api - 可用账号： 0 个
2023-04-02 23:12:48.379 | INFO     | platforms.ariadne_bot:start_background:199 - ChatGPT for QQ 登录账号成功
2023-04-02 23:12:48.381 | INFO     | platforms.ariadne_bot:start_background:200 - 尝试从 Mirai 服务中读取机器人 QQ 的 session key……
2023-04-02 23:12:48.382 | INFO     | platforms.ariadne_bot:start_background:202 - [提示] 当前为反向 ws 模式，请确保你的 mirai api http 设置了正确的 reverse-ws adapter 配置
2023-04-02 23:12:48.383 | INFO     | platforms.ariadne_bot:start_background:203 - [提示] 配置不正确会导致 Mirai 端出现错误提示。
2023-04-02 23:12:48.384 | SUCCESS  | launart.manager:launch:384 - Layer #3:[elizabeth.service] preparation completed.
2023-04-02 23:12:48.384 | INFO     | launart.manager:launch:389 - All components prepared, start blocking phase.
2023-04-02 23:13:04.019 | SUCCESS  | graia.ariadne.connection.ws:_:64 - Successfully got session key
2023-04-02 23:13:33.333 | INFO     | graia.ariadne.model:log:82 - 1651000187: [RECV][33(1470667317)] -> 你在哪里
2023-04-02 23:13:35.421 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-04-02 23:13:35.423 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-04-02 23:13:35.425 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
2023-04-02 23:13:46.771 | DEBUG    | adapter.ms.bing:ask:78 - [Bing AI 响应] 你好，这里是必应。我在互联网上。😊
剩余回复数：1 / 20
Loading page (1/2)
Rendering (2/2)
Done
2023-04-02 23:13:48.204 | DEBUG    | middlewares.timeout:handle_respond:46 - [Timeout] 取消计时……
2023-04-02 23:13:49.175 | INFO     | graia.ariadne.model:log:82 - 1651000187: [SEND][孙逸轩(1470667317)] <- [图片]
2023-04-02 23:13:49.179 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
2023-04-02 23:16:01.674 | INFO     | graia.ariadne.model:log:82 - 1651000187: [RECV][33(1470667317)] -> 那你能干什么
2023-04-02 23:16:01.675 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-04-02 23:16:01.676 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-04-02 23:16:01.678 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
2023-04-02 23:16:10.606 | DEBUG    | adapter.ms.bing:ask:78 - [Bing AI 响应] 我能为你提供信息，娱乐，创意和建议。我也能
生成诗歌，故事，代码，歌词等等。
剩余回复数：2 / 20
Loading page (1/2)
Rendering (2/2)
Done

配置：

> [text_to_speech]
engine = "vits"
always = true
default = "1000"
[vits]
api_url = "http://127.0.0.1:23456/voice"
speed = 1.4
lang = "zh"
timeout = 60

**Comment by lss233** [comment]
你这里面似乎没有语音部分的功能了……，你有重新拉取代码吗？ `docker-compose pull && docker-compose up -d`

**Comment by iamyx123** [comment]
> 你这里面似乎没有语音部分的功能了……，你有重新拉取代码吗？ `docker-compose pull && docker-compose up -d`

我使用的是windows的快速部署包https://github.com/lss233/chatgpt-mirai-qq-bot/actions/runs/4589328019

**Comment by lss233** [comment]
我知道了，你开了图片模式。 语音功能是不会读出图片里的文字的。

**Comment by tamakyi** [comment]
linux源码部署 pull了dev分支 目前已经没有报错。但是我没有用转语音，所以无法确认语音是否正常
