### ISSUE TITLE
POE报错...

### ISSUE THREAD

**Issue by yqs6666** [lss233/chatgpt-mirai-qq-bot#506]
启动之后过几分钟就出现如下报错信息：
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: Connection to remote host was lost.
chatgpt-qq-chatgpt-1     | ERROR:websocket:Connection to remote host was lost. - goodbye
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: Connection to remote host was lost.
chatgpt-qq-chatgpt-1     | ERROR:websocket:Connection to remote host was lost. - goodbye
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: Connection to remote host was lost.
chatgpt-qq-chatgpt-1     | ERROR:websocket:Connection to remote host was lost. - goodbye
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: Connection to remote host was lost.
chatgpt-qq-chatgpt-1     | ERROR:websocket:Connection to remote host was lost. - goodbye
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: Connection to remote host was lost.
chatgpt-qq-chatgpt-1     | ERROR:websocket:Connection to remote host was lost. - goodbye
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: Connection to remote host was lost.
chatgpt-qq-chatgpt-1     | ERROR:websocket:Connection to remote host was lost. - goodbye
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: Connection to remote host was lost.
chatgpt-qq-chatgpt-1     | ERROR:websocket:Connection to remote host was lost. - goodbye
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: Connection to remote host was lost.
chatgpt-qq-chatgpt-1     | ERROR:websocket:Connection to remote host was lost. - goodbye
此时还能正常响应、回复消息。再过段时间，
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | 2023-04-02 13:57:58.221 | ERROR    | universal:request:230 - Response timed out.
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/poe.py", line 256, in send_message
chatgpt-qq-chatgpt-1     |     message = self.message_queues[human_message_id].get(timeout=timeout)
chatgpt-qq-chatgpt-1     |               │    │              │                             └ 20
chatgpt-qq-chatgpt-1     |               │    │              └ 208314205
chatgpt-qq-chatgpt-1     |               │    └ {}
chatgpt-qq-chatgpt-1     |               └ <poe.Client object at 0x7f385cfe34d0>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/queue.py", line 179, in get
chatgpt-qq-chatgpt-1     |     raise Empty
chatgpt-qq-chatgpt-1     |           └ <class '_queue.Empty'>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | _queue.Empty
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | During handling of the above exception, another exception occurred:
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/bot.py", line 32, in <module>
chatgpt-qq-chatgpt-1     |     main()
chatgpt-qq-chatgpt-1     |     └ <function main at 0x7f385b155440>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/platforms/ariadne_bot.py", line 336, in main
chatgpt-qq-chatgpt-1     |     app.launch_blocking()
chatgpt-qq-chatgpt-1     |     │   └ <classmethod(<function Ariadne.launch_blocking at 0x7f385dc6e7a0>)>
chatgpt-qq-chatgpt-1     |     └ <graia.ariadne.app.Ariadne object at 0x7f385e5e2cd0>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
chatgpt-qq-chatgpt-1     |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
chatgpt-qq-chatgpt-1     |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
chatgpt-qq-chatgpt-1     |     │   │              │                    │   │       └ <property object at 0x7f385dc66430>
chatgpt-qq-chatgpt-1     |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7f385dcc0c50>
chatgpt-qq-chatgpt-1     |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1     |     │   │              └ <function Launart.launch_blocking at 0x7f385e00fba0>
chatgpt-qq-chatgpt-1     |     │   └ <launart.manager.Launart object at 0x7f385cfab9d0>
chatgpt-qq-chatgpt-1     |     └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/launart/manager.py", line 494, in launch_blocking
chatgpt-qq-chatgpt-1     |     loop.run_until_complete(launch_task)
chatgpt-qq-chatgpt-1     |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.11/site-packages/launart/manager...
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7f38609c8680>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
chatgpt-qq-chatgpt-1     |     self.run_forever()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7f38609c85e0>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
chatgpt-qq-chatgpt-1     |     self._run_once()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7f38609ca3e0>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
chatgpt-qq-chatgpt-1     |     handle._run()
chatgpt-qq-chatgpt-1     |     │      └ <function Handle._run at 0x7f3860918900>
chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7f385905b250>()>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
chatgpt-qq-chatgpt-1     |     self._context.run(self._callback, *self._args)
chatgpt-qq-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f385905b250>()>
chatgpt-qq-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7f385905b250>()>
chatgpt-qq-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7f385905b250>()>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | > File "/app/universal.py", line 179, in request
chatgpt-qq-chatgpt-1     |     async for rendered in task:
chatgpt-qq-chatgpt-1     |                           └ <async_generator object ConversationContext.ask at 0x7f38593668a0>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 151, in ask
chatgpt-qq-chatgpt-1     |     async for item in self.adapter.ask(prompt):
chatgpt-qq-chatgpt-1     |                       │    │       │   └ '你好'
chatgpt-qq-chatgpt-1     |                       │    │       └ <function PoeAdapter.ask at 0x7f385d25b100>
chatgpt-qq-chatgpt-1     |                       │    └ <adapter.quora.poe.PoeAdapter object at 0x7f385dd3d350>
chatgpt-qq-chatgpt-1     |                       └ <conversation.ConversationContext object at 0x7f385c823450>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/adapter/quora/poe.py", line 40, in ask
chatgpt-qq-chatgpt-1     |     for final_resp in self.poe_client.send_message(chatbot=self.poe_bot.value, message=msg):
chatgpt-qq-chatgpt-1     |         │             │    │          │                    │    │       │              └ '你好'
chatgpt-qq-chatgpt-1     |         │             │    │          │                    │    │       └ <enum.property object at 0x7f3861123890>
chatgpt-qq-chatgpt-1     |         │             │    │          │                    │    └ <PoeBot.Sage: 'capybara'>
chatgpt-qq-chatgpt-1     |         │             │    │          │                    └ <adapter.quora.poe.PoeAdapter object at 0x7f385dd3d350>
chatgpt-qq-chatgpt-1     |         │             │    │          └ <function Client.send_message at 0x7f385f3f5080>
chatgpt-qq-chatgpt-1     |         │             │    └ <poe.Client object at 0x7f385cfe34d0>
chatgpt-qq-chatgpt-1     |         │             └ <adapter.quora.poe.PoeAdapter object at 0x7f385dd3d350>
chatgpt-qq-chatgpt-1     |         └ None
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/poe.py", line 260, in send_message
chatgpt-qq-chatgpt-1     |     raise RuntimeError("Response timed out.")
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | RuntimeError: Response timed out.
chatgpt-qq-chatgpt-1     | 2023-04-02 13:57:58.384 | INFO     | graia.ariadne.model:log:82 - 530144563: [SEND][清和🍃(2193215221)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n原因：Response timed out.
chatgpt-qq-chatgpt-1     | 2023-04-02 13:57:58.384 | DEBUG    | middlewares.timeout:on_respond:40 - [Timeout] 取消计时……
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'
chatgpt-qq-chatgpt-1     | WARNING:root:Websocket returned error: 'messages'
chatgpt-qq-chatgpt-1     | ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x7f385cfe34d0>>: 'messages'

**Comment by lss233** [comment]
`RuntimeError: Response timed out.` 看样子是你连接到 POE 服务器超时了。

**Comment by Winnie0408** [comment]
同遇到这个问题，日志中会输出大量相同 （约1000行）的报错信息（具体见下），但似乎对AI的正常使用没有影响，且go-cqhttp端没有任何报错。

报错为：
`ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x3ff7fb005e0>>: 'messages'
WARNING:root:Websocket returned error: 'messages'
`

**Comment by yqs6666** [comment]
有解决方案吗

**Comment by jijunhao** [comment]
这个是poe-api那个包那边的问题，只能等他们升级了

**Comment by lss233** [comment]
已修复
