### ISSUE TITLE
windowsserver2019启动报错

### ISSUE THREAD

**Issue by a2841905265** [lss233/chatgpt-mirai-qq-bot#53]
Traceback (most recent call last):
  File "D:\wx\chatgpt\bot.py", line 18, in <module>
    import chatbot
  File "D:\wx\chatgpt\chatbot.py", line 14, in <module>
    bot = AsyncChatbot(config.openai.dict(exclude_none=True, by_alias=False), conversation_id=None, base_url=config.openai.base_url)
  File "D:\wx\chatgpt\python3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 116, in __init__
    self.refresh_session()
  File "D:\wx\chatgpt\python3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 295, in refresh_session
    asyncio.run(self.get_cf_cookies())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "D:\wx\chatgpt\python3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 370, in get_cf_cookies
    browser = await p.chromium.launch(headless=False)
  File "D:\wx\chatgpt\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 12809, in launch
    await self._impl_obj.launch(
  File "D:\wx\chatgpt\python3.9\lib\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "D:\wx\chatgpt\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "D:\wx\chatgpt\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "D:\wx\chatgpt\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1033\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

D:\wx\chatgpt>

**Comment by lss233** [comment]
报错里面写的很清楚，你需要 `playwright install`
