### ISSUE TITLE
[BUG] 使用VITS文字转语音出现错误

### ISSUE THREAD

**Issue by SternChiri** [lss233/chatgpt-mirai-qq-bot#542]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
昨天（2023.4.4）在本地部署VITS后使用正常，今天（2023.4.5）更新到2.3.0版本后，使用VITS报错“TypeError: list indices must be integers or slices, not str”。

**运行环境:**  
- 操作系统：Windows10
- Docker： 无
- 项目版本：2.3.0

**复现步骤**  
1. 更新到2.3.0后，与此前一样的步骤打开各部分；
2. 与Bot对话后，本应发送语音消息时报错“TypeError: list indices must be integers or slices, not str”。

**预期行为**  
正常发送语音消息。

**截图**  
![image](https://user-images.githubusercontent.com/103919801/230009950-155b907e-08a5-4cba-8ce2-c6e0d1ebeaae.png)
![image](https://user-images.githubusercontent.com/103919801/230010393-e7ff7139-6548-4120-8285-03e8630a9bca.png)
![image](https://user-images.githubusercontent.com/103919801/230010760-9116052c-ea73-4fbe-a930-3834700fe31d.png)
![image](https://user-images.githubusercontent.com/103919801/230010930-88a01ec6-6dcb-4876-8e0f-24ff692ac0c5.png)

**其他内容**  
有看到另一个issue中提到VITS报错，但跟我出现的错误不一样。

**Comment by Haibersut** [comment]
收到，目前缓解措施如下：
将位于./utils下的vits_tts.py的第24行由
```
return json_dict.get(str(given_id), False)
```
改为
```
return given_id
```

**Comment by SternChiri** [comment]
修改后依然报错，控制台日志如下：
```
2023-04-05 16:20:08.828 | ERROR    | universal:request:246 - list indices must be integers or slices, not str
Traceback (most recent call last):

  File "D:\QCG\chatgpt\bot.py", line 46, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-3' coro=<start_task() running at D:\QCG\chatgpt\platforms\onebot_bot.py:268> wait_for=<_GatheringFu...
    │    │                  │       └ <function gather at 0x0000019B19F2E200>
    │    │                  └ <module 'asyncio' from 'D:\\QCG\\chatgpt\\python3.11\\python311.zip\\asyncio\\__init__.pyc'>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000019B1B71F060>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

> File "D:\QCG\chatgpt\universal.py", line 205, in request
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │      │           │       └ MessageChain([Plain(text='非'
          │      │           └ '我'
          │      └ 'group-'
          └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA89800>

  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A480>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │ │              │           │        └ MessageChain([Plain(text='非'
          │ │              │           └ '我'
          │ │              └ 'group-'
          │ └ <function Middleware.handle_respond at 0x0000019B1F88E520>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x0000019B1EF0E750>

  File "D:\QCG\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │      │           │       └ MessageChain([Plain(text='非'
          │      │           └ '我'
          │      └ 'group-'
          └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A480>

  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A840>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │ │              │           │        └ MessageChain([Plain(text='非'
          │ │              │           └ '我'
          │ │              └ 'group-'
          │ └ <function MiddlewareBaiduCloud.handle_respond at 0x0000019B1F88EC00>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x0000019B1EF0E0D0>

  File "D:\QCG\chatgpt\middlewares\baiducloud.py", line 86, in handle_respond
    return await action(session_id, prompt, rendered, respond)
                 │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
                 │      │           │       └ MessageChain([Plain(text='非'
                 │      │           └ '我'
                 │      └ 'group-'
                 └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A840>

  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A3E0>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │ │              │           │        └ MessageChain([Plain(text='非'
          │ │              │           └ '我'
          │ │              └ 'group-'
          │ └ <function Middleware.handle_respond at 0x0000019B1F88E520>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x0000019B1EF0F690>

  File "D:\QCG\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │      │           │       └ MessageChain([Plain(text='非'
          │      │           └ '我'
          │      └ 'group-'
          └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A3E0>

  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.request.<locals>.<lambda> at 0x0000019B1F88C900>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │ │              │           │        └ MessageChain([Plain(text='非'
          │ │              │           └ '我'
          │ │              └ 'group-'
          │ └ <function MiddlewareTimeout.handle_respond at 0x0000019B1F88FB00>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x0000019B1F7A4DD0>

  File "D:\QCG\chatgpt\middlewares\timeout.py", line 48, in handle_respond
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │      │           │       └ MessageChain([Plain(text='非'
          │      │           └ '我'
          │      └ 'group-'
          └ <function handle_message.<locals>.request.<locals>.<lambda> at 0x0000019B1F88C900>

  File "D:\QCG\chatgpt\universal.py", line 95, in respond
    voice = await voice_task
                  └ <Task finished name='Task-50' coro=<get_tts_voice() done, defined at D:\QCG\chatgpt\utils\text_to_speech.py:13> exception=Typ...

  File "D:\QCG\chatgpt\utils\text_to_speech.py", line 25, in get_tts_voice
    if await vits_api_instance.process_message(str(elem), output_file.name):
             │                 │                   │      │           └ 'C:\\Users\\**\\AppData\\Local\\Temp\\tmpmf3yj9j9.silk'
             │                 │                   │      └ <tempfile._TemporaryFileWrapper object at 0x0000019B1ED035D0>
             │                 │                   └ Plain(text='非'
             │                 └ <function VitsAPI.process_message at 0x0000019B1FA8B740>
             └ <utils.vits_tts.VitsAPI object at 0x0000019B1FAC5D50>

  File "D:\QCG\chatgpt\utils\vits_tts.py", line 126, in process_message
    await self.initialize()
          │    └ <function VitsAPI.initialize at 0x0000019B1FA8B1A0>
          └ <utils.vits_tts.VitsAPI object at 0x0000019B1FAC5D50>

  File "D:\QCG\chatgpt\utils\vits_tts.py", line 19, in initialize
    self.id = await self.voice_speakers_check()
    │    │          │    └ <function VitsAPI.voice_speakers_check at 0x0000019B1FA8B420>
    │    │          └ <utils.vits_tts.VitsAPI object at 0x0000019B1FAC5D50>
    │    └ None
    └ <utils.vits_tts.VitsAPI object at 0x0000019B1FAC5D50>

  File "D:\QCG\chatgpt\utils\vits_tts.py", line 45, in voice_speakers_check
    vits_list = json_array["VITS"]
                └ [{'0': '綾地寧々'}, {'1': '在原七海'}, {'2': '小茸'}, {'3': '唐乐吟'}, {'4': '綾瀬花日（加隈亜衣）（12歳。〜ちっちゃなムネのトキメキ〜）'}, {'5': '蒼井結衣（木村珠莉）（12歳。〜ちっち...

TypeError: list indices must be integers or slices, not str
2023-04-05 16:20:08.901 | DEBUG    | platforms.onebot_bot:respond:90 - [OneBot] 尝试发送消息：出现故障！如果这个问题持续出现，请和我说 “你改悔罢” 来回溯到上一条对话，你上一条说的我就当作没看见~
原因：list indices must be integers or slices, not str
2023-04-05 16:20:09.238 | DEBUG    | utils.text_to_speech:get_tts_voice:20 - [TextToSpeech] 开始转换语音 - C:\Users\**\AppData\Local\Temp\tmpdyhr3v9a.wav - group-
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-22' coro=<CQHttp._handle_event_with_response() done, defined at D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\__init__.py:606> exception=TypeError('list indices must be integers or slices, not str')>
Traceback (most recent call last):
  File "D:\QCG\chatgpt\universal.py", line 205, in request
    await action(session_id, prompt, rendered, respond)
  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
  File "D:\QCG\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
  File "D:\QCG\chatgpt\middlewares\baiducloud.py", line 86, in handle_respond
    return await action(session_id, prompt, rendered, respond)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
  File "D:\QCG\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
  File "D:\QCG\chatgpt\middlewares\timeout.py", line 48, in handle_respond
    await action(session_id, prompt, rendered, respond)
  File "D:\QCG\chatgpt\universal.py", line 95, in respond
    voice = await voice_task
            ^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\text_to_speech.py", line 25, in get_tts_voice
    if await vits_api_instance.process_message(str(elem), output_file.name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 126, in process_message
    await self.initialize()
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 19, in initialize
    self.id = await self.voice_speakers_check()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 45, in voice_speakers_check
    vits_list = json_array["VITS"]
                ~~~~~~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\__init__.py", line 608, in _handle_event_with_response
    response = await self._handle_event(payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\__init__.py", line 601, in _handle_event
    filter(lambda r: r is not None, await
                                    ^^^^^
  File "D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\bus.py", line 60, in emit
    results += await run_async_funcs(self._subscribers[event], *args,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\utils.py", line 40, in run_async_funcs
    results += await asyncio.gather(*coros)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\platforms\onebot_bot.py", line 160, in _
    await handle_message(
  File "D:\QCG\chatgpt\universal.py", line 254, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
  File "D:\QCG\chatgpt\universal.py", line 61, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
  File "D:\QCG\chatgpt\middlewares\concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
  File "D:\QCG\chatgpt\universal.py", line 61, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
  File "D:\QCG\chatgpt\middlewares\middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
  File "D:\QCG\chatgpt\universal.py", line 61, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
  File "D:\QCG\chatgpt\middlewares\ratelimit.py", line 26, in handle_request
    await action(session_id, prompt, conversation_context, respond)
  File "D:\QCG\chatgpt\universal.py", line 61, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
  File "D:\QCG\chatgpt\middlewares\timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
  File "asyncio\tasks.py", line 479, in wait_for
  File "D:\QCG\chatgpt\universal.py", line 247, in request
    await respond(config.response.error_format.format(exc=e))
  File "D:\QCG\chatgpt\universal.py", line 95, in respond
    voice = await voice_task
            ^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\text_to_speech.py", line 25, in get_tts_voice
    if await vits_api_instance.process_message(str(elem), output_file.name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 126, in process_message
    await self.initialize()
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 19, in initialize
    self.id = await self.voice_speakers_check()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 45, in voice_speakers_check
    vits_list = json_array["VITS"]
                ~~~~~~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by SternChiri** [comment]
> 收到，目前缓解措施如下： 将位于./utils下的vits_tts.py的第24行由
> 
> ```
> return json_dict.get(str(given_id), False)
> ```
> 
> 改为
> 
> ```
> return given_id
> ```

修改后依然报错，控制台日志如下：
```
2023-04-05 16:20:08.828 | ERROR    | universal:request:246 - list indices must be integers or slices, not str
Traceback (most recent call last):

  File "D:\QCG\chatgpt\bot.py", line 46, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-3' coro=<start_task() running at D:\QCG\chatgpt\platforms\onebot_bot.py:268> wait_for=<_GatheringFu...
    │    │                  │       └ <function gather at 0x0000019B19F2E200>
    │    │                  └ <module 'asyncio' from 'D:\\QCG\\chatgpt\\python3.11\\python311.zip\\asyncio\\__init__.pyc'>
    │    └ <function BaseEventLoop.run_until_complete at 0x0000019B1B71F060>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

> File "D:\QCG\chatgpt\universal.py", line 205, in request
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │      │           │       └ MessageChain([Plain(text='非'
          │      │           └ '我'
          │      └ 'group-'
          └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA89800>

  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A480>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │ │              │           │        └ MessageChain([Plain(text='非'
          │ │              │           └ '我'
          │ │              └ 'group-'
          │ └ <function Middleware.handle_respond at 0x0000019B1F88E520>
          └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x0000019B1EF0E750>

  File "D:\QCG\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │      │           │       └ MessageChain([Plain(text='非'
          │      │           └ '我'
          │      └ 'group-'
          └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A480>

  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A840>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │ │              │           │        └ MessageChain([Plain(text='非'
          │ │              │           └ '我'
          │ │              └ 'group-'
          │ └ <function MiddlewareBaiduCloud.handle_respond at 0x0000019B1F88EC00>
          └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x0000019B1EF0E0D0>

  File "D:\QCG\chatgpt\middlewares\baiducloud.py", line 86, in handle_respond
    return await action(session_id, prompt, rendered, respond)
                 │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
                 │      │           │       └ MessageChain([Plain(text='非'
                 │      │           └ '我'
                 │      └ 'group-'
                 └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A840>

  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A3E0>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │ │              │           │        └ MessageChain([Plain(text='非'
          │ │              │           └ '我'
          │ │              └ 'group-'
          │ └ <function Middleware.handle_respond at 0x0000019B1F88E520>
          └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x0000019B1EF0F690>

  File "D:\QCG\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │      │           │       └ MessageChain([Plain(text='非'
          │      │           └ '我'
          │      └ 'group-'
          └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x0000019B1FA8A3E0>

  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
          │ │              │           │        │         │        └ <function handle_message.<locals>.request.<locals>.<lambda> at 0x0000019B1F88C900>
          │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │ │              │           │        └ MessageChain([Plain(text='非'
          │ │              │           └ '我'
          │ │              └ 'group-'
          │ └ <function MiddlewareTimeout.handle_respond at 0x0000019B1F88FB00>
          └ <middlewares.timeout.MiddlewareTimeout object at 0x0000019B1F7A4DD0>

  File "D:\QCG\chatgpt\middlewares\timeout.py", line 48, in handle_respond
    await action(session_id, prompt, rendered, respond)
          │      │           │       │         └ <function handle_message.<locals>.respond at 0x0000019B1FA89F80>
          │      │           │       └ MessageChain([Plain(text='非'
          │      │           └ '我'
          │      └ 'group-'
          └ <function handle_message.<locals>.request.<locals>.<lambda> at 0x0000019B1F88C900>

  File "D:\QCG\chatgpt\universal.py", line 95, in respond
    voice = await voice_task
                  └ <Task finished name='Task-50' coro=<get_tts_voice() done, defined at D:\QCG\chatgpt\utils\text_to_speech.py:13> exception=Typ...

  File "D:\QCG\chatgpt\utils\text_to_speech.py", line 25, in get_tts_voice
    if await vits_api_instance.process_message(str(elem), output_file.name):
             │                 │                   │      │           └ 'C:\\Users\\**\\AppData\\Local\\Temp\\tmpmf3yj9j9.silk'
             │                 │                   │      └ <tempfile._TemporaryFileWrapper object at 0x0000019B1ED035D0>
             │                 │                   └ Plain(text='非'
             │                 └ <function VitsAPI.process_message at 0x0000019B1FA8B740>
             └ <utils.vits_tts.VitsAPI object at 0x0000019B1FAC5D50>

  File "D:\QCG\chatgpt\utils\vits_tts.py", line 126, in process_message
    await self.initialize()
          │    └ <function VitsAPI.initialize at 0x0000019B1FA8B1A0>
          └ <utils.vits_tts.VitsAPI object at 0x0000019B1FAC5D50>

  File "D:\QCG\chatgpt\utils\vits_tts.py", line 19, in initialize
    self.id = await self.voice_speakers_check()
    │    │          │    └ <function VitsAPI.voice_speakers_check at 0x0000019B1FA8B420>
    │    │          └ <utils.vits_tts.VitsAPI object at 0x0000019B1FAC5D50>
    │    └ None
    └ <utils.vits_tts.VitsAPI object at 0x0000019B1FAC5D50>

  File "D:\QCG\chatgpt\utils\vits_tts.py", line 45, in voice_speakers_check
    vits_list = json_array["VITS"]
                └ [{'0': '綾地寧々'}, {'1': '在原七海'}, {'2': '小茸'}, {'3': '唐乐吟'}, {'4': '綾瀬花日（加隈亜衣）（12歳。〜ちっちゃなムネのトキメキ〜）'}, {'5': '蒼井結衣（木村珠莉）（12歳。〜ちっち...

TypeError: list indices must be integers or slices, not str
2023-04-05 16:20:08.901 | DEBUG    | platforms.onebot_bot:respond:90 - [OneBot] 尝试发送消息：出现故障！如果这个问题持续出现，请和我说 “你改悔罢” 来回溯到上一条对话，你上一条说的我就当作没看见~
原因：list indices must be integers or slices, not str
2023-04-05 16:20:09.238 | DEBUG    | utils.text_to_speech:get_tts_voice:20 - [TextToSpeech] 开始转换语音 - C:\Users\**\AppData\Local\Temp\tmpdyhr3v9a.wav - group-
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-22' coro=<CQHttp._handle_event_with_response() done, defined at D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\__init__.py:606> exception=TypeError('list indices must be integers or slices, not str')>
Traceback (most recent call last):
  File "D:\QCG\chatgpt\universal.py", line 205, in request
    await action(session_id, prompt, rendered, respond)
  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
  File "D:\QCG\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
  File "D:\QCG\chatgpt\middlewares\baiducloud.py", line 86, in handle_respond
    return await action(session_id, prompt, rendered, respond)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
  File "D:\QCG\chatgpt\middlewares\middleware.py", line 12, in handle_respond
    await action(session_id, prompt, rendered, respond)
  File "D:\QCG\chatgpt\universal.py", line 67, in call
    await m.handle_respond(session_id, message, rendered, respond, n)
  File "D:\QCG\chatgpt\middlewares\timeout.py", line 48, in handle_respond
    await action(session_id, prompt, rendered, respond)
  File "D:\QCG\chatgpt\universal.py", line 95, in respond
    voice = await voice_task
            ^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\text_to_speech.py", line 25, in get_tts_voice
    if await vits_api_instance.process_message(str(elem), output_file.name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 126, in process_message
    await self.initialize()
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 19, in initialize
    self.id = await self.voice_speakers_check()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 45, in voice_speakers_check
    vits_list = json_array["VITS"]
                ~~~~~~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\__init__.py", line 608, in _handle_event_with_response
    response = await self._handle_event(payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\__init__.py", line 601, in _handle_event
    filter(lambda r: r is not None, await
                                    ^^^^^
  File "D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\bus.py", line 60, in emit
    results += await run_async_funcs(self._subscribers[event], *args,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\python3.11\Lib\site-packages\aiocqhttp\utils.py", line 40, in run_async_funcs
    results += await asyncio.gather(*coros)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\platforms\onebot_bot.py", line 160, in _
    await handle_message(
  File "D:\QCG\chatgpt\universal.py", line 254, in handle_message
    await action(session_id, message.strip(), conversation_context, respond)
  File "D:\QCG\chatgpt\universal.py", line 61, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
  File "D:\QCG\chatgpt\middlewares\concurrentlock.py", line 43, in handle_request
    await action(session_id, prompt, conversation_context, respond)
  File "D:\QCG\chatgpt\universal.py", line 61, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
  File "D:\QCG\chatgpt\middlewares\middleware.py", line 9, in handle_request
    await action(session_id, prompt, conversation_context, respond)
  File "D:\QCG\chatgpt\universal.py", line 61, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
  File "D:\QCG\chatgpt\middlewares\ratelimit.py", line 26, in handle_request
    await action(session_id, prompt, conversation_context, respond)
  File "D:\QCG\chatgpt\universal.py", line 61, in call
    await m.handle_request(session_id, message, respond, conversation_context, n)
  File "D:\QCG\chatgpt\middlewares\timeout.py", line 27, in handle_request
    await asyncio.wait_for(coro_task, config.response.max_timeout)
  File "asyncio\tasks.py", line 479, in wait_for
  File "D:\QCG\chatgpt\universal.py", line 247, in request
    await respond(config.response.error_format.format(exc=e))
  File "D:\QCG\chatgpt\universal.py", line 95, in respond
    voice = await voice_task
            ^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\text_to_speech.py", line 25, in get_tts_voice
    if await vits_api_instance.process_message(str(elem), output_file.name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 126, in process_message
    await self.initialize()
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 19, in initialize
    self.id = await self.voice_speakers_check()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QCG\chatgpt\utils\vits_tts.py", line 45, in voice_speakers_check
    vits_list = json_array["VITS"]
                ~~~~~~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by Haibersut** [comment]
看起来你用的是老版本的moegoe-simple-api？

**Comment by SternChiri** [comment]
> 看起来你用的是老版本的moegoe-simple-api？

从[https://github.com/Artrajz/MoeGoe-Simple-API](https://github.com/Artrajz/MoeGoe-Simple-API)直接下载源码部署的

**Comment by Haibersut** [comment]
> > 看起来你用的是老版本的moegoe-simple-api？
> 
> 从https://github.com/Artrajz/MoeGoe-Simple-API直接下载源码部署的 昨天刚下的，嗯

你重新下了新的moegoe也是这样吗

**Comment by SternChiri** [comment]
> > > 看起来你用的是老版本的moegoe-simple-api？
> > 
> > 
> > 从[https://github.com/Artrajz/MoeGoe-Simple-API直接下载源码部署的](https://github.com/Artrajz/MoeGoe-Simple-API%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E6%BA%90%E7%A0%81%E9%83%A8%E7%BD%B2%E7%9A%84) 昨天刚下的，嗯
> 
> 你重新下了新的moegoe也是这样吗

要重装moegoe吗……行，我试试

**Comment by Haibersut** [comment]
或者你看一下moegoe的app.py里面是否有这一行，36行开始，没有的话应该就是老版本的问题
![image](https://user-images.githubusercontent.com/117586514/230044489-1328cdd8-5eec-465a-be76-f72d1314ee23.png)

**Comment by lss233** [comment]
v2.3.1 已兼容最新的 vits 服务端接口。

**Comment by SternChiri** [comment]
更新moegoe、项目更新至v2.3.1后问题解决，感谢大佬🙏
