### ISSUE TITLE
求助，反向Websocket连接出错

### ISSUE THREAD

**Issue by ViolaVV** [lss233/chatgpt-mirai-qq-bot#547]
我在启动mirai时遇到了常见问题中提到的那个情况，但我按照教程的设置填写之后仍遇到了那个问题，issues里提到的端口问题我有看过，设置里填写的8554端口是处于listening状态的，我不太清楚要怎么解决这个问题，希望大佬们可以指教一下。
Chatgpt
```
2023-04-06 00:57:59.919 | SUCCESS  | config:scan_presets:443 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2023-04-06 00:57:59.921 | SUCCESS  | config:scan_presets:443 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-04-06 00:57:59.923 | SUCCESS  | config:scan_presets:456 - 注册预设：bing <==> ./presets\assistant\bing.txt [成功]
2023-04-06 00:57:59.924 | SUCCESS  | config:scan_presets:456 - 注册预设：dan <==> ./presets\assistant\dan.txt [成功]
2023-04-06 00:57:59.925 | SUCCESS  | config:scan_presets:456 - 注册预设：debater <==> ./presets\assistant\debater.txt [成功]
2023-04-06 00:57:59.926 | SUCCESS  | config:scan_presets:456 - 注册预设：kp <==> ./presets\assistant\kp.txt [成功]
2023-04-06 00:57:59.927 | SUCCESS  | config:scan_presets:456 - 注册预设：lawyer <==> ./presets\assistant\lawyer.txt [成功]
2023-04-06 00:57:59.928 | SUCCESS  | config:scan_presets:456 - 注册预设：long <==> ./presets\assistant\long.txt [成功]
2023-04-06 00:57:59.929 | SUCCESS  | config:scan_presets:456 - 注册预设：Lss233 <==> ./presets\assistant\Lss233.txt [成功]
2023-04-06 00:57:59.931 | SUCCESS  | config:scan_presets:456 - 注册预设：novelist <==> ./presets\assistant\novelist.txt [成功]
2023-04-06 00:57:59.932 | SUCCESS  | config:scan_presets:456 - 注册预设：poet <==> ./presets\assistant\poet.txt [成功]
2023-04-06 00:57:59.933 | SUCCESS  | config:scan_presets:456 - 注册预设：shineisheji <==> ./presets\assistant\shineisheji.txt [成功]
2023-04-06 00:57:59.934 | SUCCESS  | config:scan_presets:456 - 注册预设：catgirl <==> ./presets\role-play\catgirl.txt [成功]
2023-04-06 00:57:59.935 | SUCCESS  | config:scan_presets:456 - 注册预设：cixiaogui <==> ./presets\role-play\cixiaogui.txt [成功]
2023-04-06 00:57:59.936 | SUCCESS  | config:scan_presets:456 - 注册预设：crazy <==> ./presets\role-play\crazy.txt [成功]2023-04-06 00:57:59.937 | SUCCESS  | config:scan_presets:456 - 注册预设：debatestick <==> ./presets\role-play\debatestick.txt [成功]
2023-04-06 00:57:59.941 | SUCCESS  | config:scan_presets:456 - 注册预设：dingzhen <==> ./presets\role-play\dingzhen.txt [成功]
2023-04-06 00:57:59.943 | SUCCESS  | config:scan_presets:456 - 注册预设：DJ <==> ./presets\role-play\DJ.txt [成功]
2023-04-06 00:57:59.944 | SUCCESS  | config:scan_presets:456 - 注册预设：ERNIE <==> ./presets\role-play\ERNIE.txt [成功]2023-04-06 00:57:59.945 | SUCCESS  | config:scan_presets:456 - 注册预设：gaoqiqiang <==> ./presets\role-play\gaoqiqiang.txt [成功]
2023-04-06 00:57:59.946 | SUCCESS  | config:scan_presets:456 - 注册预设：hanli <==> ./presets\role-play\hanli.txt [成功]2023-04-06 00:57:59.948 | SUCCESS  | config:scan_presets:456 - 注册预设：huxijin <==> ./presets\role-play\huxijin.txt [成功]
2023-04-06 00:57:59.950 | SUCCESS  | config:scan_presets:456 - 注册预设：ikun <==> ./presets\role-play\ikun.txt [成功]
2023-04-06 00:57:59.951 | SUCCESS  | config:scan_presets:456 - 注册预设：MOSS <==> ./presets\role-play\MOSS.txt [成功]
2023-04-06 00:57:59.953 | SUCCESS  | config:scan_presets:456 - 注册预设：welldone <==> ./presets\role-play\welldone.txt [成功]
2023-04-06 00:57:59.957 | SUCCESS  | config:scan_presets:456 - 注册预设：zhangweiwei <==> ./presets\role-play\zhangweiwei.txt [成功]
2023-04-06 00:57:59.960 | ERROR    | config:scan_presets:453 - 注册预设：dan <==> ./presets\utils\dan.txt [失败：关键词已存在]
2023-04-06 00:57:59.962 | ERROR    | config:scan_presets:453 - 注册预设：catgirl <==> ./presets\catgirl.txt [失败：关键词已存在]
2023-04-06 00:57:59.964 | SUCCESS  | config:scan_presets:456 - 注册预设：catgirl_en <==> ./presets\catgirl_en.txt [成功]2023-04-06 00:57:59.966 | SUCCESS  | config:scan_presets:456 - 注册预设：issue402 <==> ./presets\issue402.txt [成功]
2023-04-06 00:57:59.967 | SUCCESS  | config:scan_presets:456 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2023-04-06 00:57:59.971 | INFO     | manager.bot:__check_proxy:294 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-04-06 00:58:00.060 | SUCCESS  | manager.bot:__check_proxy:302 - [代理测试] 连接成功！
2023-04-06 00:58:00.061 | INFO     | manager.bot:login_bing:147 - 正在解析第 1 个 Bing 账号
2023-04-06 00:58:00.063 | SUCCESS  | manager.bot:login_bing:152 - 解析成功！
2023-04-06 00:58:00.065 | SUCCESS  | manager.bot:login_bing:158 - 成功解析 1/1 个 Bing 账号！
2023-04-06 00:58:00.066 | INFO     | manager.bot:login:98 - 当前的 browserless_endpoint 为：https://bypass.churchless.tech/api/
2023-04-06 00:58:00.068 | INFO     | manager.bot:login:110 - 当前的 api_endpoint 为：https://api.openai.com/v1
2023-04-06 00:58:00.069 | INFO     | manager.bot:login_openai:231 - 正在登录第 1 个 OpenAI 账号
2023-04-06 00:58:00.071 | INFO     | manager.bot:__login_openai_apikey:382 - 尝试使用 api_key 登录中...
2023-04-06 00:58:00.072 | INFO     | manager.bot:__check_proxy:294 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-04-06 00:58:00.139 | SUCCESS  | manager.bot:__check_proxy:302 - [代理测试] 连接成功！
2023-04-06 00:58:00.140 | INFO     | manager.bot:__login_openai_apikey:386 - 当前检查的 API Key 为：sk-R3tfQ******oWCM
2023-04-06 00:58:00.142 | WARNING  | manager.bot:__login_openai_apikey:387 - 在查询 API 额度时遇到问题，请自行确认额度。2023-04-06 00:58:00.143 | SUCCESS  | manager.bot:login_openai:245 - 登录成功！
2023-04-06 00:58:00.145 | SUCCESS  | manager.bot:login_openai:264 - 成功登录 1/1 个 OpenAI 账号！
2023-04-06 00:58:00.146 | INFO     | manager.bot:login:124 - AI 类型：chatgpt-web - 可用账号： 0 个
2023-04-06 00:58:00.148 | INFO     | manager.bot:login:124 - AI 类型：openai-api - 可用账号： 1 个
2023-04-06 00:58:00.149 | INFO     | manager.bot:login:124 - AI 类型：poe-web - 可用账号： 0 个
2023-04-06 00:58:00.151 | INFO     | manager.bot:login:124 - AI 类型：bing-cookie - 可用账号： 1 个
2023-04-06 00:58:00.153 | INFO     | manager.bot:login:124 - AI 类型：bard-cookie - 可用账号： 0 个
2023-04-06 00:58:00.154 | INFO     | manager.bot:login:124 - AI 类型：yiyan-cookie - 可用账号： 0 个
2023-04-06 00:58:00.157 | INFO     | manager.bot:login:124 - AI 类型：chatglm-api - 可用账号： 0 个
2023-04-06 00:58:00.159 | INFO     | __main__:<module>:42 - 检测到 mirai 配置，将启动 mirai 模式……
2023-04-06 00:58:00.898 | INFO     | launart.manager:launch:331 - Launching 5 components as async task...
2023-04-06 00:58:01.054 | INFO     | graia.ariadne.service:base_telemetry:108 -
    _         _           _
   / \   _ __(_) __ _  __| |_ __   ___
  / _ \ | '__| |/ _` |/ _` | '_ \ / _ \
 / ___ \| |  | | (_| | (_| | | | |  __/
/_/   \_\_|  |_|\__,_|\__,_|_| |_|\___|

graiax-silkcoder: 0.3.6
graia-amnesia: 0.7.1
graia-ariadne: 0.11.3
graia-broadcast: 0.19.2
launart: 0.6.3
statv: 0.3.2
2023-04-06 00:58:01.067 | INFO     | launart.manager:_launchable_task_done_callback:68 - [elizabeth.connection.2421556513.websocket_server_connection] completed.
2023-04-06 00:58:01.070 | INFO     | graia.amnesia.builtins.aiohttp:launch:513 - starting server on 0.0.0.0:8554
2023-04-06 00:58:01.073 | SUCCESS  | launart.manager:launch:384 - Layer #1:[cache.client/memcache, http.server/aiohttp, http.client/aiohttp] preparation completed.
2023-04-06 00:58:01.078 | INFO     | platforms.ariadne_bot:start_background:193 - 尝试从 Mirai 服务中读取机器人 QQ 的 session key……
2023-04-06 00:58:01.081 | INFO     | platforms.ariadne_bot:start_background:195 - [提示] 当前为反向 ws 模式，请确保你的 mirai api http 设置了正确的 reverse-ws adapter 配置
2023-04-06 00:58:01.084 | INFO     | platforms.ariadne_bot:start_background:196 - [提示] 配置不正确会导致 Mirai 端出现错误提示。
2023-04-06 00:58:01.087 | SUCCESS  | launart.manager:launch:384 - Layer #3:[elizabeth.service] preparation completed.
2023-04-06 00:58:01.091 | INFO     | launart.manager:launch:389 - All components prepared, start blocking phase.
2023-04-06 00:58:14.492 | ERROR    | graia.amnesia.transport.rider:trigger_callbacks:37 - ('未能使用所配置的账号激活 session key, 请检查配置.', {'code': 2, 'msg': '指定Bot不存在'})
Traceback (most recent call last):

> File "D:\Qbot\chatgpt\python3.11\Lib\site-packages\graia\amnesia\transport\common\websocket\shortcut.py", line 20, in wrapper
    return await func(self, io, data)
                 │    │     │   └ '{"code":2,"msg":"指定Bot不存在"}'
                 │    │     └ <graia.amnesia.builtins.aiohttp.AiohttpServerWebsocketIO object at 0x000001D9F431C510>
                 │    └ <WebsocketServerConnection <ConnectionStatus connected=False alive=False verified=False stage=None> with 2 callbacks>
                 └ <function WebsocketConnectionMixin._ at 0x000001D9F1A9DDA0>
  File "D:\Qbot\chatgpt\python3.11\Lib\site-packages\graia\ariadne\connection\ws.py", line 54, in _
    validate_response(raw)  # raise it
    │                 └ {'code': 2, 'msg': '指定Bot不存在'}
    └ <function validate_response at 0x000001D9F198CC20>
  File "D:\Qbot\chatgpt\python3.11\Lib\site-packages\graia\ariadne\connection\util.py", line 61, in validate_response
    raise exc
          └ AccountNotFound('未能使用所配置的账号激活 session key, 请检查配置.', {'code': 2, 'msg': '指定Bot不存在'})

graia.ariadne.exception.AccountNotFound: ('未能使用所配置的账号激活 session key, 请检查配置.', {'code': 2, 'msg': '指定Bot不存在'})
2023-04-06 00:58:14.516 | INFO     | graia.ariadne.connection.ws:_:92 - Websocket connection closed
```

Mirai
```
  00:58:06 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  00:58:06 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.6 (arch: 64)
  00:58:06 [INFO] https://github.com/iTXTech/mirai-console-loader
  00:58:06 [INFO] This program is licensed under GNU AGPL v3
  00:58:07 [ERROR] Failed to fetch announcement for "xyz.cssxsh.mirai:fix-protocol-version"
  00:58:07 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  00:58:07 [INFO] Verifying "net.mamoe:mirai-console" v2.14.0
  00:58:08 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.14.0
  00:58:08 [INFO] Verifying "net.mamoe:mirai-core-all" v2.14.0
  00:58:08 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  00:58:09 [INFO] Verifying "net.mamoe:mirai-api-http" v2.9.1
  00:58:09 [INFO] Verifying "xyz.cssxsh.mirai:mirai-device-generator" v1.1.3
  00:58:09 [INFO] Verifying "xyz.cssxsh.mirai:fix-protocol-version"
  00:58:09 [ERROR] Failed to verify package "xyz.cssxsh.mirai:fix-protocol-version"
  00:58:09 [ERROR] com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395)
        at com.google.gson.Gson.fromJson(Gson.java:1214)
        at com.google.gson.Gson.fromJson(Gson.java:1124)
        at com.google.gson.Gson.fromJson(Gson.java:1034)
        at com.google.gson.Gson.fromJson(Gson.java:1001)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:84)
        at org.itxtech.mcl.module.builtin.RepoCache$RepoWithCache.fetchPackage(RepoCache.java:88)
        at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:101)
        at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
        at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:117)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:190)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:190)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:384)
        ... 13 more

2023-04-06 00:58:11 I/main: Starting mirai-console...
2023-04-06 00:58:11 I/main:

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-04-06 00:58:11 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-04-06 00:58:11 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-04-06 00:58:11 I/main: Welcome to visit https://mirai.mamoe.net/
2023-04-06 00:58:13 W/fix-protocol-version: Mirai版本低于预期，将升级协议版本
2023-04-06 00:58:13 I/plugin: Successfully loaded plugin fix-protocol-version v1.3.0
2023-04-06 00:58:13 I/plugin: Successfully loaded plugin mirai-api-http v2.9.1
2023-04-06 00:58:13 I/plugin: Successfully loaded plugin mirai-device-generator v1.1.3
2023-04-06 00:58:13 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-04-06 00:58:13 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-04-06 00:58:13 I/fix-protocol-version: 当前各协议版本日期:
ANDROID_PHONE   8.9.33.10335   2023-01-13T16:51:38+08:00
ANDROID_PAD   8.9.33.10335   2023-01-13T16:51:38+08:00
ANDROID_WATCH   2.0.5   2019-06-03T20:25:31+08:00
IPAD   8.9.33.614   2021-12-31T11:36:26+08:00
MACOS   5.8.9   2020-07-27T15:50:08+08:00

2023-04-06 00:58:13 I/Mirai HTTP API: ********************************************************
2023-04-06 00:58:13 I/reverse-ws adapter: >>> [reverse-ws adapter] is running
2023-04-06 00:58:13 I/Mirai HTTP API: Http api server is running with verifyKey: 1234567890
2023-04-06 00:58:13 I/Mirai HTTP API: adaptors: [reverse-ws]
2023-04-06 00:58:13 I/Mirai HTTP API: ********************************************************
2023-04-06 00:58:13 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-04-06 00:58:13 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-04-06 00:58:13 I/main: 4 plugin(s) enabled.
2023-04-06 00:58:13 I/main: mirai-console started successfully.
2023-04-06 00:58:13 W/io.ktor.util.random: NativePRNGNonBlocking is not found, fallback to default
2023-04-06 00:58:14 W/reverse-ws adapter: [reverse-ws] Connection to localhost:8554/ interrupted. Trying reconnect in 5000 ms.
```

**Comment by lss233** [comment]
你的 Miai 未登录 QQ。登录成功后再重新启动 ChatGPT 端即可。
教程：https://chatgpt-qq.lss233.com/bu-shu-jiao-cheng/kuai-su-bu-shu-jiao-cheng/windows-kuai-su-bu-shu-jiao-cheng#deng-lu-qq

**Comment by ViolaVV** [comment]
好像登录不上去...提示是这样的
Login failed: Error(bot=Bot(2421556513), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
2023-04-06 01:37:53 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2421556513), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2421556513), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
我还用onebot尝试了一下，二维码登录是可以的，但连接还是会出错，提示是这样的
[2023-04-06 01:42:37] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://localhost:8554/ws/
[2023-04-06 01:42:37] [WARNING]: 连接到反向WebSocket Universal服务器 ws://localhost:8554/ws/ 时出现错误: websocket: bad handshake

**Comment by lss233** [comment]
mirai登录不上的话看 #303 。 onebot 模式可以用的话， 要确保你配置文件里面切换成了 onebot。
