### ISSUE TITLE
[BUG] 无法启动Mirai, 启动时报错

### ISSUE THREAD

**Issue by fredzhu** [lss233/chatgpt-mirai-qq-bot#555]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中

**表现**  
 https://mirai.mamoe.net/topic/653

MCL ??? 2.1.0?????? Mirai 2.11 ???????????

  12:19:57 [INFO] Verifying "net.mamoe:mirai-console" v2.14.0
  12:20:00 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.14.0
  12:20:01 [INFO] Verifying "net.mamoe:mirai-core-all" v2.14.0
  12:20:02 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  12:20:03 [INFO] Verifying "net.mamoe:mirai-api-http" v2.9.1
  12:20:03 [INFO] Verifying "xyz.cssxsh.mirai:mirai-device-generator" v1.1.3
  12:20:03 [INFO] Verifying "xyz.cssxsh.mirai:fix-protocol-version"
  **12:20:03 [ERROR] Failed to verify package "xyz.cssxsh.mirai:fix-protocol-version"**
  12:20:03 [ERROR] com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395)
        at com.google.gson.Gson.fromJson(Gson.java:1214)
        at com.google.gson.Gson.fromJson(Gson.java:1124)
        at com.google.gson.Gson.fromJson(Gson.java:1034)
        at com.google.gson.Gson.fromJson(Gson.java:1001)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:84)
        at org.itxtech.mcl.module.builtin.RepoCache$RepoWithCache.fetchPackage(RepoCache.java:88)
        at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:101)
        at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
        at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:117)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:190)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:190)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:384)
        ... 13 more

2023-04-06 12:20:05 I/main: Starting mirai-console...
2023-04-06 12:20:05 I/main:

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓

2023-04-06 12:20:05 I/main: Backend: version 2.14.0, built on 2023-02-06 01:25:21.
2023-04-06 12:20:05 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-04-06 12:20:05 I/main: Welcome to visit https://mirai.mamoe.net/
2023-04-06 12:20:06 W/fix-protocol-version: Mirai版本低于预期，将升级协议版本
2023-04-06 12:20:06 I/plugin: Successfully loaded plugin fix-protocol-version v1.3.0
2023-04-06 12:20:06 I/plugin: Successfully loaded plugin mirai-api-http v2.9.1
2023-04-06 12:20:06 I/plugin: Successfully loaded plugin mirai-device-generator v1.1.3
2023-04-06 12:20:06 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-04-06 12:20:06 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-04-06 12:20:06 I/fix-protocol-version: 当前各协议版本日期:
ANDROID_PHONE   8.9.33.10335   2023-01-13T03:51:38-05:00
ANDROID_PAD   8.9.33.10335   2023-01-13T03:51:38-05:00
ANDROID_WATCH   2.0.5   2019-06-03T08:25:31-04:00
IPAD   8.9.33.614   2021-12-30T22:36:26-05:00
MACOS   5.8.9   2020-07-27T03:50:08-04:00

2023-04-06 12:20:06 I/Mirai HTTP API: ********************************************************
2023-04-06 12:20:06 I/reverse-ws adapter: >>> [reverse-ws adapter] is running
2023-04-06 12:20:06 I/Mirai HTTP API: Http api server is running with verifyKey: 1234567890
2023-04-06 12:20:06 I/Mirai HTTP API: adaptors: [reverse-ws]
2023-04-06 12:20:06 I/Mirai HTTP API: ********************************************************
2023-04-06 12:20:06 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-04-06 12:20:06 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-04-06 12:20:06 I/main: 4 plugin(s) enabled.
2023-04-06 12:20:06 I/main: mirai-console started successfully.
2023-04-06 12:20:06 W/io.ktor.util.random: NativePRNGNonBlocking is not found, fallback to default
2023-04-06 12:20:07 W/reverse-ws adapter: [reverse-ws] Connection to localhost:8554/ interrupted. Trying reconnect in 5000 ms.
2023-04-06 12:20:13 W/reverse-ws adapter: [reverse-ws] Connection to localhost:8554/ interrupted. Trying reconnect in 5000 ms.
>

**运行环境:**  
- 操作系统：window server 2016
- Docker： ？
- 项目版本：刚拿的windows快速部署

**Comment by lss233** [comment]
请阅读使用教程。
