### ISSUE TITLE
[BUG] 文心一言画图功能报错

### ISSUE THREAD

**Issue by lingboshuiyue** [lss233/chatgpt-mirai-qq-bot#601]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现** 
使用 文心一言 的 AI 模型，能正常进行对话，但画图时就出现异常。

**运行环境:**  
- 操作系统：CentOS Linux release 8.5.2111
- Docker： Docker version 23.0.1
- 项目版本：v2.3.4

**复现步骤**  
1. 使用 文心一言 AI 模型
2. 使用画图功能

**预期行为**  
在文心一言的 AI 模型下，也能正常进行画图。

**截图&日志**  
![image](https://user-images.githubusercontent.com/24492313/231164107-fbcbbd86-4922-4e3b-9247-20e9c7b19284.png)
![image](https://user-images.githubusercontent.com/24492313/231173088-30a0dbfe-540a-4a72-8fa3-f88959b46758.png)

错误日志：
```
2023-04-11 12:49:05.328 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-04-11 12:49:05.328 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-04-11 12:49:05.329 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
2023-04-11 12:49:11.223 | DEBUG    | adapter.baidu.yiyan:ask:140 - [Yiyan] 4723219 - 
2023-04-11 12:49:18.293 | ERROR    | universal:request:248 - 
Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
                 │    │       │                 └ 65536
                 │    │       └ <function SocketStream.receive at 0x7fd61c714cc0>
                 │    └ <anyio._backends._asyncio.SocketStream object at 0x7fd617ae4210>
                 └ <httpcore.backends.asyncio.AsyncIOStream object at 0x7fd617ae4f90>
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
          │    │         │          └ <function Event.wait at 0x7fd626c59120>
          │    │         └ <asyncio.locks.Event object at 0x7fd617ae51d0 [set]>
          │    └ <anyio._backends._asyncio.StreamProtocol object at 0x7fd617ae4d50>
          └ <anyio._backends._asyncio.SocketStream object at 0x7fd617ae4210>
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
          └ <Future cancelled>

asyncio.exceptions.CancelledError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
         │     │          └ 5.0
         │     └ <function fail_after at 0x7fd61c7b2520>
         └ <module 'anyio' from '/usr/local/lib/python3.11/site-packages/anyio/__init__.py'>
  File "/usr/local/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError

TimeoutError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'GET']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x7fd62535e160>
                 │    └ <httpcore.AsyncHTTPProxy object at 0x7fd61c098310>
                 └ <httpx.AsyncHTTPTransport object at 0x7fd61d87d690>
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
                     │          │                    └ <Request [b'GET']>
                     │          └ <function AsyncForwardHTTPConnection.handle_async_request at 0x7fd62535eb60>
                     └ <AsyncForwardHTTPConnection ['http://192.168.0.57:7890', HTTP/1.1, CLOSED, Request Count: 1]>
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http_proxy.py", line 184, in handle_async_request
    return await self._connection.handle_async_request(proxy_request)
                 │    │           │                    └ <Request [b'GET']>
                 │    │           └ <function AsyncHTTPConnection.handle_async_request at 0x7fd625602ac0>
                 │    └ <AsyncHTTPConnection ['http://192.168.0.57:7890', HTTP/1.1, CLOSED, Request Count: 1]>
                 └ <AsyncForwardHTTPConnection ['http://192.168.0.57:7890', HTTP/1.1, CLOSED, Request Count: 1]>
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
                 │    │           │                    └ <Request [b'GET']>
                 │    │           └ <function AsyncHTTP11Connection.handle_async_request at 0x7fd62535c5e0>
                 │    └ <AsyncHTTP11Connection ['http://192.168.0.57:7890', CLOSED, Request Count: 1]>
                 └ <AsyncHTTPConnection ['http://192.168.0.57:7890', HTTP/1.1, CLOSED, Request Count: 1]>
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
              │    │                           └ {'request': <Request [b'GET']>}
              │    └ <function AsyncHTTP11Connection._receive_response_headers at 0x7fd62535c860>
              └ <AsyncHTTP11Connection ['http://192.168.0.57:7890', CLOSED, Request Count: 1]>
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
                  │    │                      └ 5.0
                  │    └ <function AsyncHTTP11Connection._receive_event at 0x7fd62535c9a0>
                  └ <AsyncHTTP11Connection ['http://192.168.0.57:7890', CLOSED, Request Count: 1]>
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
                 │    │               └ <function AsyncIOStream.read at 0x7fd61c710540>
                 │    └ <httpcore.backends.asyncio.AsyncIOStream object at 0x7fd617ae4f90>
                 └ <AsyncHTTP11Connection ['http://192.168.0.57:7890', CLOSED, Request Count: 1]>
  File "/usr/local/lib/python3.11/site-packages/httpcore/backends/asyncio.py", line 31, in read
    with map_exceptions(exc_map):
         │              └ {<class 'TimeoutError'>: <class 'httpcore.ReadTimeout'>, <class 'anyio.BrokenResourceError'>: <class 'httpcore.ReadError'>, <...
         └ <function map_exceptions at 0x7fd6255e93a0>
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7fd617ae7400>
    │    │   │     │    └ TimeoutError()
    │    │   │     └ <class 'TimeoutError'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_exceptions at 0x7fd61c799c40>
    └ <contextlib._GeneratorContextManager object at 0x7fd617ae40d0>
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
          └ <class 'httpcore.ReadTimeout'>

httpcore.ReadTimeout


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/app/bot.py", line 41, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at /app/platforms/ariadne_bot.py:296> wait_for=<Task pending name='Ta...
    │    │                  │       └ <function gather at 0x7fd626c582c0>
    │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x7fd626c651c0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fd626c65120>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fd626c66f20>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fd6271abce0>
    └ <Handle <TaskStepMethWrapper object at 0x7fd617ae3b20>()>
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fd617ae3b20>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7fd617ae3b20>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7fd617ae3b20>()>

> File "/app/universal.py", line 197, in request
    async for rendered in task:
              │           └ <async_generator object retry.<locals>.decorator.<locals>.wrapper at 0x7fd61d8179c0>
              └ None

  File "/app/utils/retry.py", line 21, in wrapper
    async for result in func(*args, **kwargs):
              │         │     │       └ {'prompt': '画一只小熊猫', 'chain': MessageChain([Plain(text='画一只小熊猫')]), 'name': 'xxx'}
              │         │     └ (<conversation.ConversationContext object at 0x7fd61d89a550>,)
              │         └ <function ConversationContext.ask at 0x7fd61f85cae0>
              └ None

  File "/app/conversation.py", line 159, in ask
    async for item in self.adapter.ask(prompt):
              │       │    │       │   └ '画一只小熊猫'
              │       │    │       └ <function YiyanAdapter.ask at 0x7fd62418d580>
              │       │    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x7fd61c098a90>
              │       └ <conversation.ConversationContext object at 0x7fd61d89a550>
              └ ''

  File "/app/adapter/baidu/yiyan.py", line 137, in ask
    yield GraiaImage(data_bytes=await self.__download_image(url))
          │                           │                     └ 'http://eb118-file.cdn.bcebos.com/upload/8E0F8CE62B90BB00A4084E324B4ABA9B?x-bce-process=style/wm_ai'
          │                           └ <adapter.baidu.yiyan.YiyanAdapter object at 0x7fd61c098a90>
          └ <class 'graia.ariadne.message.element.Image'>

  File "/app/adapter/baidu/yiyan.py", line 169, in __download_image
    image = await self.client.get(url)
                  │    │      │   └ 'http://eb118-file.cdn.bcebos.com/upload/8E0F8CE62B90BB00A4084E324B4ABA9B?x-bce-process=style/wm_ai'
                  │    │      └ <function AsyncClient.get at 0x7fd625388a40>
                  │    └ <httpx.AsyncClient object at 0x7fd61c098c90>
                  └ <adapter.baidu.yiyan.YiyanAdapter object at 0x7fd61c098a90>

  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
                 │    └ <function AsyncClient.request at 0x7fd6253885e0>
                 └ <httpx.AsyncClient object at 0x7fd61c098c90>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x7fd625375c90>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x7fd625375c90>
                 │    │    └ <Request('GET', 'http://eb118-file.cdn.bcebos.com/upload/8E0F8CE62B90BB00A4084E324B4ABA9B?x-bce-process=style/wm_ai')>
                 │    └ <function AsyncClient.send at 0x7fd6253887c0>
                 └ <httpx.AsyncClient object at 0x7fd61c098c90>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x7fd625388860>
                     └ <httpx.AsyncClient object at 0x7fd61c098c90>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x7fd625388900>
                     └ <httpx.AsyncClient object at 0x7fd61c098c90>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('GET', 'http://eb118-file.cdn.bcebos.com/upload/8E0F8CE62B90BB00A4084E324B4ABA9B?x-bce-process=style/wm_ai')>
                     │    └ <function AsyncClient._send_single_request at 0x7fd6253889a0>
                     └ <httpx.AsyncClient object at 0x7fd61c098c90>
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('GET', 'http://eb118-file.cdn.bcebos.com/upload/8E0F8CE62B90BB00A4084E324B4ABA9B?x-bce-process=style/wm_ai')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x7fd6253798a0>
                     └ <httpx.AsyncHTTPTransport object at 0x7fd61d87d690>
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x7fd6256034c0>
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7fd617ae7600>
    │    │   │     │    └ ReadTimeout(TimeoutError())
    │    │   │     └ <class 'httpcore.ReadTimeout'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_httpcore_exceptions at 0x7fd61c79be40>
    └ <contextlib._GeneratorContextManager object at 0x7fd617afdd50>
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ ''
          └ <class 'httpx.ReadTimeout'>

httpx.ReadTimeout
2023-04-11 12:49:18.462 | INFO     | graia.ariadne.model:log:82 - xxx: [SEND][xxx(xxx)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n原因：
2023-04-11 12:49:18.462 | DEBUG    | middlewares.timeout:on_respond:40 - [Timeout] 取消计时……
```

**其他内容**  
无

**Comment by lingboshuiyue** [comment]
确实是网络问题，打扰了。。
