### ISSUE TITLE
QQ无法登录，尝试过多种方案了

### ISSUE THREAD

**Issue by EYW-015** [lss233/chatgpt-mirai-qq-bot#71]
已经尝试过的方法

- 简易mirai登录器 [MrXiaoM/Aoki](https://github.com/MrXiaoM/Aoki)
- 使用简易部署脚本 [paradox8599/mirai-chatgpt-setup](https://github.com/paradox8599/mirai-chatgpt-setup)
- 手动使用Docker-compose

已经尝试过的登录设备

- ANDROID_PAD
- ANDROID_PHONE
- MACOS
- IPAD

选择 密码 / 扫码 / 短信验证码，登录QQ时均出现相同报错

以下是日志

## 这是使用ANDROID_PAD方式登录，提示版本过低
```
2023-01-12 13:27:32 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2023-01-12 13:27:32 I/Bot.3342006836: Bot cancelled: Bot closed
Login failed: Error(bot=Bot(3342006836), code=45, title=禁止登录, message=您好，您当前使用的版本过低，前往QQ官网im.qq.com下载新版QQ。, errorInfo=)
2023-01-12 13:27:32 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3342006836), code=45, title=禁止登录, message=您好，您当前使用的版本过低，前往QQ官网im.qq.com下载新版QQ。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3342006836), code=45, title=禁止登录, message=您好，您当前使用的版本过低，前往QQ官网im.qq.com下载新版QQ。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:309)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
## 这里是使用IPAD和MacOS登录的状态
```
Login failed: net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
2023-01-12 13:30:04 E/console: net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
        at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299)
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275)
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295)
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319)
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318)
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623)
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368)
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by lss233** [comment]
无法解决
请在此处更进：https://github.com/mamoe/mirai/issues/2418

**Comment by EYW-015** [comment]
> 无法解决
> 请在此处跟进：https://github.com/mamoe/mirai/issues/2418

原项目已更新修复此问题，还劳烦大佬跟进一下了，非常感谢

**Comment by lss233** [comment]
我能做的不多…… 你可以通过 `mcl` 把 Mirai 升级到最新版本

https://github.com/iTXTech/mirai-console-loader/blob/master/cli.md
