### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by YinyiE** [lss233/chatgpt-mirai-qq-bot#72]
正确部署(在linux系统)后使用python bot.py启动报错OSError: /home/linux1/miniconda3/lib/python3.9/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory
但相关的包已经正确安装，且目录下有提到的文件，依旧无法运行
相关日志如下
linux1@linuxlearning:~/chatGPT/chatgpt-mirai-qq-bot$ python bot.py
Traceback (most recent call last):                                                   File "/home/linux1/chatGPT/chatgpt-mirai-qq-bot/bot.py", line 21, in <module>        import chatbot                                                                   File "/home/linux1/chatGPT/chatgpt-mirai-qq-bot/chatbot.py", line 1, in <module>
    from revChatGPT.ChatGPT import Chatbot                                           File "/home/linux1/miniconda3/lib/python3.9/site-packages/revChatGPT/ChatGPT.py", line 1, in <module>
    import uuid, re, json, tls_client, logging                                       File "/home/linux1/miniconda3/lib/python3.9/site-packages/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session                                                    File "/home/linux1/miniconda3/lib/python3.9/site-packages/tls_client/sessions.py", line 1, in <module>
    from .cffi import request
  File "/home/linux1/miniconda3/lib/python3.9/site-packages/tls_client/cffi.py", line 20, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
  File "/home/linux1/miniconda3/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
  File "/home/linux1/miniconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/linux1/miniconda3/lib/python3.9/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory

**Comment by lss233** [comment]
这个有点奇怪，你的系统是什么发行版

**Comment by YinyiE** [comment]
ubuntu
s390x架构

**Comment by YinyiE** [comment]
> 这个有点奇怪，你的系统是什么发行版



> 这个有点奇怪，你的系统是什么发行版

ubuntu
s390x架构

**Comment by lss233** [comment]
s390x 架构我倒是第一次见……  
可能你需要自己编译一下 tls-client 这个依赖
另外你可以把 revChatGPT 这个依赖升级到最新版试一下

**Comment by YinyiE** [comment]
> 

我在pypi下载了源码后python setup.py install安装后还是这个问题
