### ISSUE TITLE
启动错误：配置文件有误，请重新修改！请帮忙看下

### ISSUE THREAD

**Issue by DreamyWen** [lss233/chatgpt-mirai-qq-bot#84]
环境：macOs big sur
           Python 3.9.16

命令: python bot.py

报错如下：
Traceback (most recent call last):

  File "/Users/saith/GitHub/chatgpt-mirai-qq-bot/venv/lib/python3.9/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
          │       │         │     │             └ None
          │       │         │     └ {'temperature': 0.5}
          │       │         └ 'api_key = sk-0egji1bvxNDu1JX50NunT3Blxxxx'
          │       └ <function TomlDecoder.load_line at 0x10cbc3280>
          └ <toml.decoder.TomlDecoder object at 0x10bf05850>
  File "/Users/saith/GitHub/chatgpt-mirai-qq-bot/venv/lib/python3.9/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
                   │    │          │        └ True
                   │    │          └ ['api_key', 'sk-0egji1bvxNDu1JX50NunT3Blxxxx']
                   │    └ <function TomlDecoder.load_value at 0x10cbc33a0>
                   └ <toml.decoder.TomlDecoder object at 0x10bf05850>
  File "/Users/saith/GitHub/chatgpt-mirai-qq-bot/venv/lib/python3.9/site-packages/toml/decoder.py", line 918, in load_value
    v = int(v, 0)
            └ 'sk-0egji1bvxNDu1JX50NunT3Blxxxx'

ValueError: invalid literal for int() with base 0: 'sk-0egji1bvxNDu1JX50NunT3Blxxxx'

配置文件：
[openai]
temperature = 0.5
api_key = sk-0egji1bvxNDu1JX50NunT3Blxxxx

大佬帮忙看下, 谢谢@lss233

**Comment by DreamyWen** [comment]
加个引号就可以了
