### ISSUE TITLE
当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页

### ISSUE THREAD

**Issue by wanStu** [lss233/chatgpt-mirai-qq-bot#844]
执行 `docker-compose run --rm mirai` 后报错
2023-05-19 12:52:08 I/Mirai HTTP API: ********************************************************
2023-05-19 12:52:08 I/reverse-ws adapter: >>> [reverse-ws adapter] is running
2023-05-19 12:52:08 I/Mirai HTTP API: Http api server is running with verifyKey: e07b97a5-bea8-44c2-b13c-c8971a72635e
2023-05-19 12:52:08 I/Mirai HTTP API: adaptors: [reverse-ws]
2023-05-19 12:52:08 I/Mirai HTTP API: ********************************************************
2023-05-19 12:52:08 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-05-19 12:52:08 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用2023-05-19 12:52:09 I/main: 5 plugin(s) enabled.
2023-05-19 12:52:09 I/main: Auto-login 260xxxx708, protocol: ANDROID_PAD, heartbeatStrategy: STAT_HB
2023-05-19 12:52:09 W/stderr: Exception in thread "DefaultDispatcher-worker-4" java.net.UnknownHostException: chatgpt: Name or service not known
2023-05-19 12:52:09 W/stderr:   at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
2023-05-19 12:52:09 W/stderr:   at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
2023-05-19 12:52:09 W/stderr:   at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1534)
2023-05-19 12:52:09 W/stderr:   at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
2023-05-19 12:52:09 W/stderr:   at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1524)
2023-05-19 12:52:09 W/stderr:   at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1381)
2023-05-19 12:52:09 W/stderr:   at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1305)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2023-05-19 12:52:09 W/stderr:   at mirai-api-http-2.9.1.mirai2.jar[shared]//okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
2023-05-19 12:52:09 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-05-19 12:52:09 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-05-19 12:52:09 W/stderr:   at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-19 12:52:09 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@798963f1, Dispatchers.Default]
2023-05-19 12:52:09 E/main: net.mamoe.mirai.internal.network.auth.ProducerFailureException
net.mamoe.mirai.internal.network.auth.ProducerFailureException
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(260xxxx708), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                ... 5 more
        Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(260xxxx708), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)]

2023-05-19 12:52:09 I/Bot.260xxxx708: Bot cancelled: Bot closed
2023-05-19 12:52:09 V/Bot.260xxxx708: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@2c77344f
2023-05-19 12:52:09 I/main: mirai-console started successfully.
> 
该如何解决

**Comment by lss233** [comment]
这是 Mirai 的 BUG，不要在此反馈。   

如果你无法使用 Mirai 登录机器人，可以用 go-cqhtttp。
