### ISSUE TITLE
qq登录报错

### ISSUE THREAD

**Issue by femnn** [lss233/chatgpt-mirai-qq-bot#886]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况：已经更新为最新版本客户端，使用最新版本客户端初始化后没有反应不弹出那个几个运行文件。通过对上一个版本进行覆盖登录也没有用。chatgpt.bin报错内容：
graia.ariadne.exception.AccountNotFound: ('未能使用所配置的账号激活 session key, 请检查配置.', {'code': 2, 'msg': '指定Bot不存在'})
2023-05-28 22:46:02.336 | INFO     | graia.ariadne.connection.ws:_:92 - Websocket connection closed
2023-05-28 22:46:07.341 | ERROR    | graia.amnesia.transport.rider:trigger_callbacks:37 - ('未能使用所配置的账号激活 session key, 请检查配置.', {'code': 2, 'msg': '指定Bot不存在'})
go-cqhttp报错内容：
连接到反向服务器时出现错误
mariai报错内容：
Login failed: Error(bot=Bot(1728331040), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
2023-05-28 22:47:17 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1728331040), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1728331040), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与 我们联系。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**运行环境:**  
- 操作系统：？win10
- Docker： ？
- 项目版本：？2.5.0-2.5.1

**复现步骤**  
描述你是如何触发这个 BUG 的
就是一步步安装教程安装，之前登录都没问题，chatgpt也成功连上了但是登录qq出了问题，各种显示连接不上。使用qr码还是mirai都无法登录成功

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/28421346/b350434a-adb4-42c4-b6c0-a06858528845)
![cmd_wc4fJIRbwt](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/28421346/7e59eef0-a3e6-471a-988e-3038c99f6d7c)
![cmd_2fmIC24Z2Y](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/28421346/624e4280-e981-41b9-b3f7-c210898c21d6)

**Comment by femnn** [comment]
已经在群里解决了

**Comment by Adiolph** [comment]
@femnn 请问老哥是怎么解决的呢？

**Comment by lss233** [comment]
mirai 基本上不能用了。 go-cqhttp 是没问题的，只是你没开程序导致连不上而已。

**Comment by lss233** [comment]
qq登陆出现错误的问题与本项目无关，请到对应的项目下提问。
