### ISSUE TITLE
win端API版运行启动ChatGTP的报错

### ISSUE THREAD

**Issue by FSHebe233** [lss233/chatgpt-mirai-qq-bot#92]
Traceback (most recent call last):
  File "D:\c\chatgpt\bot.py", line 23, in <module>
    import chatbot
  File "D:\c\chatgpt\chatbot.py", line 1, in <module>
    from revChatGPT.Official import Chatbot, Prompt
  File "D:\c\chatgpt\python3.9\lib\site-packages\revChatGPT\Official.py", line 10, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
这怎么解决

**Comment by lss233** [comment]
在 D:\c\chatgpt 下启动cmd，执行：
```cmd
python3.9\python.exe -m pip install openai
```

**Comment by lss233** [comment]
#101
