### ISSUE TITLE
ChatGPT.cmd无法正常启动

### ISSUE THREAD

**Issue by Mizorene** [lss233/chatgpt-mirai-qq-bot#925]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
脚本通过api正常登录后在准备接受消息时产生了非正常的退出。
**运行环境:**  
- 操作系统：win11 22H2 22621.1702
- 项目版本：v2.5.1

**复现步骤**  
描述你是如何触发这个 BUG 的
启动ChatGPT.cmd时出现

**预期行为**  
脚本正常运行

**截图**  
相关日志、聊天记录的截图，没有可跳过
2023-06-07 00:04:51.575 | SUCCESS  | platforms.onebot_bot:startup:349 - 启动完毕，接收消息中……
2023-06-07 00:04:53.001 | INFO     | __main__:<module>:49 - [Edge TTS] 读取成功！
2023-06-07 00:04:53.007 | ERROR    | utils.exithooks:foo:36 - 看样子程序似乎没有正常退出。
2023-06-07 00:04:53.009 | ERROR    | utils.exithooks:foo:37 - [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。
NoneType: None
2023-06-07 00:04:53.033 | ERROR    | utils.exithooks:foo:38 - 你可以在这里阅读常见问题的解决方案：
2023-06-07 00:04:53.034 | ERROR    | utils.exithooks:foo:39 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
Exception ignored in atexit callback: <function foo at 0x00000180BF768360>
Traceback (most recent call last):
  File "D:\Ro\chatgpt\utils\exithooks.py", line 40, in foo
    raise hooks.exception
  File "D:\Ro\chatgpt\bot.py", line 54, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "D:\Ro\chatgpt\platforms\onebot_bot.py", line 356, in start_task
    return await bot.run_task(host=config.onebot.reverse_ws_host, port=config.onebot.reverse_ws_port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ro\python3.11\Lib\site-packages\hypercorn\asyncio\__init__.py", line 49, in serve
    await worker_serve(
  File "D:\Ro\python3.11\Lib\site-packages\hypercorn\asyncio\run.py", line 84, in worker_serve
    sockets = config.create_sockets()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ro\python3.11\Lib\site-packages\hypercorn\config.py", line 198, in create_sockets
    insecure_sockets = self._create_sockets(self.bind)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ro\python3.11\Lib\site-packages\hypercorn\config.py", line 261, in _create_sockets
    sock.bind(binding)
PermissionError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。
程序已停止运行。
Press any key to continue . . .

**Comment by Mizorene** [comment]
解决了，是防火墙的原因，启动脚本的时候window没弹出防火墙允许联网的选项。
