### ISSUE TITLE
[BUG] openai账号无法登陆，昨天晚上还是正常的

### ISSUE THREAD

**Issue by lige47** [lss233/chatgpt-mirai-qq-bot#932]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√ ] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
无法登陆openai

**运行环境:**  
- 操作系统：windows系统
- Docker： ？
- 项目版本：2.5.1

**复现步骤**  
描述你是如何触发这个 BUG 的
直接打开chatgpt for qq，显示无法登陆openai账号，已经替换了新的密钥，还是无法登陆

**预期行为**  
正常登陆

**截图**  
2023-06-08 11:30:43.464 | INFO     | manager.bot:__check_proxy:363 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-06-08 11:30:43.719 | SUCCESS  | manager.bot:__check_proxy:371 - [代理测试] 连接成功！
2023-06-08 11:30:43.720 | INFO     | manager.bot:login:118 - 当前的 browserless_endpoint 为：https://chatgpt-proxy.lss233.com/api/
2023-06-08 11:30:43.720 | INFO     | manager.bot:login:134 - 当前的 api_endpoint 为：https://api.openai.com/v1
2023-06-08 11:30:43.721 | INFO     | manager.bot:login_openai:299 - 正在登录第 1 个 OpenAI 账号
2023-06-08 11:30:43.722 | INFO     | manager.bot:__login_V1:389 - 模式：无浏览器登录
2023-06-08 11:30:43.722 | INFO     | manager.bot:__check_proxy:363 - [代理测试] 正在检查代理配置：http://127.0.0.1:7890
2023-06-08 11:30:43.938 | SUCCESS  | manager.bot:__check_proxy:371 - [代理测试] 连接成功！
2023-06-08 11:30:43.941 | INFO     | manager.bot:__login_V1:414 - 尝试使用 access_token 登录中...
2023-06-08 11:30:49.363 | ERROR    | manager.bot:login_openai:328 - 未知错误：
2023-06-08 11:30:49.363 | ERROR    | manager.bot:login_openai:329 -
Traceback (most recent call last):

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
             │     └ (65536,)
             └ <bound method SSLObject.read of <ssl.SSLObject object at 0x000001D5A4EF0FD0>>

  File "ssl.py", line 921, in read

ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2546)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
                 │    │       │                 └ 65536
                 │    │       └ <function TLSStream.receive at 0x000001D5A6152340>
                 │    └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x000001D5A61AA410>, standard_compatible=False, _...
                 └ <httpcore.backends.asyncio.AsyncIOStream object at 0x000001D5A4EF6010>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\anyio\streams\tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
                 │    │                      │    │           │     └ 65536
                 │    │                      │    │           └ <function SSLObject.read at 0x000001D5A1054CC0>
                 │    │                      │    └ <ssl.SSLObject object at 0x000001D5A4EF0FD0>
                 │    │                      └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x000001D5A61AA410>, standard_compatible=False, _...
                 │    └ <function TLSStream._call_sslobject_method at 0x000001D5A6152160>
                 └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x000001D5A61AA410>, standard_compatible=False, _...
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
                 │    │                └ <function SocketStream.receive at 0x000001D5A61AD440>
                 │    └ <anyio._backends._asyncio.SocketStream object at 0x000001D5A61AA410>
                 └ TLSStream(transport_stream=<anyio._backends._asyncio.SocketStream object at 0x000001D5A61AA410>, standard_compatible=False, _...
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
          │    │         │          └ <function Event.wait at 0x000001D5A2C79580>
          │    │         └ <asyncio.locks.Event object at 0x000001D5A6053550 [set]>
          │    └ <anyio._backends._asyncio.StreamProtocol object at 0x000001D5A6053390>
          └ <anyio._backends._asyncio.SocketStream object at 0x000001D5A61AA410>

  File "asyncio\locks.py", line 213, in wait
    true will not block at all.

asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 32, in read
    with anyio.fail_after(timeout):
         │     │          └ 5.0
         │     └ <function fail_after at 0x000001D5A6116480>
         └ <module 'anyio' from 'D:\\soft\\chatgpt\\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\\python3.11\\Lib\\site-packages\\anyio...
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\anyio\_core\_tasks.py", line 118, in __exit__
    raise TimeoutError

TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'GET']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x000001D5A46B7920>
                 │    └ <httpcore.AsyncHTTPProxy object at 0x000001D5A6082210>
                 └ <httpx.AsyncHTTPTransport object at 0x000001D5A6082150>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
                     │          │                    └ <Request [b'GET']>
                     │          └ <function AsyncTunnelHTTPConnection.handle_async_request at 0x000001D5A46D49A0>
                     └ <AsyncTunnelHTTPConnection ['https://chatgpt-proxy.lss233.com:443', HTTP/1.1, CLOSED, Request Count: 1]>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    return await self._connection.handle_async_request(request)
                 │    │           │                    └ <Request [b'GET']>
                 │    │           └ <function AsyncHTTP11Connection.handle_async_request at 0x000001D5A46B5E40>
                 │    └ <AsyncHTTP11Connection ['https://chatgpt-proxy.lss233.com:443', CLOSED, Request Count: 1]>
                 └ <AsyncTunnelHTTPConnection ['https://chatgpt-proxy.lss233.com:443', HTTP/1.1, CLOSED, Request Count: 1]>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 112, in handle_async_request
    raise exc
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
              │    │                           └ {'request': <Request [b'GET']>}
              │    └ <function AsyncHTTP11Connection._receive_response_headers at 0x000001D5A46B60C0>
              └ <AsyncHTTP11Connection ['https://chatgpt-proxy.lss233.com:443', CLOSED, Request Count: 1]>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
                  │    │                      └ 5.0
                  │    └ <function AsyncHTTP11Connection._receive_event at 0x000001D5A46B6200>
                  └ <AsyncHTTP11Connection ['https://chatgpt-proxy.lss233.com:443', CLOSED, Request Count: 1]>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\_async\http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
                 │    │               └ <function AsyncIOStream.read at 0x000001D5A61B0E00>
                 │    └ <httpcore.backends.asyncio.AsyncIOStream object at 0x000001D5A4EF6010>
                 └ <AsyncHTTP11Connection ['https://chatgpt-proxy.lss233.com:443', CLOSED, Request Count: 1]>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with map_exceptions(exc_map):
         │              └ {<class 'TimeoutError'>: <class 'httpcore.ReadTimeout'>, <class 'anyio.BrokenResourceError'>: <class 'httpcore.ReadError'>, <...
         └ <function map_exceptions at 0x000001D5A45451C0>

  File "contextlib.py", line 155, in __exit__

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
          └ <class 'httpcore.ReadTimeout'>

httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\chatgpt\bot.py", line 17, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x000001D5A4EB2200>
    │    │                  └ <manager.bot.BotManager object at 0x000001D5A4135050>
    │    └ <function BaseEventLoop.run_until_complete at 0x000001D5A2C85580>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000001D5A6196E30>()>

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\chatgpt\manager\bot.py", line 136, in login
    await self.login_openai()
          │    └ <function BotManager.login_openai at 0x000001D5A4EB2840>
          └ <manager.bot.BotManager object at 0x000001D5A4135050>

> File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\chatgpt\manager\bot.py", line 305, in login_openai    bot = await self.__login_V1(account)
                │               └ OpenAIAccessTokenAuth(mode='browserless', proxy='http://127.0.0.1:7890', driver_exec_path=None, browser_exec_path=None, conve...
                └ <manager.bot.BotManager object at 0x000001D5A4135050>

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\chatgpt\manager\bot.py", line 417, in __login_V1
    if await __V1_check_auth():

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\chatgpt\manager\bot.py", line 404, in __V1_check_auth
    await bot.get_conversations(0, 1)
          │   └ <function AsyncChatbot.get_conversations at 0x000001D5A4E904A0>
          └ <revChatGPT.V1.AsyncChatbot object at 0x000001D5A6053A50>

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\revChatGPT\V1.py", line 1097, in get_conversations
    response = await self.session.get(url)
                     │    │       │   └ 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1'
                     │    │       └ <function AsyncClient.get at 0x000001D5A46E6200>
                     │    └ <httpx.AsyncClient object at 0x000001D5A6073150>
                     └ <revChatGPT.V1.AsyncChatbot object at 0x000001D5A6053A50>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
                 │    └ <function AsyncClient.request at 0x000001D5A46E5DA0>
                 └ <httpx.AsyncClient object at 0x000001D5A6073150>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x000001D5A46D9C10>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x000001D5A46D9C10>
                 │    │    └ <Request('GET', 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1')>
                 │    └ <function AsyncClient.send at 0x000001D5A46E5F80>
                 └ <httpx.AsyncClient object at 0x000001D5A6073150>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x000001D5A46E6020>
                     └ <httpx.AsyncClient object at 0x000001D5A6073150>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x000001D5A46E60C0>
                     └ <httpx.AsyncClient object at 0x000001D5A6073150>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('GET', 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1')>
                     │    └ <function AsyncClient._send_single_request at 0x000001D5A46E6160>
                     └ <httpx.AsyncClient object at 0x000001D5A6073150>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('GET', 'https://chatgpt-proxy.lss233.com/api/conversations?offset=0&limit=1')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x000001D5A46D7060>
                     └ <httpx.AsyncHTTPTransport object at 0x000001D5A6082150>
  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x000001D5A4527100>

  File "contextlib.py", line 155, in __exit__

  File "D:\soft\chatgpt\Windows-quickstart-go-cqhttp-refs.tags.v2.5.1\python3.11\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ ''
          └ <class 'httpx.ReadTimeout'>

httpx.ReadTimeout
2023-06-08 11:30:49.402 | SUCCESS  | manager.bot:login_openai:332 - 成功登录 0/1 个 OpenAI 账号！
2023-06-08 11:30:49.403 | ERROR    | manager.bot:login:143 - 没有登录成功的账号，程序无法启动！
程序已停止运行。
Press any key to continue . . .

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lige47** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/97075835/2595d2e4-50f1-4a8f-9d34-1ad40a53dde4)

**Comment by imRhoAias** [comment]
一样一样，不过没重启的好像还可以用，，，

**Comment by lige47** [comment]
> 

我昨天晚上还是正常，今天就这样了

**Comment by lige47** [comment]
我昨天晚上正常，今天就这样了

**Comment by Nothingness-Void** [comment]
请参考 https://github.com/lss233/chatgpt-mirai-qq-bot/issues/929#issuecomment-1581002399 反正我这么操作后解决了 登录三个号都能正常使用

**Comment by imRhoAias** [comment]
> 请参考 [#929 (comment)](https://github.com/lss233/chatgpt-mirai-qq-bot/issues/929#issuecomment-1581002399) 反正我这么操作后解决了 登录三个号都能

小白没看明白，，，，

**Comment by Nothingness-Void** [comment]
> > 请参考 [#929 (comment)](https://github.com/lss233/chatgpt-mirai-qq-bot/issues/929#issuecomment-1581002399) 反正我这么操作后解决了 登录三个号都能
> 
> 小白没看明白，，，，

参考教程设置接入点链接 然后把我搭的地址写进去 `https://[fakeopen.nothingnessvoid.tech/api/](https://fakeopen.nothingnessvoid.tech/)/`

**Comment by linxp001** [comment]
大佬牛逼，好使了

**Comment by B17w153** [comment]
> > > > 请参考 [#929 (comment)](https://github.com/lss233/chatgpt-mirai-qq-bot/issues/929#issuecomment-1581002399) 反正我这么操作后解决了 登录三个号都能
> > > 
> > > 
> > > 小白没看明白，，，，
> > 
> > 
> > 参考教程设置接入点链接 然后把我搭的地址写进去
> 
> ![E7QP)N(B8598@W1M75_Z5 K](https://user-images.githubusercontent.com/133833496/244337294-9d476969-0c13-476a-9223-bb7a792c591f.png) 好像，，，不行？ ![8 $1_L@50 C5G4MH}4L39](https://user-images.githubusercontent.com/133833496/244337538-45601dbf-4c26-42f6-bce8-869d07388146.png) 这样不对吗

您猜怎么着 我的建议是 把https://[fakeopen.nothingnessvoid.tech/api/里面的[删掉
```bash
https://fakeopen.nothingnessvoid.tech/api/```

**Comment by Nothingness-Void** [comment]
http://[us.nothingnessvoid.tech:8080/chatgpt/](http://us.nothingnessvoid.tech:8080/chatgpt/) 
我自己用https://github.com/linweiyuan/go-chatgpt-api这个项目又搭建了一个接入点 如果各位还是进不去把接入点换成这个

**Comment by plapha** [comment]
牛逼

**Comment by Kasualix** [comment]
而你，兄弟，才是我的英雄

> 我自己用 https://github.com/linweiyuan/go-chatgpt-api 这个项目又搭建了一个接入点 如果各位还是进不去把接入点换成这个 `http://us.nothingnessvoid.tech:8080/chatgpt/`

**Comment by Nothingness-Void** [comment]
破案了 https://github.com/pengzhile/pandora/issues/628 这个作者是 ai.fakeopen.com的搭建者 本项目默认的API接入点用的就是ai.fakeopen.com 然后因为很多人使用他的开源项目没有标注原作者信息（包括我），所以原作者开始封禁这些域名 用不了的八成是被封了吧

**Comment by lss233** [comment]
已恢复。

**Comment by slamd14** [comment]
> http://us.nothingnessvoid.tech:8080/chatgpt/

真正的英雄

**Comment by 123sghn** [comment]
> 破案了 [pengzhile/pandora#628](https://github.com/pengzhile/pandora/issues/628) 这个作者是 ai.fakeopen.com的搭建者 本项目默认的API接入点用的就是ai.fakeopen.com 然后因为很多人使用他的开源项目没有标注原作者信息（包括我），所以原作者开始封禁这些域名 用不了的八成是被封了吧

大佬。请问还有好用的api接入点么？

**Comment by Nothingness-Void** [comment]
我上边发了能用的，现在官方的也能用NothingnessVoid发件人: ***@***.*** ***@***.***> 代表 123sghn ***@***.***>发送时间: 2023年6月20日星期二 下午3:08收件人: chatgpt-mirai-qq-bot ***@***.***>抄送: 1744914510 ***@***.***>; comment ***@***.***>主题: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] openai账号无法登陆，昨天晚上还是正常的 (Issue #932)

破案了 pengzhile/pandora#628 这个作者是 ai.fakeopen.com的搭建者 本项目默认的API接入点用的就是ai.fakeopen.com 然后因为很多人使用他的开源项目没有标注原作者信息（包括我），所以原作者开始封禁这些域名 用不了的八成是被封了吧

大佬。请问还有好用的api接入点么？

**Comment by shadowbox-cash** [comment]
> 



> 

还是报错，显示

Sorry, you have been blocked
You are unable to access fakeopen.com

**Comment by Nothingness-Void** [comment]
> > 
> 
> > 
> 
> 还是报错，显示
> 
> Sorry, you have been blocked You are unable to access fakeopen.com

换成我发的接入点就好了

**Comment by Nothingness-Void** [comment]
> 

http://sgp.nothingnessvoid.tech/chatgpt/

**Comment by shadowbox-cash** [comment]
> 



> http://sgp.nothingnessvoid.tech/chatgpt/

非常感谢，但还是报错
OpenAI: {"errorMessage":"Fallback failed."} (code: 404)

不过已经不是之前的被封掉的错误了，这个问题大佬知道什么原因吗？

**Comment by linxp001** [comment]
> > 
> 
> > http://sgp.nothingnessvoid.tech/chatgpt/
> 
> 非常感谢，但还是报错 OpenAI: {"errorMessage":"Fallback failed."} (code: 404)
> 
> 不过已经不是之前的被封掉的错误了，这个问题大佬知道什么原因吗？ <img alt="image" width="1454" src="https://user-images.githubusercontent.com/71253948/248168202-5617d4ef-b446-4f01-aea7-b3ad5b536511.png">

建议你认真看一下https://github.com/linweiyuan/go-chatgpt-api
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/75927451/e490dd0e-fa84-4657-ae05-7ffc5bdf306e)

**Comment by Nothingness-Void** [comment]
> > 
> 
> > http://sgp.nothingnessvoid.tech/chatgpt/
> 
> 非常感谢，但还是报错 OpenAI: {"errorMessage":"Fallback failed."} (code: 404)
> 
> 不过已经不是之前的被封掉的错误了，这个问题大佬知道什么原因吗？ <img alt="image" width="1454" src="https://user-images.githubusercontent.com/71253948/248168202-5617d4ef-b446-4f01-aea7-b3ad5b536511.png">

你把/api/去掉就行了

**Comment by shadowbox-cash** [comment]
> 



> > > 
> > 
> > 
> > > http://sgp.nothingnessvoid.tech/chatgpt/
> > 
> > 
> > 非常感谢，但还是报错 OpenAI: {"errorMessage":"Fallback failed."} (code: 404)
> > 不过已经不是之前的被封掉的错误了，这个问题大佬知道什么原因吗？ <img alt="image" width="1454" src="https://user-images.githubusercontent.com/71253948/248168202-5617d4ef-b446-4f01-aea7-b3ad5b536511.png">
> 
> 你把/api/去掉就行了

报错 521： Web server is down
<img width="1393" alt="image" src="https://github.com/lss233/chatgpt-mirai-qq-bot/assets/71253948/65e95604-b97c-408a-a566-fe2f333cd974">

**Comment by shadowbox-cash** [comment]
直接访问http://sgp.nothingnessvoid.tech/chatgpt/ 也是这个错误
<img width="982" alt="image" src="https://github.com/lss233/chatgpt-mirai-qq-bot/assets/71253948/87665c26-95ed-4002-b562-c89991ecd23d">

**Comment by Nothingness-Void** [comment]
> 直接访问http://sgp.nothingnessvoid.tech/chatgpt/ 也是这个错误 <img alt="image" width="982" src="https://user-images.githubusercontent.com/71253948/248453243-87665c26-95ed-4002-b562-c89991ecd23d.png">

我改了一下 你看这个吧 https://github.com/lss233/chatgpt-mirai-qq-bot/issues/981

**Comment by linxp001** [comment]
> > 直接访问http://sgp.nothingnessvoid.tech/chatgpt/ 也是这个错误 <img alt="image" width="982" src="https://user-images.githubusercontent.com/71253948/248453243-87665c26-95ed-4002-b562-c89991ecd23d.png">
> 
> 我改了一下 你看这个吧 #981

把你的接入点注释掉就好了

**Comment by Nothingness-Void** [comment]
> > > 直接访问http://sgp.nothingnessvoid.tech/chatgpt/ 也是这个错误 <img alt="image" width="982" src="https://user-images.githubusercontent.com/71253948/248453243-87665c26-95ed-4002-b562-c89991ecd23d.png">
> > 
> > 
> > 我改了一下 你看这个吧 #981
> 
> 把你的接入点注释掉就好了

我改了我服务的端口现在必须要加端口号才能用http://sgp.nothingnessvoid.tech:8080/chatgpt/
